/* 英语题库 批1：PEP 五上 Unit1-Unit4（选项顺序已打乱，答案位置随机） */
QA.en.push(
{i:910,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“kind” 的意思是？",o:["和蔼的","严厉的","年轻的","聪明的"],a:0,k:"词汇：形容人的形容词 kind",e:"kind 意为“和蔼的、慈祥的”，常用来形容人性格温和友善。记忆：k-i-n-d，与“友好的”同义。"},
{i:911,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“严格”用英语怎么说？",o:["kind","strict","funny","shy"],a:1,k:"词汇：strict 严格的",e:"strict 意为“严格的”，发音 /strɪkt/，常用来形容要求严格的老师。"},
{i:912,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“old” 的意思是？",o:["高的","年老的","矮的","年轻的"],a:1,k:"词汇：old 年老的",e:"old 意为“年老的、旧的”，反义词是 young（年轻的）。"},
{i:913,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“滑稽的”用英语怎么说？",o:["funny","kind","clever","polite"],a:0,k:"词汇：funny 滑稽的",e:"funny 意为“滑稽的、有趣的”，如 a funny story（一个有趣的故事）。"},
{i:914,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“hard-working” 的意思是？",o:["害羞的","和蔼的","勤奋的","懒惰的"],a:2,k:"词汇：hard-working 勤奋的",e:"hard-working 是复合词，由 hard（努力）+ working（工作）组成，意为“勤奋的”。"},
{i:915,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“乐于助人的”用英语怎么说？",o:["helpful","old","young","strict"],a:0,k:"词汇：helpful 乐于助人的",e:"helpful 由 help（帮助）+ ful（形容词后缀）组成，意为“乐于助人的、有帮助的”。"},
{i:916,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“clever” 的意思是？",o:["聪明的","漂亮的","强壮的","笨拙的"],a:0,k:"词汇：clever 聪明的",e:"clever 意为“聪明的”，同义词是 smart，反义词是 stupid（愚蠢的）。"},
{i:917,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“害羞的”用英语怎么说？",o:["kind","funny","shy","polite"],a:2,k:"词汇：shy 害羞的",e:"shy 意为“害羞的、腼腆的”，如 a shy girl（一个害羞的女孩）。"},
{i:918,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“polite” 的意思是？",o:["安静的","有礼貌的","强壮的","忙碌的"],a:1,k:"词汇：polite 有礼貌的",e:"polite 意为“有礼貌的”，反义词是 rude（粗鲁的）。"},
{i:919,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“年轻的”用英语怎么说？",o:["young","tall","old","short"],a:0,k:"词汇：young 年轻的",e:"young 意为“年轻的”，反义词是 old（年老的）。"},
{i:920,c:"en-1",ch:"五上·Unit 1 What's he like?",f:1,q:"——What's he like?——He's ____（和蔼的）.",o:[],a:"kind",k:"句型：What's he like? 回答用 He's + 形容词",e:"What's he like? 问“他是什么样的人”，回答用 “He's + 形容词”，如 He's kind.（他和蔼。）"},
{i:921,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"问“你的数学老师是谁？”用英语怎么说？",o:["Who's your maths teacher?","What's your maths teacher?","Where's your maths teacher?","How is your maths teacher?"],a:0,k:"句型：Who's...? 问“是谁”",e:"询问人是谁用 Who's...?（Who is 的缩写），Who's your maths teacher? 意为“你的数学老师是谁？”。"},
{i:922,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"——Is she young?——____",o:["No, she is.","Yes, she is.","Yes, she isn't.","Yes, he is."],a:1,k:"句型：Is she...? 的肯定回答",e:"Is she young? 问“她年轻吗？”，肯定回答 Yes, she is.，注意 she 对应 is。"},
{i:923,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“What's he like?” 的答语是？",o:["He likes apples.","He's my father.","He's 10.","He's funny."],a:3,k:"句型：What's he like? 的答语",e:"What's he like? 问外貌或性格，答语用 He's + 形容词，He's funny.（他很滑稽。）正确。"},
{i:924,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"Mr Li 很严格，我们可以说：",o:["Mr Li is clever.","Mr Li is strict.","Mr Li is polite.","Mr Li is shy."],a:1,k:"句型：用 is + 形容词描述人",e:"描述 Mr Li 很严格：Mr Li is strict.，strict 是“严格的”。"},
{i:925,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“Do you know her?” 的意思是？",o:["你是她吗？","你认识她吗？","你喜欢她吗？","你了解她吗？"],a:1,k:"句型：Do you know...?",e:"Do you know her? 意为“你认识她吗？”，know 是“认识、知道”。"},
{i:926,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“sometimes” 的意思是？",o:["经常","总是","从不","有时候"],a:3,k:"词汇：频度副词 sometimes",e:"sometimes 意为“有时候”，是频度副词；always 总是、never 从不。"},
{i:927,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"——Who's that man?——He's ____. 下面哪个答语正确？",o:["young","my uncle","funny","kind"],a:1,k:"句型：Who's that man? 的答语",e:"问“那个男人是谁？”答语应回答身份，He's my uncle.（他是我叔叔。）正确。"},
{i:928,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“be like” 在 What's he like? 中表示？",o:["喜欢","想要","像……一样","是什么样的人"],a:3,k:"语法：What...like? 句型",e:"What is sb like? 问“某人是什么样的人”，like 是介词“像”，不是“喜欢”。"},
{i:929,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"形容一个人又聪明又勤奋，应说：",o:["He is clever and hard-working.","He is polite and young.","He is old and strict.","He is shy and funny."],a:0,k:"句型：and 连接两个形容词",e:"用 and 连接两个形容词：He is clever and hard-working.（他又聪明又勤奋。）"},
{i:930,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“Ms Wang” 中的 Ms 表示？",o:["女士（不知婚否）","夫人（已婚）","小姐（年轻）","先生"],a:0,k:"文化常识：称谓 Ms/Mr/Mrs/Miss",e:"Ms 用于女士（不表明婚否），Mr 先生，Mrs 夫人（已婚），Miss 小姐（未婚）。"},
{i:931,c:"en-1",ch:"五上·Unit 1 What's he like?",f:1,q:"“What's she like?” “She's ____（漂亮的）.”",o:[],a:"pretty",k:"词汇：pretty 漂亮的",e:"pretty 意为“漂亮的、可爱的”，回答 What's she like? 用 She's pretty."},
{i:932,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"——Is your English teacher strict?——____",o:["No, he is kind.","Yes, she is young.","Yes, she is kind.","No, she isn't. She's kind."],a:3,k:"句型：Is...strict? 的回答",e:"问“你的英语老师严格吗？”否定回答 No, she isn't. 后补充 She's kind.（她和蔼。）注意 she 用 isn't。"},
{i:933,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“He makes us laugh.” 的意思是？",o:["他让我们哭","他让我们学习","他让我们生气","他让我们笑（他很有趣）"],a:3,k:"句型：make sb do sth",e:"make sb laugh 意为“让某人笑”，laugh 是动词原形（make 后接动词原形）。"},
{i:934,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"下列哪组都是形容人的词？",o:["book, pen, ruler","apple, banana, pear","red, blue, green","kind, funny, polite"],a:3,k:"词汇分类：形容词",e:"kind（和蔼）、funny（滑稽）、polite（礼貌）都是形容人的形容词。"},
{i:935,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“know” 的意思是？",o:["喜欢","认识、知道","听到","看见"],a:1,k:"词汇：know 认识",e:"know 意为“认识、知道”，Do you know...? 就是“你认识……吗？”。"},
{i:936,c:"en-1",ch:"五上·Unit 1 What's he like?",f:1,q:"——What's your father like?——He's ____（强壮的）.",o:[],a:"strong",k:"词汇：strong 强壮的",e:"strong 意为“强壮的”，He's strong. 他很强壮。"},
{i:937,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"形容老师很和蔼，用哪个词？",o:["strict","tall","kind","old"],a:2,k:"词汇辨析：kind 和蔼",e:"和蔼用 kind；strict 严格、old 年老、tall 高，都不合题意。"},
{i:938,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“He's very helpful at home.” 意思是？",o:["他在家很乐于助人","他在家很懒惰","他在家很安静","他在家很调皮"],a:0,k:"句型：helpful 的用法",e:"He's very helpful at home. 意为“他在家很乐于助人”，helpful 是“乐于助人的”。"},
{i:939,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“What's she like?” 问的是？",o:["她在哪里","她几岁","她是什么样的人","她想要什么"],a:2,k:"句型：What's she like?",e:"What's she like? 问“她是什么样的人”，like 是介词，不是“喜欢”。"},
{i:940,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“Is he young?” 的否定回答是？",o:["No, he isn't.","Yes, he isn't.","Yes, she is.","No, he is."],a:0,k:"句型：一般疑问句的回答",e:"Is he young? 否定回答 No, he isn't.（不，他不年轻。）注意 he 用 isn't。"},
{i:941,c:"en-1",ch:"五上·Unit 1 What's he like?",f:0,q:"“He has big eyes.” 的意思是？",o:["他有两只眼睛","他的眼睛很小","他喜欢大眼睛","他有一双大眼睛"],a:3,k:"句型：have/has 表示拥有",e:"He has big eyes. 意为“他有一双大眼睛”，主语 he 用 has（have 的第三人称单数）。"},
{i:942,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“星期一”用英语怎么说？",o:["Tuesday","Saturday","Monday","Sunday"],a:2,k:"词汇：星期 Monday",e:"星期一 Monday，缩写 Mon.。记法：mon 像月亮，星期一 moon day。"},
{i:943,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“Wednesday” 的意思是？",o:["星期五","星期四","星期二","星期三"],a:3,k:"词汇：星期 Wednesday",e:"Wednesday 星期三，缩写 Wed.，注意拼写中间有 d。"},
{i:944,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“星期五”用英语怎么说？",o:["Sunday","Thursday","Friday","Tuesday"],a:2,k:"词汇：星期 Friday",e:"星期五 Friday，缩写 Fri.，Friday 与朋友 friend 相似，周五是快乐的一天。"},
{i:945,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“weekend” 的意思是？",o:["工作日","周末","假期","一周"],a:1,k:"词汇：weekend 周末",e:"weekend 由 week（周）+ end（结束）组成，意为“周末”，指周六、周日。"},
{i:946,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“watch TV” 的意思是？",o:["看电影","看书","看电视","玩电脑"],a:2,k:"短语：watch TV 看电视",e:"watch TV 看电视，watch 是“观看”，TV 是 television 的缩写。"},
{i:947,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“做作业”用英语怎么说？",o:["read books","watch TV","do homework","play football"],a:2,k:"短语：do homework 做作业",e:"do homework 做作业，homework 是不可数名词，不能说 a homework。"},
{i:948,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“read books” 的意思是？",o:["写字","画画","读书","唱歌"],a:2,k:"短语：read books 读书",e:"read books 读书、看书，read 读 /riːd/。"},
{i:949,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“play football” 的意思是？",o:["打排球","打篮球","打乒乓球","踢足球"],a:3,k:"短语：play football 踢足球",e:"play football 踢足球。球类运动前不加 the，如 play basketball 打篮球。"},
{i:950,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“wash my clothes” 的意思是？",o:["洗我的衣服","洗我的头发","洗我的手","洗我的脸"],a:0,k:"短语：wash my clothes",e:"wash 洗，clothes 衣服，wash my clothes 意为“洗我的衣服”。"},
{i:951,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“Saturday” 的意思是？",o:["星期三","星期一","星期日","星期六"],a:3,k:"词汇：星期 Saturday",e:"Saturday 星期六，缩写 Sat.，周六 often 是休息日。"},
{i:952,c:"en-2",ch:"五上·Unit 2 My week",f:1,q:"I have maths and English on ____（星期一）.",o:[],a:"Mondays",k:"句型：on + 星期",e:"在星期几前用介词 on，on Mondays 意为“在星期一”（习惯用复数）。"},
{i:953,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"——What do you have on Mondays?——____",o:["I have maths and English.","I go to school.","It's Monday.","I like Mondays."],a:0,k:"句型：What do you have on...?",e:"问“星期一你上什么课？”答语用 I have + 课程：I have maths and English.（我上数学和英语。）"},
{i:954,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"——What do you do on the weekend?——____",o:["I am ten.","I have lunch.","It's sunny.","I often read books."],a:3,k:"句型：What do you do on the weekend?",e:"问“周末你做什么？”答语用 I + 动词短语：I often read books.（我经常读书。）"},
{i:955,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“often” 的意思是？",o:["总是","从不","经常","偶尔"],a:2,k:"词汇：频度副词 often",e:"often 经常，always 总是，never 从不，usually 通常，都是频度副词。"},
{i:956,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“Do you often play football?” 的肯定回答是？",o:["Yes, I do.","Yes, I can.","No, I don't.","Yes, I am."],a:0,k:"句型：Do you...? 的回答",e:"Do you...? 开头的问句，肯定回答 Yes, I do.，do 对应助动词 do。"},
{i:957,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“Sunday” 是一周的星期几？",o:["星期日","星期一","星期六","星期五"],a:0,k:"词汇：星期 Sunday",e:"Sunday 星期日，缩写 Sun.，英语习惯把周日作为一周的第一天。"},
{i:958,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“I have a cooking class.” 意思是？",o:["我有一节烹饪课","我有一节体育课","我有一节英语课","我有一节数学课"],a:0,k:"句型：have a class 上课",e:"I have a cooking class. 意为“我有一节烹饪课”，cooking 是烹饪。"},
{i:959,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“Tuesday” 的意思是？",o:["星期一","星期二","星期四","星期三"],a:1,k:"词汇：星期 Tuesday",e:"Tuesday 星期二，缩写 Tue.，注意拼写 Tuesday。"},
{i:960,c:"en-2",ch:"五上·Unit 2 My week",f:1,q:"I often do homework and ____（读书）on the weekend.",o:[],a:"read books",k:"短语：read books 读书",e:"and 连接两个并列的动作：do homework and read books（做作业和读书）。"},
{i:961,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"一周的第一天（英语习惯）是？",o:["Sunday","Friday","Monday","Saturday"],a:0,k:"文化常识：一周的第一天",e:"英语国家习惯把 Sunday（星期日）作为一周的第一天，Sunday 在最前。"},
{i:962,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“Thursday” 的意思是？",o:["星期二","星期三","星期五","星期四"],a:3,k:"词汇：星期 Thursday",e:"Thursday 星期四，缩写 Thu.，注意拼写与 Tuesday 区分。"},
{i:963,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"——Do you often watch TV?——____",o:["Yes, I do homework.","No, I can't.","Yes, I am.","No, I don't. I often read books."],a:3,k:"句型：Do you often...? 的回答",e:"问“你经常看电视吗？”否定回答 No, I don't.，补充 I often read books.。"},
{i:964,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“play sports” 的意思是？",o:["做运动","做作业","玩玩具","看电视"],a:0,k:"短语：play sports 做运动",e:"play sports 意为“做运动、锻炼”，sports 是 sport 的复数。"},
{i:965,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“What do you have on Thursdays?” 中 have 的意思是？",o:["吃","拥有","有","上（课）"],a:3,k:"句型：have 的用法",e:"问课程时 What do you have...? 中 have 表示“上（课）”，I have maths. 我上数学课。"},
{i:966,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“I like weekends.” 意思是？",o:["我喜欢工作日","我喜欢周末","我喜欢放假","我喜欢星期一"],a:1,k:"句型：like + 名词",e:"I like weekends. 意为“我喜欢周末”，weekends 是周末（复数泛指）。"},
{i:967,c:"en-2",ch:"五上·Unit 2 My week",f:1,q:"——What do you do on the weekend?——I often ____（洗衣服）.",o:[],a:"wash my clothes",k:"短语：wash my clothes 洗衣服",e:"wash my clothes 洗我的衣服，wash 洗，clothes 衣服。"},
{i:968,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“on the weekend” 的意思是？",o:["在晚上","在周末","在工作日","在早上"],a:1,k:"短语：on the weekend 在周末",e:"on the weekend 在周末（英式也用 at the weekend），on + 具体时间。"},
{i:969,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"下面哪个不是课程？",o:["maths","Chinese","English","football"],a:3,k:"词汇分类：课程",e:"English（英语）、maths（数学）、Chinese（语文）是课程，football（足球）是运动。"},
{i:970,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“I often play football with my friends.” 意思是？",o:["我经常一个人踢足球","我不会踢足球","我经常和朋友踢足球","我讨厌踢足球"],a:2,k:"句型：with 和……一起",e:"I often play football with my friends. 意为“我经常和朋友踢足球”，with 是和……一起。"},
{i:971,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“You should play sports every day.” 中 should 意思是？",o:["可以","想要","必须","应该"],a:3,k:"词汇：情态动词 should",e:"should 意为“应该”，You should... 是“你应该……”，表示建议。"},
{i:972,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"——What day is it today?——____",o:["I like it.","It's sunny.","I have English.","It's Monday."],a:3,k:"句型：What day is it today?",e:"问“今天星期几？”答语用 It's + 星期：It's Monday.（星期一。）"},
{i:973,c:"en-2",ch:"五上·Unit 2 My week",f:0,q:"“We have art on Fridays.” 意思是？",o:["我们星期五有科学课","我们星期五有体育课","我们星期五有美术课","我们星期五有音乐课"],a:2,k:"句型：have art 上美术课",e:"We have art on Fridays. 意为“我们星期五有美术课”，art 是美术。"},
{i:974,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“sandwich” 的意思是？",o:["汉堡包","三明治","沙拉","冰淇淋"],a:1,k:"词汇：食物 sandwich",e:"sandwich 三明治，注意拼写，复数 sandwiches。"},
{i:975,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“salad” 的意思是？",o:["三明治","面条","米饭","沙拉"],a:3,k:"词汇：食物 salad",e:"salad 沙拉，如 vegetable salad（蔬菜沙拉）。"},
{i:976,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“汉堡包”用英语怎么说？",o:["cake","sandwich","hamburger","bread"],a:2,k:"词汇：食物 hamburger",e:"hamburger 汉堡包，口语常说 burger。"},
{i:977,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“ice cream” 的意思是？",o:["牛奶","冰淇淋","果汁","蛋糕"],a:1,k:"词汇：食物 ice cream",e:"ice cream 冰淇淋，由 ice（冰）+ cream（奶油）组成。"},
{i:978,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“tea” 的意思是？",o:["牛奶","水","咖啡","茶"],a:3,k:"词汇：饮品 tea",e:"tea 茶，green tea 绿茶、milk tea 奶茶。"},
{i:979,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“fresh” 的意思是？",o:["新鲜的","甜的","辣的","美味的"],a:0,k:"词汇：fresh 新鲜的",e:"fresh 新鲜的，如 fresh vegetables（新鲜蔬菜）。"},
{i:980,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“healthy” 的意思是？",o:["好吃的","健康的","便宜的","大的"],a:1,k:"词汇：healthy 健康的",e:"healthy 健康的，由 health（健康）+ y 组成，healthy food 健康食品。"},
{i:981,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“delicious” 的意思是？",o:["辣的","美味的","甜的","新鲜的"],a:1,k:"词汇：delicious 美味的",e:"delicious 美味的、可口的，是形容食物好吃的常用词。"},
{i:982,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“甜的”用英语怎么说？",o:["hot","healthy","fresh","sweet"],a:3,k:"词汇：sweet 甜的",e:"sweet 甜的，反义词是 sour（酸的）。"},
{i:983,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“hot” 在食物中意思是？",o:["冷的","热的","辣的","甜的"],a:2,k:"词汇：hot 双义",e:"hot 有两个意思：热的（天气热）和辣的（食物辣）。"},
{i:984,c:"en-3",ch:"五上·Unit 3 What would you like?",f:1,q:"——What would you like to eat?——I'd like a ____（三明治）.",o:[],a:"sandwich",k:"句型：I'd like... 想要",e:"I'd like = I would like，意为“我想要”，I'd like a sandwich.（我想要一个三明治。）"},
{i:985,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"——What would you like to drink?——____",o:["I like tea.","I want tea.","I'd like some tea.","I'd like a sandwich."],a:2,k:"句型：What would you like to drink?",e:"问“你想喝什么？”答语用 I'd like some + 饮品：I'd like some tea.（我想要点茶。）"},
{i:986,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"——Would you like some salad?——____",o:["Yes, I do.","Yes, I am.","No, I don't.","Yes, please."],a:3,k:"句型：Would you like...? 的回答",e:"Would you like...? 是“你想要……吗？”肯定回答 Yes, please.，否定 No, thanks.。"},
{i:987,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“What would you like to eat?” 的意思是？",o:["你喜欢什么？","你想喝什么？","你想吃什么？","你要什么？"],a:2,k:"句型：What would you like to eat?",e:"eat 吃、drink 喝，问“你想吃什么？”用 What would you like to eat?。"},
{i:988,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“I'd like” 是哪个的缩写？",o:["I would like","I had like","I will like","I do like"],a:0,k:"语法：I'd like 的构成",e:"I'd like 是 I would like 的缩写，意为“我想要”，是礼貌的表达。"},
{i:989,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“I love ice cream. It's sweet.” 意思是？",o:["冰淇淋很健康","我爱吃冰淇淋，它是辣的","我讨厌冰淇淋","我爱吃冰淇淋，它是甜的"],a:3,k:"句型：love + 名词",e:"I love ice cream. 我爱吃冰淇淋。It's sweet. 它是甜的。"},
{i:990,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“My favourite food is beef noodles.” 意思是？",o:["我最喜欢的食物是牛肉面","我不喜欢牛肉面","我最喜欢的食物是米饭","牛肉面很贵"],a:0,k:"句型：My favourite food is...",e:"My favourite food is... 意为“我最喜欢的食物是……”，favourite 最喜欢的。"},
{i:991,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“favourite” 的意思是？",o:["讨厌的","最喜欢的","特别的","普通的"],a:1,k:"词汇：favourite 最喜欢的",e:"favourite 最喜欢的，英式拼写；美式拼写 favorite。"},
{i:992,c:"en-3",ch:"五上·Unit 3 What would you like?",f:1,q:"——What's your favourite food?——I like ____（沙拉）best.",o:[],a:"salad",k:"句型：like...best 最喜欢",e:"like...best 意为“最喜欢”，I like salad best.（我最喜欢沙拉。）"},
{i:993,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“It's hot.” 形容辣椒（chilli）时表示？",o:["热的","甜的","辣的","凉的"],a:2,k:"词汇：hot 辣的",e:"形容食物时 hot 表示“辣的”，The chilli is hot.（辣椒很辣。）"},
{i:994,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“I'm hungry.” 意思是？",o:["我累了","我饱了","我渴了","我饿了"],a:3,k:"词汇：hungry 饿的",e:"hungry 饿的，thirsty 渴的，I'm hungry.（我饿了。）"},
{i:995,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"——What's your favourite drink?——____",o:["I'm thirsty.","I drink water.","I like milk best.","I want tea."],a:2,k:"句型：favourite drink",e:"问“你最喜欢的饮品是什么？”答语 I like milk best.（我最喜欢牛奶。）"},
{i:996,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“eat” 和 “drink” 分别表示？",o:["跑、跳","吃、喝","看、听","喝、吃"],a:1,k:"词汇：eat/drink",e:"eat 吃，drink 喝，eat and drink 吃喝。"},
{i:997,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“A hamburger, please.” 用于什么场景？",o:["问路","告别","点餐","打招呼"],a:2,k:"句型：点餐用语",e:"“A hamburger, please.” 是点餐用语，意为“请给我一个汉堡包”。"},
{i:998,c:"en-3",ch:"五上·Unit 3 What would you like?",f:1,q:"Tomatoes are ____（新鲜的）and healthy.",o:[],a:"fresh",k:"词汇：fresh 新鲜的",e:"Tomatoes are fresh and healthy.（西红柿新鲜又健康。）fresh 新鲜的。"},
{i:999,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“Here you are.” 的意思是？",o:["给你","你好","谢谢","再见"],a:0,k:"交际用语：Here you are.",e:"Here you are. 意为“给你”，是递东西时的常用语。"},
{i:1000,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“Thank you.” 的回应是？",o:["Thank you.","OK.","Sorry.","You're welcome."],a:3,k:"交际用语：感谢的回应",e:"回应 Thank you. 用 You're welcome.（不客气。）"},
{i:1001,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“I don't like grapes. They're sour.” 中 sour 意思是？",o:["甜的","辣的","酸的","苦的"],a:2,k:"词汇：sour 酸的",e:"sour 酸的，反义词 sweet 甜的，grapes 葡萄。"},
{i:1002,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“What would you like to drink?” 的答语是？",o:["Some juice, please.","I like dogs.","A book, please.","I am fine."],a:0,k:"句型：drink 饮品的答语",e:"问想喝什么，答 Some juice, please.（来点果汁。）juice 是饮品。"},
{i:1003,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“vegetables” 的意思是？",o:["肉类","面包","水果","蔬菜"],a:3,k:"词汇：vegetables 蔬菜",e:"vegetables 蔬菜，单数 vegetable，如 tomatoes、potatoes 都是蔬菜。"},
{i:1004,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“We should eat healthy food.” 意思是？",o:["我们应该吃健康的食物","我们应该吃很多食物","我们应该少吃","我们应该吃辣的食物"],a:0,k:"句型：should + 动词原形",e:"We should eat healthy food. 意为“我们应该吃健康的食物”，should 后接动词原形。"},
{i:1005,c:"en-3",ch:"五上·Unit 3 What would you like?",f:0,q:"“Can I have some water, please?” 中 Can I 意思是？",o:["我想要","我可以……吗","我能……","我需要"],a:1,k:"句型：Can I...? 请求",e:"Can I have...? 意为“我可以要……吗？”，是礼貌请求的句型。"},
{i:1006,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“sing” 的意思是？",o:["唱歌","跑步","跳舞","画画"],a:0,k:"词汇：sing 唱歌",e:"sing 唱歌，sing a song 唱一首歌。"},
{i:1007,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“跳舞”用英语怎么说？",o:["swim","draw","sing","dance"],a:3,k:"词汇：dance 跳舞",e:"dance 跳舞，dance to the music 随着音乐跳舞。"},
{i:1008,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“draw” 的意思是？",o:["画画","写字","唱歌","跳舞"],a:0,k:"词汇：draw 画画",e:"draw 画画，draw a picture 画一幅画。"},
{i:1009,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“cook” 的意思是？",o:["吃","做饭","洗","买"],a:1,k:"词汇：cook 做饭",e:"cook 做饭，cook dinner 做晚饭。"},
{i:1010,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“swim” 的意思是？",o:["打球","跑步","游泳","跳高"],a:2,k:"词汇：swim 游泳",e:"swim 游泳，现在分词 swimming（双写 m）。"},
{i:1011,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“打篮球”用英语怎么说？",o:["play football","play ping-pong","play basketball","play volleyball"],a:2,k:"短语：play basketball 打篮球",e:"play basketball 打篮球，球类运动前不加 the。"},
{i:1012,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“speak English” 的意思是？",o:["说英语","学英语","写英语","读英语"],a:0,k:"短语：speak English 说英语",e:"speak English 说英语，speak + 语言，如 speak Chinese 说中文。"},
{i:1013,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“do kung fu” 的意思是？",o:["练武术","打篮球","跑步","跳舞"],a:0,k:"短语：do kung fu 练武术",e:"do kung fu 练武术、打功夫，kung fu 是外来词。"},
{i:1014,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“play the pipa” 的意思是？",o:["弹钢琴","拉小提琴","弹琵琶","打鼓"],a:2,k:"短语：play the pipa 弹琵琶",e:"play the pipa 弹琵琶。乐器前要加 the，如 play the piano 弹钢琴。"},
{i:1015,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“What can you do?” 的意思是？",o:["你是谁？","你想要什么？","你喜欢什么？","你会做什么？"],a:3,k:"句型：What can you do?",e:"What can you do? 意为“你会做什么？”，can 是情态动词“能、会”。"},
{i:1016,c:"en-4",ch:"五上·Unit 4 What can you do?",f:1,q:"——What can you do?——I can ____（唱歌）.",o:[],a:"sing",k:"句型：I can + 动词原形",e:"回答 What can you do? 用 I can + 动词原形：I can sing.（我会唱歌。）"},
{i:1017,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"——Can you swim?——____",o:["Yes, I can.","Yes, I am.","Yes, I do.","Yes, I will."],a:0,k:"句型：Can you...? 的回答",e:"Can you...? 问“你会……吗？”肯定回答 Yes, I can.，否定 No, I can't.。"},
{i:1018,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can play the piano.” 中 the 说明 piano 是？",o:["运动","食物","动物","乐器"],a:3,k:"语法：乐器前加 the",e:"play + the + 乐器（如 the piano、the pipa）；play + 球类不加 the。"},
{i:1019,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can't dance.” 的否定形式，can't 是？",o:["不会、不能","必须","想要","会"],a:0,k:"词汇：can't 不会",e:"can't = cannot，意为“不会、不能”，I can't dance.（我不会跳舞。）"},
{i:1020,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“What about you?” 的意思是？",o:["你是谁？","你几岁？","你呢？","你在哪？"],a:2,k:"句型：What about you?",e:"What about you? 意为“你呢？”，用于反问对方同样的问题。"},
{i:1021,c:"en-4",ch:"五上·Unit 4 What can you do?",f:1,q:"——Can you ____（游泳）?——Yes, I can.",o:[],a:"swim",k:"句型：Can you...? 问能力",e:"Can you swim? 你会游泳吗？can 后接动词原形 swim。"},
{i:1022,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can sing English songs.” 意思是？",o:["我会唱英文歌","我会写英文歌","我喜欢英文歌","我会唱中文歌"],a:0,k:"句型：I can sing...",e:"I can sing English songs. 意为“我会唱英文歌”，song 歌。"},
{i:1023,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“party” 的意思是？",o:["比赛","聚会","作业","考试"],a:1,k:"词汇：party 聚会",e:"party 聚会、派对，have a party 举行聚会。"},
{i:1024,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"——Can you do any kung fu?——____",o:["No, I don't.","No, I can't.","No, I am not.","No, I won't."],a:1,k:"句型：Can you...? 否定回答",e:"Can you...? 的否定回答 No, I can't.，助动词用 can。"},
{i:1025,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can draw cartoons.” 中 cartoon 意思是？",o:["照片","地图","卡通画","表格"],a:2,k:"词汇：cartoon 卡通",e:"cartoon 卡通画、漫画，draw cartoons 画卡通画。"},
{i:1026,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“next” 在 “next Tuesday” 中意思是？",o:["前（个）","这（个）","上（个）","下（个）"],a:3,k:"词汇：next 下一个",e:"next 下一个，next Tuesday 下周二，last Tuesday 上周二。"},
{i:1027,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“wonderful” 的意思是？",o:["安静的","普通的","糟糕的","精彩的"],a:3,k:"词汇：wonderful 精彩的",e:"wonderful 精彩的、极好的，a wonderful party 精彩的聚会。"},
{i:1028,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can cook delicious food.” 意思是？",o:["我会吃美味的食物","我喜欢美味的食物","我不会做饭","我会做美味的食物"],a:3,k:"句型：can + 动词原形",e:"I can cook delicious food. 意为“我会做美味的食物”，cook 做饭。"},
{i:1029,c:"en-4",ch:"五上·Unit 4 What can you do?",f:1,q:"I can do ____ ____（武术）.",o:[],a:"kung fu",k:"短语：do kung fu 练武术",e:"do kung fu 练武术，固定搭配，注意拼写 kung fu。"},
{i:1030,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“Can you play basketball?” 的否定回答是？",o:["No, I am not.","No, I don't.","No, I can't.","No, I didn't."],a:2,k:"句型：Can 问句的回答",e:"Can 开头的一般疑问句，否定回答用 No, I can't.。"},
{i:1031,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can help you.” 的意思是？",o:["我不帮你","我能帮助你","你能帮助我","谢谢你的帮助"],a:1,k:"句型：I can help you.",e:"I can help you. 意为“我能帮助你”，help 帮助。"},
{i:1032,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“Let's have a party!” 中 Let's 是？",o:["我们","他们","你们","让我们"],a:3,k:"句型：Let's = Let us",e:"Let's = Let us，意为“让我们”，Let's have a party! 让我们开个派对吧！"},
{i:1033,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can't do any kung fu.” 中 any 用于？",o:["问句","肯定句","否定句","感叹句"],a:2,k:"语法：any 用于否定句和疑问句",e:"any 常用于否定句和疑问句，I can't do any kung fu.（我一点武术也不会。）"},
{i:1034,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“What can you do for the party?” 意思是？",o:["你能为聚会做些什么？","聚会在哪？","聚会在什么时候？","你在哪聚会？"],a:0,k:"句型：What can you do for...?",e:"What can you do for the party? 意为“你能为聚会做些什么？”，for 为、为了。"},
{i:1035,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can draw pictures.” 中 draw pictures 意思是？",o:["拍照","写字","画画","看书"],a:2,k:"短语：draw pictures 画画",e:"draw pictures 画画，draw 画，picture 图画。"},
{i:1036,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“have a try” 的意思是？",o:["试一试","想一想","看一看","玩一玩"],a:0,k:"短语：have a try 试一试",e:"have a try 试一试，try 尝试，Let me have a try. 让我试试。"},
{i:1037,c:"en-4",ch:"五上·Unit 4 What can you do?",f:0,q:"“I can play basketball well.” 中 well 意思是？",o:["好（地）","坏的","很好","快的"],a:0,k:"语法：well 修饰动词",e:"well 是副词“好地”，修饰动词 play：play basketball well 篮球打得好。"}
);
