/* 英语题库 批2：PEP 五上 Unit5-Unit6 + 五下 Unit1-Unit2（选项顺序已打乱，答案位置随机） */
QA.en.push(
{i:1038,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“clock” 的意思是？",o:["植物","钟表","瓶子","照片"],a:1,k:"词汇：clock 钟表",e:"clock 钟表，wall clock 挂钟；注意与 o'clock（点钟）区分。"},
{i:1039,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“plant” 的意思是？",o:["植物","照片","自行车","钟表"],a:0,k:"词汇：plant 植物",e:"plant 植物，也可以作动词“种植”，plant trees 种树。"},
{i:1040,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“水瓶”用英语怎么说？",o:["photo","bike","water bottle","clock"],a:2,k:"词汇：water bottle 水瓶",e:"water bottle 水瓶，water 水 + bottle 瓶子。"},
{i:1041,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“photo” 的意思是？",o:["植物","照片","瓶子","椅子"],a:1,k:"词汇：photo 照片",e:"photo 照片，复数 photos（直接加 s），take photos 拍照。"},
{i:1042,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“自行车”用英语怎么说？",o:["bike","bus","car","train"],a:0,k:"词汇：bike 自行车",e:"bike 自行车，ride a bike 骑自行车。"},
{i:1043,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“front” 的意思是？",o:["上面","后面","旁边","前面"],a:3,k:"词汇：front 前面",e:"front 前面，in front of 在……前面，与 behind（后面）相对。"},
{i:1044,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“between” 的意思是？",o:["在……上面","在……之间","在……后面","在……旁边"],a:1,k:"介词：between 在……之间",e:"between 在两者之间，between A and B 在 A 和 B 之间。"},
{i:1045,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“above” 的意思是？",o:["在……上面","在……下面","在……前面","在……里面"],a:0,k:"介词：above 在……上面",e:"above 在……上方（不接触），与 below（在……下方）相对。"},
{i:1046,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“beside” 的意思是？",o:["在……旁边","在……后面","在……上面","在……之间"],a:0,k:"介词：beside 在……旁边",e:"beside 在……旁边，相当于 next to，如 beside the bed 床旁边。"},
{i:1047,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“behind” 的意思是？",o:["在……旁边","在……里面","在……后面","在……前面"],a:2,k:"介词：behind 在……后面",e:"behind 在……后面，反义词 in front of 在……前面。"},
{i:1048,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:1,q:"There is a big ____（床）in my room.",o:[],a:"bed",k:"句型：There is...",e:"There is a big bed in my room.（我房间里有一张大床。）There is + 单数名词。"},
{i:1049,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“There is a clock on the wall.” 意思是？",o:["床下有一个钟表","门外有一个钟表","桌子上有一个钟表","墙上有一个钟表"],a:3,k:"句型：There is... 方位表达",e:"There is a clock on the wall. 意为“墙上有一个钟表”，on the wall 在墙上。"},
{i:1050,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“The ball is beside the dog.” 中 ball 在狗的？",o:["里面","上面","旁边","下面"],a:2,k:"介词：beside 旁边",e:"The ball is beside the dog. 意为“球在狗旁边”，beside 在……旁边。"},
{i:1051,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"——Where is the photo?——It's ____ the bed. 在床的上方用？",o:["above","under","beside","behind"],a:0,k:"介词：above 在……上方",e:"照片在床的上方用 above（不接触）：It's above the bed.。"},
{i:1052,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“There are some books on the desk.” 中 There are 表示？",o:["有（单数）","有（复数）","想要","是"],a:1,k:"句型：There are + 复数名词",e:"There are + 复数名词，表示“有……”，如 There are some books. 有一些书。"},
{i:1053,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“between” 和 “beside” 的区别是？",o:["beside 在两者之间，between 在旁边","between 在两者之间，beside 在旁边","都是上面","意思一样"],a:1,k:"介词辨析：between/beside",e:"between 在两者之间（中间夹着），beside 在旁边（紧挨着）。"},
{i:1054,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“My room is really nice.” 中 really 意思是？",o:["很快","真的、非常","很少","很坏"],a:1,k:"词汇：really 非常",e:"really 真的、非常，My room is really nice.（我的房间真的很好。）"},
{i:1055,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:1,q:"There are many ____（照片）on the wall.",o:[],a:"photos",k:"词汇：photo 复数 photos",e:"photo 的复数是 photos（直接加 s），There are many photos on the wall. 墙上有许多照片。"},
{i:1056,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“The cat is behind the door.” 意思是？",o:["猫在门上面","猫在门旁边","猫在门前面","猫在门后面"],a:3,k:"介词：behind 后面",e:"The cat is behind the door. 意为“猫在门后面”，behind 在……后面。"},
{i:1057,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“lots of” 的意思是？",o:["没有","许多","一些","几个"],a:1,k:"短语：lots of 许多",e:"lots of = a lot of，意为“许多”，可修饰可数和不可数名词。"},
{i:1058,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“Is there a bike in your room?” 的肯定回答是？",o:["Yes, it is.","Yes, I am.","Yes, there is.","Yes, there are."],a:2,k:"句型：Is there...? 的回答",e:"Is there...? 问“有……吗？（单数）”肯定回答 Yes, there is.。"},
{i:1059,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“front” 常和哪个介词搭配表示“在……前面”？",o:["of","at","on","in"],a:3,k:"短语：in front of",e:"in front of 在……前面（外部），in the front of 在……内部的前部。"},
{i:1060,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:1,q:"The water bottle is ____（在……上面）the desk.",o:[],a:"on",k:"介词：on 在……上面",e:"on 在……上面（接触表面），The water bottle is on the desk.（水瓶在桌上。）"},
{i:1061,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“There is” 后面接？",o:["形容词","动词","复数名词","单数名词"],a:3,k:"语法：There is + 单数",e:"There is 后接单数名词或不可数名词，There are 后接复数名词。"},
{i:1062,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“grandparents” 的意思是？",o:["祖父母","朋友","兄弟姐妹","父母"],a:0,k:"词汇：grandparents 祖父母",e:"grandparents 祖父母（外祖父母），grandfather 爷爷、grandmother 奶奶。"},
{i:1063,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“What's in the room?” 中 in the room 意思是？",o:["在房间里","在房间外","在床下","在桌子旁"],a:0,k:"短语：in the room 在房间里",e:"in the room 在房间里，What's in the room? 房间里有什么？"},
{i:1064,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“The computer is on the desk.” 中 computer 意思是？",o:["电视","收音机","电话","电脑"],a:3,k:"词汇：computer 电脑",e:"computer 电脑，on the desk 在书桌上。"},
{i:1065,c:"en-5",ch:"五上·Unit 5 There is a big bed",f:0,q:"“a lot of” 和 “lots of” 都表示？",o:["很少","没有","一些","许多"],a:3,k:"短语：a lot of / lots of",e:"a lot of = lots of，意为“许多”，用法相同。"},
{i:1066,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“forest” 的意思是？",o:["湖泊","高山","河流","森林"],a:3,k:"词汇：forest 森林",e:"forest 森林，in the forest 在森林里。"},
{i:1067,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“湖泊”用英语怎么说？",o:["river","hill","tree","lake"],a:3,k:"词汇：lake 湖泊",e:"lake 湖泊，如 West Lake 西湖。"},
{i:1068,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“river” 的意思是？",o:["湖泊","河流","小溪","海洋"],a:1,k:"词汇：river 河流",e:"river 河流，如 the Yellow River 黄河。"},
{i:1069,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“mountain” 的意思是？",o:["草地","小山","高山","森林"],a:2,k:"词汇：mountain 高山",e:"mountain 高山，如 mountain climbing 爬山。"},
{i:1070,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“hill” 和 “mountain” 的区别是？",o:["都是河流","hill 是小山，mountain 是高山","一样大","mountain 是小山，hill 是高山"],a:1,k:"词汇辨析：hill/mountain",e:"hill 小山（较矮），mountain 高山（高大），如泰山是 mountain。"},
{i:1071,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“bridge” 的意思是？",o:["桥","树","房子","村庄"],a:0,k:"词汇：bridge 桥",e:"bridge 桥，over the river 在河上，a bridge over the river 河上的桥。"},
{i:1072,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“building” 的意思是？",o:["农场","建筑物","村庄","房子"],a:1,k:"词汇：building 建筑物",e:"building 建筑物、大楼，如 tall building 高楼。"},
{i:1073,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“village” 的意思是？",o:["房子","公园","城市","村庄"],a:3,k:"词汇：village 村庄",e:"village 村庄，in the village 在村庄里；city 城市。"},
{i:1074,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“house” 的意思是？",o:["学校","医院","房子","商店"],a:2,k:"词汇：house 房子",e:"house 房子、住宅，与 home（家）不同，house 侧重建筑物。"},
{i:1075,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“nature park” 的意思是？",o:["自然公园","动物园","游乐园","植物园"],a:0,k:"短语：nature park 自然公园",e:"nature park 自然公园，nature 自然。"},
{i:1076,c:"en-6",ch:"五上·Unit 6 In a nature park",f:1,q:"There is a ____（湖泊）in the park.",o:[],a:"lake",k:"句型：There is a lake",e:"There is a lake in the park.（公园里有一个湖泊。）lake 湖泊。"},
{i:1077,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"——Is there a river in the park?——____",o:["Yes, there are.","Yes, there is.","Yes, it is.","Yes, I do."],a:1,k:"句型：Is there...? 的回答",e:"Is there a river...? 问“有河流吗？（单数）”肯定回答 Yes, there is.。"},
{i:1078,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"——Are there any trees in the park?——____",o:["Yes, there are.","No, there is.","Yes, they are.","Yes, there is."],a:0,k:"句型：Are there any...? 的回答",e:"Are there any trees...? 问“有树吗？（复数）”肯定回答 Yes, there are.。"},
{i:1079,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“There are many trees.” 中 many 修饰？",o:["可数名词复数","不可数名词","形容词","动词"],a:0,k:"语法：many + 复数名词",e:"many 修饰可数名词复数，many trees 许多树；much 修饰不可数名词。"},
{i:1080,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“Are there any ducks?” 中 any 用在？",o:["肯定句","疑问句和否定句","感叹句","祈使句"],a:1,k:"语法：any 的用法",e:"any 用于疑问句和否定句，some 用于肯定句。Are there any ducks? 有鸭子吗？"},
{i:1081,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“Let's go to the forest.” 意思是？",o:["我们去森林吧","我们去学校吧","我们去公园吧","我们去商店吧"],a:0,k:"句型：Let's go to...",e:"Let's go to the forest. 意为“我们去森林吧”，Let's 让我们。"},
{i:1082,c:"en-6",ch:"五上·Unit 6 In a nature park",f:1,q:"There is a ____（桥）over the river.",o:[],a:"bridge",k:"词汇：bridge 桥",e:"There is a bridge over the river.（河上有一座桥。）bridge 桥。"},
{i:1083,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“The nature park is so quiet.” 中 quiet 意思是？",o:["巨大的","安静的","吵闹的","美丽的"],a:1,k:"词汇：quiet 安静的",e:"quiet 安静的，注意与 quite（相当）区分。"},
{i:1084,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“Is there a hill in the park?” 的否定回答是？",o:["No, it isn't.","No, there isn't.","No, I'm not.","No, there aren't."],a:1,k:"句型：Is there...? 否定回答",e:"Is there...?（单数）否定回答 No, there isn't.。"},
{i:1085,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“We can see a village.” 意思是？",o:["我们能看见一个村庄","村庄很漂亮","我们看不见村庄","我们住在村庄"],a:0,k:"句型：We can see...",e:"We can see a village. 意为“我们能看见一个村庄”，see 看见。"},
{i:1086,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“There is a house in the village.” 中 house 是？",o:["河流","动物","房子","树木"],a:2,k:"词汇：house 房子",e:"house 房子，There is a house in the village.（村庄里有一座房子。）"},
{i:1087,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“on the mountain” 意思是？",o:["在山旁","在山上","在山里","在山下"],a:1,k:"短语：on the mountain 在山上",e:"on the mountain 在山上（山坡上），on the hill 在小山上。"},
{i:1088,c:"en-6",ch:"五上·Unit 6 In a nature park",f:1,q:"There are some ____（树）near the lake.",o:[],a:"trees",k:"词汇：tree 复数 trees",e:"tree 树，复数 trees；There are some trees near the lake.（湖附近有一些树。）"},
{i:1089,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“It's so beautiful.” 中 beautiful 意思是？",o:["新鲜的","安静的","巨大的","美丽的"],a:3,k:"词汇：beautiful 美丽的",e:"beautiful 美丽的，It's so beautiful.（太美了。）"},
{i:1090,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“There aren't any birds.” 意思是？",o:["没有鸟","鸟很漂亮","有很多鸟","有一些鸟"],a:0,k:"句型：There aren't any...",e:"There aren't any birds. 意为“没有鸟”，否定句中用 any。"},
{i:1091,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“I love the nature park.” 中 love 意思是？",o:["讨厌","害怕","想要","爱、喜欢"],a:3,k:"词汇：love 喜爱",e:"love 爱、喜欢，I love the nature park.（我喜欢这个自然公园。）"},
{i:1092,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“Where is the nature park?” 中 Where 问？",o:["人物","时间","地点","数量"],a:2,k:"句型：Where 问地点",e:"Where 问地点“在哪里”，Where is the nature park? 自然公园在哪里？"},
{i:1093,c:"en-6",ch:"五上·Unit 6 In a nature park",f:0,q:"“There are some small houses.” 中 small 意思是？",o:["高的","大的","矮的","小的"],a:3,k:"词汇：small 小的",e:"small 小的，反义词 big 大的，small houses 小房子。"},
{i:1094,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“吃早饭”用英语怎么说？",o:["have lunch","eat dinner","eat lunch","eat breakfast"],a:3,k:"短语：eat breakfast 吃早饭",e:"eat breakfast 吃早饭，eat dinner 吃晚饭，have lunch 吃午饭。"},
{i:1095,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“have class” 的意思是？",o:["放学","下课","上课","上学"],a:2,k:"短语：have class 上课",e:"have class 上课，have classes 上课（多节），下课是 be out of class。"},
{i:1096,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“做运动”用英语怎么说？",o:["play games","do sports","play sports","make sports"],a:2,k:"短语：play sports 做运动",e:"play sports 做运动、锻炼，固定搭配。"},
{i:1097,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“eat dinner” 的意思是？",o:["吃午饭","吃早饭","吃晚饭","吃零食"],a:2,k:"短语：eat dinner 吃晚饭",e:"eat dinner 吃晚饭，breakfast 早饭、lunch 午饭、dinner 晚饭。"},
{i:1098,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“做早操”用英语怎么说？",o:["do homework","do housework","do morning exercises","do kung fu"],a:2,k:"短语：do morning exercises 做早操",e:"do morning exercises 做早操，morning exercises 早操（常用复数）。"},
{i:1099,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“clean my room” 的意思是？",o:["擦我的桌子","洗我的衣服","整理我的书包","打扫我的房间"],a:3,k:"短语：clean my room 打扫房间",e:"clean my room 打扫我的房间，clean 打扫、清洁。"},
{i:1100,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“去散步”用英语怎么说？",o:["go for a walk","go swimming","go shopping","go to school"],a:0,k:"短语：go for a walk 去散步",e:"go for a walk 去散步，walk 散步。"},
{i:1101,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“go shopping” 的意思是？",o:["去上学","去散步","去游泳","去购物"],a:3,k:"短语：go shopping 去购物",e:"go shopping 去购物，go + doing 表示去做某事。"},
{i:1102,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“take a dancing class” 的意思是？",o:["上舞蹈课","上体育课","上美术课","上音乐课"],a:0,k:"短语：take a dancing class 上舞蹈课",e:"take a dancing class 上舞蹈课，take a class 上课。"},
{i:1103,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“When do you get up?” 中 get up 意思是？",o:["吃饭","睡觉","上学","起床"],a:3,k:"短语：get up 起床",e:"get up 起床，go to bed 上床睡觉。"},
{i:1104,c:"en-7",ch:"五下·Unit 1 My day",f:1,q:"I ____（吃早饭）at 7 o'clock.",o:[],a:"eat breakfast",k:"句型：I eat breakfast at...",e:"I eat breakfast at 7 o'clock.（我七点吃早饭。）at + 具体时间。"},
{i:1105,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"——When do you go to bed?——____",o:["On Monday.","Yes, I do.","At 9 o'clock.","I like it."],a:2,k:"句型：When do you...? 的回答",e:"问“你什么时候睡觉？”答语用 At + 时间：At 9 o'clock.（九点。）"},
{i:1106,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“at 6:30” 中的 at 表示？",o:["在几点","在星期几","在哪天","在哪里"],a:0,k:"介词：at + 具体时刻",e:"at 用于具体时刻前，at 6:30 在六点半；on 用于星期、日期前。"},
{i:1107,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“I usually get up at 6:30.” 中 usually 意思是？",o:["通常","从不","总是","有时"],a:0,k:"词汇：频度副词 usually",e:"usually 通常，always 总是，never 从不，often 经常。"},
{i:1108,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“What do you do on the weekend?” 意思是？",o:["你几点起床？","你周一做什么？","你周末做什么？","你喜欢什么？"],a:2,k:"句型：What do you do on the weekend?",e:"What do you do on the weekend? 意为“你周末做什么？”，on the weekend 在周末。"},
{i:1109,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“I often clean my room on Saturdays.” 意思是？",o:["我不打扫房间","我星期六经常打扫房间","我每天打扫房间","我星期六从不打扫房间"],a:1,k:"句型：on + 星期复数",e:"I often clean my room on Saturdays. 意为“我星期六经常打扫房间”，on Saturdays 每逢周六。"},
{i:1110,c:"en-7",ch:"五下·Unit 1 My day",f:1,q:"I do ____ ____（早操）every day.",o:[],a:"morning exercises",k:"短语：morning exercises 早操",e:"do morning exercises 做早操，exercises 用复数。"},
{i:1111,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“When” 问的是？",o:["人物","时间","地点","原因"],a:1,k:"句型：When 问时间",e:"When 问“什么时候”，When do you...? 你什么时候……？"},
{i:1112,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“I have dinner with my family.” 中 with 意思是？",o:["在……里面","没有","在……旁边","和……一起"],a:3,k:"介词：with 和……一起",e:"with 和……一起，with my family 和我的家人一起。"},
{i:1113,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“at night” 的意思是？",o:["在下午","在中午","在晚上","在早上"],a:2,k:"短语：at night 在晚上",e:"at night 在晚上（夜里），in the morning 在早上。"},
{i:1114,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“in the morning” 的意思是？",o:["在晚上","在早上","在中午","在下午"],a:1,k:"短语：in the morning 在早上",e:"in the morning 在早上，in the afternoon 在下午，in the evening 在傍晚。"},
{i:1115,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“I play sports with my father.” 意思是？",o:["我和爸爸一起做运动","我不做运动","我爸爸和我一起玩","我喜欢做运动"],a:0,k:"句型：with 一起做",e:"I play sports with my father. 意为“我和爸爸一起做运动”。"},
{i:1116,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“finish” 的意思是？",o:["玩耍","开始","学习","完成"],a:3,k:"词汇：finish 完成",e:"finish 完成，finish my homework 完成作业。"},
{i:1117,c:"en-7",ch:"五下·Unit 1 My day",f:1,q:"I often ____ ____（散步）after dinner.",o:[],a:"go for a walk",k:"短语：go for a walk 散步",e:"go for a walk 去散步，after dinner 晚饭后。"},
{i:1118,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“I go to bed at 9:30.” 中 go to bed 意思是？",o:["起床","上床睡觉","去上学","回家"],a:1,k:"短语：go to bed 睡觉",e:"go to bed 上床睡觉，get up 起床。"},
{i:1119,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“My day is busy.” 中 busy 意思是？",o:["无聊的","快乐的","忙碌的","轻松的"],a:2,k:"词汇：busy 忙碌的",e:"busy 忙碌的，I'm busy.（我很忙。）"},
{i:1120,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“I get up at 6:30.” 中 6:30 读作？",o:["sixty thirty","six thirty","six three","six o'clock"],a:1,k:"时间表达：6:30 读法",e:"6:30 读作 six thirty，先读小时再读分钟。"},
{i:1121,c:"en-7",ch:"五下·Unit 1 My day",f:0,q:"“have lunch” 的意思是？",o:["吃午饭","吃早饭","吃水果","吃晚饭"],a:0,k:"短语：have lunch 吃午饭",e:"have lunch 吃午饭，have breakfast 吃早饭，have dinner 吃晚饭。"},
{i:1122,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“spring” 的意思是？",o:["冬天","秋天","春天","夏天"],a:2,k:"词汇：季节 spring",e:"spring 春天，in spring 在春天。"},
{i:1123,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“夏天”用英语怎么说？",o:["spring","summer","winter","autumn"],a:1,k:"词汇：季节 summer",e:"summer 夏天，summer holiday 暑假。"},
{i:1124,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“autumn” 的意思是？",o:["春天","夏天","秋天","冬天"],a:2,k:"词汇：季节 autumn",e:"autumn 秋天（美式 fall），in autumn 在秋天。"},
{i:1125,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“winter” 的意思是？",o:["秋天","冬天","夏天","春天"],a:1,k:"词汇：季节 winter",e:"winter 冬天，winter holiday 寒假，make a snowman 堆雪人。"},
{i:1126,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“season” 的意思是？",o:["天气","季节","温度","月份"],a:1,k:"词汇：season 季节",e:"season 季节，four seasons 四季。"},
{i:1127,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“堆雪人”用英语怎么说？",o:["make a kite","make a cake","make a snowman","make a card"],a:2,k:"短语：make a snowman 堆雪人",e:"make a snowman 堆雪人，snowman 雪人，复数 snowmen。"},
{i:1128,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“pick apples” 的意思是？",o:["买苹果","种苹果","吃苹果","摘苹果"],a:3,k:"短语：pick apples 摘苹果",e:"pick apples 摘苹果，pick 摘、采，常与秋天搭配。"},
{i:1129,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“去野餐”用英语怎么说？",o:["go shopping","go swimming","go on a picnic","go home"],a:2,k:"短语：go on a picnic 去野餐",e:"go on a picnic 去野餐，picnic 野餐。"},
{i:1130,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“go swimming” 的意思是？",o:["去跑步","去购物","去散步","去游泳"],a:3,k:"短语：go swimming 去游泳",e:"go swimming 去游泳，go + 动词ing 表示去做某事。"},
{i:1131,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“plant flowers” 的意思是？",o:["种花","买花","摘花","浇水"],a:0,k:"短语：plant flowers 种花",e:"plant flowers 种花，plant 种植。"},
{i:1132,c:"en-8",ch:"五下·Unit 2 My favourite season",f:1,q:"——Which season do you like best?——I like ____（冬天）best.",o:[],a:"winter",k:"句型：Which season do you like best?",e:"Which season do you like best? 问“你最喜欢哪个季节？”，答 I like winter best.。"},
{i:1133,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“Which season do you like best?” 中 best 意思是？",o:["最","好","坏","快"],a:0,k:"语法：like...best 最喜欢",e:"like...best 意为“最喜欢”，best 是 well 的最高级“最”。"},
{i:1134,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"——Why do you like summer?——____",o:["Because I can go swimming.","Because I can make a snowman.","I don't know.","Because I can pick apples."],a:0,k:"句型：Why...? Because...",e:"Why 问原因，Because 回答：Because I can go swimming.（因为我能去游泳。）"},
{i:1135,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“because” 的意思是？",o:["所以","因为","而且","但是"],a:1,k:"词汇：because 因为",e:"because 因为，引导原因状语从句，回答 Why 的问句。"},
{i:1136,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“I like spring best.” 意思是？",o:["我最喜欢春天","我喜欢春天","我讨厌春天","春天很冷"],a:0,k:"句型：like...best",e:"I like spring best. 意为“我最喜欢春天”，best 表示“最”。"},
{i:1137,c:"en-8",ch:"五下·Unit 2 My favourite season",f:1,q:"I can ____（堆雪人）in winter.",o:[],a:"make a snowman",k:"短语：make a snowman 堆雪人",e:"I can make a snowman in winter.（冬天我能堆雪人。）"},
{i:1138,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“The weather is hot.” 中 hot 意思是？",o:["暖和的","热的","凉爽的","冷的"],a:1,k:"词汇：hot 热的",e:"hot 热的，The weather is hot.（天气很热。）cold 冷的。"},
{i:1139,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“It's cold and snowy.” 意思是？",o:["天气下雨","天气又热又晴","天气很凉爽","天气又冷又下雪"],a:3,k:"句型：It's + 天气",e:"It's cold and snowy. 意为“天气寒冷又下雪”，snowy 下雪的。"},
{i:1140,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“There are beautiful flowers everywhere.” 中 everywhere 意思是？",o:["到处","某处","没有地方","哪里"],a:0,k:"词汇：everywhere 到处",e:"everywhere 到处，由 every + where 组成，There are flowers everywhere. 到处是花。"},
{i:1141,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“go on a picnic” 在哪个季节最合适？",o:["winter","summer","spring","都可以"],a:2,k:"文化常识：野餐的季节",e:"春天（spring）天气温暖、万物复苏，最适合野餐；也可用 go on a picnic 表达春游。"},
{i:1142,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“I like winter because I can skate.” 中 skate 意思是？",o:["跳舞","滑冰","跑步","游泳"],a:1,k:"词汇：skate 滑冰",e:"skate 滑冰，go skating 去滑冰，skate 在冬天进行。"},
{i:1143,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“Which season do you like best?” 的答语是？",o:["Yes, I do.","I like apples.","It's autumn.","I like autumn best."],a:3,k:"句型：Which season...? 答语",e:"回答 Which season do you like best? 用 I like + 季节 + best.。"},
{i:1144,c:"en-8",ch:"五下·Unit 2 My favourite season",f:1,q:"I like ____（秋天）because the leaves are pretty.",o:[],a:"autumn",k:"词汇：autumn 秋天",e:"I like autumn because the leaves are pretty.（我喜欢秋天，因为叶子很美。）"},
{i:1145,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“the leaves fall” 的意思是？",o:["叶子很多","叶子长大","树叶很绿","叶子落下"],a:3,k:"词汇：leaves/fall",e:"leaves 是 leaf 的复数“树叶”，fall 落下、掉落，秋天树叶落下。"},
{i:1146,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“warm” 和 “cool” 分别表示？",o:["潮湿的、干燥的","晴的、雨的","暖和的、凉爽的","热的、冷的"],a:2,k:"词汇：warm/cool",e:"warm 暖和的（春），cool 凉爽的（秋），hot 热的（夏），cold 冷的（冬）。"},
{i:1147,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“There are four seasons in a year.” 意思是？",o:["一年有十二个月","四季都很美","一年有三百六十五天","一年有四个季节"],a:3,k:"句型：There are four seasons",e:"There are four seasons in a year. 意为“一年有四个季节”。"},
{i:1148,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“I can fly kites in spring.” 意思是？",o:["我春天可以摘苹果","我春天可以游泳","我春天可以放风筝","我春天可以滑雪"],a:2,k:"句型：fly kites 放风筝",e:"I can fly kites in spring. 意为“我春天可以放风筝”，fly kites 放风筝。"},
{i:1149,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“golden” 在 “golden leaves” 中意思是？",o:["金色的","蓝色的","绿色的","红色的"],a:0,k:"词汇：golden 金色的",e:"golden 金色的，golden leaves 金色的叶子（秋天的落叶）。"},
{i:1150,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“It's snowing.” 意思是？",o:["正在下雪","正在刮风","正在下雨","正在打雷"],a:0,k:"句型：It's snowing. 正在下雪",e:"It's snowing. 正在下雪，现在进行时；snow 下雪。"},
{i:1151,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“I like summer best because of the ice cream.” 中 because of 意思是？",o:["所以","虽然","但是","因为"],a:3,k:"短语：because of 因为",e:"because of 因为（后接名词短语），because 因为（后接句子）。"},
{i:1152,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“swim” 的现在进行时是？",o:["swam","swiming","swims","swimming"],a:3,k:"语法：swim 的 ing 形式",e:"swim 以重读闭音节结尾，双写 m 再加 ing：swimming。"},
{i:1153,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“The colours are beautiful in autumn.” 中 colours 意思是？",o:["树叶","颜色","天空","花朵"],a:1,k:"词汇：colour 颜色",e:"colours 颜色（英式），美式 colors。"},
{i:1154,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“Which is your favourite season?” 中 favourite 意思是？",o:["特别的","普通的","最喜欢的","讨厌的"],a:2,k:"词汇：favourite 最喜欢的",e:"favourite 最喜欢的，my favourite season 我最喜欢的季节。"},
{i:1155,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“go skiing” 的意思是？",o:["去滑冰","去滑雪","去跑步","去游泳"],a:1,k:"短语：go skiing 去滑雪",e:"go skiing 去滑雪，ski 滑雪，在冬天进行。"},
{i:1156,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“It's warm in spring.” 中 warm 意思是？",o:["凉爽的","炎热的","暖和的","寒冷的"],a:2,k:"词汇：warm 暖和的",e:"warm 暖和的，It's warm in spring.（春天天气暖和。）"},
{i:1157,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“I can pick apples in autumn.” 意思是？",o:["秋天我可以摘苹果","秋天我可以种花","秋天我可以滑雪","秋天我可以游泳"],a:0,k:"句型：pick apples 摘苹果",e:"I can pick apples in autumn. 意为“秋天我可以摘苹果”，摘苹果是秋天的活动。"},
{i:1158,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“snowman” 的复数形式是？",o:["snowsmen","snowmans","snowmanes","snowmen"],a:3,k:"语法：snowman 的复数",e:"snowman 的复数是不规则变化：snowmen（man→men）。"},
{i:1159,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“My favourite season is winter.” 意思是？",o:["我不喜欢冬天","我最喜欢的季节是冬天","我最喜欢的季节是夏天","冬天很冷"],a:1,k:"句型：My favourite season is...",e:"My favourite season is winter. 意为“我最喜欢的季节是冬天”。"},
{i:1160,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“go on a picnic” 的近义词是？",o:["go fishing","have a picnic","go swimming","go skating"],a:1,k:"短语：have a picnic 野餐",e:"go on a picnic = have a picnic，都表示“去野餐”。"},
{i:1161,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“There are green trees and pink flowers.” 中 pink 意思是？",o:["蓝色的","绿色的","黄色的","粉色的"],a:3,k:"词汇：pink 粉色的",e:"pink 粉色的，pink flowers 粉色的花。"},
{i:1162,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“I love the snow.” 中 snow 意思是？",o:["雨","云","风","雪"],a:3,k:"词汇：snow 雪",e:"snow 雪（名词），下雪（动词），snowy 下雪的。"},
{i:1163,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“Why?” 是用来问？",o:["时间","原因","数量","地点"],a:1,k:"句型：Why 问原因",e:"Why 问原因“为什么”，用 Because 回答。"},
{i:1164,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“I like spring. There are flowers everywhere.” 意思是？",o:["我喜欢春天，到处都有花","我喜欢秋天，叶子很美","我喜欢冬天，到处是雪","我不喜欢春天"],a:0,k:"句型：everywhere 到处",e:"I like spring. There are flowers everywhere. 意为“我喜欢春天，到处都有花”。"},
{i:1165,c:"en-8",ch:"五下·Unit 2 My favourite season",f:0,q:"“summer holiday” 的意思是？",o:["假期","寒假","周末","暑假"],a:3,k:"短语：summer holiday 暑假",e:"summer holiday 暑假，winter holiday 寒假。"}
);
