/* 英语题库 批3：PEP 五下 Unit3-Unit6（选项顺序已打乱，答案位置随机） */
QA.en.push(
{i:1166,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“一月”用英语怎么说？",o:["January","April","February","March"],a:0,k:"词汇：月份 January",e:"January 一月，缩写 Jan.，New Year's Day 在 January 1st。"},
{i:1167,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“February” 的意思是？",o:["二月","四月","三月","一月"],a:0,k:"词汇：月份 February",e:"February 二月，缩写 Feb.，是全年最短的月份。"},
{i:1168,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“三月”用英语怎么说？",o:["June","July","May","March"],a:3,k:"词汇：月份 March",e:"March 三月，缩写 Mar.，spring 春天通常从 March 开始。"},
{i:1169,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“April” 的意思是？",o:["三月","六月","四月","五月"],a:2,k:"词汇：月份 April",e:"April 四月，缩写 Apr.，April Fool's Day 愚人节在 4月1日。"},
{i:1170,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“五月”用英语怎么说？",o:["April","June","May","March"],a:2,k:"词汇：月份 May",e:"May 五月，Labor Day（劳动节）在 May 1st，May 还表示“可以”。"},
{i:1171,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“June” 的意思是？",o:["六月","五月","七月","八月"],a:0,k:"词汇：月份 June",e:"June 六月，Children's Day 儿童节在 June 1st。"},
{i:1172,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“七月”用英语怎么说？",o:["June","August","July","May"],a:2,k:"词汇：月份 July",e:"July 七月，Party's birthday 建党节在 July 1st。"},
{i:1173,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“August” 的意思是？",o:["八月","六月","九月","七月"],a:0,k:"词汇：月份 August",e:"August 八月，缩写 Aug.，暑假（summer holiday）常在 July 和 August。"},
{i:1174,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“九月”用英语怎么说？",o:["September","November","December","October"],a:0,k:"词汇：月份 September",e:"September 九月，缩写 Sep.，Teachers' Day 教师节在 September 10th。"},
{i:1175,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“October” 的意思是？",o:["十月","九月","十一月","十二月"],a:0,k:"词汇：月份 October",e:"October 十月，缩写 Oct.，National Day 国庆节在 October 1st。"},
{i:1176,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“十一月”用英语怎么说？",o:["September","December","October","November"],a:3,k:"词汇：月份 November",e:"November 十一月，缩写 Nov.，Thanksgiving 感恩节在 November。"},
{i:1177,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“December” 的意思是？",o:["一月","十二月","二月","十一月"],a:1,k:"词汇：月份 December",e:"December 十二月，缩写 Dec.，Christmas 圣诞节在 December 25th。"},
{i:1178,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“month” 的意思是？",o:["天","年","星期","月"],a:3,k:"词汇：month 月份",e:"month 月，there are twelve months in a year（一年有十二个月）。"},
{i:1179,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“year” 的意思是？",o:["年","月","日","时"],a:0,k:"词汇：year 年",e:"year 年，a year 一年，this year 今年，next year 明年。"},
{i:1180,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“sports meet” 的意思是？",o:["运动会场","运动会面","体育课","运动会"],a:3,k:"短语：sports meet 运动会",e:"sports meet 运动会，meet 这里指“集会”，校运会通常在 spring 举行。"},
{i:1181,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“trip” 的意思是？",o:["聚会","旅行","比赛","演出"],a:1,k:"词汇：trip 旅行",e:"trip 旅行、出游，school trip 学校旅行（春游/秋游）。"},
{i:1182,c:"en-9",ch:"五下·Unit 3 My school calendar",f:1,q:"——When is the trip?——It's in ____（十月）.",o:[],a:"October",k:"句型：When is...? It's in...",e:"问“旅行什么时候？”答语用 It's in + 月份：It's in October.（在十月。）"},
{i:1183,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“When is the party?” 中 When 问？",o:["地点","原因","时间","人物"],a:2,k:"句型：When 问时间",e:"When is the party? 问“聚会是什么时候？”，When 询问时间。"},
{i:1184,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“Easter” 的意思是？",o:["复活节","感恩节","春节","圣诞节"],a:0,k:"文化常识：Easter 复活节",e:"Easter 复活节，在每年春季，人们会画复活节彩蛋（Easter eggs）。"},
{i:1185,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“There are twelve months in a year.” 意思是？",o:["一年有十二个月","一周有七天","一年有四个季节","一个月有三十天"],a:0,k:"句型：There are... in a year",e:"There are twelve months in a year. 意为“一年有十二个月”。"},
{i:1186,c:"en-9",ch:"五下·Unit 3 My school calendar",f:1,q:"My birthday is in ____（五月）.",o:[],a:"May",k:"句型：My birthday is in...",e:"My birthday is in May.（我的生日在五月。）in + 月份。"},
{i:1187,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“in October” 表示？",o:["到十月","在十月一号","在十月","从十月"],a:2,k:"介词：in + 月份",e:"in + 月份表示“在……月”，in October 在十月；具体某日用 on。"},
{i:1188,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“We'll go to the Great Wall.” 中 We'll 是？",o:["我们正在","我们能够","我们曾经","我们将要"],a:3,k:"语法：We'll = We will",e:"We'll 是 We will 的缩写，意为“我们将要”，表示将来。"},
{i:1189,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“a few” 的意思是？",o:["没有","一些（修饰不可数名词）","许多","一些（修饰可数名词）"],a:3,k:"语法：a few 修饰可数名词",e:"a few 一些（修饰可数名词复数），a little 一些（修饰不可数名词）。"},
{i:1190,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“the Great Wall” 的意思是？",o:["高墙","围墙","长城","大墙"],a:2,k:"专有名词：the Great Wall 长城",e:"the Great Wall 长城，We'll go to the Great Wall.（我们将去长城。）"},
{i:1191,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“When is Children's Day?” 正确答案是？",o:["It's in June.","It's in April.","It's in May.","It's in July."],a:0,k:"文化常识：儿童节",e:"Children's Day（儿童节）在 June 1st（六月一日），所以答 It's in June.。"},
{i:1192,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“Teachers' Day” 在几月？",o:["October","July","September","August"],a:2,k:"文化常识：教师节",e:"Teachers' Day（教师节）在 September 10th（九月十日）。"},
{i:1193,c:"en-9",ch:"五下·Unit 3 My school calendar",f:1,q:"——When is the sports meet?——It's in ____（四月）.",o:[],a:"April",k:"句型：When is the sports meet?",e:"When is the sports meet? 问“运动会什么时候？”答 It's in April.（在四月。）"},
{i:1194,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“English test” 的意思是？",o:["英语课","英语测试","英语老师","英语书"],a:1,k:"短语：English test 英语测试",e:"English test 英语测试，test 测试、考试。"},
{i:1195,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“I'll make a card.” 中 make a card 意思是？",o:["做一张卡片","画一幅画","买一本书","写一封信"],a:0,k:"短语：make a card 做卡片",e:"make a card 做卡片，I'll make a card for my mum.（我要给妈妈做一张卡片。）"},
{i:1196,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“What will you do for your mum?” 中 mum 意思是？",o:["老师","爸爸","奶奶","妈妈"],a:3,k:"词汇：mum 妈妈",e:"mum 妈妈（英式），美式 mom。"},
{i:1197,c:"en-9",ch:"五下·Unit 3 My school calendar",f:0,q:"“I'll cook for my mother.” 意思是？",o:["我要买饭给妈妈","我要为妈妈做饭","妈妈为我做饭","我要和妈妈一起吃饭"],a:1,k:"句型：I'll + 动词原形",e:"I'll cook for my mother. 意为“我要为妈妈做饭”，cook for 为……做饭。"},
{i:1198,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“第一”的序数词是？",o:["first","third","one","second"],a:0,k:"语法：序数词 first",e:"first 第一，基数词 one 变序数词 first（不规则变化）。"},
{i:1199,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“second” 的意思是？",o:["第一","第四","第三","第二"],a:3,k:"语法：序数词 second",e:"second 第二，基数词 two 变序数词 second（不规则变化）。"},
{i:1200,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“第三”的序数词是？",o:["first","three","third","fourth"],a:2,k:"语法：序数词 third",e:"third 第三，基数词 three 变序数词 third（不规则变化）。"},
{i:1201,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“fourth” 的意思是？",o:["第四","第五","第三","第二"],a:0,k:"语法：序数词 fourth",e:"fourth 第四，four 变 fourth，直接在基数词后加 th。"},
{i:1202,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“第五”的序数词是？",o:["five","fifth","sixth","fourth"],a:1,k:"语法：序数词 fifth",e:"fifth 第五，five 变 fifth，注意把 ve 改成 f 再加 th。"},
{i:1203,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“twelfth” 的意思是？",o:["第二十","第十二","第二","第十"],a:1,k:"语法：序数词 twelfth",e:"twelfth 第十二，twelve 变 twelfth，ve 改 f 再加 th。"},
{i:1204,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“第二十”的序数词是？",o:["twenty-first","twentieth","twenty","twelfth"],a:1,k:"语法：序数词 twentieth",e:"twentieth 第二十，twenty 变 y 为 i 再加 eth。"},
{i:1205,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“twenty-first” 的意思是？",o:["第二十一","第二十","第三十","第十二"],a:0,k:"语法：twenty-first 第二十一",e:"twenty-first 第二十一，几十几的序数词只变个位：twenty-first。"},
{i:1206,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“special” 的意思是？",o:["特别的","忙碌的","高兴的","普通的"],a:0,k:"词汇：special 特别的",e:"special 特别的、特殊的，a special day 特别的一天。"},
{i:1207,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“festival” 的意思是？",o:["节日","生日","假期","周末"],a:0,k:"词汇：festival 节日",e:"festival 节日，the Spring Festival 春节。"},
{i:1208,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“show” 在 “art show” 中意思是？",o:["观看","展示","告诉","展览、演出"],a:3,k:"词汇：show 展览",e:"show 展览、演出，art show 艺术展、美术展。"},
{i:1209,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“contest” 的意思是？",o:["聚会","旅行","比赛","展览"],a:2,k:"词汇：contest 比赛",e:"contest 比赛、竞赛，a singing contest 歌唱比赛。"},
{i:1210,c:"en-10",ch:"五下·Unit 4 When is Easter",f:1,q:"——When is Easter——It's on May ____（第一）.",o:[],a:"first",k:"句型：日期表达 on May 1st",e:"It's on May first.（在五月一日。）具体某日用 on + 月 + 序数词。"},
{i:1211,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“on May 1st” 中 on 表示？",o:["在月份","在具体某天","在年份","在季节"],a:1,k:"介词：on + 具体日期",e:"on + 具体某天（on May 1st），in + 月份（in May）。"},
{i:1212,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"——When is your birthday?——____",o:["It's in spring.","I'm ten.","It's on March 3rd.","It's sunny."],a:2,k:"句型：When is your birthday?",e:"问“你的生日是什么时候？”答 It's on + 具体日期：It's on March 3rd.。"},
{i:1213,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“birthday” 的意思是？",o:["星期日","生日","节日","假日"],a:1,k:"词汇：birthday 生日",e:"birthday 生日，Happy birthday! 生日快乐！"},
{i:1214,c:"en-10",ch:"五下·Unit 4 When is Easter",f:1,q:"“October 2nd” 读作 October the ____.",o:[],a:"second",k:"日期读法：2nd 读 second",e:"2nd 是 second（第二）的缩写，October 2nd 读作 October the second。"},
{i:1215,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“There are special days in April.” 意思是？",o:["四月有很多天","四月里有一些特别的日子","四月是节日","四月很特别"],a:1,k:"句型：There are special days",e:"There are special days in April. 意为“四月里有一些特别的日子”。"},
{i:1216,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“The singing contest will be in May.” 中 singing 意思是？",o:["跑步","跳舞","歌唱","画画"],a:2,k:"词汇：singing 歌唱",e:"singing 歌唱（sing 的 ing 形式），a singing contest 歌唱比赛。"},
{i:1217,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“on April 1st” 是愚人节，英语是？",o:["New Year's Day","April Fool's Day","Easter Day","Christmas Day"],a:1,k:"文化常识：愚人节",e:"April Fool's Day 愚人节（4月1日），人们会开善意的玩笑。"},
{i:1218,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“first, second, third” 是？",o:["地点词","序数词","基数词","时间词"],a:1,k:"语法：序数词",e:"first、second、third 都是序数词（表顺序），对应基数词 one、two、three。"},
{i:1219,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“one, two, three” 是？",o:["时间词","地点词","序数词","基数词"],a:3,k:"语法：基数词",e:"one、two、three 是基数词（表数量），对应序数词 first、second、third。"},
{i:1220,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“When is the English test?” 中 test 意思是？",o:["比赛","演出","测试","聚会"],a:2,k:"词汇：test 测试",e:"test 测试、考试，an English test 英语测试。"},
{i:1221,c:"en-10",ch:"五下·Unit 4 When is Easter",f:1,q:"——When is your birthday?——It's on June ____（第十二）.",o:[],a:"twelfth",k:"语法：序数词 twelfth",e:"第十二 twelfth，June 12th 读作 June the twelfth。"},
{i:1222,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“We'll have an English party.” 意思是？",o:["英语很难","我们正在上英语课","我们将举行英语聚会","我们喜欢英语"],a:2,k:"句型：We'll have...",e:"We'll have an English party. 意为“我们将举行英语聚会”，We'll = We will。"},
{i:1223,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“What's the date today?” 问的是？",o:["今天星期几","几点钟","今天天气","今天几月几号"],a:3,k:"句型：What's the date? 问日期",e:"What's the date today? 问“今天几月几号？”（日期）；What day is it today? 问星期。"},
{i:1224,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“It's on May 5th.” 中 5th 读作？",o:["fifth of May","the fifth of May","five","the fifth"],a:3,k:"日期读法：5th 读 fifth",e:"5th 是 fifth（第五）的缩写，May 5th 读作 May the fifth。"},
{i:1225,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“New Year's Day” 是几月几日？",o:["12月25日","5月1日","1月1日","2月1日"],a:2,k:"文化常识：元旦",e:"New Year's Day 元旦在 January 1st（1月1日）。"},
{i:1226,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“National Day” 是几月几日？",o:["7月1日","6月1日","10月1日","9月10日"],a:2,k:"文化常识：国庆节",e:"National Day 国庆节在 October 1st（10月1日）。"},
{i:1227,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“last” 在 “last year” 中意思是？",o:["上一个","下一个","这个","每个"],a:0,k:"词汇：last 上一个",e:"last 上一个，last year 去年，next year 明年。"},
{i:1228,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“What will you do on your birthday?” 意思是？",o:["你的生日在什么时候？","你喜欢生日吗？","你生日那天要做什么？","你几岁了？"],a:2,k:"句型：What will you do...?",e:"What will you do on your birthday? 意为“你生日那天要做什么？”，will 表将来。"},
{i:1229,c:"en-10",ch:"五下·Unit 4 When is Easter",f:0,q:"“I'll eat some noodles on my birthday.” 意思是？",o:["我生日那天要吃面条","我每天吃面条","我生日那天要吃蛋糕","我喜欢吃面条"],a:0,k:"句型：I'll + 动词原形",e:"I'll eat some noodles on my birthday. 意为“我生日那天要吃面条”（中国人过生日吃长寿面）。"},
{i:1230,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“mine” 的意思是？",o:["她的（东西）","他的（东西）","你的（东西）","我的（东西）"],a:3,k:"语法：名词性物主代词 mine",e:"mine 我的（东西），名词性物主代词，= my + 名词，如 The book is mine.。"},
{i:1231,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“yours” 的意思是？",o:["你的（东西）","我的（东西）","他的（东西）","他们的（东西）"],a:0,k:"语法：名词性物主代词 yours",e:"yours 你的（东西），= your + 名词，如 It's yours.。"},
{i:1232,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“his” 作为物主代词意思是？",o:["你的（东西）","她的（东西）","我的（东西）","他的（东西）"],a:3,k:"语法：物主代词 his",e:"his 他的（形容词性：his book；名词性：The book is his.）。"},
{i:1233,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“hers” 的意思是？",o:["他的（东西）","我们的（东西）","她们的（东西）","她的（东西）"],a:3,k:"语法：名词性物主代词 hers",e:"hers 她的（东西），= her + 名词，如 The bag is hers.。"},
{i:1234,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“theirs” 的意思是？",o:["他们的（东西）","我的（东西）","你的（东西）","我们的（东西）"],a:0,k:"语法：名词性物主代词 theirs",e:"theirs 他们的（东西），= their + 名词，如 The books are theirs.。"},
{i:1235,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“ours” 的意思是？",o:["我们的（东西）","他们的（东西）","她的（东西）","你们的（东西）"],a:0,k:"语法：名词性物主代词 ours",e:"ours 我们的（东西），= our + 名词，如 The classroom is ours.。"},
{i:1236,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“whose” 的意思是？",o:["谁的","怎样","什么","哪里"],a:0,k:"语法：疑问词 whose",e:"whose 谁的，Whose dog is it? 这是谁的狗？"},
{i:1237,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“climbing” 的意思是？",o:["正在跳","正在爬","正在吃","正在玩"],a:1,k:"语法：现在分词 climbing",e:"climbing 正在爬（climb + ing），The monkey is climbing. 猴子正在爬。"},
{i:1238,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“eating” 的意思是？",o:["正在睡","正在跑","正在喝","正在吃"],a:3,k:"语法：现在分词 eating",e:"eating 正在吃（eat + ing），The dog is eating. 狗正在吃。"},
{i:1239,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“playing” 的意思是？",o:["正在工作","正在学习","正在看书","正在玩"],a:3,k:"语法：现在分词 playing",e:"playing 正在玩（play + ing），The children are playing. 孩子们正在玩。"},
{i:1240,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“jumping” 的意思是？",o:["正在跳","正在跑","正在爬","正在走"],a:0,k:"语法：现在分词 jumping",e:"jumping 正在跳（jump + ing），The rabbit is jumping. 兔子正在跳。"},
{i:1241,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“drinking” 的意思是？",o:["正在吃","正在看","正在睡","正在喝"],a:3,k:"语法：现在分词 drinking",e:"drinking 正在喝（drink + ing），The cat is drinking water. 猫正在喝水。"},
{i:1242,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“sleeping” 的意思是？",o:["正在吃饭","正在睡觉","正在唱歌","正在跑步"],a:1,k:"语法：现在分词 sleeping",e:"sleeping 正在睡觉（sleep + ing），The dog is sleeping. 狗正在睡觉。"},
{i:1243,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:1,q:"——Whose dog is it?——It's ____（我的）.",o:[],a:"mine",k:"句型：Whose...is it? It's mine.",e:"Whose dog is it? 问“这是谁的狗？”答 It's mine.（是我的。）mine 名词性物主代词。"},
{i:1244,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"——Whose book is this?——It's ____.",o:["her","he","she","hers"],a:3,k:"语法：名词性物主代词",e:"回答 Whose 的问句用名词性物主代词：It's hers.（是她的。）hers = her book。"},
{i:1245,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“The dog is sleeping.” 表示动作？",o:["经常发生","已经完成","将要发生","正在进行"],a:3,k:"语法：现在进行时",e:"be + 动词ing 构成现在进行时，表示动作正在进行：The dog is sleeping. 狗正在睡觉。"},
{i:1246,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“Is it yours?” 的肯定回答是？",o:["Yes, it is.","Yes, I do.","Yes, I am.","Yes, it does."],a:0,k:"句型：Is it yours? 的回答",e:"Is it yours? 问“是你的吗？”肯定回答 Yes, it is.。"},
{i:1247,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:1,q:"Look! The cat is ____（正在爬）the tree.",o:[],a:"climbing",k:"语法：现在进行时 climbing",e:"Look! The cat is climbing the tree.（看！猫正在爬树。）is + climbing。"},
{i:1248,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“These are our books. They're ____.”",o:["ours","us","we","our"],a:0,k:"语法：名词性物主代词 ours",e:"They're ours. 是我们的。ours = our books，避免名词重复。"},
{i:1249,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“My dog is very cute.” 中 cute 意思是？",o:["瘦小的","凶猛的","可爱的","高大的"],a:2,k:"词汇：cute 可爱的",e:"cute 可爱的、机灵的，a cute dog 可爱的狗。"},
{i:1250,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“What is he doing?” 的答语是？",o:["He eats dinner.","He's eating dinner.","He likes dinner.","He ate dinner."],a:1,k:"句型：What is he doing? 的回答",e:"问“他正在做什么？”答用现在进行时 He's eating dinner.（他正在吃晚饭。）"},
{i:1251,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“正在游泳”用英语怎么说？",o:["swimming","swiming","swam","swims"],a:0,k:"语法：swim 的 ing 形式",e:"swim 双写 m 加 ing：swimming，He is swimming. 他正在游泳。"},
{i:1252,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“正在跑步”用英语怎么说？",o:["runs","run","runing","running"],a:3,k:"语法：run 的 ing 形式",e:"run 双写 n 加 ing：running，She is running. 她正在跑步。"},
{i:1253,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:1,q:"The rabbits are ____（正在吃）carrots.",o:[],a:"eating",k:"语法：现在进行时 eating",e:"The rabbits are eating carrots.（兔子们正在吃胡萝卜。）are + eating。"},
{i:1254,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“Whose” 用来问？",o:["什么时候","谁的物品归谁","谁的","在哪里"],a:2,k:"语法：whose 的用法",e:"Whose 用来询问物品归属“谁的”，Whose bag is it? 这是谁的包？"},
{i:1255,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“The birds are flying.” 中 flying 意思是？",o:["正在跳","正在跑","正在飞","正在叫"],a:2,k:"语法：现在进行时 flying",e:"flying 正在飞（fly 变 y 为 i 加 ing），The birds are flying. 鸟儿正在飞。"},
{i:1256,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“I'm listening to music.” 中 listening 意思是？",o:["正在写","正在听","正在看","正在说"],a:1,k:"语法：现在进行时 listening",e:"listening 正在听，listen to music 听音乐，I'm listening to music. 我正在听音乐。"},
{i:1257,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“The monkey is climbing.” 意思是？",o:["猴子正在爬","猴子正在跳","猴子正在吃","猴子正在睡"],a:0,k:"句型：现在进行时",e:"The monkey is climbing. 意为“猴子正在爬”，is + climbing 现在进行时。"},
{i:1258,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“These are yours.” 中 These 指？",o:["那个","这些","那些","这个"],a:1,k:"语法：these 这些",e:"these 这些（this 的复数），those 那些（that 的复数）。"},
{i:1259,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“I have a new book. It's ____.”",o:["my","me","mine","I"],a:2,k:"语法：名词性物主代词 mine",e:"It's mine. 是我的。mine 名词性物主代词，my 是形容词性（后面要接名词）。"},
{i:1260,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“The cat is drinking water.” 意思是？",o:["猫正在玩","猫正在吃饭","猫正在睡觉","猫正在喝水"],a:3,k:"句型：现在进行时",e:"The cat is drinking water. 意为“猫正在喝水”，drink water 喝水。"},
{i:1261,c:"en-11",ch:"五下·Unit 5 Whose dog is it?",f:0,q:"“everyone” 的意思是？",o:["任何人","每个人","没人","某人"],a:1,k:"词汇：everyone 每个人",e:"everyone 每个人，Everyone is happy. 每个人都很开心。"},
{i:1262,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“做早操”用英语怎么说？",o:["doing morning exercises","reading a book","having class","eating lunch"],a:0,k:"短语：do morning exercises 做早操",e:"do morning exercises 做早操，现在进行时 doing morning exercises。"},
{i:1263,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“having class” 的意思是？",o:["正在上课","正在吃饭","正在听音乐","正在读书"],a:0,k:"短语：have class 上课",e:"have class 上课，现在进行时 having class 正在上课。"},
{i:1264,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“eating lunch” 的意思是？",o:["正在吃午饭","正在吃晚饭","正在吃零食","正在吃早饭"],a:0,k:"短语：eat lunch 吃午饭",e:"eat lunch 吃午饭，现在进行时 eating lunch 正在吃午饭。"},
{i:1265,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“正在读书”用英语怎么说？",o:["writing a book","reading a letter","reading a book","reading a map"],a:2,k:"短语：read a book 读书",e:"read a book 读书，现在进行时 reading a book 正在读书。"},
{i:1266,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“listening to music” 的意思是？",o:["正在听音乐","正在跳舞","正在听老师讲","正在唱歌"],a:0,k:"短语：listen to music 听音乐",e:"listen to music 听音乐，listen 是不及物动词，接宾语要加 to。"},
{i:1267,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“靠右走”用英语怎么说？",o:["keep to the right","keep quiet","keep clean","keep to the left"],a:0,k:"短语：keep to the right 靠右走",e:"keep to the right 靠右走（交通规则），keep 保持。"},
{i:1268,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“keep your desk clean” 的意思是？",o:["整理书包","保持你的书桌整洁","搬动你的书桌","擦干净黑板"],a:1,k:"短语：keep...clean 保持整洁",e:"keep your desk clean 保持你的书桌整洁，keep + 名词 + 形容词。"},
{i:1269,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“小声说话”用英语怎么说？",o:["talk fast","talk slow","talk loudly","talk quietly"],a:3,k:"短语：talk quietly 小声说话",e:"talk quietly 小声说话，quietly 是 quiet 的副词“安静地”。"},
{i:1270,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“take turns” 的意思是？",o:["轮流","一起","到处","立刻"],a:0,k:"短语：take turns 轮流",e:"take turns 轮流，Take turns, please.（请轮流来。）"},
{i:1271,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“quietly” 的意思是？",o:["慢慢地","安静地","大声地","快速地"],a:1,k:"词汇：quietly 安静地",e:"quietly 是 quiet（安静的）的副词形式“安静地”，Work quietly! 安静地做事！"},
{i:1272,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:1,q:"——What are you doing?——I'm ____（正在读书）.",o:[],a:"reading a book",k:"句型：What are you doing? 的回答",e:"问“你正在做什么？”答 I'm + 动词ing：I'm reading a book.（我正在读书。）"},
{i:1273,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“Keep quiet, please.” 意思是？",o:["请大声说话","请排队","请走右边","请保持安静"],a:3,k:"句型：Keep quiet! 保持安静",e:"Keep quiet, please. 意为“请保持安静”，keep + 形容词。"},
{i:1274,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“What are you doing?” 问的是？",o:["你想要什么","你正在做什么","你几岁","你喜欢什么"],a:1,k:"句型：What are you doing?",e:"What are you doing? 问“你正在做什么？”，是现在进行时的特殊疑问句。"},
{i:1275,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“What is she doing?” 的答语是？",o:["She reads.","She read.","She likes reading.","She's reading."],a:3,k:"句型：What is she doing? 的回答",e:"问“她正在做什么？”答 She's + 动词ing：She's reading.（她正在读书。）"},
{i:1276,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:1,q:"He is ____ ____（做早操）now.",o:[],a:"doing morning exercises",k:"短语：doing morning exercises 做早操",e:"He is doing morning exercises now.（他现在正在做早操。）now 提示用现在进行时。"},
{i:1277,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“Can we use your crayons?” 意思是？",o:["我们能借用你的蜡笔吗？","你有蜡笔吗？","蜡笔是什么？","我们能看你的蜡笔吗？"],a:0,k:"句型：Can we use...?",e:"Can we use your crayons? 意为“我们能借用你的蜡笔吗？”，use 使用。"},
{i:1278,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“Take turns.” 在游戏中表示？",o:["快点","加油","一起上","轮流来"],a:3,k:"短语：take turns 轮流",e:"Take turns. 轮流来，是课堂和游戏中的常用指令。"},
{i:1279,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“What are they doing?” 的答语是？",o:["They played.","They play.","They're playing.","They like playing."],a:2,k:"句型：What are they doing? 的回答",e:"问“他们正在做什么？”答 They're + 动词ing：They're playing.（他们正在玩。）"},
{i:1280,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“The students are having class.” 意思是？",o:["学生们正在吃饭","学生们正在回家","学生们正在下课","学生们正在上课"],a:3,k:"句型：现在进行时",e:"The students are having class. 意为“学生们正在上课”，are + having 现在进行时。"},
{i:1281,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“Keep your desk clean.” 是？",o:["感叹句","祈使句（请求或命令）","陈述句","疑问句"],a:1,k:"语法：祈使句",e:"以动词原形开头的句子是祈使句，表示请求或命令：Keep your desk clean.（保持书桌整洁。）"},
{i:1282,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“I'm eating lunch with my friends.” 意思是？",o:["我每天和朋友吃午饭","朋友在吃午饭","我喜欢和朋友吃午饭","我正在和朋友吃午饭"],a:3,k:"句型：现在进行时",e:"I'm eating lunch with my friends. 意为“我正在和朋友吃午饭”，with 和……一起。"},
{i:1283,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:1,q:"Please ____ ____（小声说话）in the library.",o:[],a:"talk quietly",k:"短语：talk quietly 小声说话",e:"Please talk quietly in the library.（请在图书馆里小声说话。）"},
{i:1284,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“Do you want some water?” 中 want 意思是？",o:["喜欢","想要","讨厌","需要"],a:1,k:"词汇：want 想要",e:"want 想要，Do you want some water? 你想要些水吗？"},
{i:1285,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“Keep to the right.” 适合在？",o:["餐厅里","操场上","上下楼梯","教室里"],a:2,k:"文化常识：靠右走",e:"Keep to the right. 靠右走，是上下楼梯、走廊行走的安全规则。"},
{i:1286,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“现在进行时”一般用哪个结构？",o:["动词过去式","be + 动词ing","will + 动词","动词原形"],a:1,k:"语法：现在进行时结构",e:"现在进行时结构：be（am/is/are）+ 动词ing，表示正在进行的动作。"},
{i:1287,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“I'm listening to music.” 中 listen 后接 to 表示？",o:["写……","看……","听……","说……"],a:2,k:"语法：listen to 听",e:"listen 是不及物动词，接宾语要加 to：listen to music 听音乐。"},
{i:1288,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“The bird is flying.” 中 bird 意思是？",o:["鸟","猫","狗","鱼"],a:0,k:"词汇：bird 鸟",e:"bird 鸟，The bird is flying. 鸟正在飞。"},
{i:1289,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“quiet” 和 “quietly” 的区别是？",o:["读音不同","意思不同","quietly 形容词，quiet 副词","quiet 形容词，quietly 副词"],a:3,k:"语法：形容词和副词",e:"quiet 形容词（安静的），quietly 副词（安静地）：Be quiet.（安静）与 Talk quietly.（小声说话）。"},
{i:1290,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“What is the little monkey doing?” 中 little 意思是？",o:["胖的","小的","高的","大的"],a:1,k:"词汇：little 小的",e:"little 小的，the little monkey 小猴子；a little 一点。"},
{i:1291,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:1,q:"——What is he doing?——He's ____（正在上课）.",o:[],a:"having class",k:"短语：have class 上课",e:"What is he doing? 问“他正在做什么？”答 He's having class.（他正在上课。）"},
{i:1292,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“In the library, we should keep quiet.” 意思是？",o:["我喜欢图书馆","在图书馆里我们应该保持安静","在图书馆里我们可以大声说话","图书馆很大"],a:1,k:"句型：should keep quiet",e:"In the library, we should keep quiet. 意为“在图书馆里我们应该保持安静”，should 应该。"},
{i:1293,c:"en-12",ch:"五下·Unit 6 Work quietly!",f:0,q:"“Any more?” 的意思是？",o:["什么？","没有吗？","还有吗？","多少？"],a:2,k:"短语：any more 还有（更多）",e:"Any more? 意为“还有吗？”，询问是否还有更多。"}
);
