// 英语题库 一年级（启蒙阶段，2026-09-10 整套重写）
// 一上 Unit 1-5 + 一下 Unit 6-8 = 8 个 Unit，每 Unit 20~21 题，共 163 题。
// 旧版问题：每章 20 题只覆盖 13~16 个知识点（重复率 25%~46%），且 8 个单元全无拔高题。
// 新版：163 个知识点零重复（重复率 0%）、每章 ≥4 道拔高(d:2)、每章 1 道填空(f:1)。i 用 0~159 加 160~162。
// 说明：人教 PEP 英语正式教材从三年级起，一年级为启蒙，按话题（打招呼/字母/颜色/数字/玩具/动物/食物/身体）编排。
if(!global.QA)global.QA={};
if(!QA["1en"])QA["1en"]=[];
QA["1en"].push(
// ══════════ 一上·Unit 1 Hello! 打招呼 ══════════
{i:0,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“Hello!”的中文意思是？",o:["你好！","再见！","谢谢！","对不起！"],a:0,k:"打招呼：Hello",e:"解析：Hello! 是英语中最常用的打招呼用语，意思是“你好！”。"},
{i:1,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"熟人之间打招呼，还可以简短地说？",o:["Hi!","Bye!","Sorry!","No!"],a:0,k:"打招呼：Hi",e:"解析：Hi! 和 Hello! 都表示“你好！”，Hi 更随意，常用于熟人之间。"},
{i:2,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“Goodbye!”的意思是？",o:["再见！","你好！","谢谢！","是的！"],a:0,k:"告别：Goodbye",e:"解析：Goodbye! 是告别用语，意思是“再见！”。"},
{i:3,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"和人道别时，比 Goodbye 更简短的说法是？",o:["Bye!","Hello!","Thanks!","OK!"],a:0,k:"告别：Bye",e:"解析：Bye! 是 Goodbye! 的简短说法，都是“再见”。"},
{i:4,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"早上见到老师，应该说什么？",o:["Good morning.","Good night.","Good afternoon.","Goodbye."],a:0,k:"问候：Good morning",e:"解析：Good morning. 是“早上好”，用于上午见面时问候。"},
{i:5,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"下午见面时，应该说？",o:["Good afternoon.","Good morning.","Good night.","Good evening."],a:0,k:"问候：Good afternoon",e:"解析：Good afternoon. 是“下午好”，用于中午之后到傍晚前。"},
{i:6,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"晚上睡觉前对家人说？",o:["Good night.","Good morning.","Goodbye.","Hello."],a:0,k:"问候：Good night",e:"解析：Good night. 是“晚安”，用于睡前道别，不是见面问候。"},
{i:7,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"别人问“How are you?”，你很好，应该回答？",o:["I'm fine, thank you.","I'm five.","Goodbye.","Hello."],a:0,k:"问候应答：How are you?",e:"解析：How are you? 问“你好吗？”，回答 I'm fine, thank you.（我很好，谢谢）。"},
{i:8,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“Thank you.”的意思是？",o:["谢谢！","对不起！","你好！","再见！"],a:0,k:"礼貌：Thank you",e:"解析：Thank you. 是“谢谢”，也可说 Thanks."},
{i:9,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"不小心碰到别人，应该说什么？",o:["Sorry.","Thanks.","Hello.","Bye."],a:0,k:"礼貌：Sorry",e:"解析：Sorry. 是“对不起”，用于道歉。"},
{i:10,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"想请别人帮忙或递东西时，礼貌地说？",o:["Please.","Sorry.","Bye.","No."],a:0,k:"礼貌：Please",e:"解析：Please. 是“请”，加上它语气更客气。"},
{i:11,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"向别人介绍自己的名字，应该说？",o:["I'm Tom.","You're Tom.","He is Tom.","This is Tom."],a:0,k:"自我介绍：I'm...",e:"解析：I'm... 是“我是……”，用来介绍自己。"},
{i:12,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"别人问“What's your name?”，你应该回答？",o:["My name is Amy.","I'm fine.","Thank you.","Goodbye."],a:0,k:"问答：What's your name?",e:"解析：What's your name? 问“你叫什么名字？”，回答 My name is...（我叫……）。"},
{i:13,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"第一次见到新同学，可以说？",o:["Nice to meet you.","Good night.","See you.","Sorry."],a:0,k:"初次见面：Nice to meet you",e:"解析：Nice to meet you. 是“很高兴认识你”，用于初次见面。"},
{i:14,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"别人问你一个问题，你表示肯定，说？",o:["Yes.","No.","Please.","Sorry."],a:0,k:"肯定与否定：Yes",e:"解析：Yes 表示“是、对”；No 表示“不是、不对”。"},
{i:15,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"你想打断别人或借过，礼貌地说？",o:["Excuse me.","Goodbye.","Thanks.","OK."],a:0,k:"礼貌：Excuse me",e:"解析：Excuse me. 是“打扰一下、借过”，用于引起注意或借过。"},
{i:16,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,d:2,q:"小明早上到校，见到老师，最合适的说法是？",o:["Good morning, Miss Li.","Good night, Miss Li.","Bye, Miss Li.","Sorry, Miss Li."],a:0,k:"情景运用：早上问候老师",e:"解析：早上到校是上午，要用 Good morning，并加上老师的称呼。"},
{i:17,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,d:2,q:"放学了，你跟同学和老师道别，下面哪句不合适？",o:["Good night.","Goodbye.","Bye.","See you."],a:0,k:"情景辨析：告别用语",e:"解析：放学道别用 Goodbye/Bye/See you；Good night 是睡前说的，用在这里不合适。"},
{i:18,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,d:2,q:"同学把橡皮借给你，你应该说什么？",o:["Thank you.","Sorry.","Excuse me.","Good night."],a:0,k:"情景运用：表达感谢",e:"解析：别人帮了你或借东西给你，要说 Thank you.（谢谢）。"},
{i:160,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,d:2,q:"第一次见到新同学，你想先打招呼再介绍自己的名字，下面哪句话最合适？",o:["Hello! I'm Amy.","Bye! I'm Amy.","Thank you, Amy.","Good night, Amy."],a:0,k:"情景综合运用：打招呼＋自我介绍",e:"解析：初次见面先 Hello 打招呼，再用 I'm... 介绍自己。"},
{i:19,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:1,q:"补全对话：— Hello! — ____!（你好）",o:[],a:"Hi",k:"对话填空：Hello 的应答",e:"解析：对方说 Hello，可以回答 Hi 或 Hello，填“Hi”。"},

// ══════════ 一上·Unit 2 Letters 字母 Aa–Ff ══════════
{i:20,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"英语字母表中，排在最前面的两个字母是？",o:["Aa, Bb","Bb, Cc","Aa, Cc","Ee, Ff"],a:0,k:"字母顺序：Aa Bb",e:"解析：字母表从 Aa 开始，接着是 Bb。"},
{i:21,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母 B 的小写形式是？",o:["b","d","p","q"],a:0,k:"字母大小写：Bb",e:"解析：大写 B 的小写是 b，要注意和 d 区分。"},
{i:22,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"下列字母中，哪一个是元音字母？",o:["Aa","Bb","Cc","Dd"],a:0,k:"元音字母：Aa",e:"解析：英语有 5 个元音字母 Aa、Ee、Ii、Oo、Uu，这里 Aa 是元音。"},
{i:23,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母 Aa 在单词 apple 中的发音，接近下面哪个？",o:["/æ/（嘴张大）","/e/","/i:/","/ʌ/"],a:0,k:"字母发音：Aa",e:"解析：apple 里的 a 发 /æ/，嘴巴要张大。"},
{i:24,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"“苹果”的英文单词是？",o:["apple","apply","appie","appla"],a:0,k:"单词：apple",e:"解析：苹果是 apple，以字母 a 开头。"},
{i:25,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"“书”的英文单词是？",o:["book","look","boot","bock"],a:0,k:"单词：book",e:"解析：书是 book，以字母 b 开头。"},
{i:26,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"“猫”的英文单词是？",o:["cat","cap","car","cake"],a:0,k:"单词：cat",e:"解析：猫是 cat，以字母 c 开头。"},
{i:27,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"“狗”的英文单词是？",o:["dog","dig","dot","bag"],a:0,k:"单词：dog",e:"解析：狗是 dog，以字母 d 开头。"},
{i:28,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"“鸡蛋”的英文单词是？",o:["egg","leg","end","age"],a:0,k:"单词：egg",e:"解析：鸡蛋是 egg，以字母 e 开头。"},
{i:29,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"“鱼”的英文单词是？",o:["fish","dish","face","five"],a:0,k:"单词：fish",e:"解析：鱼是 fish，以字母 f 开头。"},
{i:30,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"下列字母中，排在 Cc 和 Ee 之间的是？",o:["Dd","Bb","Ff","Aa"],a:0,k:"字母顺序：Cc Dd Ee",e:"解析：字母顺序是 Cc、Dd、Ee，中间是 Dd。"},
{i:31,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"大写字母 E 的小写形式是？",o:["e","f","c","a"],a:0,k:"字母大小写：Ee",e:"解析：大写 E 的小写是 e。"},
{i:32,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"下面哪一组字母的大小写配对是正确的？",o:["Ff","Ea","Cb","Af"],a:0,k:"大小写配对",e:"解析：F 的小写是 f，所以 Ff 正确；E 配 e，C 配 c，A 配 a。"},
{i:33,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"单词 banana 的第一个字母是？",o:["b","a","n","m"],a:0,k:"首字母：banana",e:"解析：banana（香蕉）以字母 b 开头。"},
{i:34,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"英语字母歌（ABC song）里，通常把字母编成歌来？",o:["帮助记忆字母顺序","练习写数字","学习句子","练习对话"],a:0,k:"字母歌的作用",e:"解析：字母歌把 26 个字母编成曲子，唱几遍就能记住顺序。"},
{i:35,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,d:2,q:"把下列字母按顺序排列：c, a, b, f, e, d。正确顺序是？",o:["a b c d e f","a c b d e f","b a c d e f","a b d c e f"],a:0,k:"字母排序",e:"解析：按字母表顺序是 a、b、c、d、e、f。"},
{i:36,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,d:2,q:"看首字母猜单词：以字母 d 开头的动物是？",o:["dog","cat","fish","egg"],a:0,k:"首字母归类：d",e:"解析：dog（狗）以 d 开头；cat 是 c，fish 是 f，egg 是 e。"},
{i:37,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,d:2,q:"下列单词中，首字母是元音字母 a 的是？",o:["apple","book","cat","dog"],a:0,k:"元音首字母归类",e:"解析：apple 以 a 开头，a 是元音字母。"},
{i:38,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,d:2,q:"写出字母 C 的左邻右舍（前后各一个）：",o:["Bb 和 Dd","Aa 和 Cc","Dd 和 Ee","Ee 和 Ff"],a:0,k:"字母邻居",e:"解析：字母顺序是 Bb、Cc、Dd，所以 Cc 前后是 Bb 和 Dd。"},
{i:39,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:1,q:"补全单词：a____le（苹果）",o:[],a:"pp",k:"单词拼写：apple",e:"解析：apple 缺少两个 p，填“pp”。"},

// ══════════ 一上·Unit 3 Colours 颜色 ══════════
{i:40,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“红色”的英文是？",o:["red","read","ride","bed"],a:0,k:"颜色：red",e:"解析：红色是 red。"},
{i:41,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“黄色”的英文是？",o:["yellow","yello","yallow","yollew"],a:0,k:"颜色：yellow",e:"解析：黄色是 yellow。"},
{i:42,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“蓝色”的英文是？",o:["blue","bule","blew","blae"],a:0,k:"颜色：blue",e:"解析：蓝色是 blue。"},
{i:43,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“绿色”的英文是？",o:["green","grean","creen","greed"],a:0,k:"颜色：green",e:"解析：绿色是 green。"},
{i:44,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“黑色”的英文是？",o:["black","bluck","bleak","block"],a:0,k:"颜色：black",e:"解析：黑色是 black。"},
{i:45,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“白色”的英文是？",o:["white","whit","whote","wite"],a:0,k:"颜色：white",e:"解析：白色是 white。"},
{i:46,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“橙色；橘子”的英文是？",o:["orange","oragne","orage","ornage"],a:0,k:"颜色：orange",e:"解析：orange 既是“橙色”，也是“橘子”。"},
{i:47,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“粉色”的英文是？",o:["pink","pick","pank","penk"],a:0,k:"颜色：pink",e:"解析：粉色是 pink。"},
{i:48,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“紫色”的英文是？",o:["purple","purpel","purbel","purpul"],a:0,k:"颜色：purple",e:"解析：紫色是 purple。"},
{i:49,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“棕色；褐色”的英文是？",o:["brown","blown","browm","brownn"],a:0,k:"颜色：brown",e:"解析：棕色（褐色）是 brown。"},
{i:50,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"想知道某物是什么颜色，应该问？",o:["What colour is it?","What is it?","How are you?","Who is it?"],a:0,k:"句型：What colour is it?",e:"解析：What colour is it? 意思是“它是什么颜色？”。"},
{i:51,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"回答“它是红色的”，应该说？",o:["It's red.","It red.","Is red.","Red it."],a:0,k:"句型：It's + 颜色",e:"解析：It's red. 意思是“它是红色的”，It's 是 It is 的缩写。"},
{i:52,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"成熟的苹果通常是什么颜色？",o:["red","blue","white","purple"],a:0,k:"颜色与生活：苹果",e:"解析：熟透的苹果是红色 red。"},
{i:53,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"香蕉是什么颜色？",o:["yellow","red","green","black"],a:0,k:"颜色与生活：香蕉",e:"解析：香蕉是黄色 yellow。"},
{i:54,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"晴朗的天空通常是什么颜色？",o:["blue","green","black","brown"],a:0,k:"颜色与生活：天空",e:"解析：晴天的天空是蓝色 blue。"},
{i:55,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"小草和树叶通常是什么颜色？",o:["green","red","white","pink"],a:0,k:"颜色与生活：植物",e:"解析：草和树叶是绿色 green。"},
{i:56,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,d:2,q:"把红色和黄色混在一起，会得到什么颜色？",o:["orange","green","purple","black"],a:0,k:"颜色的混合",e:"解析：red + yellow = orange（橙色），这是三原色调色规律。"},
{i:57,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,d:2,q:"红灯亮时我们要停下，“红灯”用英语说是？",o:["red light","green light","blue light","yellow light"],a:0,k:"颜色应用：交通灯",e:"解析：red light 是红灯；green light 是绿灯，可以通行。"},
{i:58,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,d:2,q:"“This is a yellow banana.”这句话的意思是？",o:["这是一根黄色的香蕉。","这是一个黄色的苹果。","那是黄色的香蕉。","香蕉是绿色的。"],a:0,k:"句子理解：This is...",e:"解析：This is 是“这是”，a yellow banana 是“一根黄色的香蕉”。"},
{i:161,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,d:2,q:"“The banana is yellow. The apple is red.” 这两句话告诉我们什么？",o:["香蕉是黄色的，苹果是红色的","香蕉是红色的，苹果是黄色的","香蕉和苹果都是黄色的","香蕉和苹果都是红色的"],a:0,k:"句子理解：两个颜色描述的辨析",e:"解析：yellow 黄色对应 banana 香蕉，red 红色对应 apple 苹果，别把颜色张冠李戴。"},
{i:59,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:1,q:"补全句子：— What ____ is it? — It's blue.",o:[],a:"colour",k:"句型填空：What colour",e:"解析：问颜色用 What colour is it?，填“colour”。"},

// ══════════ 一上·Unit 4 Numbers 数字 1–5 ══════════
{i:60,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"数字“1”的英文是？",o:["one","won","on","oun"],a:0,k:"数字：one",e:"解析：1 是 one。"},
{i:61,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"数字“2”的英文是？",o:["two","tow","too","twe"],a:0,k:"数字：two",e:"解析：2 是 two，注意和 too（也）拼写不同。"},
{i:62,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"数字“3”的英文是？",o:["three","tree","there","thrie"],a:0,k:"数字：three",e:"解析：3 是 three，注意和 tree（树）区分。"},
{i:63,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"数字“4”的英文是？",o:["four","for","fure","fourt"],a:0,k:"数字：four",e:"解析：4 是 four，注意和 for（为了）同音不同形。"},
{i:64,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"数字“5”的英文是？",o:["five","fife","fiv","fivw"],a:0,k:"数字：five",e:"解析：5 是 five。"},
{i:65,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"想知道有几个苹果，应该问？",o:["How many?","How are you?","What colour?","What is it?"],a:0,k:"句型：How many?",e:"解析：How many? 问“多少？”，用来问可数东西的数量。"},
{i:66,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“three books”表示几本书？",o:["3本","2本","5本","4本"],a:0,k:"数字与名词搭配",e:"解析：three 是 3，three books 是 3 本书。"},
{i:67,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"按数字顺序排列：one, three, two, five, four。正确的是？",o:["one two three four five","one three two four five","two one three four five","one two four three five"],a:0,k:"数字顺序",e:"解析：正确顺序是 1、2、3、4、5。"},
{i:68,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"one + one 等于？",o:["two","three","one","four"],a:0,k:"简单加法算式",e:"解析：1+1=2，two。"},
{i:69,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"two + three 等于？",o:["five","four","three","six"],a:0,k:"加法：2+3",e:"解析：2+3=5，five。"},
{i:70,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"一只手有几根手指？",o:["five","four","three","two"],a:0,k:"数字与生活：手指",e:"解析：一只手有 5 根手指，five。"},
{i:71,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“数字”这个单词本身是？",o:["number","namber","numbar","numbor"],a:0,k:"单词：number",e:"解析：数字是 number。"},
{i:72,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“有多少？”的完整问法是？",o:["How many...?","How much...?","How old...?","How about...?"],a:0,k:"疑问词：How many",e:"解析：How many 问可数名词的数量；How old 问年龄。"},
{i:73,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"别人问你几岁了，应该问？",o:["How old are you?","How many are you?","How are you?","What is you?"],a:0,k:"句型：How old are you?",e:"解析：How old are you? 问“你几岁了？”。"},
{i:74,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"我五岁了，应该回答？",o:["I'm five.","I'm fine.","I five.","I'm four."],a:0,k:"回答年龄：I'm five",e:"解析：I'm five. 是“我五岁了”，注意 five（5）和 fine（好）的区别。"},
{i:75,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,d:2,q:"桌子上有 2 个红苹果和 3 个青苹果，一共有几个苹果？",o:["five","four","three","six"],a:0,k:"加法应用：2+3",e:"解析：2+3=5，一共 five 个苹果。"},
{i:76,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,d:2,q:"有 5 块饼干，吃掉 2 块，还剩几块？",o:["three","two","four","one"],a:0,k:"减法应用：5−2",e:"解析：5−2=3，还剩 three 块。"},
{i:77,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,d:2,q:"“I have four pens.”这句话的意思是？",o:["我有四支钢笔。","我有五支钢笔。","我有四本书。","这是四支钢笔。"],a:0,k:"句子理解：I have...",e:"解析：I have 是“我有”，four pens 是“四支钢笔”。"},
{i:78,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,d:2,q:"下面数字中，排在 three 和 five 之间的是？",o:["four","two","one","six"],a:0,k:"数字邻居",e:"解析：3（three）、4（four）、5（five），中间是 four。"},
{i:79,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:1,q:"补全：one, two, ____, four, five。",o:[],a:"three",k:"数字顺序填空",e:"解析：1、2、3、4、5，缺少的是 three。"},

// ══════════ 一上·Unit 5 Toys 玩具 ══════════
{i:80,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“玩具”的英文总称是？",o:["toy","boy","joy","key"],a:0,k:"单词：toy",e:"解析：玩具是 toy。"},
{i:81,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“球”的英文是？",o:["ball","doll","bell","tall"],a:0,k:"单词：ball",e:"解析：球是 ball。"},
{i:82,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“洋娃娃”的英文是？",o:["doll","ball","door","dog"],a:0,k:"单词：doll",e:"解析：洋娃娃是 doll，注意和 ball（球）区分。"},
{i:83,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“小汽车”的英文是？",o:["car","cat","cap","card"],a:0,k:"单词：car",e:"解析：小汽车是 car。"},
{i:84,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“泰迪熊”的英文是？",o:["teddy bear","teddy bare","teddy beer","tedy bear"],a:0,k:"单词：teddy bear",e:"解析：泰迪熊是 teddy bear。"},
{i:85,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“风筝”的英文是？",o:["kite","ball","cat","bike"],a:0,k:"单词：kite",e:"解析：风筝是 kite。"},
{i:86,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“气球”的英文是？",o:["balloon","ballon","baloon","balloom"],a:0,k:"单词：balloon",e:"解析：气球是 balloon（注意有两个 l、两个 o）。"},
{i:87,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“飞机”的英文是？",o:["plane","plan","plant","plate"],a:0,k:"单词：plane",e:"解析：飞机是 plane。"},
{i:88,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“小船”的英文是？",o:["boat","boot","coat","goat"],a:0,k:"单词：boat",e:"解析：小船是 boat，注意和 boot（靴子）区分。"},
{i:89,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“机器人”的英文是？",o:["robot","robet","rebot","robort"],a:0,k:"单词：robot",e:"解析：机器人是 robot。"},
{i:90,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"想说“我有一个球”，应该说？",o:["I have a ball.","I has a ball.","I have ball.","I am a ball."],a:0,k:"句型：I have a...",e:"解析：I have a... 表示“我有一个……”，I 后面用 have。"},
{i:91,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"向别人介绍“这是我的玩具车”，应该说？",o:["This is my car.","That is my car.","It is my cars.","This my car."],a:0,k:"句型：This is my...",e:"解析：This is my... 是“这是我的……”，介绍近处的东西。"},
{i:92,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"想表达“我喜欢这个娃娃”，应该说？",o:["I like this doll.","I likes this doll.","I like doll.","I am like doll."],a:0,k:"句型：I like...",e:"解析：I like... 表示“我喜欢……”，I 后面动词用原形 like。"},
{i:93,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"邀请小伙伴一起玩，可以说？",o:["Let's play!","Let's go!","Let's eat!","Let's sing!"],a:0,k:"句型：Let's play",e:"解析：Let's play! 是“我们一起玩吧！”，Let's 是 Let us 的缩写。"},
{i:94,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"想知道“这是什么？”，应该问？",o:["What's this?","What's that?","Who's this?","How's this?"],a:0,k:"句型：What's this?",e:"解析：What's this? 问“这是什么？”（近处）；that 指远处。"},
{i:95,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"回答“它是一只风筝”，应该说？",o:["It's a kite.","It's kite.","Is a kite.","Its a kite."],a:0,k:"句型：It's a...",e:"解析：It's a... 是“它是一个……”，a 不能省。"},
{i:96,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,d:2,q:"下面哪一组东西全部是玩具？",o:["ball, doll, kite","car, cat, cake","book, bag, pen","apple, egg, milk"],a:0,k:"词汇归类：玩具",e:"解析：ball（球）、doll（娃娃）、kite（风筝）都是玩具；cake 是食物。"},
{i:97,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,d:2,q:"“Can I play with your ball?”这句话是在说什么？",o:["请求一起玩你的球","问球是什么颜色","说球很好看","把球送给你"],a:0,k:"句子理解：Can I...",e:"解析：Can I...? 是“我可以……吗？”，play with 是“玩……”，整句是请求一起玩。"},
{i:98,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,d:2,q:"哪种玩具通常在天上飞？",o:["kite","ball","doll","car"],a:0,k:"玩具特征：会飞的",e:"解析：kite（风筝）放上天会飞；ball 在地上拍，car 在地上跑。"},
{i:162,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,d:2,q:"“I have a ball, a kite and a car.” 这句话里一共提到几种玩具？",o:["3 种","2 种","4 种","1 种"],a:0,k:"句子理解：玩具数量统计",e:"解析：a ball（球）、a kite（风筝）、a car（小汽车），一共 3 种玩具。"},
{i:99,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:1,q:"补全：I ____ a new robot.（我有一个新机器人）",o:[],a:"have",k:"句型填空：I have",e:"解析：I have 表示“我有”，填“have”。"},

// ══════════ 一下·Unit 6 Animals 动物 ══════════
{i:100,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“狗”的英文是？",o:["dog","dig","dot","dag"],a:0,k:"动物：dog",e:"解析：狗是 dog。"},
{i:101,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“猫”的英文是？",o:["cat","cap","car","cut"],a:0,k:"动物：cat",e:"解析：猫是 cat。"},
{i:102,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“猪”的英文是？",o:["pig","big","peg","pug"],a:0,k:"动物：pig",e:"解析：猪是 pig。"},
{i:103,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“鸭子”的英文是？",o:["duck","dack","dock","dog"],a:0,k:"动物：duck",e:"解析：鸭子是 duck。"},
{i:104,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“鸟”的英文是？",o:["bird","brid","bard","bord"],a:0,k:"动物：bird",e:"解析：鸟是 bird。"},
{i:105,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“兔子”的英文是？",o:["rabbit","rabit","rabitt","rabbet"],a:0,k:"动物：rabbit",e:"解析：兔子是 rabbit（两个 b）。"},
{i:106,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“猴子”的英文是？",o:["monkey","monky","monke","monqey"],a:0,k:"动物：monkey",e:"解析：猴子是 monkey。"},
{i:107,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“老虎”的英文是？",o:["tiger","tigger","tigor","tigre"],a:0,k:"动物：tiger",e:"解析：老虎是 tiger。"},
{i:108,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“大象”的英文是？",o:["elephant","elephent","elephnat","elphant"],a:0,k:"动物：elephant",e:"解析：大象是 elephant。"},
{i:109,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“熊猫”的英文是？",o:["panda","pende","pando","pinda"],a:0,k:"动物：panda",e:"解析：熊猫是 panda。"},
{i:110,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“动物”的英文总称是？",o:["animal","anemal","animel","animan"],a:0,k:"单词：animal",e:"解析：动物是 animal。"},
{i:111,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"回答“它是一只猫”，应该说？",o:["It's a cat.","It's cat.","Its a cat.","Is a cat."],a:0,k:"句型：It's a + 动物",e:"解析：It's a cat. 表示“它是一只猫”，a 不能省略。"},
{i:112,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"小猫的叫声是？",o:["meow","woof","quack","moo"],a:0,k:"动物叫声：cat",e:"解析：猫叫 meow（喵）；woof 是狗叫，quack 是鸭叫。"},
{i:113,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"小狗的叫声是？",o:["woof","meow","quack","oink"],a:0,k:"动物叫声：dog",e:"解析：狗叫 woof（汪）；oink 是猪叫。"},
{i:114,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"下面哪种动物最大？",o:["elephant","cat","rabbit","bird"],a:0,k:"动物特征：大小",e:"解析：大象 elephant 是陆地上最大的动物。"},
{i:115,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,d:2,q:"下面哪一组动物全部会游泳？",o:["duck, fish","cat, dog","bird, monkey","tiger, rabbit"],a:0,k:"动物特征：会游泳",e:"解析：duck（鸭子）和 fish（鱼）都会游泳。"},
{i:116,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,d:2,q:"“It has a long nose.”描述的是哪种动物？",o:["elephant","monkey","rabbit","cat"],a:0,k:"描述猜测：长鼻子",e:"解析：long nose 是长鼻子，大象的鼻子最长。"},
{i:117,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,d:2,q:"猴子最喜欢吃下面哪种食物？",o:["banana","rice","bread","milk"],a:0,k:"动物与食物",e:"解析：猴子爱吃香蕉 banana。"},
{i:118,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,d:2,q:"“I can see three birds.”的意思是？",o:["我看见三只鸟。","我有三只鸟。","鸟有三只。","我喜欢三只鸟。"],a:0,k:"句子理解：I can see...",e:"解析：I can see 是“我能看见”，three birds 是“三只鸟”。"},
{i:119,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:1,q:"补全：— What's this? — It's a ____.（熊猫）",o:[],a:"panda",k:"动物填空：panda",e:"解析：熊猫是 panda，填“panda”。"},

// ══════════ 一下·Unit 7 Food 食物 ══════════
{i:120,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“面包”的英文是？",o:["bread","breed","bred","cake"],a:0,k:"食物：bread",e:"解析：面包是 bread。"},
{i:121,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“牛奶”的英文是？",o:["milk","malk","melk","millk"],a:0,k:"食物：milk",e:"解析：牛奶是 milk。"},
{i:122,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“蛋糕”的英文是？",o:["cake","coke","cack","caek"],a:0,k:"食物：cake",e:"解析：蛋糕是 cake；coke 是可乐，注意区分。"},
{i:123,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“米饭”的英文是？",o:["rice","rise","race","rike"],a:0,k:"食物：rice",e:"解析：米饭是 rice。"},
{i:124,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“水”的英文是？",o:["water","woter","watar","milk"],a:0,k:"食物：water",e:"解析：水是 water。"},
{i:125,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“果汁”的英文是？",o:["juice","juce","joice","juise"],a:0,k:"食物：juice",e:"解析：果汁是 juice。"},
{i:126,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“面条”的英文是？",o:["noodles","noodls","rice","noddles"],a:0,k:"食物：noodles",e:"解析：面条是 noodles，常用复数。"},
{i:127,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“鸡蛋”的英文是？",o:["egg","leg","age","fish"],a:0,k:"食物：egg",e:"解析：鸡蛋是 egg。"},
{i:128,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“食物”的英文总称是？",o:["food","foot","fool","fond"],a:0,k:"单词：food",e:"解析：食物是 food，注意和 foot（脚）区分。"},
{i:129,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"想说“我喜欢苹果”，应该说？",o:["I like apples.","I likes apple.","I like apple.","I am like apples."],a:0,k:"句型：I like + 复数",e:"解析：表示喜欢一类东西，名词常用复数 I like apples."},
{i:130,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"想说“我不喜欢牛奶”，应该说？",o:["I don't like milk.","I not like milk.","I doesn't like milk.","I no like milk."],a:0,k:"句型：I don't like...",e:"解析：否定用 don't like，I 后面用 don't。"},
{i:131,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"主人招待客人“吃点面包吧”，会说？",o:["Have some bread.","Has some bread.","Have a bread.","Eat breads."],a:0,k:"句型：Have some...",e:"解析：Have some... 是“吃点/喝点……吧”，bread 是不可数，不加 s。"},
{i:132,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"感觉“饿了”，应该说？",o:["I'm hungry.","I'm thirsty.","I'm happy.","I'm tired."],a:0,k:"感受：hungry",e:"解析：hungry 是“饿的”；thirsty 是“渴的”。"},
{i:133,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"感觉“渴了”，应该说？",o:["I'm thirsty.","I'm hungry.","I'm full.","I'm sad."],a:0,k:"感受：thirsty",e:"解析：thirsty 是“渴的”；full 是“饱的”。"},
{i:134,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,d:2,q:"下面哪一组全部是水果？",o:["apple, banana, orange","bread, rice, noodles","milk, water, juice","cake, egg, fish"],a:0,k:"食物分类：水果",e:"解析：apple（苹果）、banana（香蕉）、orange（橘子）都是水果。"},
{i:135,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,d:2,q:"口渴的时候，下面哪种最合适？",o:["water","bread","rice","cake"],a:0,k:"食物应用：解渴",e:"解析：water（水）最能解渴。"},
{i:136,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,d:2,q:"“Would you like some juice?”这句话是在？",o:["询问对方想不想喝果汁","说果汁很好喝","把果汁递过去","说没有果汁"],a:0,k:"句子理解：Would you like...",e:"解析：Would you like...? 是礼貌地问“你想要……吗？”。"},
{i:137,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,d:2,q:"为了身体健康，我们应该怎么做？",o:["多吃水果和蔬菜","只吃蛋糕","只喝果汁","不喝水"],a:0,k:"健康饮食",e:"解析：水果蔬菜富含维生素，搭配主食才健康，不能只吃甜食。"},
{i:138,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,d:2,q:"“I want two eggs.”的意思是？",o:["我想要两个鸡蛋。","我有两个鸡蛋。","我喜欢两个鸡蛋。","这是两个鸡蛋。"],a:0,k:"句子理解：I want...",e:"解析：I want 是“我想要”，two eggs 是“两个鸡蛋”。"},
{i:139,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:1,q:"补全：I'm ____.（我渴了）",o:[],a:"thirsty",k:"感受填空：thirsty",e:"解析：渴了是 thirsty，填“thirsty”。"},

// ══════════ 一下·Unit 8 My body 五官与身体 ══════════
{i:140,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“眼睛”的英文是？",o:["eye","ear","arm","egg"],a:0,k:"身体部位：eye",e:"解析：眼睛是 eye。"},
{i:141,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“耳朵”的英文是？",o:["ear","eye","are","arm"],a:0,k:"身体部位：ear",e:"解析：耳朵是 ear。"},
{i:142,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“鼻子”的英文是？",o:["nose","noise","rose","note"],a:0,k:"身体部位：nose",e:"解析：鼻子是 nose，注意和 noise（噪音）区分。"},
{i:143,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“嘴巴”的英文是？",o:["mouth","month","mouse","moth"],a:0,k:"身体部位：mouth",e:"解析：嘴巴是 mouth；month 是“月份”，注意区分。"},
{i:144,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“头”的英文是？",o:["head","hand","hair","hear"],a:0,k:"身体部位：head",e:"解析：头是 head；hand 是手，hair 是头发。"},
{i:145,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“手”的英文是？",o:["hand","head","hard","hair"],a:0,k:"身体部位：hand",e:"解析：手是 hand。"},
{i:146,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“脚”的英文是？",o:["foot","food","boot","feet"],a:0,k:"身体部位：foot",e:"解析：脚的单数是 foot；food 是食物。"},
{i:147,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“腿”的英文是？",o:["leg","foot","arm","let"],a:0,k:"身体部位：leg",e:"解析：腿是 leg。"},
{i:148,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“胳膊”的英文是？",o:["arm","are","art","aim"],a:0,k:"身体部位：arm",e:"解析：胳膊是 arm。"},
{i:149,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“脸”的英文是？",o:["face","fade","fact","fase"],a:0,k:"身体部位：face",e:"解析：脸是 face。"},
{i:150,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"介绍“这是我的鼻子”，应该说？",o:["This is my nose.","This is my noses.","These is my nose.","This my nose."],a:0,k:"句型：This is my nose",e:"解析：This is my nose. 表示“这是我的鼻子”。"},
{i:151,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"老师说“Touch your ears.”，意思是让你？",o:["摸摸耳朵","摸摸眼睛","摸摸鼻子","举起手"],a:0,k:"指令：Touch your...",e:"解析：Touch 是“摸”，your ears 是“你的耳朵”。"},
{i:152,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"我们用眼睛来做什么？",o:["see（看）","hear（听）","smell（闻）","eat（吃）"],a:0,k:"感官功能：eye",e:"解析：眼睛用来 see（看）；耳朵 hear（听），鼻子 smell（闻）。"},
{i:153,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"我们用耳朵来做什么？",o:["hear（听）","see（看）","smell（闻）","walk（走）"],a:0,k:"感官功能：ear",e:"解析：耳朵用来 hear（听）。"},
{i:154,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,d:2,q:"我们通常有几只眼睛？用英语说是？",o:["two eyes","one eye","two eye","two ears"],a:0,k:"复数：eyes",e:"解析：人有两只眼睛，two eyes，eye 变复数加 s。"},
{i:155,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,d:2,q:"下面哪一组全部是头部器官？",o:["eye, ear, nose","hand, foot, leg","arm, leg, foot","head, hand, arm"],a:0,k:"身体部位归类：头部",e:"解析：eye（眼）、ear（耳）、nose（鼻）都在头上。"},
{i:156,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,d:2,q:"我们用脚来做什么？",o:["walk（走路）","see（看）","hear（听）","smell（闻）"],a:0,k:"身体部位功能：foot",e:"解析：脚用来走路 walk；跑步也用脚。"},
{i:157,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,d:2,q:"“Clap your hands.”这句话让你做什么？",o:["拍手","摸头","跺脚","指鼻子"],a:0,k:"指令：Clap your hands",e:"解析：Clap 是“拍”，hands 是“手”，Clap your hands 就是拍手。"},
{i:158,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,d:2,q:"“I have two hands and two feet.”的意思是？",o:["我有两只手和两只脚。","我有两只手和一个头。","我有两只脚和两只眼睛。","我有一只手和两只脚。"],a:0,k:"句子理解：身体部位",e:"解析：two hands 两只手，two feet 两只脚（foot 的复数是 feet）。"},
{i:159,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:1,q:"补全：Touch your ____.（摸摸你的鼻子）",o:[],a:"nose",k:"部位填空：nose",e:"解析：鼻子是 nose，填“nose”。"}
);