if(!global.QA)global.QA={};
if(!QA["1en"])QA["1en"]=[];
QA["1en"].push(
{i:0,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“Hello!”的中文意思是？",o:["你好！","再见！","谢谢！","对不起！"],a:0,k:"打招呼：Hello",e:"解析：Hello! 是英语中最常用的打招呼用语，意思是'你好！'。"},
{i:1,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"你向小伙伴打招呼，可以说？",o:["Hi!","Bye!","Sorry!","No!"],a:0,k:"打招呼：Hi",e:"解析：Hi! 和 Hello! 都表示'你好！'，是熟人之间常用的打招呼方式。"},
{i:2,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“Goodbye!”的意思是？",o:["再见！","你好！","谢谢！","是！"],a:0,k:"告别：Goodbye",e:"解析：Goodbye! 是告别用语，意思是'再见！'，也可说 Bye!"},
{i:3,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"早上见到老师，你会说？",o:["Good morning.","Good night.","Goodbye.","Thank you."],a:0,k:"问候：Good morning",e:"解析：Good morning. 是'早上好'，用于上午见面时的问候。"},
{i:4,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"别人问“How are you?”，你很好，可以说？",o:["I'm fine, thank you.","I'm five.","Goodbye.","Hello."],a:0,k:"问候：How are you?",e:"解析：How are you? 问'你好吗？'，I'm fine 表示'我很好'，再加 thank you（谢谢）。"},
{i:5,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“Thank you.”的意思是？",o:["谢谢！","对不起！","你好！","再见！"],a:0,k:"礼貌：Thank you",e:"解析：Thank you. 是'谢谢！'，用来表达感谢。"},
{i:6,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"别人给你东西，你应说？",o:["Thank you.","Sorry.","Goodbye.","Hello."],a:0,k:"礼貌：Thank you",e:"解析：收到东西或帮助时应说 Thank you.（谢谢）。"},
{i:7,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“Hi!”和下面哪句意思相近？",o:["Hello!","Bye!","No!","Yes!"],a:0,k:"打招呼：Hi",e:"解析：Hi! 和 Hello! 都表示'你好！'，意思相近。"},
{i:8,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:1,q:"“你好！”用英语说是 ____。",o:[],a:"Hello",k:"打招呼：Hello",e:"解析：'你好！'的英语是 Hello，熟人之间也可以说 Hi。"},
{i:9,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:1,q:"和别人说再见，用 ____!（再见）",o:[],a:"Goodbye",k:"告别：Goodbye",e:"解析：'再见'的英语是 Goodbye，也可简写为 Bye。"},

{i:10,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母 Aa 的大写是？",o:["A","B","C","D"],a:0,k:"字母：A",e:"解析：字母 Aa 的大写形式是 A，小写是 a。"},
{i:11,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母“Bb”的小写是？",o:["b","a","c","d"],a:0,k:"字母：B",e:"解析：字母 Bb 的小写是 b，大写是 B。"},
{i:12,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"下列字母中，排在 Cc 后面的是？",o:["Dd","Bb","Aa","Ee"],a:0,k:"字母顺序",e:"解析：字母顺序为 Aa、Bb、Cc、Dd、Ee、Ff，Cc 后面是 Dd。"},
{i:13,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"单词“apple”（苹果）以哪个字母开头？",o:["A","B","C","D"],a:0,k:"字母：A",e:"解析：apple 以字母 A 开头，A 发 /æ/ 音。"},
{i:14,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"单词“cat”（猫）以哪个字母开头？",o:["C","A","B","D"],a:0,k:"字母：C",e:"解析：cat 以字母 C 开头。"},
{i:15,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母 Ee 的大写是？",o:["E","F","D","B"],a:0,k:"字母：E",e:"解析：字母 Ee 的大写是 E，小写是 e。"},
{i:16,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母“Ff”的小写是？",o:["f","e","a","b"],a:0,k:"字母：F",e:"解析：字母 Ff 的小写是 f，大写是 F。"},
{i:17,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"下列字母中，紧挨在 Ff 前面的是？",o:["Ee","Dd","Cc","Bb"],a:0,k:"字母顺序",e:"解析：顺序 Aa、Bb、Cc、Dd、Ee、Ff，紧挨在 Ff 前面的是 Ee。"},
{i:18,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母 Dd 的小写是？",o:["d","b","p","q"],a:0,k:"字母：D",e:"解析：字母 Dd 的小写是 d，大写是 D。"},
{i:19,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:1,q:"单词“狗 dog”以字母 ____ 开头。",o:[],a:"D",k:"字母：D",e:"解析：dog（狗）以字母 D 开头。"},
{i:20,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:1,q:"字母“Ee”的小写写法是 ____。",o:[],a:"e",k:"字母：E",e:"解析：字母 Ee 的小写是 e。"},

{i:21,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“红色”用英语说是？",o:["red","yellow","blue","green"],a:0,k:"颜色：red",e:"解析：red 表示'红色'。"},
{i:22,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“蓝色”用英语说是？",o:["blue","black","brown","green"],a:0,k:"颜色：blue",e:"解析：blue 表示'蓝色'。"},
{i:23,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“yellow”的意思是？",o:["黄色","绿色","红色","蓝色"],a:0,k:"颜色：yellow",e:"解析：yellow 表示'黄色'。"},
{i:24,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“green”的意思是？",o:["绿色","黄色","白色","黑色"],a:0,k:"颜色：green",e:"解析：green 表示'绿色'。"},
{i:25,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"下列颜色中表示“黄色”的是？",o:["yellow","red","blue","green"],a:0,k:"颜色：yellow",e:"解析：yellow 表示'黄色'。"},
{i:26,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"你想说“红色的书”，应说？",o:["red book","yellow book","blue book","green book"],a:0,k:"搭配：颜色+物品",e:"解析：颜色词放在物品前，red book 即'红色的书'。"},
{i:27,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“red”的意思是？",o:["红色","蓝色","黄色","绿色"],a:0,k:"颜色：red",e:"解析：red 表示'红色'。"},
{i:28,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"天空常是蓝色，蓝色用英语说是？",o:["blue","green","yellow","red"],a:0,k:"颜色：blue",e:"解析：blue 表示'蓝色'，天空是 blue sky。"},
{i:29,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:1,q:"“绿色”用英语说是 ____。",o:[],a:"green",k:"颜色：green",e:"解析：'绿色'的英语是 green。"},
{i:30,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:1,q:"“黄色”用英语说是 ____。",o:[],a:"yellow",k:"颜色：yellow",e:"解析：'黄色'的英语是 yellow。"},

{i:31,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“one”的意思是？",o:["一","二","三","五"],a:0,k:"数字：one",e:"解析：one 表示数字'一'。"},
{i:32,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“two”的意思是？",o:["二","一","三","四"],a:0,k:"数字：two",e:"解析：two 表示数字'二'。"},
{i:33,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“three”的意思是？",o:["三","二","四","五"],a:0,k:"数字：three",e:"解析：three 表示数字'三'。"},
{i:34,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“four”的意思是？",o:["四","三","五","二"],a:0,k:"数字：four",e:"解析：four 表示数字'四'。"},
{i:35,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“five”的意思是？",o:["五","四","三","二"],a:0,k:"数字：five",e:"解析：five 表示数字'五'。"},
{i:36,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"你有 3 支铅笔，用英语说？",o:["three pencils","two pencils","four pencils","five pencils"],a:0,k:"数字+物品",e:"解析：3 是 three，铅笔是 pencil（复数为 pencils），three pencils 即'三支铅笔'。"},
{i:37,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"下列数字中“五”是？",o:["five","four","three","two"],a:0,k:"数字：five",e:"解析：five 表示'五'。"},
{i:38,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“一”用英语说是？",o:["one","two","three","four"],a:0,k:"数字：one",e:"解析：one 表示数字'一'。"},
{i:39,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:1,q:"“四”用英语说是 ____。",o:[],a:"four",k:"数字：four",e:"解析：数字'四'的英语是 four。"},
{i:40,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:1,q:"“二”用英语说是 ____。",o:[],a:"two",k:"数字：two",e:"解析：数字'二'的英语是 two。"},

{i:41,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“ball”的意思是？",o:["球","娃娃","汽车","风筝"],a:0,k:"玩具：ball",e:"解析：ball 表示'球'。"},
{i:42,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“doll”的意思是？",o:["娃娃","球","风筝","车"],a:0,k:"玩具：doll",e:"解析：doll 表示'娃娃'。"},
{i:43,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“car”的意思是？",o:["小汽车","球","娃娃","积木"],a:0,k:"玩具：car",e:"解析：car 表示'小汽车'。"},
{i:44,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“kite”的意思是？",o:["风筝","球","车","娃娃"],a:0,k:"玩具：kite",e:"解析：kite 表示'风筝'。"},
{i:45,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“teddy bear”的意思是？",o:["玩具熊","娃娃","球","汽车"],a:0,k:"玩具：teddy bear",e:"解析：teddy bear 表示'玩具熊'。"},
{i:46,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"你喜欢玩球，会说？",o:["I like the ball.","I like the doll.","I like the car.","I like the kite."],a:0,k:"句型：I like...",e:"解析：I like... 表示'我喜欢……'，the ball 是'球'。"},
{i:47,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"下列物品中是“风筝”的是？",o:["kite","ball","car","doll"],a:0,k:"玩具：kite",e:"解析：kite 表示'风筝'。"},
{i:48,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“娃娃”用英语说是？",o:["doll","ball","car","kite"],a:0,k:"玩具：doll",e:"解析：doll 表示'娃娃'。"},
{i:49,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:1,q:"“球”用英语说是 ____。",o:[],a:"ball",k:"玩具：ball",e:"解析：'球'的英语是 ball。"},
{i:50,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:1,q:"“小汽车”用英语说是 ____。",o:[],a:"car",k:"玩具：car",e:"解析：'小汽车'的英语是 car。"},

{i:51,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“cat”的意思是？",o:["猫","狗","鱼","鸭"],a:0,k:"动物：cat",e:"解析：cat 表示'猫'。"},
{i:52,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“dog”的意思是？",o:["狗","猫","兔","鸟"],a:0,k:"动物：dog",e:"解析：dog 表示'狗'。"},
{i:53,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“fish”的意思是？",o:["鱼","猫","狗","鸟"],a:0,k:"动物：fish",e:"解析：fish 表示'鱼'。"},
{i:54,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“bird”的意思是？",o:["鸟","鱼","兔","鸭"],a:0,k:"动物：bird",e:"解析：bird 表示'鸟'。"},
{i:55,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“rabbit”的意思是？",o:["兔子","鸭","鱼","猫"],a:0,k:"动物：rabbit",e:"解析：rabbit 表示'兔子'。"},
{i:56,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“duck”的意思是？",o:["鸭子","兔子","鸟","狗"],a:0,k:"动物：duck",e:"解析：duck 表示'鸭子'。"},
{i:57,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"你喜欢小狗，会说？",o:["I like the dog.","I like the cat.","I like the fish.","I like the bird."],a:0,k:"句型：I like...",e:"解析：dog 是'狗'，I like the dog. 即'我喜欢小狗'。"},
{i:58,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"下列动物中“鱼”是？",o:["fish","cat","dog","duck"],a:0,k:"动物：fish",e:"解析：fish 表示'鱼'。"},
{i:59,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:1,q:"“猫”用英语说是 ____。",o:[],a:"cat",k:"动物：cat",e:"解析：'猫'的英语是 cat。"},
{i:60,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:1,q:"“鸟”用英语说是 ____。",o:[],a:"bird",k:"动物：bird",e:"解析：'鸟'的英语是 bird。"},

{i:61,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“apple”的意思是？",o:["苹果","香蕉","蛋","牛奶"],a:0,k:"食物：apple",e:"解析：apple 表示'苹果'。"},
{i:62,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“banana”的意思是？",o:["香蕉","苹果","面包","水"],a:0,k:"食物：banana",e:"解析：banana 表示'香蕉'。"},
{i:63,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“egg”的意思是？",o:["鸡蛋","苹果","牛奶","面包"],a:0,k:"食物：egg",e:"解析：egg 表示'鸡蛋'。"},
{i:64,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“milk”的意思是？",o:["牛奶","水","果汁","茶"],a:0,k:"食物：milk",e:"解析：milk 表示'牛奶'。"},
{i:65,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“bread”的意思是？",o:["面包","米饭","蛋","苹果"],a:0,k:"食物：bread",e:"解析：bread 表示'面包'。"},
{i:66,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“water”的意思是？",o:["水","牛奶","果汁","面包"],a:0,k:"食物：water",e:"解析：water 表示'水'。"},
{i:67,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"你想吃苹果，会说？",o:["I like apples.","I like bananas.","I like eggs.","I like milk."],a:0,k:"句型：I like...",e:"解析：apple 的复数是 apples，I like apples. 即'我喜欢苹果'。"},
{i:68,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"下列食物中“鸡蛋”是？",o:["egg","apple","milk","bread"],a:0,k:"食物：egg",e:"解析：egg 表示'鸡蛋'。"},
{i:69,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:1,q:"“香蕉”用英语说是 ____。",o:[],a:"banana",k:"食物：banana",e:"解析：'香蕉'的英语是 banana。"},
{i:70,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:1,q:"“牛奶”用英语说是 ____。",o:[],a:"milk",k:"食物：milk",e:"解析：'牛奶'的英语是 milk。"},

{i:71,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“eye”的意思是？",o:["眼睛","耳朵","鼻子","嘴巴"],a:0,k:"身体：eye",e:"解析：eye 表示'眼睛'。"},
{i:72,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“ear”的意思是？",o:["耳朵","眼睛","手","脚"],a:0,k:"身体：ear",e:"解析：ear 表示'耳朵'。"},
{i:73,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“nose”的意思是？",o:["鼻子","嘴巴","眼睛","手"],a:0,k:"身体：nose",e:"解析：nose 表示'鼻子'。"},
{i:74,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“mouth”的意思是？",o:["嘴巴","鼻子","眼睛","耳朵"],a:0,k:"身体：mouth",e:"解析：mouth 表示'嘴巴'。"},
{i:75,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“hand”的意思是？",o:["手","脚","头","腿"],a:0,k:"身体：hand",e:"解析：hand 表示'手'。"},
{i:76,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“foot”的意思是？",o:["脚","手","头","腿"],a:0,k:"身体：foot",e:"解析：foot 表示'脚'。"},
{i:77,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"你想让别人看你的手，应说？",o:["Look at my hand.","Look at my foot.","This is my hand.","Touch your hand."],a:0,k:"句型：Look at my...",e:"解析：Look at my hand. 意思是'看我的手'，hand 是'手'。"},
{i:78,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"下列身体部位中“鼻子”是？",o:["nose","eye","ear","mouth"],a:0,k:"身体：nose",e:"解析：nose 表示'鼻子'。"},
{i:79,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:1,q:"“眼睛”用英语说是 ____。",o:[],a:"eye",k:"身体：eye",e:"解析：'眼睛'的英语是 eye。"},
{i:80,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:1,q:"“手”用英语说是 ____。",o:[],a:"hand",k:"身体：hand",e:"解析：'手'的英语是 hand。"}
);
