if(!global.QA)global.QA={};
if(!QA["1en"])QA["1en"]=[];
QA["1en"].push(
{i:24000,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"下午见到同学，应该说：",o:["Good morning.","Good afternoon.","Good night.","Goodbye."],a:1,k:"问候语：Good afternoon",e:"解析：下午见面问好用“Good afternoon.”；早上用“Good morning.”，睡前用“Good night.”。"},
{i:24001,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"晚上睡觉前，可以对家人说：",o:["Good afternoon.","Hello.","Thank you.","Good night."],a:3,k:"问候语：Good night",e:"解析：睡觉前道晚安用“Good night.”；它不是打招呼用语，而是分别、就寝时说的话。"},
{i:24002,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"你想知道新同学的名字，应该问：",o:["How are you?","What's your name?","Good morning.","I'm fine."],a:1,k:"句型：What's your name?",e:"解析：询问对方名字用“What's your name?”（你叫什么名字？）；“How are you?”是问身体怎么样。"},
{i:24003,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"别人问“What's your name?”，你可以回答：",o:["I'm fine.","Goodbye.","I'm Amy.","Thank you."],a:2,k:"句型：I'm + 名字",e:"解析：回答名字用“I'm Amy.”（我是艾米）。“I'm fine.”是回答“How are you?”的。"},
{i:24004,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“How are you?”的意思是：",o:["你好吗？","你几岁了？","你叫什么名字？","再见！"],a:0,k:"句型：How are you?",e:"解析：“How are you?”是见面时问候对方身体、心情，意思是“你好吗？”，常回答“I'm fine, thank you.”。"},
{i:24005,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"“I'm fine, thank you.”的意思是：",o:["我五岁了。","我很好，谢谢。","我是艾米。","对不起。"],a:1,k:"句型：I'm fine, thank you.",e:"解析：“fine”表示身体好、很好，整句意思是“我很好，谢谢。”，用来回答“How are you?”。"},
{i:24006,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"放学离开学校时，应该对老师说：",o:["Good morning.","Hello.","Goodbye.","Good night."],a:2,k:"告别语：Goodbye",e:"解析：分别、离开时用“Goodbye.”（再见）；“Hello.”是见面时用的。"},
{i:24007,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:0,q:"别人对你说“Thank you.”，你可以回答：",o:["Goodbye.","Hello.","Good night.","You're welcome."],a:3,k:"礼貌用语：You're welcome",e:"解析：别人道谢后要说“You're welcome.”（不用谢），这是英语里最常见的回应。"},
{i:24008,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:1,q:"早上见到老师问好，要说“Good ____.”",o:[],a:"morning",k:"问候语：Good morning",e:"解析：早上（上午）问候用“Good morning.”，下午用“Good afternoon.”。"},
{i:24009,c:"1en-1",ch:"一上·Unit 1 Hello! 打招呼",f:1,q:"晚上睡觉前，对爸爸妈妈说“Good ____.”",o:[],a:"night",k:"问候语：Good night",e:"解析：睡前道晚安说“Good night.”（晚安），注意不是“Good evening.”。"},
{i:24010,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母 Bb 的大写是？",o:["D","A","B","E"],a:2,k:"字母：Bb",e:"解析：Bb 的大写是 B，小写是 b。字母有大写和小写两种写法。"},
{i:24011,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"字母 Cc 的大写是？",o:["E","D","C","B"],a:2,k:"字母：Cc",e:"解析：Cc 的大写是 C，小写是 c。C 排在 A、B 后面，是第三个字母。"},
{i:24012,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"单词“egg”（鸡蛋）以哪个字母开头？",o:["A","B","C","E"],a:3,k:"字母与单词：egg",e:"解析：“egg”拼写为 e-g-g，第一个字母是 E。"},
{i:24013,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"单词“fish”（鱼）以哪个字母开头？",o:["D","F","A","B"],a:1,k:"字母与单词：fish",e:"解析：“fish”拼写为 f-i-s-h，第一个字母是 F。"},
{i:24014,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"小写字母 a 的大写是？",o:["C","A","B","E"],a:1,k:"字母：Aa",e:"解析：小写 a 的大写是 A，Aa 是字母表的第一个字母。"},
{i:24015,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"按字母表顺序，Aa 后面紧挨着的是？",o:["Cc","Dd","Bb","Ee"],a:2,k:"字母顺序：Aa Bb Cc",e:"解析：字母表顺序是 Aa、Bb、Cc、Dd、Ee、Ff，所以 Aa 后面是 Bb。"},
{i:24016,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"“苹果”的正确英文拼写是？",o:["eppla","apple","aplle","appel"],a:1,k:"单词拼写：apple",e:"解析：“苹果”拼写为 a-p-p-l-e，有两个 p，结尾是 l-e。"},
{i:24017,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:0,q:"“狗”的正确英文拼写是？",o:["dgo","god","dog","odg"],a:2,k:"单词拼写：dog",e:"解析：“狗”拼写为 d-o-g，字母顺序不能调换，god 是另一个单词。"},
{i:24018,c:"1en-2",ch:"一上·Unit 2 Letters 字母 Aa–Ff",f:1,q:"小写字母 c 的大写写法是 ____。",o:[],a:"C",k:"字母：Cc",e:"解析：c 的大写是 C，写法像个小月牙。"},
{i:24019,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“black”的意思是？",o:["白色","绿色","黑色","红色"],a:2,k:"颜色词：black",e:"解析：“black”是黑色，如黑板 black board。"},
{i:24020,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“white”的意思是？",o:["黑色","白色","蓝色","绿色"],a:1,k:"颜色词：white",e:"解析：“white”是白色，black（黑）和 white（白）是一对反义词。"},
{i:24021,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"香蕉是什么颜色的？",o:["blue","yellow","red","green"],a:1,k:"颜色词：yellow",e:"解析：香蕉是黄色的，黄色是 yellow；blue 是蓝色，red 是红色，green 是绿色。"},
{i:24022,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“brown”的意思是？",o:["绿色","棕色","紫色","灰色"],a:1,k:"颜色词：brown",e:"解析：“brown”表示棕色、褐色，巧克力常是 brown。"},
{i:24023,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“一支蓝色的铅笔”用英语说是？",o:["a red pencil","a green pencil","a blue pencil","a black pencil"],a:2,k:"颜色+名词：a blue pencil",e:"解析：英语里颜色放在名词前面，蓝色的铅笔是 a blue pencil。"},
{i:24024,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“orange”表示颜色时的意思是？",o:["红色","橙色","绿色","白色"],a:1,k:"颜色词：orange",e:"解析：“orange”既可指橙子这种水果，也可表示橙色。"},
{i:24025,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"“pink”的意思是？",o:["紫色","粉色","棕色","黑色"],a:1,k:"颜色词：pink",e:"解析：“pink”是粉色，桃花常是 pink。"},
{i:24026,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:0,q:"天空和大海常常是什么颜色？",o:["green","white","red","blue"],a:3,k:"颜色词：blue",e:"解析：天空和大海是蓝色的，蓝色是 blue。"},
{i:24027,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:1,q:"“黑色”用英语说是 ____。",o:[],a:"black",k:"颜色词：black",e:"解析：黑色是 black，拼写为 b-l-a-c-k。"},
{i:24028,c:"1en-3",ch:"一上·Unit 3 Colours 颜色",f:1,q:"雪是白色的，“白色”用英语说是 ____。",o:[],a:"white",k:"颜色词：white",e:"解析：白色是 white，拼写为 w-h-i-t-e。"},
{i:24029,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“How many?”的意思是？",o:["你几岁？","多少个？","多少钱？","什么颜色？"],a:1,k:"句型：How many?",e:"解析：“How many?”用来问可数东西的数量，意思是“多少个？”。"},
{i:24030,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“三”用英语说是？",o:["two","three","four","five"],a:1,k:"数字词：three",e:"解析：一 one、二 two、三 three、四 four、五 five，三是 three。"},
{i:24031,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"2 + 1 = 3，三用英语说是？",o:["one","three","two","four"],a:1,k:"数字词：three",e:"解析：2 加 1 等于 3，三的英文是 three。"},
{i:24032,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"你有 4 本书，用英语说是？",o:["three books","five books","four books","two books"],a:2,k:"数字+名词：four books",e:"解析：4 是 four，“4 本书”要说 four books，数字超过 1 时名词要加 s。"},
{i:24033,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"“five”的意思是？",o:["四","五","三","二"],a:1,k:"数字词：five",e:"解析：five 是五；four 是四，别把这两个词记混。"},
{i:24034,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"小鸟有两只翅膀，“two”的意思是？",o:["一","二","三","四"],a:1,k:"数字词：two",e:"解析：two 是二，two wings 就是两只翅膀。"},
{i:24035,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"一只猫有四条腿，四用英语说是？",o:["four","three","two","five"],a:0,k:"数字词：four",e:"解析：猫有四条腿，四是 four，four legs 就是四条腿。"},
{i:24036,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:0,q:"按 one、two、three 的顺序，下一个是？",o:["five","four","one","two"],a:1,k:"数字顺序：one two three four",e:"解析：数字顺序是 one、two、three、four、five，three 后面是 four。"},
{i:24037,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:1,q:"“三”用英语说是 ____。",o:[],a:"three",k:"数字词：three",e:"解析：三是 three，拼写为 t-h-r-e-e。"},
{i:24038,c:"1en-4",ch:"一上·Unit 4 Numbers 数字 1–5",f:1,q:"数字 1 用英语说是 ____。",o:[],a:"one",k:"数字词：one",e:"解析：1 是 one，拼写为 o-n-e。"},
{i:24039,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“plane”的意思是？",o:["火车","飞机","汽车","娃娃"],a:1,k:"玩具词：plane",e:"解析：“plane”是飞机，玩具飞机是 a toy plane。"},
{i:24040,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“boat”的意思是？",o:["汽车","风筝","小船","球"],a:2,k:"玩具词：boat",e:"解析：“boat”是小船，car 才是汽车，kite 是风筝。"},
{i:24041,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“balloon”的意思是？",o:["积木","球","气球","风筝"],a:2,k:"玩具词：balloon",e:"解析：“balloon”是气球；“ball”才是球，两个词长得很像，要分清。"},
{i:24042,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"你想说“我有一个风筝”，应说：",o:["I have a doll.","I have a ball.","I have a kite.","I have a car."],a:2,k:"句型：I have a ...",e:"解析：“I have a kite.”意思是“我有一个风筝”，have 表示“有”，kite 是风筝。"},
{i:24043,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"“toy”的意思是？",o:["书本","玩具","食物","动物"],a:1,k:"单词：toy",e:"解析：“toy”是玩具，ball、doll、kite 都是 toy。"},
{i:24044,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"下列单词中表示“玩具熊”的是？",o:["balloon","plane","teddy bear","boat"],a:2,k:"玩具词：teddy bear",e:"解析：“teddy bear”是玩具熊，teddy 和 bear 两个词合起来写。"},
{i:24045,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"玩具小汽车的英文是？",o:["kite","car","doll","ball"],a:1,k:"玩具词：car",e:"解析：小汽车是 car；kite 风筝、doll 娃娃、ball 球都不是车。"},
{i:24046,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:0,q:"朋友问你喜欢什么玩具，你说“我喜欢球”，应说：",o:["I like the kite.","I like the doll.","I like the ball.","I like the car."],a:2,k:"句型：I like the ...",e:"解析：“I like the ball.”意思是“我喜欢这个球”，like 表示“喜欢”。"},
{i:24047,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:1,q:"“风筝”用英语说是 ____。",o:[],a:"kite",k:"玩具词：kite",e:"解析：风筝是 kite，拼写为 k-i-t-e。"},
{i:24048,c:"1en-5",ch:"一上·Unit 5 Toys 玩具",f:1,q:"“玩具娃娃”用英语说是 ____。",o:[],a:"doll",k:"玩具词：doll",e:"解析：娃娃是 doll，拼写为 d-o-l-l，结尾有两个 l。"},
{i:24049,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“monkey”的意思是？",o:["老虎","猴子","大象","熊猫"],a:1,k:"动物词：monkey",e:"解析：“monkey”是猴子，猴子爱吃香蕉。"},
{i:24050,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“panda”的意思是？",o:["狮子","熊猫","猴子","鸭子"],a:1,k:"动物词：panda",e:"解析：“panda”是熊猫，是中国的国宝。"},
{i:24051,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“pig”的意思是？",o:["牛","猪","羊","鸭"],a:1,k:"动物词：pig",e:"解析：“pig”是猪；牛是 cow，鸭是 duck。"},
{i:24052,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“cow”的意思是？",o:["马","鸡","奶牛","猪"],a:2,k:"动物词：cow",e:"解析：“cow”是奶牛，我们喝的牛奶就来自 cow。"},
{i:24053,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“lion”的意思是？",o:["老虎","狮子","大象","熊"],a:1,k:"动物词：lion",e:"解析：“lion”是狮子；老虎是 tiger，不要记混。"},
{i:24054,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"你喜欢熊猫，可以说：",o:["I like the dog.","I like the panda.","I like the cat.","I like the fish."],a:1,k:"句型：I like the ...",e:"解析：“I like the panda.”意思是“我喜欢熊猫”，panda 是熊猫。"},
{i:24055,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"下列单词中表示“猴子”的是？",o:["panda","pig","monkey","cow"],a:2,k:"动物词：monkey",e:"解析：猴子是 monkey；panda 熊猫、pig 猪、cow 奶牛都不是。"},
{i:24056,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:0,q:"“hen”的意思是？",o:["鸭子","母鸡","小鸟","兔子"],a:1,k:"动物词：hen",e:"解析：“hen”是母鸡；鸭子是 duck，兔子是 rabbit。"},
{i:24057,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:1,q:"“熊猫”用英语说是 ____。",o:[],a:"panda",k:"动物词：panda",e:"解析：熊猫是 panda，拼写为 p-a-n-d-a。"},
{i:24058,c:"1en-6",ch:"一下·Unit 6 Animals 动物",f:1,q:"“猴子”用英语说是 ____。",o:[],a:"monkey",k:"动物词：monkey",e:"解析：猴子是 monkey，拼写为 m-o-n-k-e-y。"},
{i:24059,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“rice”的意思是？",o:["面条","米饭","蛋糕","果汁"],a:1,k:"食物词：rice",e:"解析：“rice”是米饭；面条是 noodles。"},
{i:24060,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“noodles”的意思是？",o:["米饭","面条","鸡蛋","牛奶"],a:1,k:"食物词：noodles",e:"解析：“noodles”是面条，常用复数形式，结尾加 s。"},
{i:24061,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“cake”的意思是？",o:["糖果","蛋糕","米饭","汤"],a:1,k:"食物词：cake",e:"解析：“cake”是蛋糕，生日吃的生日蛋糕是 birthday cake。"},
{i:24062,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“juice”的意思是？",o:["水","茶","果汁","牛奶"],a:2,k:"食物词：juice",e:"解析：“juice”是果汁；水是 water，牛奶是 milk。"},
{i:24063,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"你口渴了想喝水，可以说：",o:["I like bread.","I like rice.","I want water.","I like eggs."],a:2,k:"句型：I want ...",e:"解析：“I want water.”意思是“我想要水”，want 表示“想要”，水是 water。"},
{i:24064,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"“orange”表示水果时的意思是？",o:["苹果","橙子","香蕉","梨"],a:1,k:"食物词：orange",e:"解析：“orange”作水果讲是橙子，作颜色讲是橙色。"},
{i:24065,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"下列单词中表示“米饭”的是？",o:["noodles","bread","rice","cake"],a:2,k:"食物词：rice",e:"解析：米饭是 rice；noodles 面条、bread 面包、cake 蛋糕都不是米饭。"},
{i:24066,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:0,q:"你饿了想吃面包，可以说：",o:["I like milk.","I want bread.","I like water.","I want rice."],a:1,k:"句型：I want ...",e:"解析：“I want bread.”意思是“我想要面包”，bread 是面包。"},
{i:24067,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:1,q:"“面包”用英语说是 ____。",o:[],a:"bread",k:"食物词：bread",e:"解析：面包是 bread，拼写为 b-r-e-a-d。"},
{i:24068,c:"1en-7",ch:"一下·Unit 7 Food 食物",f:1,q:"“水”用英语说是 ____。",o:[],a:"water",k:"食物词：water",e:"解析：水是 water，拼写为 w-a-t-e-r。"},
{i:24069,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“head”的意思是？",o:["手","头","脚","耳"],a:1,k:"身体部位：head",e:"解析：“head”是头；手是 hand，脚是 foot。"},
{i:24070,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“leg”的意思是？",o:["脚","手","腿","鼻"],a:2,k:"身体部位：leg",e:"解析：“leg”是腿；脚是 foot，手是 hand，别记混。"},
{i:24071,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“arm”的意思是？",o:["腿","手","胳膊","头"],a:2,k:"身体部位：arm",e:"解析：“arm”是胳膊；hand 是手，leg 是腿。"},
{i:24072,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“hair”的意思是？",o:["眉毛","头发","手指","脸"],a:1,k:"身体部位：hair",e:"解析：“hair”是头发，长在 head（头）上。"},
{i:24073,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“face”的意思是？",o:["脸","头","脖子","肩膀"],a:0,k:"身体部位：face",e:"解析：“face”是脸，眼睛、鼻子、嘴巴都长在脸上。"},
{i:24074,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"你想让同学摸摸鼻子，可以说：",o:["Touch your mouth.","Touch your ear.","Touch your nose.","Touch your eye."],a:2,k:"指令：Touch your ...",e:"解析：“Touch your nose.”意思是“摸摸你的鼻子”，touch 是“摸”，nose 是鼻子。"},
{i:24075,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"下列单词中表示“脚”的是？",o:["hand","head","foot","leg"],a:2,k:"身体部位：foot",e:"解析：脚是 foot；hand 手、head 头、leg 腿都不是脚。"},
{i:24076,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:0,q:"“This is my head.”的意思是？",o:["这是我的手。","这是我的脸。","这是我的头。","这是我的腿。"],a:2,k:"句型：This is my ...",e:"解析：“This is my head.”意思是“这是我的头”，head 是头。"},
{i:24077,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:1,q:"“耳朵”用英语说是 ____。",o:[],a:"ear",k:"身体部位：ear",e:"解析：耳朵是 ear，拼写为 e-a-r。"},
{i:24078,c:"1en-8",ch:"一下·Unit 8 My body 五官与身体",f:1,q:"“脚”用英语说是 ____。",o:[],a:"foot",k:"身体部位：foot",e:"解析：脚是 foot，拼写为 f-o-o-t，中间是两个 o。"}
);
