if(!global.QA)global.QA={};
if(!QA["2en"])QA["2en"]=[];
QA["2en"].push(
{i:25000,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"“Good morning.”的意思是？",o:["晚上好。","早上好。","再见。","谢谢。"],a:1,k:"问候：Good morning",e:"解析：Good morning. 是“早上好”，用于上午见面问候；Good evening 才是“晚上好”。"},
{i:25001,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"睡觉前对家人说“晚安”，应该说？",o:["Good morning.","Good afternoon.","Good night.","Hello!"],a:2,k:"问候：Good night",e:"解析：睡前道别说 Good night.（晚安）；Good evening 是傍晚见面时的“晚上好”，两者用法不同。"},
{i:25002,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"早上见到李老师，你会说？",o:["Good night, Miss Li.","Good afternoon, Miss Li.","Good evening, Miss Li.","Good morning, Miss Li."],a:3,k:"问候：Good morning",e:"解析：早上见到老师要说 Good morning, Miss Li.（李老师，早上好），Miss 用于称呼女老师。"},
{i:25003,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"对方说“Nice to meet you.”，你应该回答？",o:["Good morning.","Nice to meet you, too.","I'm fine.","See you."],a:1,k:"交际：Nice to meet you, too",e:"解析：初次见面对方说“很高兴认识你”，通常回答 Nice to meet you, too.（我也很高兴认识你），too 表示“也”。"},
{i:25004,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"别人对你说“Thank you.”，你应回答？",o:["You're welcome.","Good night.","Goodbye.","I'm sorry."],a:0,k:"礼貌用语：You're welcome",e:"解析：Thank you. / Thanks. 的常用回答是 You're welcome.（不客气），不能用来回答道别。"},
{i:25005,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"“Goodbye.”的另一种说法是？",o:["Bye!","Hello!","Sorry.","Thanks."],a:0,k:"道别：Bye",e:"解析：Goodbye 和 Bye 都表示“再见”，Bye 更口语化，常和朋友、家人使用。"},
{i:25006,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"“Hi!”的意思是？",o:["再见。","你好！","谢谢。","对不起。"],a:1,k:"问候：Hi",e:"解析：Hi 和 Hello 都表示“你好”，用于朋友之间打招呼，回答也可以说 Hi!"},
{i:25007,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"朋友问“How are you?”，你身体不太舒服，应回答？",o:["I'm five.","I'm not so good.","I'm Tom.","Good night."],a:1,k:"回答：I'm not so good",e:"解析：感觉不太好时说 I'm not so good.；“我很好”才说 I'm fine, thank you.，I'm five 是回答年龄。"},
{i:25008,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"你想知道新同学的名字，应该问？",o:["How are you?","How old are you?","What's your name?","Good morning."],a:2,k:"询问姓名：What's your name?",e:"解析：问名字用 What's your name?（你叫什么名字？），回答用 My name is... 或 I'm...；How old 问的是年龄。"},
{i:25009,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:1,q:"—How are you? —I'm ____, thank you.",o:[],a:"fine",k:"回答：I'm fine",e:"解析：How are you? 最常用的回答是 I'm fine, thank you.（我很好，谢谢），fine 表示“身体好、不错”。"},
{i:25010,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"字母“H”的小写是？",o:["h","n","k","b"],a:0,k:"字母：Hh",e:"解析：大写 H 的小写是 h，写法是一竖加一竖再加中间一短横，占中上两格。"},
{i:25011,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"字母“i”的大写是？",o:["L","I","J","N"],a:1,k:"字母：Ii",e:"解析：小写 i 的大写是 I，大写 I 是一竖，上下各有一小横；小写的点上一点。"},
{i:25012,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"单词“nose”（鼻子）以哪个字母开头？",o:["M","N","H","L"],a:1,k:"字母：Nn",e:"解析：nose 拼写为 n-o-s-e，首字母是 n，大写写作 N。"},
{i:25013,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"单词“mouth”（嘴）以哪个字母开头？",o:["N","W","M","H"],a:2,k:"字母：Mm",e:"解析：mouth 拼写为 m-o-u-t-h，首字母是 m，大写写作 M。"},
{i:25014,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"单词“leg”（腿）以哪个字母开头？",o:["I","N","L","G"],a:2,k:"字母：Ll",e:"解析：leg 拼写为 l-e-g，首字母是 l，大写写作 L。"},
{i:25015,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"单词“girl”（女孩）以哪个字母开头？",o:["J","G","K","N"],a:1,k:"字母：Gg",e:"解析：girl 拼写为 g-i-r-l，首字母是 g，大写写作 G。"},
{i:25016,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"按字母表顺序，字母 Gg 后面紧挨着的是？",o:["Hh","Kk","Jj","Mm"],a:0,k:"字母顺序：Gg Hh",e:"解析：字母表顺序是 Gg、Hh、Ii、Jj、Kk、Ll、Mm、Nn，Gg 后面紧挨着 Hh。"},
{i:25017,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"按字母表顺序，字母 Kk 后面紧挨着的是？",o:["Mm","Nn","Ll","Ii"],a:2,k:"字母顺序：Kk Ll",e:"解析：这一段的顺序是 Ii、Jj、Kk、Ll、Mm、Nn，Kk 后面紧挨着 Ll。"},
{i:25018,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:1,q:"单词“kite”（风筝）以字母 ____ 开头。",o:[],a:"K",k:"字母：Kk",e:"解析：kite 拼写为 k-i-t-e，首字母是 k，大写写作 K。"},
{i:25019,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:1,q:"按字母表顺序填空：Gg, Hh, Ii, Jj, Kk, Ll, Mm, ____。",o:[],a:"Nn",k:"字母顺序：Mm Nn",e:"解析：Mm 后面是 Nn，Nn 是这一组字母 Gg–Nn 的最后一个。"},
{i:25020,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“red”的意思是？",o:["蓝色","红色","绿色","黄色"],a:1,k:"颜色：red",e:"解析：red 是“红色”，如 a red apple（一个红苹果）、a red flower（一朵红花）。"},
{i:25021,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“yellow”的意思是？",o:["白色","黄色","橙色","紫色"],a:1,k:"颜色：yellow",e:"解析：yellow 是“黄色”，香蕉、小鸭子常用 yellow 来形容。"},
{i:25022,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“blue”的意思是？",o:["绿色","黑色","蓝色","棕色"],a:2,k:"颜色：blue",e:"解析：blue 是“蓝色”，天空和大海常用 blue 形容，如 blue sky（蓝天）。"},
{i:25023,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“green”的意思是？",o:["灰色","绿色","粉色","金色"],a:1,k:"颜色：green",e:"解析：green 是“绿色”，小草和树叶是绿色的，如 green grass。"},
{i:25024,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“star”的意思是？",o:["心形","星形","圆形","方形"],a:1,k:"形状：star",e:"解析：star 是“星形、星星”；circle 是圆形，square 是方形，heart 是心形。"},
{i:25025,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“heart”的意思是？",o:["心形","菱形","星形","长方形"],a:0,k:"形状：heart",e:"解析：heart 是“心形”，也可以表示“心脏”，两个意思写法相同。"},
{i:25026,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"—What colour is the banana? —It's ____.",o:["red","blue","yellow","black"],a:2,k:"颜色问答：What colour",e:"解析：What colour 用来问“什么颜色”，香蕉是黄色的，所以回答 It's yellow."},
{i:25027,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“rectangle”的意思是？",o:["长方形","三角形","圆形","正方形"],a:0,k:"形状：rectangle",e:"解析：rectangle 是“长方形”；square 是“正方形”，triangle 是“三角形”，circle 是“圆形”。"},
{i:25028,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:1,q:"“绿色”用英语说是 ____。",o:[],a:"green",k:"颜色：green",e:"解析：绿色的英文是 green，拼写为 g-r-e-en，注意中间是 ee 发长音。"},
{i:25029,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:1,q:"“蓝色”用英语说是 ____。",o:[],a:"blue",k:"颜色：blue",e:"解析：蓝色的英文是 blue，拼写为 b-l-u-e，注意不要写成 blua。"},
{i:25030,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“one”的意思是？",o:["二","一","四","五"],a:1,k:"数字：one",e:"解析：one 是“一”，one 到 ten 依次表示一到十，two 才是“二”。"},
{i:25031,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“two”的意思是？",o:["二","三","六","七"],a:0,k:"数字：two",e:"解析：two 是“二”，如 two books（两本书），two 后面的名词要用复数。"},
{i:25032,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“three”的意思是？",o:["三","四","八","九"],a:0,k:"数字：three",e:"解析：three 是“三”，拼写是 t-h-r-ee，开头的 th 要咬舌发音。"},
{i:25033,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“four”的意思是？",o:["五","四","九","十"],a:1,k:"数字：four",e:"解析：four 是“四”，five 是“五”，两个词都以 f 开头，要注意区分。"},
{i:25034,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“five”的意思是？",o:["四","五","六","二"],a:1,k:"数字：five",e:"解析：five 是“五”，five pens 就是“五支钢笔”，名词要用复数。"},
{i:25035,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"—How many apples do you see? —I see ____.（三个）",o:["two","three","five","ten"],a:1,k:"数量问答：How many",e:"解析：How many 用来问“多少”，后面接复数名词；三个就是 three。"},
{i:25036,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"Two and three is ____.",o:["four","five","six","seven"],a:1,k:"数字：two and three",e:"解析：2 加 3 等于 5，所以填 five；and 在数字里表示“加”。"},
{i:25037,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"I have ____ books.（四本）",o:["three","five","four","six"],a:2,k:"数字：four books",e:"解析：“四”是 four，四本书要说 four books，数字大于 1 时名词要用复数形式。"},
{i:25038,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:1,q:"“三”用英语说是 ____。",o:[],a:"three",k:"数字：three",e:"解析：数字 3 的英文是 three，注意不要和 tree（树）弄混，tree 是 t-r-ee。"},
{i:25039,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:1,q:"“五”用英语说是 ____。",o:[],a:"five",k:"数字：five",e:"解析：数字 5 的英文是 five，five 后面接名词时用复数，如 five pens。"},
{i:25040,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“rabbit”的意思是？",o:["鸭子","兔子","鱼","鸟"],a:1,k:"动物：rabbit",e:"解析：rabbit 是“兔子”，兔子爱吃胡萝卜 carrot，跑得也很快。"},
{i:25041,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“dog”的意思是？",o:["猫","狗","猪","鸟"],a:1,k:"动物：dog",e:"解析：dog 是“狗”，cat 是“猫”，dog 和 cat 都是常见的宠物。"},
{i:25042,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“bird”的意思是？",o:["鱼","鸟","蜜蜂","马"],a:1,k:"动物：bird",e:"解析：bird 是“鸟”，鸟会飞，可以说 Birds can fly.，复数直接在词尾加 s。"},
{i:25043,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“fish”的意思是？",o:["鸭子","鱼","蛇","羊"],a:1,k:"动物：fish",e:"解析：fish 是“鱼”，一条鱼是 a fish，两条鱼还是 two fish，fish 单复数同形。"},
{i:25044,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“duck”的意思是？",o:["鸭子","鹅","鸡","猪"],a:0,k:"动物：duck",e:"解析：duck 是“鸭子”，鸭子会游泳，可以说 Ducks can swim.，复数是 ducks。"},
{i:25045,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“pig”的意思是？",o:["牛","猪","羊","马"],a:1,k:"动物：pig",e:"解析：pig 是“猪”；cow 是“奶牛”，sheep 是“绵羊”，horse 是“马”。"},
{i:25046,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"—What's this? —It's a ____.（猫）",o:["cat","dog","bird","fish"],a:0,k:"动物：cat",e:"解析：What's this? 用来问“这是什么”，回答用 It's a...；“猫”是 cat。"},
{i:25047,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"I like ____ very much.（猴子）",o:["ducks","monkeys","pigs","fish"],a:1,k:"动物：monkey",e:"解析：“猴子”是 monkey，表示喜欢某一类动物时常用复数 monkeys，monkey 变复数直接加 s。"},
{i:25048,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:1,q:"“狗”用英语说是 ____。",o:[],a:"dog",k:"动物：dog",e:"解析：狗的英文是 dog，拼写为 d-o-g，小狗可以说 a little dog。"},
{i:25049,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:1,q:"“鸟”用英语说是 ____。",o:[],a:"bird",k:"动物：bird",e:"解析：鸟的英文是 bird，拼写为 b-i-r-d，复数形式是 birds。"},
{i:25050,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“dad”的意思是？",o:["爸爸","妈妈","爷爷","哥哥"],a:0,k:"家庭成员：dad",e:"解析：dad 是口语里的“爸爸”，书面常用 father，两个词意思一样。"},
{i:25051,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“mum”的意思是？",o:["奶奶","妈妈","姐姐","姑姑"],a:1,k:"家庭成员：mum",e:"解析：mum 是口语里的“妈妈”，mother 更正式；grandma 才是“奶奶”。"},
{i:25052,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“family”的意思是？",o:["学校","家庭","朋友","班级"],a:1,k:"家庭：family",e:"解析：family 是“家庭、家人”，This is my family. 意思是“这是我的家人”。"},
{i:25053,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"—Who's he? —He's my ____.（爸爸）",o:["mother","sister","father","grandma"],a:2,k:"家庭成员：father",e:"解析：he 指男性，所以要用表示男性的词，“爸爸”是 father 或 dad，mother 是妈妈。"},
{i:25054,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"—Who's she? —She's my ____.（妹妹）",o:["brother","sister","father","grandpa"],a:1,k:"家庭成员：sister",e:"解析：she 指女性，“姐妹”用 sister，“兄弟”用 brother，不要弄混。"},
{i:25055,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“grandfather”的意思是？",o:["爷爷/外公","奶奶/外婆","爸爸","叔叔"],a:0,k:"家庭成员：grandfather",e:"解析：grandfather 是“爷爷、外公”，口语常说 grandpa；grandmother 才是“奶奶、外婆”。"},
{i:25056,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“This is my family.”的意思是？",o:["这是我的学校。","这是我的家人。","这是我的朋友。","这是我的书。"],a:1,k:"句型：This is...",e:"解析：This is... 用来介绍“这是……”，family 是“家人、家庭”，合起来就是“这是我的家人”。"},
{i:25057,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"I love my ____.（我的家人）",o:["family","school","bag","teacher"],a:0,k:"家庭：family",e:"解析：“我爱我的家人”说 I love my family.，love 是“爱、喜爱”，后面直接跟名词。"},
{i:25058,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:1,q:"“爸爸”口语用英语说是 ____。",o:[],a:"dad",k:"家庭成员：dad",e:"解析：口语里的“爸爸”是 dad，拼写为 d-a-d，书面语里常用 father。"},
{i:25059,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:1,q:"“奶奶”用英语说是 ____。",o:[],a:"grandma",k:"家庭成员：grandma",e:"解析：“奶奶、外婆”口语说 grandma，也可以说 grandmother，grand 表示“隔一代的”。"},
{i:25060,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“bread”的意思是？",o:["蛋糕","面包","米饭","面条"],a:1,k:"食物：bread",e:"解析：bread 是“面包”，是不可数名词，一般不说 a bread，可以说 some bread。"},
{i:25061,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“milk”的意思是？",o:["牛奶","果汁","茶","咖啡"],a:0,k:"饮料：milk",e:"解析：milk 是“牛奶”；juice 是“果汁”，tea 是“茶”，coffee 是“咖啡”。"},
{i:25062,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“water”的意思是？",o:["汤","水","酒","饮料"],a:1,k:"饮料：water",e:"解析：water 是“水”，喝一杯水可以说 a glass of water，water 也是不可数名词。"},
{i:25063,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“egg”的意思是？",o:["肉","鸡蛋","鱼","汤"],a:1,k:"食物：egg",e:"解析：egg 是“鸡蛋”，一个鸡蛋要说 an egg，因为 egg 以元音音素开头。"},
{i:25064,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“soup”的意思是？",o:["沙拉","汤","米饭","面条"],a:1,k:"食物：soup",e:"解析：soup 是“汤”，喝汤常说 have soup 或 eat soup，不用 drink soup。"},
{i:25065,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"I'd like some ____.（我想要一些牛奶）",o:["rice","milk","noodles","bread"],a:1,k:"点餐：I'd like...",e:"解析：I'd like... 是礼貌地说“我想要……”，后面直接跟食物名词，“牛奶”是 milk。"},
{i:25066,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"—Have some cake, please. —____.",o:["Thank you.","Good night.","Goodbye.","Sorry."],a:0,k:"交际：Thank you",e:"解析：别人请你吃东西时，要礼貌地说 Thank you.（谢谢），不能回答道别或道歉的话。"},
{i:25067,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“I like rice.”的意思是？",o:["我不喜欢米饭。","我喜欢米饭。","我要面条。","这是我的米饭。"],a:1,k:"句型：I like...",e:"解析：I like... 表示“我喜欢……”，rice 是“米饭”；表示不喜欢要说 I don't like..."},
{i:25068,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:1,q:"“水”用英语说是 ____。",o:[],a:"water",k:"饮料：water",e:"解析：水的英文是 water，拼写为 w-a-t-er，drink water 就是“喝水”。"},
{i:25069,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:1,q:"“牛奶”用英语说是 ____。",o:[],a:"milk",k:"饮料：milk",e:"解析：牛奶的英文是 milk，拼写为 m-i-l-k，a cup of milk 是“一杯牛奶”。"},
{i:25070,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“pencil box”的意思是？",o:["铅笔盒","书包","课本","橡皮"],a:0,k:"文具：pencil box",e:"解析：pencil box 是“铅笔盒”，由 pencil（铅笔）和 box（盒子）组成，用来装文具。"},
{i:25071,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“schoolbag”的意思是？",o:["书桌","书包","铅笔","卷笔刀"],a:1,k:"文具：schoolbag",e:"解析：schoolbag 是“书包”，由 school（学校）和 bag（包）两个词合成。"},
{i:25072,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“glue”的意思是？",o:["胶水","剪刀","订书机","墨水"],a:0,k:"文具：glue",e:"解析：glue 是“胶水”，用来把纸粘在一起；剪刀是 scissors。"},
{i:25073,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“desk”的意思是？",o:["椅子","课桌","黑板","窗户"],a:1,k:"文具：desk",e:"解析：desk 是“课桌、书桌”，chair 是“椅子”，两个词常一起出现。"},
{i:25074,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“chair”的意思是？",o:["椅子","门","书柜","尺子"],a:0,k:"文具：chair",e:"解析：chair 是“椅子”，sit on the chair 意思是“坐在椅子上”，与 desk（课桌）搭配使用。"},
{i:25075,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“Open your book.”的意思是？",o:["合上你的书。","打开你的书。","举起你的书。","给我你的书。"],a:1,k:"课堂用语：Open your book",e:"解析：open 是“打开”，Open your book. 是课堂上常用的指令，反义是 Close your book."},
{i:25076,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"I have a new ____.（新书包）",o:["schoolbag","ruler","eraser","crayon"],a:0,k:"文具：schoolbag",e:"解析：“书包”是 schoolbag，I have a new schoolbag. 意思是“我有一个新书包”。"},
{i:25077,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"Show me your ____.（铅笔）",o:["pencil","bag","book","pen"],a:0,k:"文具：pencil",e:"解析：Show me... 是“给我看……”，“铅笔”是 pencil；pen 是“钢笔”，两者不同。"},
{i:25078,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:1,q:"“书”用英语说是 ____。",o:[],a:"book",k:"文具：book",e:"解析：书的英文是 book，拼写为 b-oo-k，读书可以说 read a book。"},
{i:25079,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:1,q:"“书包”用英语说是 ____。",o:[],a:"schoolbag",k:"文具：schoolbag",e:"解析：书包的英文是 schoolbag，由 school（学校）和 bag（包）两部分组成。"},
{i:25080,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“car”的意思是？",o:["火车","小汽车","飞机","轮船"],a:1,k:"玩具：car",e:"解析：car 是“小汽车”，玩具小汽车可以说 a toy car；train 才是“火车”。"},
{i:25081,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“plane”的意思是？",o:["飞机","风筝","气球","积木"],a:0,k:"玩具：plane",e:"解析：plane 是“飞机”；kite 是“风筝”，balloon 是“气球”，block 是“积木”。"},
{i:25082,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“boat”的意思是？",o:["汽车","小船","娃娃","拼图"],a:1,k:"玩具：boat",e:"解析：boat 是“小船”，ship 指更大的“轮船”；doll 是“娃娃”，puzzle 是“拼图”。"},
{i:25083,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“balloon”的意思是？",o:["皮球","气球","风筝","陀螺"],a:1,k:"玩具：balloon",e:"解析：balloon 是“气球”，ball 是“球”，两个词都以 ball 开头，balloon 后面多出 oon。"},
{i:25084,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“yo-yo”的意思是？",o:["积木","溜溜球","陀螺","洋娃娃"],a:1,k:"玩具：yo-yo",e:"解析：yo-yo 是“溜溜球”，拼写中间有连字符；block 是“积木”，doll 是“洋娃娃”。"},
{i:25085,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"This is my ____.（风筝）",o:["kite","ball","doll","robot"],a:0,k:"玩具：kite",e:"解析：This is my kite. 意思是“这是我的风筝”，“风筝”是 kite，ball 是“球”。"},
{i:25086,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"I have a ____.（我有一个球）",o:["plane","ball","boat","puzzle"],a:1,k:"玩具：ball",e:"解析：“球”是 ball，I have a ball. 意思是“我有一个球”，a 用在辅音开头的词前。"},
{i:25087,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"Look at my new toy ____.（玩具汽车）",o:["car","train","robot","block"],a:0,k:"玩具：car",e:"解析：Look at... 是“看……”，“玩具汽车”是 toy car；train 是“火车”，robot 是“机器人”。"},
{i:25088,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:1,q:"“球”用英语说是 ____。",o:[],a:"ball",k:"玩具：ball",e:"解析：球的英文是 ball，拼写为 b-a-ll，踢足球是 play football。"},
{i:25089,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:1,q:"“飞机”用英语说是 ____。",o:[],a:"plane",k:"玩具：plane",e:"解析：飞机的英文是 plane，拼写为 p-l-a-n-e，也可以说 aeroplane。"},
{i:25090,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“swim”的意思是？",o:["跑步","游泳","跳跃","飞行"],a:1,k:"动作：swim",e:"解析：swim 是“游泳”，I can swim. 意思是“我会游泳”；run 是“跑”，jump 是“跳”。"},
{i:25091,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“fly”的意思是？",o:["飞","走","爬","跳"],a:0,k:"动作：fly",e:"解析：fly 是“飞”，Birds can fly. 意思是“鸟儿会飞”；walk 是“走”，jump 是“跳”。"},
{i:25092,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“drink”的意思是？",o:["吃","喝","跑","睡"],a:1,k:"动作：drink",e:"解析：drink 是“喝”，eat 是“吃”，drink milk 是“喝牛奶”，两个词不要弄混。"},
{i:25093,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“sleep”的意思是？",o:["唱歌","睡觉","跳舞","画画"],a:1,k:"动作：sleep",e:"解析：sleep 是“睡觉”，go to sleep 表示“去睡觉”；sing 是“唱歌”，dance 是“跳舞”。"},
{i:25094,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“play”的意思是？",o:["读","玩","写","工作"],a:1,k:"动作：play",e:"解析：play 是“玩、踢（球）”，play football 是“踢足球”；read 是“读”，write 是“写”。"},
{i:25095,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"I can ____.（我会游泳）",o:["swim","sing","read","draw"],a:0,k:"句型：I can...",e:"解析：can 是情态动词，后面跟动词原形，表示“会、能”，游泳是 swim。"},
{i:25096,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"Let's ____ together.（让我们一起唱歌）",o:["sing","run","jump","walk"],a:0,k:"句型：Let's...",e:"解析：Let's... 是“让我们……吧”，后面跟动词原形，“唱歌”是 sing，together 是“一起”。"},
{i:25097,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“I can read and write.”的意思是？",o:["我会跑和跳。","我会读和写。","我会唱歌。","我会画画。"],a:1,k:"动作：read and write",e:"解析：read 是“读”，write 是“写”，and 连接两个动作，表示“和”。"},
{i:25098,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:1,q:"“游泳”用英语说是 ____。",o:[],a:"swim",k:"动作：swim",e:"解析：游泳的英文是 swim，拼写为 s-w-i-m，去游泳可以说 go swimming。"},
{i:25099,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:1,q:"“吃”用英语说是 ____。",o:[],a:"eat",k:"动作：eat",e:"解析：吃的英文是 eat，拼写为 e-a-t，eat an apple 是“吃一个苹果”。"}
);
