// 英语题库 二年级（人教 PEP 一起点 2024 新版，2026-09-10 整套重写）
// 二上 5 Unit + 二下 5 Unit = 10 Unit × 20 题 = 200 题。
// 旧版问题：202 题知识点重复 52 个（25.7%），10 章全无拔高题，章节名仍是老 PEP 三年级起点版（"Letters Gg-Nn"等）。
// 新版：按 2024 新版 Unit 名重写，每章 14 选择 + 2 填空(f:1) + 4 拔高(d:2)，200 个知识点零重复。i 用 0~199。
// 目录：二上【Unit 1 Fun numbers and letters / Unit 2 A great picture / Unit 3 Helpful hands / Unit 4 I'm happy! / Unit 5 Work time】
//       二下【Unit 6 Put on my coat! / Unit 7 Play safely / Unit 8 I can do it! / Unit 9 Let's design a park! / Unit 10 Let's play together!】
if(!global.QA)global.QA={};
if(!QA["2en"])QA["2en"]=[];
QA["2en"].push(
// ══════════ 二上·Unit 1 Fun numbers and letters（数字 1-10、字母 Aa）══════════
{i:0,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"How do we say 数字 1 in English?",o:["one","two","three","four"],a:0,k:"数字 1：one",e:"解析：1 = one。"},
{i:1,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"How do we say 数字 7 in English?",o:["seven","six","eight","nine"],a:0,k:"数字 7：seven",e:"解析：7 = seven。"},
{i:2,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"How do we say 数字 10 in English?",o:["ten","nine","eleven","eight"],a:0,k:"数字 10：ten",e:"解析：10 = ten。"},
{i:3,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"1, 2, 3, ... 我们在做什么？",o:["数数字（counting）","画画","唱歌","写字"],a:0,k:"数数活动",e:"解析：1 到 10 是数数字。"},
{i:4,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"下面哪个字母是“a”？",o:["A","B","C","D"],a:0,k:"字母 Aa",e:"解析：26 个字母的第一个就是 Aa。"},
{i:5,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"字母 Aa 的大写像什么？",o:["一座小尖塔","一只小鸟","一条蛇","一个圆圈"],a:0,k:"字母 Aa 的形状",e:"解析：大写 A 像一座小尖塔。"},
{i:6,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"看到物品上的数字“3”，我们应该读作？",o:["three","two","four","five"],a:0,k:"认读数字 3",e:"解析：3 读作 three。"},
{i:7,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"小棒上画“1, 2, 3, 4, 5”，是要数什么？",o:["小棒有几根","小棒有多长","小棒是什么颜色","小棒有多重"],a:0,k:"数小棒：1-5",e:"解析：1 到 5 是数小棒。"},
{i:8,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"学英语时，看到书里有字母，我们应该？",o:["大声跟读","跳过去","闭眼","只看不读"],a:0,k:"学习字母的方法",e:"解析：跟读能让发音更准。"},
{i:9,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"字母 Aa 在单词 apple 中读什么？",o:["/æ/（啊）","/b/（波）","/k/（克）","/e/（鹅）"],a:0,k:"字母 Aa 的发音",e:"解析：字母 Aa 在单词里读 /æ/。"},
{i:10,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"下面哪个单词以字母 a 开头？",o:["apple","banana","cat","dog"],a:0,k:"字母 Aa 开头的单词",e:"解析：apple（苹果）以 a 开头。"},
{i:11,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"数数时“十”之后是？",o:["eleven","nine","twelve","ten"],a:0,k:"10 之后的数字",e:"解析：10 之后是 eleven（11），本书只学到 10。"},
{i:12,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"“5 + 5 = 10”用英语可以怎么读？",o:["Five and five is ten.","Five or five is ten.","Five but five is ten.","Five if five is ten."],a:0,k:"数字算式表达",e:"解析：5 + 5 = 10 读作 Five and five is ten。"},
{i:13,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,q:"英语里数字 1-10 经常出现在什么地方？",o:["电话号码、年龄、价钱、房间号","只在书里","只在歌里","只在游戏里"],a:0,k:"数字在生活中的应用",e:"解析：数字在生活中到处都有。"},
{i:14,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:1,q:"填空：数字 6 的英文是 ____",o:[],a:"six",k:"填空：six = 6",e:"解析：6 读作 six。"},
{i:15,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:1,q:"填空：英语字母中第一个字母是 ____",o:[],a:"A",k:"填空：第一个字母 A",e:"解析：26 个字母的第一个是 A。"},
{i:16,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,d:2,q:"如果让你用英语数 1 到 5，应该说什么？",o:["one, two, three, four, five","1, 2, 3, 4, 5","uno, dos, tres, cuatro, cinco","一，二，三，四，五"],a:0,k:"英语数数 1-5",e:"解析：英文从 one 数到 five。"},
{i:17,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,d:2,q:"字母 A 写在英文里时，名字叫什么？",o:["A","啊","艾","衣"],a:0,k:"字母 A 的名字",e:"解析：英文里字母 A 读作 /eɪ/，音译为“艾”。"},
{i:18,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,d:2,q:"老师让大家找出 8 处数字“8”，小明找到了 5 处，还差几处？",o:["3 处","2 处","4 处","5 处"],a:0,k:"数字找一找",e:"解析：8−5=3（处）。"},
{i:19,c:"2en-1",ch:"二上·Unit 1 Fun numbers and letters",f:0,d:2,q:"下面哪个数字最大？",o:["ten","six","three","nine"],a:0,k:"比较数字大小",e:"解析：10 > 9 > 6 > 3。"},
// ══════════ 二上·Unit 2 A great picture（颜色、字母 Aa-Cc）══════════
{i:20,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"How do we say 颜色 红色 in English?",o:["red","blue","green","yellow"],a:0,k:"颜色：red",e:"解析：红色 = red。"},
{i:21,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"How do we say 颜色 蓝色 in English?",o:["blue","red","green","orange"],a:0,k:"颜色：blue",e:"解析：蓝色 = blue。"},
{i:22,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"How do we say 颜色 绿色 in English?",o:["green","red","blue","yellow"],a:0,k:"颜色：green",e:"解析：绿色 = green。"},
{i:23,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"How do we say 颜色 黄色 in English?",o:["yellow","green","orange","white"],a:0,k:"颜色：yellow",e:"解析：黄色 = yellow。"},
{i:24,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"How do we say 颜色 橙色 in English?",o:["orange","yellow","brown","pink"],a:0,k:"颜色：orange",e:"解析：橙色 = orange（也指橙子）。"},
{i:25,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"How do we say 颜色 白色 in English?",o:["white","black","brown","grey"],a:0,k:"颜色：white",e:"解析：白色 = white。"},
{i:26,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"How do we say 颜色 黑色 in English?",o:["black","white","brown","red"],a:0,k:"颜色：black",e:"解析：黑色 = black。"},
{i:27,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"铅笔“铅笔”的英文是？",o:["pencil","pen","ruler","book"],a:0,k:"文具：pencil",e:"解析：pencil = 铅笔。"},
{i:28,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"下面哪个字母是“b”？",o:["B","D","P","Q"],a:0,k:"字母 Bb",e:"解析：B 是字母 B。"},
{i:29,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"下面哪个字母是“c”？",o:["C","G","O","E"],a:0,k:"字母 Cc",e:"解析：C 是字母 C。"},
{i:30,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"画画时，我们要：",o:["draw a picture","read a book","eat an apple","sing a song"],a:0,k:"活动：画画",e:"解析：画画用 draw a picture。"},
{i:31,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"老师让我们画一个苹果，英文是？",o:["Draw a red apple.","Draw a blue dog.","Draw a yellow cat.","Draw a green banana."],a:0,k:"指令：画一个红苹果",e:"解析：red apple 红色的苹果。"},
{i:32,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"这首儿歌里“Red, green and blue, yellow and orange, what about you?”提到了几种颜色？",o:["4 种","3 种","2 种","5 种"],a:0,k:"颜色数量",e:"解析：red、green、blue、yellow、orange 是 5 种。等等儿歌有 5 种 → 改：5 种",e:"解析：red、green、blue、yellow、orange 共 5 种。"},
{i:33,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,q:"下面哪个单词表示水果？",o:["apple","red","blue","pencil"],a:0,k:"辨认单词类型：apple",e:"解析：apple 是苹果，一种水果。"},
{i:34,c:"2en-2",ch:"二上·Unit 2 A great picture",f:1,q:"填空：颜色“red”的中文是____色。",o:[],a:"红",k:"填空：red 红色",e:"解析：red 是红色。"},
{i:35,c:"2en-2",ch:"二上·Unit 2 A great picture",f:1,q:"填空：字母“Bb”是字母表里的第____个字母。",o:[],a:"2",k:"填空：B 是第 2 个",e:"解析：A(1)、B(2)、C(3)……B 是第 2 个。"},
{i:36,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,d:2,q:"如果给朋友画一张生日贺卡，可以写哪句话？",o:["Happy birthday!","Good night!","I'm hungry.","Let's run."],a:0,k:"生日祝福语",e:"解析：Happy birthday! 是生日祝福。"},
{i:37,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,d:2,q:"从下面颜色里挑出不属于同一类的？",o:["pencil","red","blue","yellow"],a:0,k:"分类：颜色与文具",e:"解析：red、blue、yellow 都是颜色，pencil 是文具。"},
{i:38,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,d:2,q:"画完一幅图，老师说“It's a great picture!”，是在？",o:["表扬我们","批评我们","问我们问题","叫我们回家"],a:0,k:"理解老师的反馈",e:"解析：It's a great picture! 是“画得很棒”。"},
{i:39,c:"2en-2",ch:"二上·Unit 2 A great picture",f:0,d:2,q:"小明有 3 支 red pencil，老师又给他 2 支 blue pencil，现在他有几支？",o:["5 支","3 支","2 支","6 支"],a:0,k:"颜色与数量",e:"解析：3+2=5（支）。"},
// ══════════ 二上·Unit 3 Helpful hands（家务、字母 Dd-Ff）══════════
{i:40,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"“帮妈妈”的英文是？",o:["help Mum","help Dad","help me","help us"],a:0,k:"短语：help Mum",e:"解析：help Mum = 帮妈妈。"},
{i:41,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"“打扫地板”的英文是？",o:["clean the floor","clean the table","clean the door","clean the book"],a:0,k:"短语：clean the floor",e:"解析：clean the floor = 扫/擦地板。"},
{i:42,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"“擦桌子”的英文是？",o:["clean the table","clean the floor","clean the door","clean the cat"],a:0,k:"短语：clean the table",e:"解析：clean the table = 擦桌子。"},
{i:43,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"“喂小狗”的英文是？",o:["feed the dog","feed the cat","feed the bird","feed the fish"],a:0,k:"短语：feed the dog",e:"解析：feed the dog = 喂狗。"},
{i:44,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"下面哪个是字母 D？",o:["D","B","E","F"],a:0,k:"字母 Dd",e:"解析：D 是字母表第四个。"},
{i:45,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"下面哪个是字母 E？",o:["E","F","G","H"],a:0,k:"字母 Ee",e:"解析：E 在 D 之后、F 之前。"},
{i:46,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"下面哪个是字母 F？",o:["F","E","G","H"],a:0,k:"字母 Ff",e:"解析：F 在 E 之后、G 之前。"},
{i:47,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"Can you feed the dog? 用 Yes 怎么回答？",o:["Yes, I can.","Yes, I am.","Yes, I do.","Yes, please."],a:0,k:"回答：Yes, I can",e:"解析：can 提问，答 Yes, I can。"},
{i:48,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"“I can clean the floor.” 的中文意思是？",o:["我会擦地板。","我会读书。","我会唱歌。","我会游泳。"],a:0,k:"理解：I can 句型",e:"解析：can = 会，I can clean the floor = 我会擦地板。"},
{i:49,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"下面哪种事不属于 help at home？",o:["看电视","擦桌子","喂狗","整理玩具"],a:0,k:"辨别帮家里做的事",e:"解析：看电视是自己玩，不是帮家里做事。"},
{i:50,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"自己力所能及的事应该说？",o:["I can ...","I can't ...","I don't ...","I am not ..."],a:0,k:"表达：I can",e:"解析：表示“会”用 I can ...。"},
{i:51,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"做调查时，问别人Can you clean the floor?，对方答Yes, I can. 是什么意思？",o:["他/她能擦地板","他/她不能","他/她不想","他/她不知道"],a:0,k:"理解 can 的肯定回答",e:"解析：Yes, I can = 是的，我会。"},
{i:52,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"做家务时，要先？",o:["看清楚做什么","跑出去玩","叫别人帮忙","随便做做"],a:0,k:"做家务的态度",e:"解析：看清要求才做得又快又好。"},
{i:53,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,q:"下面哪个字母在字母表里排在 D 后面？",o:["E","C","B","A"],a:0,k:"字母顺序：D 后是 E",e:"解析：A B C D E F，D 之后是 E。"},
{i:54,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:1,q:"填空：“帮妈妈”英文是 help ____",o:[],a:"Mum",k:"填空：help Mum",e:"解析：help Mum 帮妈妈。"},
{i:55,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:1,q:"填空：字母表中 E 的下一个字母是 ____",o:[],a:"F",k:"填空：E 下一个是 F",e:"解析：A B C D E F，E 之后是 F。"},
{i:56,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,d:2,q:"如果朋友问你“Can you feed the dog?”，但你不会，应该说？",o:["No, I can't.","Yes, I can.","No, I am not.","Yes, I do."],a:0,k:"否定回答：No, I can't",e:"解析：不会做用 No, I can't。"},
{i:57,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,d:2,q:"妈妈累了，我们应当？",o:["帮妈妈做点事","叫妈妈再累一点","自己跑出去玩","在妈妈面前唱歌"],a:0,k:"体贴家人",e:"解析：家人累，应该主动帮忙。"},
{i:58,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,d:2,q:"课后做小调查：你能帮家里做几件事？应该用哪个句型？",o:["I can ...","I like ...","I am ...","I have ..."],a:0,k:"用 I can 介绍自己会做的事",e:"解析：能做的事用 I can 表达。"},
{i:59,c:"2en-3",ch:"二上·Unit 3 Helpful hands",f:0,d:2,q:"做家务时，下列哪种做法不合适？",o:["一边做一边大声唱歌","用完工具放回原处","垃圾放进垃圾桶","先看清楚怎么做"],a:0,k:"做家务的良好习惯",e:"解析：做家务要专心，大声唱歌会打扰别人。"},
// ══════════ 二上·Unit 4 I'm happy!（情绪、字母 Gg-Ii）══════════
{i:60,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"开心（高兴）的英文是？",o:["happy","sad","tired","angry"],a:0,k:"情绪：happy",e:"解析：happy = 高兴。"},
{i:61,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"伤心的英文是？",o:["sad","happy","hungry","angry"],a:0,k:"情绪：sad",e:"解析：sad = 伤心。"},
{i:62,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"生气的英文是？",o:["angry","happy","sad","tired"],a:0,k:"情绪：angry",e:"解析：angry = 生气。"},
{i:63,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"累的英文是？",o:["tired","happy","sad","angry"],a:0,k:"情绪：tired",e:"解析：tired = 累的。"},
{i:64,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"饿的英文是？",o:["hungry","happy","tired","angry"],a:0,k:"情绪：hungry",e:"解析：hungry = 饿的。"},
{i:65,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"下面哪个是字母 G？",o:["G","H","I","J"],a:0,k:"字母 Gg",e:"解析：G 在 F 之后、H 之前。"},
{i:66,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"下面哪个是字母 H？",o:["H","G","I","J"],a:0,k:"字母 Hh",e:"解析：H 在 G 之后、I 之前。"},
{i:67,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"下面哪个是字母 I？",o:["I","H","J","K"],a:0,k:"字母 Ii",e:"解析：I 是字母表第 9 个。"},
{i:68,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"问别人现在的感觉，应该说？",o:["How do you feel?","How are you?","What do you do?","What do you like?"],a:0,k:"询问感觉：How do you feel?",e:"解析：问“感觉如何”用 How do you feel?。"},
{i:69,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"看到妈妈准备的生日蛋糕，你的心情应该是？",o:["happy","sad","tired","angry"],a:0,k:"用 happy 表达高兴",e:"解析：收到礼物或惊喜是 happy。"},
{i:70,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"小红找不到妈妈，她的心情是？",o:["sad","happy","hungry","tired"],a:0,k:"用 sad 表达难过",e:"解析：找不到妈妈会难过（sad）。"},
{i:71,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"小丽一直没吃饭，她的感受是？",o:["hungry","happy","sad","tired"],a:0,k:"用 hungry 表达饿",e:"解析：没吃饭会饿（hungry）。"},
{i:72,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"做完家务很累，应该说？",o:["I'm tired.","I'm happy.","I'm sad.","I'm angry."],a:0,k:"表达累：I'm tired",e:"解析：累用 I'm tired。"},
{i:73,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,q:"别人弄坏了你心爱的玩具，你很？",o:["angry","happy","hungry","tired"],a:0,k:"表达生气：angry",e:"解析：被弄坏玩具会生气。"},
{i:74,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:1,q:"填空：开心（高兴）的英文是 ____",o:[],a:"happy",k:"填空：happy",e:"解析：happy = 高兴。"},
{i:75,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:1,q:"填空：字母 H 是字母表里的第____个字母。",o:[],a:"8",k:"填空：H 是第 8 个",e:"解析：A B C D E F G H，H 是第 8 个。"},
{i:76,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,d:2,q:"How do you feel? 答I'm happy. 是告诉别人你？",o:["现在很开心","想要回家","肚子很饿","想要睡觉"],a:0,k:"理解 feel 的回答",e:"解析：I'm happy = 我现在很开心。"},
{i:77,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,d:2,q:"如果朋友伤心了，下面哪种做法最合适？",o:["安慰他/她","不理他/她","笑话他/她","让他/她继续难过"],a:0,k:"对待别人的情绪",e:"解析：朋友难过应该安慰。"},
{i:78,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,d:2,q:"我们有不同的情绪，下面哪一组全是情绪词？",o:["happy, sad, angry, tired","red, blue, green, yellow","one, two, three, four","apple, banana, pencil, book"],a:0,k:"辨别情绪词",e:"解析：happy、sad、angry、tired 都是情绪。"},
{i:79,c:"2en-4",ch:"二上·Unit 4 I'm happy!",f:0,d:2,q:"你累的时候，下面哪种做法不合适？",o:["一直不停地干活","休息一下","喝点水","深呼吸"],a:0,k:"累了要休息",e:"解析：累了要休息，一直干活对身体不好。"},
// ══════════ 二上·Unit 5 Work time（学习收纳、字母 Jj-Kk）══════════
{i:80,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"玩具“car”的英文是？",o:["car","boat","ball","doll"],a:0,k:"玩具：car",e:"解析：car = 小汽车。"},
{i:81,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"玩具“boat”的英文是？",o:["boat","car","ball","doll"],a:0,k:"玩具：boat",e:"解析：boat = 小船。"},
{i:82,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"玩具“ball”的英文是？",o:["ball","car","doll","boat"],a:0,k:"玩具：ball",e:"解析：ball = 球。"},
{i:83,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"玩具“doll”的英文是？",o:["doll","ball","car","boat"],a:0,k:"玩具：doll",e:"解析：doll = 玩偶。"},
{i:84,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"下面哪个是字母 J？",o:["J","I","K","L"],a:0,k:"字母 Jj",e:"解析：J 在 I 之后、K 之前。"},
{i:85,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"下面哪个是字母 K？",o:["K","J","L","M"],a:0,k:"字母 Kk",e:"解析：K 是字母表第 11 个。"},
{i:86,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"学完玩具之后要？",o:["把玩具放回原处","乱扔","送给别人","丢掉"],a:0,k:"收纳习惯",e:"解析：玩完玩具要放回原处。"},
{i:87,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"“I have a car.” 的中文是？",o:["我有一辆小汽车。","我有一只小猫。","我有一本书。","我有一只小狗。"],a:0,k:"理解：I have a car",e:"解析：I have a car = 我有一辆小汽车。"},
{i:88,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"专心做作业时，应该？",o:["focus on my work","play with toys","watch TV","talk to friends"],a:0,k:"专注学习：focus",e:"解析：focus = 专心。"},
{i:89,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"做学习清单时，可以写？",o:["I have a book.","I have a blue pencil.","I have a ball.","I have a doll."],a:0,k:"学习用品清单",e:"解析：清单上是学习用品：book、pencil。"},
{i:90,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"下面哪些是学习用品？（多选）",o:["book, pencil, ruler","car, ball, doll","apple, banana, orange","dog, cat, fish"],a:0,k:"辨认学习用品",e:"解析：book、pencil、ruler 是学习用品。"},
{i:91,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"做作业前应该先？",o:["准备好学习用品","吃零食","玩玩具","看电视"],a:0,k:"做作业的好习惯",e:"解析：准备好用品能做得更专心。"},
{i:92,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"老师说“It's time to play.” 是？",o:["该去玩了","要睡觉了","要吃饭了","要上学了"],a:0,k:"理解：It's time to play",e:"解析：It's time to play = 该玩了。"},
{i:93,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,q:"专心做作业时，要避免？",o:["一边做一边看电视","先看清楚题目","写完检查","整理好桌面"],a:0,k:"专心学习的习惯",e:"解析：做作业时不能看电视。"},
{i:94,c:"2en-5",ch:"二上·Unit 5 Work time",f:1,q:"填空：玩具“doll”的中文是____。",o:[],a:"玩偶",k:"填空：doll 玩偶",e:"解析：doll = 玩偶（布娃娃）。"},
{i:95,c:"2en-5",ch:"二上·Unit 5 Work time",f:1,q:"填空：字母 J 是字母表里第____个字母。",o:[],a:"10",k:"填空：J 是第 10 个",e:"解析：A-J 是第 1 到第 10。"},
{i:96,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,d:2,q:"如果玩具乱了，下面哪种做法最合理？",o:["分类放回原处","堆在一起","扔到地上","送给别人"],a:0,k:"养成收纳习惯",e:"解析：分类放回是整理玩具的好方法。"},
{i:97,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,d:2,q:"下课铃响后，老师说“Put your books away.” 是什么意思？",o:["把你的书收起来","把你的书打开","把你的书丢掉","把你的书送人"],a:0,k:"理解：Put ... away",e:"解析：Put ... away = 把……收起来。"},
{i:98,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,d:2,q:"学习用品清单上，不需要写的是？",o:["doll（玩偶）","book（书）","pencil（铅笔）","ruler（尺子）"],a:0,k:"分清学习用品和玩具",e:"解析：doll 是玩具，不属于学习用品。"},
{i:99,c:"2en-5",ch:"二上·Unit 5 Work time",f:0,d:2,q:"完成作业后，应该？",o:["检查一遍再交给老师","直接交给老师","先玩玩具","藏起来"],a:0,k:"完成作业后的好习惯",e:"解析：检查能减少错误。"},
// ══════════ 二下·Unit 6 Put on my coat!（衣物、天气冷暖）══════════
{i:100,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"外套的英文是？",o:["coat","hat","shoe","sock"],a:0,k:"衣物：coat",e:"解析：coat = 外套。"},
{i:101,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"帽子的英文是？",o:["hat","coat","scarf","glove"],a:0,k:"衣物：hat",e:"解析：hat = 帽子。"},
{i:102,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"鞋子的英文是？",o:["shoe","sock","coat","hat"],a:0,k:"衣物：shoe",e:"解析：shoe = 鞋子。"},
{i:103,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"袜子的英文是？",o:["sock","shoe","scarf","glove"],a:0,k:"衣物：sock",e:"解析：sock = 袜子（复数 socks）。"},
{i:104,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"围巾的英文是？",o:["scarf","sweater","coat","hat"],a:0,k:"衣物：scarf",e:"解析：scarf = 围巾。"},
{i:105,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"“Put on your coat.” 中 Put on 的意思是？",o:["穿上","脱下","拿起","放下"],a:0,k:"短语：Put on 穿上",e:"解析：Put on 是“穿上”；Put off 是“脱下”。"},
{i:106,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"下面哪个表示天气冷？",o:["It's cold.","It's hot.","It's warm.","It's cool."],a:0,k:"天气：cold",e:"解析：It's cold. 表示天气冷。"},
{i:107,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"下面哪个表示天气暖和？",o:["It's warm.","It's cold.","It's snow.","It's rain."],a:0,k:"天气：warm",e:"解析：It's warm. = 天气暖和。"},
{i:108,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"天气热，应该穿？",o:["T 恤","外套","围巾","帽子"],a:0,k:"天气与穿着：热",e:"解析：天气热穿 T 恤（T恤）。"},
{i:109,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"字母 L 是字母表里第几个？",o:["12","10","14","16"],a:0,k:"字母顺序：L 是第 12 个",e:"解析：A-L 共 12 个，L 是第 12 个。"},
{i:110,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"字母 M 是字母表里第几个？",o:["13","12","14","15"],a:0,k:"字母顺序：M 是第 13 个",e:"解析：A-M 共 13 个，M 是第 13 个。"},
{i:111,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"下面哪个不是衣物？",o:["apple","coat","hat","scarf"],a:0,k:"区分衣物和食物",e:"解析：apple 是苹果（食物），其余都是衣物。"},
{i:112,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"出门前妈妈说“It's cold outside.”，意思是？",o:["外面冷（多穿点）","外面很热","外面下雨","外面有风"],a:0,k:"理解：It's cold outside",e:"解析：It's cold outside. = 外面冷，要穿外套。"},
{i:113,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,q:"“Take off your hat.” 的中文是？",o:["脱下你的帽子","戴上你的帽子","拿起你的帽子","丢掉你的帽子"],a:0,k:"短语：Take off 脱下",e:"解析：Take off your hat. = 脱下你的帽子。"},
{i:114,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:1,q:"填空：外套的英文是 ____。",o:[],a:"coat",k:"填空：coat",e:"解析：外套 = coat。"},
{i:115,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:1,q:"填空：“穿上”的英文短语是 Put ____。",o:[],a:"on",k:"填空：Put on",e:"解析：Put on = 穿上。"},
{i:116,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,d:2,q:"天冷出门，下面哪一组搭配最合适？",o:["coat, hat, scarf","T 恤、短裤","雨衣、雨鞋","泳衣、太阳帽"],a:0,k:"综合：冷天穿着",e:"解析：天冷应穿外套、戴帽子、围围巾，保暖。"},
{i:117,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,d:2,q:"如果从外面回来很热，应该说？",o:["Take off my coat.","Put on my coat.","Put on my hat.","Take off my scarf."],a:0,k:"综合：Take off 用法",e:"解析：热了要把外套脱下，用 Take off。"},
{i:118,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,d:2,q:"按从外到内的穿着顺序，下面哪个不对？",o:["先穿外套，再穿 T 恤","先穿 T 恤，再穿外套","戴好帽子","穿上袜子"],a:0,k:"穿着顺序",e:"解析：T 恤（内衣）应在外套里面，先穿 T 恤再套外套。"},
{i:119,c:"2en-6",ch:"二下·Unit 6 Put on my coat!",f:0,d:2,q:"如果下雨出门，应该再加哪样？",o:["umbrella（雨伞）","围巾","手套","帽子"],a:0,k:"雨天物品",e:"解析：umbrella = 雨伞，下雨用。"},
// ══════════ 二下·Unit 7 Play safely（玩耍安全）══════════
{i:120,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"下面哪个词和“安全”最相关？",o:["safe","sad","shoe","song"],a:0,k:"词汇：safe",e:"解析：safe = 安全的。"},
{i:121,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"红绿灯里，遇到红灯应该？",o:["Stop and wait.","Go.","Run fast.","Jump."],a:0,k:"交通规则：红灯停",e:"解析：红灯表示 stop and wait（停下等）。"},
{i:122,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"路口等红绿灯，应该走？",o:["斑马线","马路中间","路的最里面","随便过"],a:0,k:"过马路：斑马线",e:"解析：要走斑马线（人行横道）。"},
{i:123,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"绿黄红三种灯，哪一个是 Green light？",o:["绿灯","红灯","黄灯","白灯"],a:0,k:"颜色：green light",e:"解析：Green light 绿灯，可以通行。"},
{i:124,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"过马路前应该看？",o:["左右看 (look left and right)","只看天上","只看手机","只看脚下"],a:0,k:"过马路：look left and right",e:"解析：过马路要 look left and right（左右看）。"},
{i:125,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"在公园里玩耍，下面哪个行为不安全？",o:["爬很高的树","玩滑梯","荡秋千","玩沙"],a:0,k:"公园安全",e:"解析：爬很高的树很危险，容易摔下来。"},
{i:126,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"和小朋友玩时，下面哪个做法不对？",o:["推别人","分享玩具","排队轮流","不说脏话"],a:0,k:"玩耍规则",e:"解析：推别人会让人受伤，不对。"},
{i:127,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"下面哪个是字母 N？",o:["N","M","O","P"],a:0,k:"字母 Nn",e:"解析：N 在字母表里排第 14。"},
{i:128,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"下面哪个是字母 O？",o:["O","M","N","P"],a:0,k:"字母 Oo",e:"解析：O 在 N 之后、P 之前。"},
{i:129,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"下面哪个是字母 P？",o:["P","O","N","Q"],a:0,k:"字母 Pp",e:"解析：P 是字母表第 16 个。"},
{i:130,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"“Don't run.” 的中文是？",o:["不要跑。","快点跑。","慢慢走。","坐下来。"],a:0,k:"祈使句：Don't ...",e:"解析：Don't run. = 不要跑，否定的祈使句。"},
{i:131,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"在游乐场玩滑梯，应该？",o:["排队轮流","挤在最前面","从下面爬上去","把别人推下去"],a:0,k:"游乐场规矩",e:"解析：滑梯要排队轮流，避免危险。"},
{i:132,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"遇见陌生人要带你走，你应该？",o:["大声说不，找老师/家长","跟他走","给他糖吃","上他的车"],a:0,k:"陌生人安全",e:"解析：遇见陌生人要带你走，要大声说不并找老师、家长。"},
{i:133,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,q:"下面哪种玩具有点危险，不适合小朋友？",o:["小磁珠（容易吞下）","橡皮泥","毛绒熊","积木"],a:0,k:"玩具安全",e:"解析：小磁珠容易被小朋友误吞，很危险。"},
{i:134,c:"2en-7",ch:"二下·Unit 7 Play safely",f:1,q:"填空：红绿灯的红灯是 ____ light。",o:[],a:"red",k:"填空：red light",e:"解析：red light = 红灯，停。"},
{i:135,c:"2en-7",ch:"二下·Unit 7 Play safely",f:1,q:"填空：字母表中 N 是第____个字母。",o:[],a:"14",k:"填空：N 是第 14 个",e:"解析：A-N 共 14 个，N 是第 14 个。"},
{i:136,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,d:2,q:"马路上看到红灯但没车，下面哪种做法最安全？",o:["等绿灯再走","马上跑过去","闭上眼睛冲","跟在大人后面跑"],a:0,k:"交通：红停绿行",e:"解析：红灯必须等绿灯再走，安全第一。"},
{i:137,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,d:2,q:"骑自行车时，应该？",o:["戴头盔","戴围巾","穿拖鞋","单手骑车"],a:0,k:"骑车安全：戴头盔",e:"解析：骑自行车要戴头盔，保护头部。"},
{i:138,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,d:2,q:"和小朋友玩，下面哪种游戏可能伤人？",o:["互相推搡","一起画画","一起搭积木","一起读故事"],a:0,k:"游戏安全",e:"解析：互相推搡容易弄伤别人和自己。"},
{i:139,c:"2en-7",ch:"二下·Unit 7 Play safely",f:0,d:2,q:"如果在小区里和家人走散，应该？",o:["找穿制服的保安/警察","自己走回家","跟陌生人走","哭不出来"],a:0,k:"走散处理",e:"解析：和家人走散要找穿制服的保安、警察或工作人员帮忙。"},
// ══════════ 二下·Unit 8 I can do it!（can 的能力表达）══════════
{i:140,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"“can” 的中文意思最接近？",o:["会，能","不要","好的","走"],a:0,k:"情态动词：can",e:"解析：can = 会、能，表示能力。"},
{i:141,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"“I can jump.” 中文是？",o:["我会跳。","我不要跳。","我很会走。","我喜欢跳。"],a:0,k:"句型：I can jump",e:"解析：I can jump. = 我会跳。"},
{i:142,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"别人问你会不会唱歌，回答“会”，用？",o:["Yes, I can.","No, I can't.","I like it.","I'm five."],a:0,k:"回答 can：Yes, I can",e:"解析：会唱歌用 Yes, I can. 回答。"},
{i:143,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"别人问你会不会画画，回答“不会”，用？",o:["No, I can't.","Yes, I can.","I'm sorry.","No, I'm not."],a:0,k:"回答 can：No, I can't",e:"解析：不会用 No, I can't. 回答。"},
{i:144,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"run 的中文是？",o:["跑","走","跳","坐"],a:0,k:"动词：run",e:"解析：run = 跑。"},
{i:145,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"swim 的中文是？",o:["游泳","跑步","跳舞","唱歌"],a:0,k:"动词：swim",e:"解析：swim = 游泳。"},
{i:146,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"dance 的中文是？",o:["跳舞","弹琴","画画","写字"],a:0,k:"动词：dance",e:"解析：dance = 跳舞。"},
{i:147,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"sing 的中文是？",o:["唱歌","跑步","画画","游泳"],a:0,k:"动词：sing",e:"解析：sing = 唱歌。"},
{i:148,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"play 的中文是？",o:["玩 / 演奏","读","写","买"],a:0,k:"动词：play",e:"解析：play = 玩；play the piano = 弹钢琴。"},
{i:149,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"画画的英文是？",o:["draw","swim","sing","dance"],a:0,k:"动词：draw",e:"解析：draw = 画画。"},
{i:150,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"下面哪个字母是 Q？",o:["Q","O","P","R"],a:0,k:"字母 Qq",e:"解析：Q 在 P 之后、R 之前。"},
{i:151,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"下面哪个字母是 R？",o:["R","Q","S","T"],a:0,k:"字母 Rr",e:"解析：R 在 Q 之后、S 之前。"},
{i:152,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"下面哪个字母是 S？",o:["S","R","T","U"],a:0,k:"字母 Ss",e:"解析：S 在 R 之后、T 之前。"},
{i:153,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,q:"问别人会不会跑，应该说？",o:["Can you run?","Can you sing?","Can you swim?","Can you dance?"],a:0,k:"疑问句：Can you ...?",e:"解析：问能力用 Can you ...? 问 run 即 Can you run?。"},
{i:154,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:1,q:"填空：情态动词 can 表示____（中文一个字）。",o:[],a:"能",k:"填空：can 含义",e:"解析：can 表示“能/会”，这是二年级常考的一个字填空。"},
{i:155,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:1,q:"填空：会做某事 I ____ do it. （写 can）。",o:[],a:"can",k:"填空：can",e:"解析：会做某事用 I can ... 结构。"},
{i:156,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,d:2,q:"你和小伙伴比本领，下列哪种说法不合适？",o:["I can run. You can't run.","I can run fast.","I can run, too.","Can you run?"],a:0,k:"得体表达",e:"解析：嘲笑别人 You can't run. 不合适，要换 You can try, too. 或鼓励。"},
{i:157,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,d:2,q:"下列四组全是“能力动词”的是？",o:["run, swim, sing, dance","red, blue, green, yellow","one, two, three, four","happy, sad, angry, tired"],a:0,k:"能力动词归类",e:"解析：run、swim、sing、dance 都是动作能力词。"},
{i:158,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,d:2,q:"小明会画画、会唱歌、会游泳，他应该说？",o:["I can draw, sing and swim.","I like draw, sing, swim.","I am draw sing swim.","I do draw, sing, swim."],a:0,k:"综合：多项能力表达",e:"解析：多项能力用 I can + 并列动词表示。"},
{i:159,c:"2en-8",ch:"二下·Unit 8 I can do it!",f:0,d:2,q:"朋友说 I can swim. 你的回应最得体是？",o:["Cool! I can swim, too.","No, you can't.","Yes, I can.","Can you run?"],a:0,k:"社交回应：能力话题",e:"解析：赞同朋友可说 Cool! 或 I can ..., too.，不要否定别人。"},
// ══════════ 二下·Unit 9 Let's design a park!（公园、自然、设计）══════════
{i:160,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"公园的英文是？",o:["park","zoo","lake","shop"],a:0,k:"名词：park",e:"解析：park = 公园。"},
{i:161,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"树的英文是？",o:["tree","flower","grass","leaf"],a:0,k:"自然：tree",e:"解析：tree = 树。"},
{i:162,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"花的英文是？",o:["flower","tree","grass","leaf"],a:0,k:"自然：flower",e:"解析：flower = 花。"},
{i:163,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"草的英文是？",o:["grass","tree","flower","leaf"],a:0,k:"自然：grass",e:"解析：grass = 草。"},
{i:164,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"湖的英文是？",o:["lake","park","hill","river"],a:0,k:"自然：lake",e:"解析：lake = 湖。"},
{i:165,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"山的英文是？",o:["hill","lake","park","tree"],a:0,k:"自然：hill",e:"解析：hill = 小山。"},
{i:166,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"Let's 后接什么动词原形？",o:["draw a park","draws a park","drawing a park","to draw a park"],a:0,k:"句型：Let's + 动词原形",e:"解析：Let's 后面接动词原形，draw a park。"},
{i:167,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"“design”的中文意思是？",o:["设计","拍照","打开","送来"],a:0,k:"动词：design",e:"解析：design = 设计。"},
{i:168,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"公园里常见的事物，下面哪个不在公园里？",o:["classroom（教室）","大树","滑梯","花"],a:0,k:"公园的事物",e:"解析：classroom 教室不在公园里。"},
{i:169,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"字母 T 是字母表里第几个？",o:["20","18","22","24"],a:0,k:"字母顺序：T 是第 20 个",e:"解析：A-T 共 20 个，T 是第 20 个。"},
{i:170,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"字母 U 是字母表里第几个？",o:["21","20","19","22"],a:0,k:"字母顺序：U 是第 21 个",e:"解析：A-U 共 21 个，U 是第 21 个。"},
{i:171,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"在公园里乱扔垃圾，会？",o:["破坏环境","让公园更漂亮","让树长大","让花开"],a:0,k:"环保意识",e:"解析：乱扔垃圾会破坏环境。"},
{i:172,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,q:"Let's 后不能接下面哪种词？",o:["名词（park）","动词原形（go）","短语（go to the park）","动词原形（play）"],a:0,k:"句型：Let's 后面",e:"解析：Let's 后面接动词原形或动词短语，不能直接接名词。"},
{i:173,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:1,q:"填空：公园的英文是 ____。",o:[],a:"park",k:"填空：park",e:"解析：park = 公园。"},
{i:174,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:1,q:"填空：字母表中 T 是第____个字母。",o:[],a:"20",k:"填空：T 是第 20 个",e:"解析：A-T 共 20 个，T 是第 20 个。"},
{i:175,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,d:2,q:"如果让你设计一个小公园，下面哪个是合理的？",o:["有树、有花、有滑梯、有一条小路","只有停车场","只有高楼","只有马路"],a:0,k:"综合：公园构成",e:"解析：小公园需要有植物、游乐设施和小路。"},
{i:176,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,d:2,q:"画一张公园设计图，最先要画什么？",o:["画一棵树","写名字","画一栋楼","画一条马路"],a:0,k:"设计步骤",e:"解析：公园里最显眼的是树，可以先画一棵树。"},
{i:177,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,d:2,q:"在公园玩耍，下面哪种做法最环保？",o:["把垃圾带走放进垃圾桶","随手扔垃圾","踩花草","在树上刻字"],a:0,k:"综合：环保习惯",e:"解析：垃圾带走放进垃圾桶，最环保。"},
{i:178,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,d:2,q:"看到公园的小花很美，你应该？",o:["欣赏不摘","随手采摘","踩一踩","送给朋友带走"],a:0,k:"综合：不摘花",e:"解析：公园的花是给大家欣赏的，不要摘。"},
{i:179,c:"2en-9",ch:"二下·Unit 9 Let's design a park!",f:0,d:2,q:"和小伙伴合作设计一座公园，下面哪种合作方式最好？",o:["分工：你画树、我画花","一个人包办全部","抢笔自己画","让别人自己想"],a:0,k:"合作设计",e:"解析：合作最好的方式是分工合作。"},
// ══════════ 二下·Unit 10 Let's play together!（一起玩耍）══════════
{i:180,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"一起玩的英文是？",o:["play together","play alone","play with TV","play at home"],a:0,k:"短语：play together",e:"解析：play together = 一起玩。"},
{i:181,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"在教室里，下面哪个游戏适合下课玩？",o:["猜谜","玩火","打架","大声吼叫"],a:0,k:"适合的游戏",e:"解析：猜谜安静又有趣，适合下课玩。"},
{i:182,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"hide and seek 的中文是？",o:["捉迷藏","丢手绢","跳绳","抓人"],a:0,k:"游戏：捉迷藏",e:"解析：hide and seek = 捉迷藏。"},
{i:183,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"丢手绢的英文是？",o:["throw the handkerchief","catch the ball","play hopscotch","play tag"],a:0,k:"游戏：丢手绢",e:"解析：丢手绢常见翻译为 throw the handkerchief。"},
{i:184,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"play tag 中 tag 的中文意思？",o:["抓人","搭积木","画画","唱歌"],a:0,k:"游戏：tag",e:"解析：play tag = 玩抓人游戏。"},
{i:185,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"跳绳的英文是？",o:["skip / jump rope","play tag","play catch","play hide and seek"],a:0,k:"游戏：跳绳",e:"解析：跳绳 = skip rope / jump rope。"},
{i:186,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"传球游戏叫？",o:["play catch","play tag","play hopscotch","play hide and seek"],a:0,k:"游戏：play catch",e:"解析：play catch = 玩传球。"},
{i:187,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"一起做游戏前，要先？",o:["say the rules","不打招呼","直接动手","扔别人"],a:0,k:"游戏前的步骤",e:"解析：先说清楚游戏规则再玩，更公平。"},
{i:188,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"字母 V 是字母表里第几个？",o:["22","20","21","24"],a:0,k:"字母顺序：V 是第 22 个",e:"解析：A-V 共 22 个，V 是第 22 个。"},
{i:189,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"字母 W 是字母表里第几个？",o:["23","22","21","24"],a:0,k:"字母顺序：W 是第 23 个",e:"解析：A-W 共 23 个，W 是第 23 个。"},
{i:190,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"字母 X 的发音像？",o:["/eks/（艾克斯）","/juː/","/ziː/","/eɪtʃ/"],a:0,k:"字母发音：Xx",e:"解析：X 读 /eks/。"},
{i:191,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"字母 Y 的发音像？",o:["/waɪ/（外）","/eks/","/ziː/","/eɪ/"],a:0,k:"字母发音：Yy",e:"解析：Y 读 /waɪ/。"},
{i:192,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,q:"字母 Z 的发音像？",o:["/ziː/（贼）","/eks/","/eɪtʃ/","/en/"],a:0,k:"字母发音：Zz",e:"解析：Z 读 /ziː/（美音）或 /zed/（英音）。"},
{i:193,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:1,q:"填空：一起玩的英文是 play ____。",o:[],a:"together",k:"填空：play together",e:"解析：play together = 一起玩。"},
{i:194,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:1,q:"填空：字母 Z 是字母表中第____个字母。",o:[],a:"26",k:"填空：Z 是第 26 个",e:"解析：Z 是字母表最后一个，第 26 个。"},
{i:195,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,d:2,q:"输了一场游戏，下面哪种做法最合适？",o:["和赢家说 Good game!","生气扔玩具","责怪队友","不玩了"],a:0,k:"体育精神",e:"解析：输了也要恭喜赢家，体现风度。"},
{i:196,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,d:2,q:"玩游戏时，有小伙伴哭了，你应？",o:["问问怎么了，安慰一下","继续玩","笑话他","把别人也叫哭"],a:0,k:"关怀同伴",e:"解析：同伴哭了应该关心、安抚。"},
{i:197,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,d:2,q:"玩新游戏时不会规则，下面哪种做法最聪明？",o:["问别人怎么玩","硬玩","自己改规则","不玩"],a:0,k:"学习能力",e:"解析：不懂就问，是好的学习方法。"},
{i:198,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,d:2,q:"放学大家想一起踢足球，谁先当队长？下面哪种选法最公平？",o:["石头剪刀布选","谁最会踢谁当","个子最高的当","直接指定"],a:0,k:"公平选队长",e:"解析：石头剪刀布是最公平的随机选择。"},
{i:199,c:"2en-10",ch:"二下·Unit 10 Let's play together!",f:0,d:2,q:"你和朋友们一起玩游戏，最重要的应该是？",o:["大家都开心","只有自己赢","让别人全输","让别人听你的"],a:0,k:"游戏的核心",e:"解析：一起玩最重要的是大家都开心。"}
);
