if(!global.QA)global.QA={};
if(!QA["2en"])QA["2en"]=[];
QA["2en"].push(
{i:0,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"“Good afternoon.”的意思是？",o:["下午好。","早上好。","晚上好。","晚安。"],a:0,k:"问候：Good afternoon",e:"解析：Good afternoon. 是'下午好'，用于下午见面问候。"},
{i:1,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"“Good evening.”的意思是？",o:["晚上好。","下午好。","早上好。","你好！"],a:0,k:"问候：Good evening",e:"解析：Good evening. 是'晚上好'，用于傍晚或晚上见面问候。"},
{i:2,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"下午见到朋友，你会说？",o:["Good afternoon.","Good morning.","Good night.","Goodbye."],a:0,k:"问候：Good afternoon",e:"解析：下午见面说 Good afternoon.（下午好）。"},
{i:3,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"“How are you?”的意思是？",o:["你好吗？","你叫什么名字？","你几岁？","你是谁？"],a:0,k:"问候：How are you?",e:"解析：How are you? 是'你好吗？'，用来询问对方近况。"},
{i:4,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"别人问“How are you?”，你回答“我很好，谢谢”，应说？",o:["I'm fine, thank you.","I'm five.","I'm Tom.","Goodbye."],a:0,k:"回答：I'm fine",e:"解析：I'm fine 表示'我很好'，thank you 是'谢谢'。"},
{i:5,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"初次见面，礼貌地说“很高兴见到你”，应说？",o:["Nice to meet you.","Good morning.","Thank you.","See you."],a:0,k:"礼貌：Nice to meet you",e:"解析：Nice to meet you. 是'很高兴见到你'，用于初次见面。"},
{i:6,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"朋友问“What's your name?”，你叫 Lucy，应说？",o:["My name is Lucy.","I'm fine.","I'm six.","Goodbye."],a:0,k:"问姓名：My name is...",e:"解析：回答名字用 My name is + 名字，即 My name is Lucy."},
{i:7,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:0,q:"“See you.”的意思是？",o:["再见。/回头见。","你好！","谢谢！","对不起！"],a:0,k:"告别：See you",e:"解析：See you. 是'再见/回头见'，比 Goodbye 更口语。"},
{i:8,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:1,q:"“下午好。”用英语说是 ____。",o:[],a:"Good afternoon",k:"问候：Good afternoon",e:"解析：'下午好'的英语是 Good afternoon。"},
{i:9,c:"2en-1",ch:"二上·Unit 1 Greetings 问候",f:1,q:"“晚上好。”用英语说是 ____。",o:[],a:"Good evening",k:"问候：Good evening",e:"解析：'晚上好'的英语是 Good evening。"},

{i:10,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"字母 Gg 的大写是？",o:["G","H","J","K"],a:0,k:"字母：G",e:"解析：字母 Gg 的大写是 G，小写是 g。"},
{i:11,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"字母“Hh”的小写是？",o:["h","g","j","k"],a:0,k:"字母：H",e:"解析：字母 Hh 的小写是 h，大写是 H。"},
{i:12,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"单词“green”（绿色）以哪个字母开头？",o:["G","H","I","J"],a:0,k:"字母：G",e:"解析：green 以字母 G 开头。"},
{i:13,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"单词“ice”（冰）以哪个字母开头？",o:["I","G","H","J"],a:0,k:"字母：I",e:"解析：ice 以字母 I 开头。"},
{i:14,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"字母 Kk 的大写是？",o:["K","L","M","N"],a:0,k:"字母：K",e:"解析：字母 Kk 的大写是 K，小写是 k。"},
{i:15,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"字母“Ll”的小写是？",o:["l","k","m","n"],a:0,k:"字母：L",e:"解析：字母 Ll 的小写是 l，大写是 L。"},
{i:16,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"字母 Mm 的大写是？",o:["M","N","L","K"],a:0,k:"字母：M",e:"解析：字母 Mm 的大写是 M，小写是 m。"},
{i:17,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"字母“Nn”的小写是？",o:["n","m","l","k"],a:0,k:"字母：N",e:"解析：字母 Nn 的小写是 n，大写是 N。"},
{i:18,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:0,q:"下列字母中，紧挨在 Nn 前面的是？",o:["Mm","Ll","Kk","Gg"],a:0,k:"字母顺序",e:"解析：顺序 Gg、Hh、Ii、Jj、Kk、Ll、Mm、Nn，紧挨在 Nn 前面的是 Mm。"},
{i:19,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:1,q:"单词“手 hand”以字母 ____ 开头。",o:[],a:"H",k:"字母：H",e:"解析：hand（手）以字母 H 开头。"},
{i:20,c:"2en-2",ch:"二上·Unit 2 Letters 字母 Gg–Nn",f:1,q:"字母“Kk”的小写写法是 ____。",o:[],a:"k",k:"字母：K",e:"解析：字母 Kk 的小写是 k。"},

{i:21,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“orange”的意思是？",o:["橙色","黑色","白色","粉色"],a:0,k:"颜色：orange",e:"解析：orange 表示'橙色'（也指'橙子'）。"},
{i:22,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“black”的意思是？",o:["黑色","白色","棕色","绿色"],a:0,k:"颜色：black",e:"解析：black 表示'黑色'。"},
{i:23,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“white”的意思是？",o:["白色","黑色","红色","蓝色"],a:0,k:"颜色：white",e:"解析：white 表示'白色'。"},
{i:24,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“pink”的意思是？",o:["粉色","紫色","橙色","黑色"],a:0,k:"颜色：pink",e:"解析：pink 表示'粉色'。"},
{i:25,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“purple”的意思是？",o:["紫色","粉色","橙色","棕色"],a:0,k:"颜色：purple",e:"解析：purple 表示'紫色'。"},
{i:26,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“circle”的意思是？",o:["圆形","方形","三角形","星形"],a:0,k:"形状：circle",e:"解析：circle 表示'圆形'。"},
{i:27,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“square”的意思是？",o:["方形","圆形","三角形","星形"],a:0,k:"形状：square",e:"解析：square 表示'方形（正方形）'。"},
{i:28,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:0,q:"“triangle”的意思是？",o:["三角形","方形","圆形","星形"],a:0,k:"形状：triangle",e:"解析：triangle 表示'三角形'。"},
{i:29,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:1,q:"“黑色”用英语说是 ____。",o:[],a:"black",k:"颜色：black",e:"解析：'黑色'的英语是 black。"},
{i:30,c:"2en-3",ch:"二上·Unit 3 Colours & Shapes 颜色与形状",f:1,q:"“圆形”用英语说是 ____。",o:[],a:"circle",k:"形状：circle",e:"解析：'圆形'的英语是 circle。"},

{i:31,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“six”的意思是？",o:["六","七","八","九"],a:0,k:"数字：six",e:"解析：six 表示数字'六'。"},
{i:32,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“seven”的意思是？",o:["七","六","八","十"],a:0,k:"数字：seven",e:"解析：seven 表示数字'七'。"},
{i:33,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“eight”的意思是？",o:["八","七","九","六"],a:0,k:"数字：eight",e:"解析：eight 表示数字'八'。"},
{i:34,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“nine”的意思是？",o:["九","八","十","七"],a:0,k:"数字：nine",e:"解析：nine 表示数字'九'。"},
{i:35,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“ten”的意思是？",o:["十","九","八","七"],a:0,k:"数字：ten",e:"解析：ten 表示数字'十'。"},
{i:36,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"你有 8 本书，用英语说？",o:["eight books","seven books","nine books","ten books"],a:0,k:"数字+物品",e:"解析：8 是 eight，书 book 复数为 books，eight books 即'八本书'。"},
{i:37,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"下列数字中“十”是？",o:["ten","nine","eight","seven"],a:0,k:"数字：ten",e:"解析：ten 表示'十'。"},
{i:38,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:0,q:"“一”到“十”中排在最后的是？",o:["ten","one","nine","six"],a:0,k:"数字顺序",e:"解析：one 到 ten 中，ten（十）排在最后。"},
{i:39,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:1,q:"“九”用英语说是 ____。",o:[],a:"nine",k:"数字：nine",e:"解析：数字'九'的英语是 nine。"},
{i:40,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:1,q:"“七”用英语说是 ____。",o:[],a:"seven",k:"数字：seven",e:"解析：数字'七'的英语是 seven。"},
{i:41,c:"2en-4",ch:"二上·Unit 4 Numbers 数字 1–10",f:1,q:"“八”用英语说是 ____。",o:[],a:"eight",k:"数字：eight",e:"解析：数字'八'的英语是 eight。"},

{i:42,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“tiger”的意思是？",o:["老虎","大象","熊猫","狮子"],a:0,k:"动物：tiger",e:"解析：tiger 表示'老虎'。"},
{i:43,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“elephant”的意思是？",o:["大象","老虎","熊","猴子"],a:0,k:"动物：elephant",e:"解析：elephant 表示'大象'。"},
{i:44,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“monkey”的意思是？",o:["猴子","熊猫","狮子","兔子"],a:0,k:"动物：monkey",e:"解析：monkey 表示'猴子'。"},
{i:45,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“panda”的意思是？",o:["熊猫","老虎","大象","鸟"],a:0,k:"动物：panda",e:"解析：panda 表示'熊猫'。"},
{i:46,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“bear”的意思是？",o:["熊","老虎","狮子","猴子"],a:0,k:"动物：bear",e:"解析：bear 表示'熊'。"},
{i:47,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"“lion”的意思是？",o:["狮子","熊","老虎","大象"],a:0,k:"动物：lion",e:"解析：lion 表示'狮子'。"},
{i:48,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"你最喜欢熊猫，会说？",o:["I like pandas.","I like tigers.","I like lions.","I like bears."],a:0,k:"句型：I like...",e:"解析：panda 复数为 pandas，I like pandas. 即'我喜欢熊猫'。"},
{i:49,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:0,q:"下列动物中“大象”是？",o:["elephant","tiger","lion","bear"],a:0,k:"动物：elephant",e:"解析：elephant 表示'大象'。"},
{i:50,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:1,q:"“老虎”用英语说是 ____。",o:[],a:"tiger",k:"动物：tiger",e:"解析：'老虎'的英语是 tiger。"},
{i:51,c:"2en-5",ch:"二上·Unit 5 Animals 动物",f:1,q:"“熊猫”用英语说是 ____。",o:[],a:"panda",k:"动物：panda",e:"解析：'熊猫'的英语是 panda。"},

{i:52,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“father”的意思是？",o:["爸爸","妈妈","爷爷","弟弟"],a:0,k:"家庭：father",e:"解析：father 表示'爸爸'，口语常说 dad。"},
{i:53,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“mother”的意思是？",o:["妈妈","爸爸","奶奶","姐姐"],a:0,k:"家庭：mother",e:"解析：mother 表示'妈妈'，口语常说 mum。"},
{i:54,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“grandpa”的意思是？",o:["爷爷","奶奶","爸爸","哥哥"],a:0,k:"家庭：grandpa",e:"解析：grandpa 表示'爷爷'，也可说 grandfather。"},
{i:55,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“grandma”的意思是？",o:["奶奶","爷爷","妈妈","妹妹"],a:0,k:"家庭：grandma",e:"解析：grandma 表示'奶奶'，也可说 grandmother。"},
{i:56,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“brother”的意思是？",o:["兄弟","姐妹","爸爸","妈妈"],a:0,k:"家庭：brother",e:"解析：brother 表示'兄弟（哥哥/弟弟）'。"},
{i:57,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“sister”的意思是？",o:["姐妹","兄弟","奶奶","爷爷"],a:0,k:"家庭：sister",e:"解析：sister 表示'姐妹（姐姐/妹妹）'。"},
{i:58,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"那是你弟弟，应说？",o:["He's my brother.","She's my sister.","He's my father.","She's my mother."],a:0,k:"句型：He's my...",e:"解析：弟弟是男孩用 he，brother 是'兄弟'，所以是 He's my brother."},
{i:59,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:0,q:"“baby”的意思是？",o:["婴儿","男孩","女孩","朋友"],a:0,k:"家庭：baby",e:"解析：baby 表示'婴儿'。"},
{i:60,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:1,q:"“妈妈”用英语说是 ____（mother/mum）。",o:[],a:"mother",k:"家庭：mother",e:"解析：'妈妈'的英语是 mother，口语常说 mum。"},
{i:61,c:"2en-6",ch:"二上·Unit 6 My family 家庭成员",f:1,q:"“爷爷”用英语说是 ____（grandpa/grandfather）。",o:[],a:"grandpa",k:"家庭：grandpa",e:"解析：'爷爷'的英语是 grandpa，也可说 grandfather。"},

{i:62,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“rice”的意思是？",o:["米饭","面条","肉","蛋糕"],a:0,k:"食物：rice",e:"解析：rice 表示'米饭'。"},
{i:63,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“noodles”的意思是？",o:["面条","米饭","面包","水"],a:0,k:"食物：noodles",e:"解析：noodles 表示'面条'。"},
{i:64,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“meat”的意思是？",o:["肉","米饭","鱼","蛋"],a:0,k:"食物：meat",e:"解析：meat 表示'肉'。"},
{i:65,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“cake”的意思是？",o:["蛋糕","鸡蛋","面包","米饭"],a:0,k:"食物：cake",e:"解析：cake 表示'蛋糕'。"},
{i:66,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“juice”的意思是？",o:["果汁","牛奶","茶","咖啡"],a:0,k:"饮料：juice",e:"解析：juice 表示'果汁'。"},
{i:67,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“tea”的意思是？",o:["茶","果汁","咖啡","牛奶"],a:0,k:"饮料：tea",e:"解析：tea 表示'茶'。"},
{i:68,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:0,q:"“coffee”的意思是？",o:["咖啡","茶","果汁","水"],a:0,k:"饮料：coffee",e:"解析：coffee 表示'咖啡'。"},
{i:69,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:1,q:"“米饭”用英语说是 ____。",o:[],a:"rice",k:"食物：rice",e:"解析：'米饭'的英语是 rice。"},
{i:70,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:1,q:"“面条”用英语说是 ____。",o:[],a:"noodles",k:"食物：noodles",e:"解析：'面条'的英语是 noodles。"},
{i:71,c:"2en-7",ch:"二下·Unit 7 Food & Drink 食物与饮料",f:1,q:"“果汁”用英语说是 ____。",o:[],a:"juice",k:"饮料：juice",e:"解析：'果汁'的英语是 juice。"},

{i:72,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“pen”的意思是？",o:["钢笔","铅笔","书","尺子"],a:0,k:"文具：pen",e:"解析：pen 表示'钢笔'。"},
{i:73,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“pencil”的意思是？",o:["铅笔","钢笔","橡皮","书包"],a:0,k:"文具：pencil",e:"解析：pencil 表示'铅笔'。"},
{i:74,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“ruler”的意思是？",o:["尺子","铅笔","书","书包"],a:0,k:"文具：ruler",e:"解析：ruler 表示'尺子'。"},
{i:75,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“eraser”的意思是？",o:["橡皮","尺子","铅笔","钢笔"],a:0,k:"文具：eraser",e:"解析：eraser 表示'橡皮'。"},
{i:76,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“book”的意思是？",o:["书","书包","尺子","铅笔"],a:0,k:"文具：book",e:"解析：book 表示'书'。"},
{i:77,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“bag”的意思是？",o:["书包","书","铅笔","橡皮"],a:0,k:"文具：bag",e:"解析：bag 表示'书包/袋子'。"},
{i:78,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:0,q:"“crayon”的意思是？",o:["蜡笔","钢笔","尺子","橡皮"],a:0,k:"文具：crayon",e:"解析：crayon 表示'蜡笔'。"},
{i:79,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:1,q:"“铅笔”用英语说是 ____。",o:[],a:"pencil",k:"文具：pencil",e:"解析：'铅笔'的英语是 pencil。"},
{i:80,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:1,q:"“橡皮”用英语说是 ____。",o:[],a:"eraser",k:"文具：eraser",e:"解析：'橡皮'的英语是 eraser。"},
{i:81,c:"2en-8",ch:"二下·Unit 8 School things 文具",f:1,q:"“尺子”用英语说是 ____。",o:[],a:"ruler",k:"文具：ruler",e:"解析：'尺子'的英语是 ruler。"},

{i:82,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“ball”的意思是？",o:["球","娃娃","车","风筝"],a:0,k:"玩具：ball",e:"解析：ball 表示'球'。"},
{i:83,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“train”的意思是？",o:["火车","汽车","球","娃娃"],a:0,k:"玩具：train",e:"解析：train 表示'火车'。"},
{i:84,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“robot”的意思是？",o:["机器人","娃娃","球","积木"],a:0,k:"玩具：robot",e:"解析：robot 表示'机器人'。"},
{i:85,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“block”的意思是？",o:["积木","球","车","风筝"],a:0,k:"玩具：block",e:"解析：block 表示'积木'。"},
{i:86,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"“puzzle”的意思是？",o:["拼图","积木","球","娃娃"],a:0,k:"玩具：puzzle",e:"解析：puzzle 表示'拼图'。"},
{i:87,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"你喜欢机器人，会说？",o:["I like robots.","I like dolls.","I like balls.","I like kites."],a:0,k:"句型：I like...",e:"解析：robot 复数为 robots，I like robots. 即'我喜欢机器人'。"},
{i:88,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:0,q:"下列玩具中“火车”是？",o:["train","car","ball","doll"],a:0,k:"玩具：train",e:"解析：train 表示'火车'。"},
{i:89,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:1,q:"“娃娃”用英语说是 ____。",o:[],a:"doll",k:"玩具：doll",e:"解析：'娃娃'的英语是 doll。"},
{i:90,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:1,q:"“风筝”用英语说是 ____。",o:[],a:"kite",k:"玩具：kite",e:"解析：'风筝'的英语是 kite。"},
{i:91,c:"2en-9",ch:"二下·Unit 9 Toys 玩具",f:1,q:"“机器人”用英语说是 ____。",o:[],a:"robot",k:"玩具：robot",e:"解析：'机器人'的英语是 robot。"},

{i:92,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“run”的意思是？",o:["跑","跳","走","唱"],a:0,k:"动作：run",e:"解析：run 表示'跑'。"},
{i:93,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“jump”的意思是？",o:["跳","跑","走","飞"],a:0,k:"动作：jump",e:"解析：jump 表示'跳'。"},
{i:94,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“walk”的意思是？",o:["走","跑","跳","站"],a:0,k:"动作：walk",e:"解析：walk 表示'走'。"},
{i:95,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“sing”的意思是？",o:["唱歌","跳舞","读书","写字"],a:0,k:"动作：sing",e:"解析：sing 表示'唱歌'。"},
{i:96,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“dance”的意思是？",o:["跳舞","唱歌","画画","睡觉"],a:0,k:"动作：dance",e:"解析：dance 表示'跳舞'。"},
{i:97,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“read”的意思是？",o:["读","写","画","吃"],a:0,k:"动作：read",e:"解析：read 表示'读/看书'。"},
{i:98,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“write”的意思是？",o:["写","读","画","唱"],a:0,k:"动作：write",e:"解析：write 表示'写'。"},
{i:99,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:0,q:"“draw”的意思是？",o:["画画","写字","读书","睡觉"],a:0,k:"动作：draw",e:"解析：draw 表示'画画'。"},
{i:100,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:1,q:"“跑”用英语说是 ____。",o:[],a:"run",k:"动作：run",e:"解析：'跑'的英语是 run。"},
{i:101,c:"2en-10",ch:"二下·Unit 10 Actions 动作",f:1,q:"“跳”用英语说是 ____。",o:[],a:"jump",k:"动作：jump",e:"解析：'跳'的英语是 jump。"}
);
