// 三年级英语 · 人教PEP（三年级起点）
// 三上 Unit 1~6 + 三下 Unit 1~6，共 12 单元 × 20 题 = 240 题
// 每单元：14 选择题 + 2 填空题 + 4 拔高题（d:2）
// 2026-09-10 整套重写：原 240 题知识点重复 13.8%、全 12 单元零拔高，重写后 0 重复、每单元 4 拔高
if(!global.QA)global.QA={};
if(!QA["3en"])QA["3en"]=[];
QA["3en"].push(
// ══════════ 三上·Unit 1 Hello! 打招呼与问候 ══════════
{i:0,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"“Hello!”的中文意思是？",o:["你好！","再见！","谢谢！","对不起！"],a:0,k:"问候语：Hello",e:"解析：Hello! 是英语中最常用的打招呼用语，意为“你好！”，熟人之间也可以说 Hi。"},
{i:1,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"你想告诉别人“我是 Tom”，应该说？",o:["I'm Tom.","You're Tom.","He's Tom.","She's Tom."],a:0,k:"自我介绍：I'm + 名字",e:"解析：I'm 是 I am 的缩写，I'm Tom. 意为“我是 Tom”，用来向别人介绍自己。"},
{i:2,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"早上见到老师，你应该说？",o:["Good morning.","Good night.","Goodbye.","Thank you."],a:0,k:"问候语：Good morning",e:"解析：Good morning. 意为“早上好”，用于上午见面时问候。"},
{i:3,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"下午两点见到同学，说“下午好”应该用？",o:["Good afternoon.","Good morning.","Good evening.","Good night."],a:0,k:"问候语：Good afternoon",e:"解析：afternoon 是“下午”，Good afternoon. 用于中午到傍晚之间的问候。"},
{i:4,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"晚上睡觉前对家人说“晚安”，应该说？",o:["Good night.","Good morning.","Good afternoon.","Hello."],a:0,k:"问候语：Good night",e:"解析：Good night. 是睡前或夜间道别时说的“晚安”，不是见面问候语。"},
{i:5,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"放学和同学分开时说“再见”，应该说？",o:["Goodbye!","Hello!","Good morning!","Nice to meet you!"],a:0,k:"告别语：Goodbye",e:"解析：Goodbye! 意为“再见”，用于和他人分别时，也可以说 Bye!"},
{i:6,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"你想知道对方的名字，应该问？",o:["What's your name?","How are you?","How old are you?","Where are you?"],a:0,k:"问姓名：What's your name?",e:"解析：What's your name? 意为“你叫什么名字？”，可以回答 My name is... 或 I'm..."},
{i:7,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"—Nice to meet you.  —____",o:["Nice to meet you, too.","I'm fine, thank you.","Goodbye.","You're welcome."],a:0,k:"交际用语：Nice to meet you",e:"解析：初次见面说 Nice to meet you.（很高兴认识你），对方常回答 Nice to meet you, too.，too 表示“也”。"},
{i:8,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"—How are you?  —____",o:["I'm fine, thank you.","I'm nine.","My name is Lily.","It's a pen."],a:0,k:"交际用语：How are you 的应答",e:"解析：How are you? 问的是身体好不好，应答 I'm fine, thank you.（我很好，谢谢）。"},
{i:9,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"别人对你说“Thank you.”，你应该回答？",o:["You're welcome.","I'm sorry.","Good night.","Thank you, too."],a:0,k:"交际用语：You're welcome",e:"解析：回应感谢用 You're welcome.（不客气）；I'm sorry. 是道歉用语。"},
{i:10,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"下列单词中，哪一个是文具？",o:["ruler","apple","monkey","milk"],a:0,k:"词汇：文具 ruler",e:"解析：ruler 是“尺子”，属于文具；apple 苹果、monkey 猴子、milk 牛奶都不是文具。"},
{i:11,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"“I'm”是“I ____”的缩写。",o:["am","is","are","be"],a:0,k:"缩写：I'm = I am",e:"解析：I'm 是 I am 的缩写，I 只能和 am 搭配，表示“我是”。"},
{i:12,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"“eraser”的意思是？",o:["橡皮","铅笔","书包","尺子"],a:0,k:"词汇：文具 eraser",e:"解析：eraser 是“橡皮”，用来擦掉铅笔写出的字迹。"},
{i:13,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"你想把新同学 Mike 介绍给大家，可以说？",o:["This is Mike.","I'm Mike.","You're Mike.","Are you Mike?"],a:0,k:"介绍他人：This is...",e:"解析：向别人介绍第三个人用 This is...，意为“这是……”。"},
{i:14,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"“Hi, I'm Sarah.”的中文意思是？",o:["你好，我是萨拉。","再见，萨拉。","你好吗，萨拉？","谢谢你，萨拉。"],a:0,k:"句型翻译：Hi, I'm...",e:"解析：Hi 相当于 Hello，I'm 是 I am 的缩写，整句意为“你好，我是萨拉”。"},
{i:15,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:1,q:"“你好！”用英语说是 ____。",o:[],a:"Hello",k:"填空：Hello",e:"解析：“你好！”的英语是 Hello，熟人之间也可以说 Hi。"},
{i:16,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:1,q:"晚上道别说“晚安”：Good ____.",o:[],a:"night",k:"填空：Good night",e:"解析：Good night. 是夜间或睡前道别时说的“晚安”。"},
{i:17,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,d:2,q:"下面四句话中，哪一句是见面打招呼用的，而不是道别时用的？",o:["Good morning!","Goodbye!","See you!","Good night!"],a:0,k:"拔高：辨别见面语与告别语",e:"解析：Good morning! 是见面问候；Goodbye!、See you!、Good night! 都用于分别或睡前。"},
{i:18,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,d:2,q:"—Hello! I'm Mike. What's your name?  —____",o:["My name is Lily.","I'm fine, thank you.","Goodbye, Mike.","You're welcome."],a:0,k:"拔高：问候后接自我介绍",e:"解析：别人问 What's your name?，应回答自己的名字，如 My name is Lily.；I'm fine 是回答 How are you 的。"},
{i:19,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,d:2,q:"初次见面时，下列哪种说法最合适？",o:["Nice to meet you.","Goodbye.","How old are you?","Give me your pen."],a:0,k:"拔高：初次见面的礼貌用语",e:"解析：初次见面说 Nice to meet you.（很高兴认识你）最合适；一见面向别人问年龄或索要东西都不礼貌。"},
// ══════════ 三上·Unit 2 Colours 颜色 ══════════
{i:20,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“红色”用英语说是？",o:["red","yellow","blue","green"],a:0,k:"颜色：red",e:"解析：red 表示“红色”，如 a red apple（一个红苹果）。"},
{i:21,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"下面哪个单词表示“蓝色”？",o:["blue","black","brown","green"],a:0,k:"颜色：blue",e:"解析：blue 表示“蓝色”，如 a blue sky（蓝色的天空）。"},
{i:22,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“yellow”的意思是？",o:["黄色","绿色","红色","蓝色"],a:0,k:"颜色：yellow",e:"解析：yellow 表示“黄色”，如 a yellow banana（黄色的香蕉）。"},
{i:23,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“green”的意思是？",o:["绿色","蓝色","黄色","紫色"],a:0,k:"颜色：green",e:"解析：green 表示“绿色”，如 green trees（绿树）。"},
{i:24,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“black”的意思是？",o:["黑色","白色","棕色","粉色"],a:0,k:"颜色：black",e:"解析：black 表示“黑色”，如 a black cat（一只黑猫）。"},
{i:25,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"下列哪个是“白色”的正确拼写？",o:["white","wihte","whtie","with"],a:0,k:"拼写：white",e:"解析：white 正确拼写为 w-h-i-t-e，意思是“白色”；with 意为“和……一起”，不是颜色词。"},
{i:26,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“orange”既有“橙子”的意思，还可以表示什么颜色？",o:["橙色","棕色","紫色","灰色"],a:0,k:"颜色：orange",e:"解析：orange 本义是“橙子”，也用来表示“橙色”。"},
{i:27,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“brown”的意思是？",o:["棕色","黑色","蓝色","绿色"],a:0,k:"颜色：brown",e:"解析：brown 表示“棕色、褐色”，如 a brown bear（一只棕熊）。"},
{i:28,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“purple”的意思是？",o:["紫色","粉色","灰色","金色"],a:0,k:"颜色：purple",e:"解析：purple 意为“紫色”；粉色是 pink，灰色是 grey/gray。"},
{i:29,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"—What colour is it?  —____",o:["It's red.","It's a cat.","Yes, it is.","I'm fine."],a:0,k:"句型：What colour is it?",e:"解析：What colour 问的是颜色，用 It's + 颜色词 回答；It's a cat. 回答的是“是什么”。"},
{i:30,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“Show me your green crayon.”的意思是？",o:["给我看你的绿色蜡笔。","给我看你的红色书包。","把它涂成绿色。","我喜欢绿色。"],a:0,k:"句型：Show me your...",e:"解析：show 是“给……看”，crayon 是“蜡笔”，整句意为“给我看你的绿色蜡笔”。"},
{i:31,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“Colour it black.”的意思是？",o:["把它涂成黑色。","它是黑色的。","给我黑色的笔。","黑色很好看。"],a:0,k:"句型：Colour it...",e:"解析：这里的 colour 作动词，意为“给……涂色”；“它是黑色的”应说 It's black."},
{i:32,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"天空是蓝色的，可以说：The sky is ____.",o:["blue","black","brown","white"],a:0,k:"句型运用：The sky is blue",e:"解析：天空是蓝色的，用 blue；black 黑、brown 棕、white 白都不符合天空的颜色。"},
{i:33,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"交通信号灯中，表示“停”的是____灯。",o:["red","green","yellow","blue"],a:0,k:"生活运用：红灯停",e:"解析：红灯停、绿灯行，表示“停”的是 red（红色的）灯；green 是通行，yellow 是等待。"},
{i:34,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“我喜欢蓝色。”用英语说是？",o:["I like blue.","I like blue it.","Blue I like.","I am blue."],a:0,k:"句型：I like + 颜色",e:"解析：表达喜欢某物用 I like...，颜色词直接跟在后面，I like blue. 即“我喜欢蓝色”。"},
{i:35,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:1,q:"“蓝色”用英语说是 ____。",o:[],a:"blue",k:"填空：blue",e:"解析：“蓝色”的英语是 blue。"},
{i:36,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:1,q:"“黑色”用英语说是 ____。",o:[],a:"black",k:"填空：black",e:"解析：“黑色”的英语是 black。"},
{i:37,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,d:2,q:"把红色和黄色调在一起，会变成什么颜色？",o:["橙色","绿色","紫色","棕色"],a:0,k:"拔高：三原色调色",e:"解析：红（red）+ 黄（yellow）调在一起是橙（orange）；蓝+黄是绿，红+蓝是紫。"},
{i:38,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,d:2,q:"下列四个单词中，哪一个是颜色词？",o:["purple","pencil","panda","plate"],a:0,k:"拔高：辨别颜色词",e:"解析：purple 是“紫色”；pencil 铅笔、panda 熊猫、plate 盘子都不是颜色词。"},
{i:39,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,d:2,q:"—What colour is your bag?  —____",o:["It's black.","It's a bag.","Yes, it is.","It's nice."],a:0,k:"拔高：问颜色并回答",e:"解析：What colour 问颜色，回答用 It's + 颜色词，如 It's black.；It's a bag. 回答的是“是什么”。"},
// ══════════ 三上·Unit 3 Look at me! 五官与身体 ══════════
{i:40,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“eye”的意思是？",o:["眼睛","耳朵","鼻子","嘴巴"],a:0,k:"身体：eye",e:"解析：eye 表示“眼睛”，两只眼睛要用复数 eyes。"},
{i:41,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“ear”的意思是？",o:["耳朵","眼睛","手臂","头"],a:0,k:"身体：ear",e:"解析：ear 表示“耳朵”，两只耳朵要用复数 ears。"},
{i:42,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“nose”的意思是？",o:["鼻子","嘴巴","脸","头"],a:0,k:"身体：nose",e:"解析：nose 表示“鼻子”，用来闻气味。"},
{i:43,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“mouth”的意思是？",o:["嘴巴","手","脚","腿"],a:0,k:"身体：mouth",e:"解析：mouth 表示“嘴巴”，用来吃东西和说话。"},
{i:44,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“face”的意思是？",o:["脸","脚","手臂","身体"],a:0,k:"身体：face",e:"解析：face 表示“脸”，如 a round face（一张圆脸）。"},
{i:45,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“head”的意思是？",o:["头","手","腿","眼睛"],a:0,k:"身体：head",e:"解析：head 表示“头”，如 touch your head（摸摸你的头）。"},
{i:46,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“hand”的意思是？",o:["手","脚","手臂","耳朵"],a:0,k:"身体：hand",e:"解析：hand 表示“手”，一只手是 a hand，两只手是 hands。"},
{i:47,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“arm”的意思是？",o:["手臂","腿","脚","头"],a:0,k:"身体：arm",e:"解析：arm 表示“手臂”，如 wave your arm（挥挥你的手臂）。"},
{i:48,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“leg”的意思是？",o:["腿","手臂","脚","脸"],a:0,k:"身体：leg",e:"解析：leg 表示“腿”，如 long legs（长长的腿）。"},
{i:49,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“foot”的意思是？",o:["脚","手","腿","头"],a:0,k:"身体：foot",e:"解析：foot 表示“脚”，两只脚是 feet，属于不规则变化的复数形式。"},
{i:50,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“body”的意思是？",o:["身体","脸","手臂","腿"],a:0,k:"身体：body",e:"解析：body 表示“身体”，如 a strong body（强壮的身体）。"},
{i:51,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“Look at me!”的意思是？",o:["看我！","听我说！","帮帮我！","跟我走！"],a:0,k:"句型：Look at me!",e:"解析：look at 意为“看……”，me 是“我”的宾格，整句是“看我！”。"},
{i:52,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“Touch your head.”的意思是？",o:["摸摸你的头。","摸摸你的手。","抬起你的腿。","闭上你的眼睛。"],a:0,k:"句型：Touch your...",e:"解析：touch 意为“触摸”，head 是“头”，整句是“摸摸你的头”。"},
{i:53,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“Clap your hands.”的意思是？",o:["拍拍你的手。","挥挥你的手臂。","跺跺你的脚。","摸摸你的鼻子。"],a:0,k:"句型：Clap your hands",e:"解析：clap 意为“拍（手）”，hands 是“手”的复数，整句是“拍拍你的手”。"},
{i:54,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:1,q:"“眼睛”用英语说是 ____。",o:[],a:"eye",k:"填空：eye",e:"解析：“眼睛”的英语是 eye，两只眼睛写作 eyes。"},
{i:55,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:1,q:"“嘴巴”用英语说是 ____。",o:[],a:"mouth",k:"填空：mouth",e:"解析：“嘴巴”的英语是 mouth，读作 /maʊθ/。"},
{i:56,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,d:2,q:"下面哪个单词表示的是“成对的器官”？",o:["ear","nose","mouth","face"],a:0,k:"拔高：成对器官 ear",e:"解析：ear（耳朵）、eye（眼睛）、hand（手）都成对出现，说两只时用复数 ears；nose、mouth、face 通常只有一个。"},
{i:57,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,d:2,q:"“Wave your arm.”这个指令要求你做什么？",o:["挥一挥手臂","摸摸鼻子","拍拍手","闭上嘴巴"],a:0,k:"拔高：理解身体动作指令",e:"解析：wave 意为“挥动”，arm 是“手臂”，整句是“挥一挥手臂”。"},
{i:58,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,d:2,q:"下列四个单词中，哪一个不是身体部位？",o:["book","eye","ear","mouth"],a:0,k:"拔高：辨别身体部位词",e:"解析：book 是“书”，属于文具；eye、ear、mouth 都是身体部位。"},
{i:59,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,d:2,q:"医生给你检查牙齿时说“Open your mouth.”，意思是？",o:["张开你的嘴","闭上你的眼睛","伸出你的手","摸摸你的头"],a:0,k:"拔高：情景理解 Open your mouth",e:"解析：open 意为“打开、张开”，mouth 是“嘴巴”，整句是“张开你的嘴”。"},
// ══════════ 三上·Unit 4 We love animals 动物 ══════════
{i:60,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“cat”的意思是？",o:["猫","狗","鸭子","猪"],a:0,k:"动物：cat",e:"解析：cat 表示“猫”，如 a black cat（一只黑猫）。"},
{i:61,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“dog”的意思是？",o:["狗","猫","熊","鸟"],a:0,k:"动物：dog",e:"解析：dog 表示“狗”，是人类忠实的朋友。"},
{i:62,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“duck”的意思是？",o:["鸭子","小鸟","大象","猴子"],a:0,k:"动物：duck",e:"解析：duck 表示“鸭子”，会游泳，叫声是 quack。"},
{i:63,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“pig”的意思是？",o:["猪","狗","熊","老虎"],a:0,k:"动物：pig",e:"解析：pig 表示“猪”，如 a fat pig（一头胖猪）。"},
{i:64,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“bear”的意思是？",o:["熊","猪","猫","猴子"],a:0,k:"动物：bear",e:"解析：bear 表示“熊”，如 a brown bear（一只棕熊）。"},
{i:65,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“elephant”的意思是？",o:["大象","老虎","猴子","熊猫"],a:0,k:"动物：elephant",e:"解析：elephant 表示“大象”，它的鼻子长长的。"},
{i:66,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“monkey”的意思是？",o:["猴子","大象","老虎","鸭子"],a:0,k:"动物：monkey",e:"解析：monkey 表示“猴子”，喜欢爬树、爱吃香蕉。"},
{i:67,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“bird”的意思是？",o:["鸟","鸭子","猫","熊"],a:0,k:"动物：bird",e:"解析：bird 表示“鸟”，会飞，如 a little bird（一只小鸟）。"},
{i:68,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“tiger”的意思是？",o:["老虎","大象","猪","狗"],a:0,k:"动物：tiger",e:"解析：tiger 表示“老虎”，身上有黑色的条纹。"},
{i:69,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“panda”的意思是？",o:["熊猫","猴子","老虎","鸭子"],a:0,k:"动物：panda",e:"解析：panda 表示“熊猫”，是我国的国宝，身体黑白两色。"},
{i:70,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“zoo”的意思是？",o:["动物园","学校","公园","农场"],a:0,k:"场所：zoo",e:"解析：zoo 表示“动物园”，如 go to the zoo（去动物园）。"},
{i:71,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"—What's this?  —____",o:["It's a duck.","Yes, it is.","I'm fine.","It's red."],a:0,k:"句型：What's this?",e:"解析：What's this? 问“这是什么？”，用 It's a/an + 名词 回答；It's red. 回答的是颜色。"},
{i:72,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“I like dogs.”的意思是？",o:["我喜欢狗。","我怕狗。","我有一只狗。","狗喜欢我。"],a:0,k:"句型：I like + 动物",e:"解析：like 意为“喜欢”，dogs 是 dog 的复数，整句是“我喜欢狗”。"},
{i:73,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“Act like a monkey.”的意思是？",o:["学猴子的样子做动作","给猴子喂食","画一只猴子","把猴子放走"],a:0,k:"句型：Act like a...",e:"解析：act 意为“表演、模仿”，like 在此表示“像……”，整句是“学猴子的样子做动作”。"},
{i:74,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"下列四个单词中，哪一个不是动物？",o:["apple","duck","dog","pig"],a:0,k:"词汇辨别：动物与水果",e:"解析：apple 是“苹果”，属于水果；duck、dog、pig 都是动物。"},
{i:75,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:1,q:"“熊猫”用英语说是 ____。",o:[],a:"panda",k:"填空：panda",e:"解析：“熊猫”的英语是 panda，是我国的国宝。"},
{i:76,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:1,q:"“鸟”用英语说是 ____。",o:[],a:"bird",k:"填空：bird",e:"解析：“鸟”的英语是 bird，复数形式是 birds。"},
{i:77,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,d:2,q:"在动物园里看到一头大象，你会怎么说？",o:["Look at the elephant! It's so big.","Look at the elephant! It's so small.","Look at the bird! It's so tall.","Look at the panda! It's so long."],a:0,k:"拔高：情景描述动物",e:"解析：大象体形巨大，用 Look at the elephant! It's so big.（看那头大象！它真大）最贴切。"},
{i:78,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,d:2,q:"“两只猫”用英语怎么说？",o:["two cats","two cat","a cats","two cat's"],a:0,k:"拔高：名词复数 two cats",e:"解析：数量超过一时名词要用复数，cat 的复数是 cats，所以“两只猫”是 two cats。"},
{i:79,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,d:2,q:"“It has a long nose.”描述的是哪种动物？",o:["elephant","duck","bird","cat"],a:0,k:"拔高：由特征推断动物",e:"解析：有长长鼻子的是大象，所以答案是 elephant；鸭子有扁嘴，鸟有翅膀。"},
// ══════════ 三上·Unit 5 Let's eat! 食物 ══════════
{i:80,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“bread”的意思是？",o:["面包","牛奶","鸡蛋","鱼"],a:0,k:"食物：bread",e:"解析：bread 表示“面包”，是不可数名词，不能说 a bread。"},
{i:81,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“egg”的意思是？",o:["鸡蛋","面包","水","米饭"],a:0,k:"食物：egg",e:"解析：egg 表示“鸡蛋”，一个鸡蛋是 an egg。"},
{i:82,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“milk”的意思是？",o:["牛奶","果汁","水","茶"],a:0,k:"食物：milk",e:"解析：milk 表示“牛奶”，是不可数名词，常说 some milk。"},
{i:83,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“water”的意思是？",o:["水","牛奶","果汁","面包"],a:0,k:"食物：water",e:"解析：water 表示“水”，是不可数名词，如 drink water（喝水）。"},
{i:84,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“cake”的意思是？",o:["蛋糕","面包","米饭","鱼"],a:0,k:"食物：cake",e:"解析：cake 表示“蛋糕”，过生日时常吃 birthday cake。"},
{i:85,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“fish”的意思是？",o:["鱼","米饭","鸡蛋","蛋糕"],a:0,k:"食物：fish",e:"解析：fish 表示“鱼”，作食物时通常用单数形式。"},
{i:86,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“rice”的意思是？",o:["米饭","面包","水","牛奶"],a:0,k:"食物：rice",e:"解析：rice 表示“米饭”，是不可数名词，如 a bowl of rice（一碗米饭）。"},
{i:87,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“juice”的意思是？",o:["果汁","牛奶","水","面包"],a:0,k:"食物：juice",e:"解析：juice 表示“果汁”，如 orange juice（橙汁）。"},
{i:88,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“I'm hungry.”的意思是？",o:["我饿了。","我渴了。","我饱了。","我累了。"],a:0,k:"句型：I'm hungry",e:"解析：hungry 意为“饥饿的”，I'm hungry. 即“我饿了”；“我渴了”是 I'm thirsty."},
{i:89,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“I'd like some juice.”的意思是？",o:["我想要一些果汁。","我不喜欢果汁。","我有一些果汁。","这是果汁。"],a:0,k:"句型：I'd like some...",e:"解析：I'd like... 是 I would like 的缩写，意为“我想要……”，比 I want 更礼貌。"},
{i:90,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“Have some bread.”的意思是？",o:["吃些面包吧。","买些面包吧。","面包不见了。","我不吃面包。"],a:0,k:"句型：Have some...",e:"解析：Have some... 是招呼别人吃喝的常用说法，意为“吃些/喝些……吧”。"},
{i:91,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"早餐想喝牛奶，可以说？",o:["I'd like some milk.","I'd like some cake.","I don't like milk.","It's a milk."],a:0,k:"情景运用：要牛奶",e:"解析：想要牛奶说 I'd like some milk.；milk 是不可数名词，不能说 It's a milk。"},
{i:92,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"下列四个单词中，哪一个不是食物？",o:["cat","egg","rice","bread"],a:0,k:"词汇辨别：食物与动物",e:"解析：cat 是“猫”，属于动物；egg 鸡蛋、rice 米饭、bread 面包都是食物。"},
{i:93,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"过生日时吃的食物通常是？",o:["cake","rice","bread","egg"],a:0,k:"情景运用：生日蛋糕",e:"解析：过生日习惯吃蛋糕，即 birthday cake；米饭、面包、鸡蛋是日常食物。"},
{i:94,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:1,q:"“牛奶”用英语说是 ____。",o:[],a:"milk",k:"填空：milk",e:"解析：“牛奶”的英语是 milk，是不可数名词。"},
{i:95,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:1,q:"“水”用英语说是 ____。",o:[],a:"water",k:"填空：water",e:"解析：“水”的英语是 water，是不可数名词。"},
{i:96,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,d:2,q:"下面哪种说法是正确的？",o:["I'd like some milk.","I'd like a milk.","I'd like two milks.","I'd like a waters."],a:0,k:"拔高：不可数名词用法",e:"解析：milk、water 等都是不可数名词，前面用 some，不用 a/an，也不能直接加 -s 表示数量。"},
{i:97,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,d:2,q:"—Can I have some juice?  —____",o:["Sure. Here you are.","No, I'm fine.","It's a juice.","I like juice."],a:0,k:"拔高：请求并应答",e:"解析：Can I have...? 是请求用语，同意时通常回答 Sure. Here you are.（当然可以，给你）。"},
{i:98,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,d:2,q:"招待客人吃东西时，下面哪句最合适？",o:["Have some cake, please.","Give me the cake.","I want the cake.","Where is the cake?"],a:0,k:"拔高：待客礼貌用语",e:"解析：招呼客人用 Have some cake, please.（请吃些蛋糕吧），语气礼貌；其他三句都不适合待客。"},
{i:99,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,d:2,q:"“I don't like eggs.”的意思是？",o:["我不喜欢吃鸡蛋。","我喜欢吃鸡蛋。","我没有鸡蛋。","鸡蛋是给我的吗？"],a:0,k:"拔高：否定句 don't like",e:"解析：don't 是 do not 的缩写，表示否定，I don't like eggs. 即“我不喜欢吃鸡蛋”。"},
// ══════════ 三上·Unit 6 Happy birthday! 数字1-10与年龄 ══════════
{i:100,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“one”表示的数字是？",o:["1","2","3","4"],a:0,k:"数字：one",e:"解析：one 表示数字 1，如 one apple（一个苹果）。"},
{i:101,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“two”表示的数字是？",o:["2","6","4","8"],a:0,k:"数字：two",e:"解析：two 表示数字 2，如 two cats（两只猫）。"},
{i:102,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“three”表示的数字是？",o:["3","5","7","9"],a:0,k:"数字：three",e:"解析：three 表示数字 3，如 three books（三本书）。"},
{i:103,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“four”表示的数字是？",o:["4","5","6","7"],a:0,k:"数字：four",e:"解析：four 表示数字 4，如 four pens（四支笔）。"},
{i:104,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“five”表示的数字是？",o:["5","9","15","50"],a:0,k:"数字：five",e:"解析：five 表示数字 5，如 five fingers（五根手指）。"},
{i:105,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“six”表示的数字是？",o:["6","7","8","9"],a:0,k:"数字：six",e:"解析：six 表示数字 6，如 six eggs（六个鸡蛋）。"},
{i:106,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“seven”表示的数字是？",o:["7","6","9","11"],a:0,k:"数字：seven",e:"解析：seven 表示数字 7，如 seven days（七天）。"},
{i:107,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“eight”表示的数字是？",o:["8","7","9","10"],a:0,k:"数字：eight",e:"解析：eight 表示数字 8，注意拼写中有 gh 两个字母。"},
{i:108,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“nine”表示的数字是？",o:["9","19","5","7"],a:0,k:"数字：nine",e:"解析：nine 表示数字 9，注意拼写是 n-i-n-e，末尾是 e。"},
{i:109,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“ten”表示的数字是？",o:["10","2","12","20"],a:0,k:"数字：ten",e:"解析：ten 表示数字 10，如 ten fingers and ten toes。"},
{i:110,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"—How old are you?  —____",o:["I'm nine.","I'm fine.","My name is Lily.","I'm from China."],a:0,k:"句型：How old are you?",e:"解析：How old are you? 问的是年龄，用 I'm + 数字 回答；I'm fine 回答 How are you。"},
{i:111,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“Happy birthday!”的意思是？",o:["生日快乐！","新年快乐！","节日快乐！","身体健康！"],a:0,k:"句型：Happy birthday!",e:"解析：birthday 意为“生日”，Happy birthday! 用来祝贺他人生日快乐。"},
{i:112,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“How many books?”问的是？",o:["有多少本书","书在哪里","书是什么颜色","这是谁的书"],a:0,k:"句型：How many...?",e:"解析：How many 意为“多少”，后面接可数名词复数，用来问数量。"},
{i:113,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"数字 3 后面的一个数字是？",o:["four","two","six","five"],a:0,k:"数序：3 的后一个数",e:"解析：按顺序 one, two, three, four，3 后面是 4，即 four。"},
{i:114,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“五只小猫”用英语怎么说？",o:["five cats","five cat","fifth cats","five cat's"],a:0,k:"数量表达：five + 复数",e:"解析：数量大于一时名词用复数，所以是 five cats。"},
{i:115,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:1,q:"数字 7 的英语是 ____。",o:[],a:"seven",k:"填空：seven",e:"解析：数字 7 的英语是 seven，拼写为 s-e-v-e-n。"},
{i:116,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:1,q:"“生日快乐！”：Happy ____!",o:[],a:"birthday",k:"填空：birthday",e:"解析：“生日”的英语是 birthday，Happy birthday! 即“生日快乐！”。"},
{i:117,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,d:2,q:"Tom 今年 8 岁，明年他几岁？用英语说是？",o:["nine","eight","seven","ten"],a:0,k:"拔高：年龄推算 nine",e:"解析：今年 8 岁（eight），明年就是 9 岁，英语是 nine。"},
{i:118,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,d:2,q:"下面哪个数字最大？",o:["ten","one","five","three"],a:0,k:"拔高：数字大小比较",e:"解析：one=1, three=3, five=5, ten=10，其中 ten 最大。"},
{i:119,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,d:2,q:"朋友过生日，你送上礼物时应该说？",o:["Happy birthday! Here's a gift for you.","How old are you?","Give me a gift.","Good night!"],a:0,k:"拔高：生日祝贺情景",e:"解析：送生日礼物时应祝贺“生日快乐！”并说 Here's a gift for you.（这是给你的礼物）。"},
// ══════════ 三下·Unit 1 Welcome back to school! 国家与同学 ══════════
{i:120,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“China”的意思是？",o:["中国","加拿大","英国","美国"],a:0,k:"国家：China",e:"解析：China 意为“中国”，首字母必须大写。"},
{i:121,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“Canada”的意思是？",o:["加拿大","中国","美国","英国"],a:0,k:"国家：Canada",e:"解析：Canada 意为“加拿大”，位于北美洲。"},
{i:122,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“the UK”指的是哪个国家？",o:["英国","美国","加拿大","中国"],a:0,k:"国家：the UK",e:"解析：the UK 是 the United Kingdom 的缩写，指“英国”，前面通常要加 the。"},
{i:123,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“the USA”指的是哪个国家？",o:["美国","英国","加拿大","澳大利亚"],a:0,k:"国家：the USA",e:"解析：the USA 是 the United States of America 的缩写，指“美国”。"},
{i:124,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“student”的意思是？",o:["学生","老师","朋友","家长"],a:0,k:"人物：student",e:"解析：student 意为“学生”，也可用 pupil 表示小学生。"},
{i:125,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“pupil”的意思是？",o:["小学生","老师","校长","家长"],a:0,k:"人物：pupil",e:"解析：pupil 意为“小学生”，在英美学校中也常用来指“学生”。"},
{i:126,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“teacher”的意思是？",o:["老师","学生","同学","朋友"],a:0,k:"人物：teacher",e:"解析：teacher 意为“老师”，由 teach（教）+ -er（人）构成。"},
{i:127,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"—Where are you from?  —____",o:["I'm from China.","I'm nine.","My name is Amy.","I'm fine."],a:0,k:"句型：Where are you from?",e:"解析：Where are you from? 问“你来自哪里？”，用 I'm from + 国家 回答。"},
{i:128,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“This is my friend, Amy.”的意思是？",o:["这是我的朋友埃米。","我是埃米的朋友。","埃米有朋友。","埃米是我的老师。"],a:0,k:"句型：This is my friend",e:"解析：This is... 用来介绍他人，friend 意为“朋友”，整句是“这是我的朋友埃米”。"},
{i:129,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“He is my friend.”中的 he 指的是？",o:["男性（他）","女性（她）","动物（它）","我们"],a:0,k:"代词：he",e:"解析：he 指男性“他”；女性用 she，动物或事物用 it。"},
{i:130,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“Welcome back to school!”的意思是？",o:["欢迎回到学校！","欢迎来我家！","放学了！","谢谢老师！"],a:0,k:"句型：Welcome back to school!",e:"解析：welcome 意为“欢迎”，back 是“回来”，整句是开学时说的“欢迎回到学校！”。"},
{i:131,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“We have two new friends today.”的意思是？",o:["今天我们有两位新朋友。","我们明天有新朋友。","我们有两个好朋友。","今天我们要交朋友。"],a:0,k:"句型：We have... today",e:"解析：have 意为“有”，new friends 是“新朋友”，today 是“今天”。"},
{i:132,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"Amy 来自英国，可以说？",o:["She's from the UK.","He's from the UK.","I'm from the UK.","It's from the UK."],a:0,k:"句型运用：She's from...",e:"解析：Amy 是女性，用 she 指代，She's from the UK. 意为“她来自英国”。"},
{i:133,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"下列四个单词中，哪一个不是国家？",o:["apple","China","Canada","the USA"],a:0,k:"词汇辨别：国家与水果",e:"解析：apple 是“苹果”，属于水果；China、Canada、the USA 都是国家名称。"},
{i:134,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:1,q:"“中国”用英语说是 ____。",o:[],a:"China",k:"填空：China",e:"解析：“中国”的英语是 China，首字母必须大写。"},
{i:135,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:1,q:"“老师”用英语说是 ____。",o:[],a:"teacher",k:"填空：teacher",e:"解析：“老师”的英语是 teacher，由 teach + -er 构成。"},
{i:136,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,d:2,q:"关于国家名称的写法，下面说法正确的是？",o:["China、Canada 等国家名首字母要大写","国家名全部小写","国家名中间字母大写","国家名可以随意写大小写"],a:0,k:"拔高：国家名首字母大写",e:"解析：英语中专有名词（国家名、人名等）首字母必须大写，如 China、Canada、Amy。"},
{i:137,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,d:2,q:"—Where are you from?  —____  （你来自加拿大）",o:["I'm from Canada.","I'm in Canada.","I like Canada.","It's Canada."],a:0,k:"拔高：回答来自哪里",e:"解析：问“来自哪里”要用 be from 回答，I'm from Canada. 意为“我来自加拿大”。"},
{i:138,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,d:2,q:"介绍一位女同学 Amy 给大家，应该说？",o:["This is Amy. She's my friend.","This is Amy. He's my friend.","This is Amy. It's my friend.","This are Amy. She's my friend."],a:0,k:"拔高：介绍他人与代词一致",e:"解析：介绍单人用 This is...，Amy 是女性用 she；This are 搭配错误。"},
{i:139,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,d:2,q:"下面哪句用于询问对方来自哪个国家？",o:["Where are you from?","How old are you?","What's your name?","What colour is it?"],a:0,k:"拔高：辨别询问来源的句型",e:"解析：Where are you from? 问“你来自哪里”；How old 问年龄，What's your name 问姓名，What colour 问颜色。"},
// ══════════ 三下·Unit 2 My family 家庭成员 ══════════
{i:140,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“father”的意思是？",o:["父亲","母亲","兄弟","姐妹"],a:0,k:"家庭：father",e:"解析：father 意为“父亲”，口语中常说 dad。"},
{i:141,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“mother”的意思是？",o:["母亲","父亲","姐妹","祖母"],a:0,k:"家庭：mother",e:"解析：mother 意为“母亲”，口语中常说 mom。"},
{i:142,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“brother”的意思是？",o:["兄弟","姐妹","父亲","叔叔"],a:0,k:"家庭：brother",e:"解析：brother 意为“兄弟”，哥哥和弟弟都可以用 brother 表示。"},
{i:143,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“sister”的意思是？",o:["姐妹","兄弟","母亲","祖母"],a:0,k:"家庭：sister",e:"解析：sister 意为“姐妹”，姐姐和妹妹都可以用 sister 表示。"},
{i:144,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“grandfather”的意思是？",o:["祖父（爷爷/外公）","父亲","兄弟","叔叔"],a:0,k:"家庭：grandfather",e:"解析：grandfather 意为“祖父、外祖父”，口语中常说 grandpa。"},
{i:145,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“grandmother”的意思是？",o:["祖母（奶奶/外婆）","母亲","姐妹","阿姨"],a:0,k:"家庭：grandmother",e:"解析：grandmother 意为“祖母、外祖母”，口语中常说 grandma。"},
{i:146,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“family”的意思是？",o:["家庭","朋友","学校","房间"],a:0,k:"家庭：family",e:"解析：family 意为“家庭”，既可以指全家人，也可以指家庭这个整体。"},
{i:147,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“This is my family.”的意思是？",o:["这是我的家人。","我爱我的家。","我的家很大。","我要回家了。"],a:0,k:"句型：This is my family",e:"解析：This is... 用于介绍，family 指“家人、家庭”，整句是“这是我的家人”。"},
{i:148,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"—Who's that man?  —____",o:["He's my father.","She's my mother.","It's a dog.","Yes, he is."],a:0,k:"句型：Who's that man?",e:"解析：Who's that man? 问“那个男人是谁？”，man 是男性，用 He's... 回答。"},
{i:149,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"下列四个单词中，哪一个不是家庭成员？",o:["milk","father","mother","sister"],a:0,k:"词汇辨别：家庭成员",e:"解析：milk 是“牛奶”，属于食物；father、mother、sister 都是家庭成员。"},
{i:150,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"向同学介绍全家福照片，应该说？",o:["This is my family.","This is my school.","That is a photo.","I like photos."],a:0,k:"情景运用：介绍全家福",e:"解析：介绍家人时用 This is my family.（这是我的家人），再逐一介绍照片中的人。"},
{i:151,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“She is my sister.”中的 she 指的是？",o:["女性（她）","男性（他）","动物（它）","他们"],a:0,k:"代词：she",e:"解析：she 指女性“她”；男性用 he，动物或事物用 it。"},
{i:152,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"爸爸的爸爸，英语称为？",o:["grandfather","father","brother","uncle"],a:0,k:"亲属关系：grandfather",e:"解析：爸爸的爸爸是祖父，英语称 grandfather，口语中叫 grandpa。"},
{i:153,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“How many people are there in your family?”问的是？",o:["你家有几口人","你家在哪里","你家人叫什么","你家有几只宠物"],a:0,k:"句型：How many people",e:"解析：How many people 问的是人数，整句意为“你家有几口人？”。"},
{i:154,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:1,q:"“母亲”用英语说是 ____。",o:[],a:"mother",k:"填空：mother",e:"解析：“母亲”的英语是 mother，口语中常说 mom。"},
{i:155,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:1,q:"“家庭”用英语说是 ____。",o:[],a:"family",k:"填空：family",e:"解析：“家庭”的英语是 family，复数形式是 families。"},
{i:156,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,d:2,q:"My mother's mother is my ____.",o:["grandmother","mother","sister","aunt"],a:0,k:"拔高：亲属关系推理",e:"解析：妈妈的妈妈是外祖母，英语称 grandmother；mother's 表示“妈妈的”。"},
{i:157,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,d:2,q:"Tom is my father's son, but he is not me. Tom is my ____.",o:["brother","father","grandfather","friend"],a:0,k:"拔高：由关系推断称谓",e:"解析：爸爸的儿子不是“我”，那就只能是“我”的兄弟，即 brother。"},
{i:158,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,d:2,q:"介绍照片中的男人和女人，下面说法正确的是？",o:["This is my father. He's a teacher. This is my mother. She's a doctor.","This is my father. She's a teacher. This is my mother. He's a doctor.","This are my father. He's a teacher.","This is my father. He's a teacher. This is my mother. He's a doctor."],a:0,k:"拔高：介绍家人时代词搭配",e:"解析：father 是男性用 he，mother 是女性用 she；This are 搭配错误，应为 This is。"},
{i:159,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,d:2,q:"—Who's that woman?  —She's my ____.",o:["mother","father","brother","grandfather"],a:0,k:"拔高：由 man/woman 判断性别",e:"解析：woman 指女性，所以答语也要用女性亲属称谓，如 mother、sister、grandmother。"},
// ══════════ 三下·Unit 3 At the zoo 动物描述 ══════════
{i:160,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“fat”的意思是？",o:["胖的","瘦的","高的","矮的"],a:0,k:"形容词：fat",e:"解析：fat 意为“胖的”，反义词是 thin（瘦的）。"},
{i:161,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“thin”的意思是？",o:["瘦的","胖的","长的","短的"],a:0,k:"形容词：thin",e:"解析：thin 意为“瘦的”，反义词是 fat（胖的）。"},
{i:162,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“tall”的意思是？",o:["高的","矮的","大的","小的"],a:0,k:"形容词：tall",e:"解析：tall 意为“高的”，常用于描述人、动物或树的高度。"},
{i:163,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“short”的意思是？",o:["矮的；短的","高的","长的","胖的"],a:0,k:"形容词：short",e:"解析：short 既可以表示“矮的”，也可以表示“短的”，要根据句子判断。"},
{i:164,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“long”的意思是？",o:["长的","短的","高的","小的"],a:0,k:"形容词：long",e:"解析：long 意为“长的”，反义词是 short（短的）。"},
{i:165,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“small”的意思是？",o:["小的","大的","高的","胖的"],a:0,k:"形容词：small",e:"解析：small 意为“小的”，反义词是 big（大的）。"},
{i:166,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“big”的意思是？",o:["大的","小的","长的","瘦的"],a:0,k:"形容词：big",e:"解析：big 意为“大的”，反义词是 small（小的）。"},
{i:167,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“giraffe”的意思是？",o:["长颈鹿","大象","猴子","老虎"],a:0,k:"动物：giraffe",e:"解析：giraffe 意为“长颈鹿”，它的脖子特别长。"},
{i:168,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“It has a long neck.”的意思是？",o:["它有一个长脖子。","它有一条长尾巴。","它有长腿。","它有长鼻子。"],a:0,k:"句型：It has a long neck",e:"解析：has 是 have 的第三人称单数形式，neck 意为“脖子”，整句是“它有一个长脖子”。"},
{i:169,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“Look at that giraffe. It's so tall.”的意思是？",o:["看那只长颈鹿，它真高。","看那只长颈鹿，它真瘦。","看那只大象，它真大。","看那只猴子，它真小。"],a:0,k:"句型：It's so tall",e:"解析：Look at... 意为“看……”，so 表示“如此、真”，tall 是“高的”。"},
{i:170,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“fat”的反义词是？",o:["thin","tall","big","long"],a:0,k:"反义词：fat ↔ thin",e:"解析：fat 是“胖的”，反义词是 thin（瘦的）。"},
{i:171,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“tall”的反义词是？",o:["short","small","thin","long"],a:0,k:"反义词：tall ↔ short",e:"解析：tall 是“高的”，反义词是 short（矮的）。"},
{i:172,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"描述一头大象，下面哪句最合适？",o:["It's big and fat.","It's small and thin.","It's short and thin.","It's tall and thin."],a:0,k:"情景运用：描述大象",e:"解析：大象又大又重，用 big and fat 描述最贴切。"},
{i:173,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"下列四个单词中，哪一个不是形容词？",o:["elephant","tall","short","thin"],a:0,k:"词汇辨别：形容词",e:"解析：elephant 是名词“大象”；tall、short、thin 都是形容词。"},
{i:174,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:1,q:"“高的”用英语说是 ____。",o:[],a:"tall",k:"填空：tall",e:"解析：“高的”的英语是 tall，反义词是 short。"},
{i:175,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:1,q:"“小的”用英语说是 ____。",o:[],a:"small",k:"填空：small",e:"解析：“小的”的英语是 small，反义词是 big。"},
{i:176,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,d:2,q:"“long”的反义词是？",o:["short","tall","small","fat"],a:0,k:"拔高：反义词 long ↔ short",e:"解析：long 是“长的”，反义词是 short；注意 short 也可表示“矮的”，要根据语境判断。"},
{i:177,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,d:2,q:"“它又大又胖。”用英语说是？",o:["It's big and fat.","It's big and thin.","It's small and fat.","It's tall and short."],a:0,k:"拔高：两个形容词并列",e:"解析：两个形容词并列时用 and 连接，big and fat 即“又大又胖”。"},
{i:178,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,d:2,q:"比较两只动物：猫很小，长颈鹿很高。下面说法正确的是？",o:["The cat is small. The giraffe is tall.","The cat is tall. The giraffe is small.","The cat is small. The giraffe is small.","The cat is tall. The giraffe is tall."],a:0,k:"拔高：对比描述动物",e:"解析：猫体型小用 small，长颈鹿个子高用 tall，两者形成对比。"},
{i:179,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,d:2,q:"描述大象的长鼻子，应该用哪个句型？",o:["It has a long nose.","It is a long nose.","It have a long nose.","It has long nose a."],a:0,k:"拔高：It has + 身体特征",e:"解析：描述“它有什么”用 It has...；主语 It 是第三人称单数，要用 has 而不是 have。"},
// ══════════ 三下·Unit 4 Where is my car? 方位与文具 ══════════
{i:180,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“in”的意思是？",o:["在……里面","在……上面","在……下面","在……旁边"],a:0,k:"方位：in",e:"解析：in 表示“在……里面”，如 in the box（在盒子里）。"},
{i:181,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“on”的意思是？",o:["在……上面","在……里面","在……下面","在……后面"],a:0,k:"方位：on",e:"解析：on 表示“在……上面”，强调两者接触，如 on the desk（在桌上）。"},
{i:182,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“under”的意思是？",o:["在……下面","在……上面","在……里面","在……前面"],a:0,k:"方位：under",e:"解析：under 表示“在……下面”，如 under the chair（在椅子下面）。"},
{i:183,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“chair”的意思是？",o:["椅子","桌子","帽子","盒子"],a:0,k:"物品：chair",e:"解析：chair 意为“椅子”，常用短语 sit on the chair（坐在椅子上）。"},
{i:184,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“desk”的意思是？",o:["书桌","椅子","床","门"],a:0,k:"物品：desk",e:"解析：desk 意为“书桌、课桌”，是学习用的桌子。"},
{i:185,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“cap”的意思是？",o:["帽子","杯子","地图","小船"],a:0,k:"物品：cap",e:"解析：cap 意为“帽子”，通常指有帽舌的帽子，如棒球帽。"},
{i:186,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“ball”的意思是？",o:["球","小船","玩具","地图"],a:0,k:"物品：ball",e:"解析：ball 意为“球”，如 a football（一个足球）。"},
{i:187,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“boat”的意思是？",o:["小船","球","帽子","盒子"],a:0,k:"物品：boat",e:"解析：boat 意为“小船”，如 a toy boat（一只玩具船）。"},
{i:188,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“map”的意思是？",o:["地图","帽子","球","盒子"],a:0,k:"物品：map",e:"解析：map 意为“地图”，注意与 cap（帽子）拼写相近，要区分。"},
{i:189,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“toy”的意思是？",o:["玩具","小船","地图","球"],a:0,k:"物品：toy",e:"解析：toy 意为“玩具”，如 a toy car（一辆玩具小汽车）。"},
{i:190,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“box”的意思是？",o:["盒子","球","帽子","船只"],a:0,k:"物品：box",e:"解析：box 意为“盒子”，复数形式是 boxes。"},
{i:191,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"—Where is my car?  —____",o:["It's under the chair.","Yes, it is.","It's red.","I'm fine."],a:0,k:"句型：Where is...?",e:"解析：Where is...? 问“在哪里”，用 It's in/on/under... 回答；It's red. 回答的是颜色。"},
{i:192,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"—Is it in your bag?  —____",o:["Yes, it is.","Yes, it isn't.","Yes, I am.","Yes, it does."],a:0,k:"句型：Is it...? 的应答",e:"解析：Is it...? 的肯定回答是 Yes, it is.，否定回答是 No, it isn't.，肯定与否定不能混用。"},
{i:193,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"玩具在盒子里面，可以说？",o:["The toy is in the box.","The toy is on the box.","The toy is under the box.","The toy is a box."],a:0,k:"情景运用：in 表示在里面",e:"解析：在箱子里面用 in，The toy is in the box. 意为“玩具在盒子里”。"},
{i:194,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:1,q:"“在……下面”用英语说是 ____。",o:[],a:"under",k:"填空：under",e:"解析：“在……下面”的英语是 under，如 under the desk。"},
{i:195,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:1,q:"“帽子（有帽舌的）”用英语说是 ____。",o:[],a:"cap",k:"填空：cap",e:"解析：“帽子”的英语是 cap，注意与 map（地图）区分拼写。"},
{i:196,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,d:2,q:"球在桌子下面，用英语怎么说？",o:["The ball is under the desk.","The ball is on the desk.","The ball is in the desk.","The ball is the desk."],a:0,k:"拔高：方位介词辨析",e:"解析：“在桌子下面”用 under the desk；on 表示在上面，in 表示在里面。"},
{i:197,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,d:2,q:"—Is your cap on the bed?  —No, ____.",o:["it isn't","it is","I'm not","you aren't"],a:0,k:"拔高：一般疑问句否定回答",e:"解析：Is it...? 的否定回答是 No, it isn't.（不，它不在）。主语是 it，不能用 I 或 you 回答。"},
{i:198,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,d:2,q:"下列四个单词中，哪一个是介词（表示位置）？",o:["under","cap","ball","map"],a:0,k:"拔高：辨别方位介词",e:"解析：under 是表示位置的介词；cap、ball、map 都是名词。"},
{i:199,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,d:2,q:"找不到书包，问妈妈应该怎么说？",o:["Where is my bag, Mum?","Where is my cap, Mum?","Is this your bag, Mum?","This is my bag, Mum."],a:0,k:"拔高：找东西的情景问答",e:"解析：找不到东西问“在哪里”用 Where is...?；Is this your bag? 是问别人，This is my bag. 是陈述句。"},
// ══════════ 三下·Unit 5 Do you like pears? 水果 ══════════
{i:200,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“pear”的意思是？",o:["梨","苹果","橙子","香蕉"],a:0,k:"水果：pear",e:"解析：pear 意为“梨”，复数形式是 pears。"},
{i:201,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“apple”的意思是？",o:["苹果","梨","葡萄","西瓜"],a:0,k:"水果：apple",e:"解析：apple 意为“苹果”，一个苹果是 an apple。"},
{i:202,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“orange”作水果时意思是？",o:["橙子","苹果","香蕉","葡萄"],a:0,k:"水果：orange",e:"解析：orange 作名词时意为“橙子”，也可以表示“橙色”。"},
{i:203,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“banana”的意思是？",o:["香蕉","草莓","西瓜","梨"],a:0,k:"水果：banana",e:"解析：banana 意为“香蕉”，猴子特别喜欢吃。"},
{i:204,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“watermelon”的意思是？",o:["西瓜","草莓","葡萄","香蕉"],a:0,k:"水果：watermelon",e:"解析：watermelon 由 water（水）+ melon（瓜）构成，意为“西瓜”。"},
{i:205,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“strawberry”的意思是？",o:["草莓","葡萄","西瓜","橙子"],a:0,k:"水果：strawberry",e:"解析：strawberry 意为“草莓”，复数形式是 strawberries，要把 y 变 i 再加 es。"},
{i:206,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“grape”的意思是？",o:["葡萄","草莓","梨","橙子"],a:0,k:"水果：grape",e:"解析：grape 意为“葡萄”，通常成串生长，说“一串葡萄”用 a bunch of grapes。"},
{i:207,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"—Do you like pears?  —____",o:["Yes, I do.","Yes, I am.","Yes, I like.","Yes, it is."],a:0,k:"句型：Do you like...? 的应答",e:"解析：Do you like...? 的肯定回答是 Yes, I do.，否定回答是 No, I don't.；不能用 am 或 is 回答。"},
{i:208,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“I like apples.”和“I don't like apples.”的区别是？",o:["前者表示喜欢，后者表示不喜欢","两句意思相同","前者表示不喜欢","后者表示想吃"],a:0,k:"句型：like 与 don't like",e:"解析：don't 表示否定，I don't like apples. 即“我不喜欢苹果”，与 I like apples. 意思相反。"},
{i:209,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“Have some fruits.”的意思是？",o:["吃些水果吧。","买些水果吧。","种些水果吧。","水果好吃。"],a:0,k:"句型：Have some fruits",e:"解析：Have some... 是招呼别人吃或喝的礼貌说法，fruits 是 fruit 的复数。"},
{i:210,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"请客人吃水果，你可以说？",o:["Have some fruits, please.","Give me the fruits.","I want fruits.","Where are the fruits?"],a:0,k:"情景运用：请客吃水果",e:"解析：招呼客人用 Have some fruits, please.（请吃些水果吧），语气礼貌。"},
{i:211,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“三个梨”用英语怎么说？",o:["three pears","three pear","third pears","three pear's"],a:0,k:"数量表达：three pears",e:"解析：数量大于一时名词要用复数，pear 的复数是 pears。"},
{i:212,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"下列四个单词中，哪一个不是水果？",o:["bread","pear","apple","grape"],a:0,k:"词汇辨别：水果与食物",e:"解析：bread 是“面包”，属于主食；pear、apple、grape 都是水果。"},
{i:213,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"—Do you like oranges?  —No, ____.",o:["I don't","I do","I'm not","it isn't"],a:0,k:"情景运用：表示不喜欢",e:"解析：Do you like...? 的否定回答是 No, I don't.；主语是 I，不能用 it 回答。"},
{i:214,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:1,q:"“苹果”用英语说是 ____。",o:[],a:"apple",k:"填空：apple",e:"解析：“苹果”的英语是 apple，一个苹果是 an apple。"},
{i:215,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:1,q:"“香蕉”用英语说是 ____。",o:[],a:"banana",k:"填空：banana",e:"解析：“香蕉”的英语是 banana，复数形式是 bananas。"},
{i:216,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,d:2,q:"“草莓”的复数形式是？",o:["strawberries","strawberrys","strawberryes","strawberry"],a:0,k:"拔高：以 y 结尾的复数变化",e:"解析：strawberry 以“辅音字母 + y”结尾，变复数时先把 y 变 i，再加 -es，即 strawberries。"},
{i:217,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,d:2,q:"想问对方喜不喜欢吃葡萄，应该说？",o:["Do you like grapes?","Do you like grape?","You like grapes?","Are you like grapes?"],a:0,k:"拔高：征求意见的句型",e:"解析：问对方喜好用 Do you like...?，葡萄通常以复数形式出现，所以是 Do you like grapes?"},
{i:218,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,d:2,q:"“我不喜欢吃西瓜。”用英语说是？",o:["I don't like watermelons.","I like watermelons.","I don't watermelons.","I not like watermelons."],a:0,k:"拔高：否定句的构成",e:"解析：一般现在时的否定句要用 don't + 动词原形，即 I don't like...；不能说 I not like。"},
{i:219,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,d:2,q:"在水果店里想买香蕉，可以对店员说？",o:["I'd like some bananas.","I don't like bananas.","Bananas are yellow.","Where are bananas?"],a:0,k:"拔高：购物时的表达",e:"解析：想买某样东西用 I'd like some...，意为“我想要一些……”，语气礼貌。"},
// ══════════ 三下·Unit 6 How many? 数字11-20 ══════════
{i:220,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“eleven”表示的数字是？",o:["11","12","20","10"],a:0,k:"数字：eleven",e:"解析：eleven 表示数字 11，注意不要与 twelve（12）混淆。"},
{i:221,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“twelve”表示的数字是？",o:["12","11","20","2"],a:0,k:"数字：twelve",e:"解析：twelve 表示数字 12，拼写是 t-w-e-l-v-e。"},
{i:222,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“thirteen”表示的数字是？",o:["13","30","3","15"],a:0,k:"数字：thirteen",e:"解析：thirteen 表示数字 13，由 three 变化而来，注意 -teen 后缀。"},
{i:223,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“fourteen”表示的数字是？",o:["14","40","4","24"],a:0,k:"数字：fourteen",e:"解析：fourteen 表示数字 14，由 four + -teen 构成。"},
{i:224,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“fifteen”表示的数字是？",o:["15","50","5","25"],a:0,k:"数字：fifteen",e:"解析：fifteen 表示数字 15，由 five 变成 fif- 后加 -teen，不是 fiveteen。"},
{i:225,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“sixteen”表示的数字是？",o:["16","60","6","26"],a:0,k:"数字：sixteen",e:"解析：sixteen 表示数字 16，由 six + -teen 构成。"},
{i:226,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“seventeen”表示的数字是？",o:["17","70","7","27"],a:0,k:"数字：seventeen",e:"解析：seventeen 表示数字 17，由 seven + -teen 构成。"},
{i:227,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“eighteen”表示的数字是？",o:["18","80","8","28"],a:0,k:"数字：eighteen",e:"解析：eighteen 表示数字 18，由 eight + -teen 构成，注意只有一个 t。"},
{i:228,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“nineteen”表示的数字是？",o:["19","90","9","29"],a:0,k:"数字：nineteen",e:"解析：nineteen 表示数字 19，由 nine + -teen 构成，拼写时去掉了 e。"},
{i:229,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“twenty”表示的数字是？",o:["20","12","2","21"],a:0,k:"数字：twenty",e:"解析：twenty 表示数字 20，注意拼写是 t-w-e-n-t-y。"},
{i:230,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"—How many kites?  —____",o:["Twelve.","Yes, twelve.","It's twelve.","Twelve kites it."],a:0,k:"句型：How many 的应答",e:"解析：How many...? 问数量，直接回答数字即可，如 Twelve.（十二个）。"},
{i:231,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“How many books?”中的 books 为什么用复数？",o:["因为数量通常不止一本，可数名词表复数用复数形式","因为 books 是固定搭配","因为 book 没有单数形式","因为问句都要用复数"],a:0,k:"语法：How many + 复数名词",e:"解析：How many 后面接可数名词的复数形式，所以用 books 而不是 book。"},
{i:232,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“十一本书”用英语怎么说？",o:["eleven books","eleven book","eleventh books","eleven book's"],a:0,k:"数量表达：eleven books",e:"解析：数量大于一时名词用复数，所以是 eleven books。"},
{i:233,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"下列四个单词中，哪一个不是数字？",o:["kite","eleven","twelve","twenty"],a:0,k:"词汇辨别：数字与物品",e:"解析：kite 是“风筝”，不是数字；eleven、twelve、twenty 分别表示 11、12、20。"},
{i:234,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:1,q:"数字 12 的英语是 ____。",o:[],a:"twelve",k:"填空：twelve",e:"解析：数字 12 的英语是 twelve，拼写为 t-w-e-l-v-e。"},
{i:235,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:1,q:"数字 20 的英语是 ____。",o:[],a:"twenty",k:"填空：twenty",e:"解析：数字 20 的英语是 twenty，拼写为 t-w-e-n-t-y。"},
{i:236,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,d:2,q:"数字 15 后面的一个数字是？",o:["sixteen","fourteen","fifty","fifteen"],a:0,k:"拔高：11~20 的数序",e:"解析：按顺序 fourteen, fifteen, sixteen，15（fifteen）后面是 16（sixteen）。"},
{i:237,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,d:2,q:"数一数：桌上有 13 支铅笔，还想再拿 7 支，一共多少支？",o:["twenty","eighteen","seventeen","thirteen"],a:0,k:"拔高：数量相加 twenty",e:"解析：13 + 7 = 20，英语是 twenty。"},
{i:238,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,d:2,q:"下列选项中，哪个数字最大？",o:["nineteen","eleven","fifteen","twelve"],a:0,k:"拔高：11~20 大小比较",e:"解析：eleven=11, twelve=12, fifteen=15, nineteen=19，其中 nineteen 最大。"},
{i:239,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,d:2,q:"“11 加 4 等于 15。”用英语怎么说？",o:["Eleven and four is fifteen.","Eleven and four is fifty.","Eleven and five is fifteen.","Eleven and four are fifteen."],a:0,k:"拔高：简单加法表达",e:"解析：11 + 4 = 15，英语中说 Eleven and four is fifteen.，主语视为整体时用 is。"},
{i:240,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,d:2,q:"下面哪种情况最应该说“Good afternoon.”？",o:["下午三点在学校见到同学","晚上睡觉前","早上起床后","和别人分别时"],a:0,k:"拔高：按时间选择问候语",e:"解析：Good afternoon. 用于中午到傍晚之间；早上用 Good morning.，睡前用 Good night.，分别时用 Goodbye."},
{i:241,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,d:2,q:"把蓝色和黄色调在一起，会变成什么颜色？",o:["绿色","橙色","紫色","棕色"],a:0,k:"拔高：蓝黄调色",e:"解析：蓝（blue）+ 黄（yellow）调在一起是绿（green）；红+黄是橙，红+蓝是紫。"},
{i:242,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,d:2,q:"“It is small. It can fly.”描述的是哪种动物？",o:["bird","elephant","pig","bear"],a:0,k:"拔高：由能力特征推断动物",e:"解析：fly 意为“飞”，又小又会飞的动物是鸟（bird）；大象、猪、熊都不会飞。"},
{i:243,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,d:2,q:"人有十根手指，用英语说“十”是？",o:["ten","two","five","nine"],a:0,k:"拔高：数手指说 ten",e:"解析：十根手指的“十”是 ten；两只手一共十个手指，即 ten fingers。"}
);
