if(!global.QA)global.QA={};
if(!QA["3en"])QA["3en"]=[];
QA["3en"].push(
{i:0,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"“Hello!”的中文意思是？",o:["你好！","再见！","谢谢！","对不起！"],a:0,k:"打招呼：Hello",e:"解析：Hello! 是英语中最常用的打招呼用语，意思是'你好！'。"},
{i:1,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"你想介绍自己叫 Tom，应说？",o:["I'm Tom.","You are Tom.","He is Tom.","This is Tom."],a:0,k:"自我介绍：I'm = I am",e:"解析：I'm 是 I am 的缩写，意思是'我是……'，用于自我介绍，I'm Tom. 即'我是 Tom'。"},
{i:2,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"早上在学校见到老师，你会说？",o:["Good morning.","Good night.","Good evening.","Good job."],a:0,k:"问候：Good morning",e:"解析：Good morning. 是'早上好'，用于上午见面时的问候。"},
{i:3,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"“Goodbye!”的意思是？",o:["你好！","再见！","谢谢！","对不起！"],a:1,k:"告别：Goodbye",e:"解析：Goodbye! 是告别用语，意思是'再见！'，也可说 Bye!"},
{i:4,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"别人问“What's your name?”，你应该回答？",o:["My name is Lily.","I'm fine.","Thank you.","Good morning."],a:0,k:"问姓名：What's your name?",e:"解析：What's your name? 问'你叫什么名字？'，常用 My name is... 或 I'm... 来回答。"},
{i:5,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"下列物品中，哪一个不是文具？",o:["apple","pen","book","ruler"],a:0,k:"词汇：文具与水果",e:"解析：apple 是'苹果'（水果），pen（钢笔）、book（书）、ruler（尺子）都是文具。"},
{i:6,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"“Hi!”和下面哪句话意思相近？",o:["Hello!","Bye!","Sorry!","Thanks!"],a:0,k:"打招呼：Hi",e:"解析：Hi! 和 Hello! 都表示'你好！'，是熟人之间常用的打招呼方式。"},
{i:7,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:1,q:"“你好！”用英语说是 ____。",o:[],a:"Hello",k:"打招呼：Hello",e:"解析：'你好！'的英语是 Hello，熟人之间也可以说 Hi。"},
{i:8,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:1,q:"I'm 是 I ____ 的缩写，用来介绍自己。",o:[],a:"am",k:"缩写：I'm = I am",e:"解析：I'm 是 I am 的缩写，am 与 I 搭配，表示'我是'。"},
{i:9,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"你想向新朋友介绍自己，可以说？",o:["Hello, I'm Mike.","Hello, you are Mike.","Goodbye, Mike.","What's Mike?"],a:0,k:"自我介绍",e:"解析：Hello, I'm Mike. 意思是'你好，我是 Mike'，用于向别人介绍自己。"},
{i:10,c:"3en-1",ch:"三上·Unit 1 Hello! 打招呼与问候",f:0,q:"“eraser”的意思是？",o:["橡皮","尺子","铅笔","书包"],a:0,k:"文具：eraser",e:"解析：eraser 是'橡皮'，用来擦掉铅笔字。"},

{i:11,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“红色”用英语说是？",o:["red","yellow","blue","green"],a:0,k:"颜色：red",e:"解析：red 表示'红色'。"},
{i:12,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"下面哪个单词表示“蓝色”？",o:["blue","black","brown","green"],a:0,k:"颜色：blue",e:"解析：blue 表示'蓝色'。"},
{i:13,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“yellow”的意思是？",o:["黄色","绿色","红色","蓝色"],a:0,k:"颜色：yellow",e:"解析：yellow 表示'黄色'，如 yellow banana（黄色的香蕉）。"},
{i:14,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“green”的意思是？",o:["绿色","蓝色","黄色","紫色"],a:0,k:"颜色：green",e:"解析：green 表示'绿色'，如 green tree（绿树）。"},
{i:15,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“black”的意思是？",o:["黑色","白色","棕色","粉色"],a:0,k:"颜色：black",e:"解析：black 表示'黑色'。"},
{i:16,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“orange”表示什么颜色？",o:["橙色","棕色","紫色","灰色"],a:0,k:"颜色：orange",e:"解析：orange 本义是'橙子'，也用来表示'橙色'。"},
{i:17,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"下列哪个是“白色”的正确拼写？",o:["white","wihte","whtie","with"],a:0,k:"拼写：white",e:"解析：white 正确拼写为 w-h-i-t-e，意思是'白色'。"},
{i:18,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:0,q:"“brown”的意思是？",o:["棕色","黑色","蓝色","绿色"],a:0,k:"颜色：brown",e:"解析：brown 表示'棕色/褐色'。"},
{i:19,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:1,q:"“蓝色”用英语说是 ____。",o:[],a:"blue",k:"颜色：blue",e:"解析：'蓝色'的英语是 blue。"},
{i:20,c:"3en-2",ch:"三上·Unit 2 Colours 颜色",f:1,q:"彩虹中红色后面通常是 ____（橙色）。",o:[],a:"orange",k:"颜色：orange",e:"解析：orange 表示'橙色'，彩虹颜色顺序中红色之后常为橙色。"},

{i:21,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“eye”的意思是？",o:["眼睛","耳朵","鼻子","嘴巴"],a:0,k:"身体：eye",e:"解析：eye 表示'眼睛'。"},
{i:22,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“nose”的意思是？",o:["鼻子","嘴巴","脸","头"],a:0,k:"身体：nose",e:"解析：nose 表示'鼻子'。"},
{i:23,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“mouth”的意思是？",o:["嘴巴","手","脚","腿"],a:0,k:"身体：mouth",e:"解析：mouth 表示'嘴巴'。"},
{i:24,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“ear”的意思是？",o:["耳朵","眼睛","手臂","头"],a:0,k:"身体：ear",e:"解析：ear 表示'耳朵'。"},
{i:25,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“hand”的意思是？",o:["手","脚","腿","身体"],a:0,k:"身体：hand",e:"解析：hand 表示'手'。"},
{i:26,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“head”的意思是？",o:["头","脸","眼睛","手臂"],a:0,k:"身体：head",e:"解析：head 表示'头'。"},
{i:27,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"你想让别人看你的脸，应说？",o:["Look at my face.","Look at my hand.","Touch your face.","This is my face."],a:0,k:"句型：Look at...",e:"解析：Look at my face. 意思是'看我的脸'，face 是'脸'。"},
{i:28,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:0,q:"“foot”的意思是？",o:["脚","腿","手","身体"],a:0,k:"身体：foot",e:"解析：foot 表示'脚'，复数形式是 feet。"},
{i:29,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:1,q:"“眼睛”用英语说是 ____。",o:[],a:"eye",k:"身体：eye",e:"解析：'眼睛'的英语是 eye。"},
{i:30,c:"3en-3",ch:"三上·Unit 3 Look at me! 五官与身体",f:1,q:"This is my ____ .（鼻子）",o:[],a:"nose",k:"身体：nose",e:"解析：nose 表示'鼻子'，This is my nose. 意思是'这是我的鼻子'。"},

{i:31,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“cat”的意思是？",o:["猫","狗","鸟","猪"],a:0,k:"动物：cat",e:"解析：cat 表示'猫'。"},
{i:32,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“dog”的意思是？",o:["狗","猫","鸭子","熊"],a:0,k:"动物：dog",e:"解析：dog 表示'狗'。"},
{i:33,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“panda”的意思是？",o:["熊猫","老虎","大象","猴子"],a:0,k:"动物：panda",e:"解析：panda 表示'熊猫'，是中国的国宝动物。"},
{i:34,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“bird”的意思是？",o:["鸟","猫","猪","兔子"],a:0,k:"动物：bird",e:"解析：bird 表示'鸟'。"},
{i:35,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“elephant”的意思是？",o:["大象","老虎","熊","鸭子"],a:0,k:"动物：elephant",e:"解析：elephant 表示'大象'。"},
{i:36,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“monkey”的意思是？",o:["猴子","熊猫","兔子","猪"],a:0,k:"动物：monkey",e:"解析：monkey 表示'猴子'。"},
{i:37,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"你有一只狗，你会说？",o:["I have a dog.","I am a dog.","This is dog.","I like dog."],a:0,k:"句型：I have a...",e:"解析：I have a dog. 意思是'我有一只狗'，have 表示'有'。"},
{i:38,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"别人问“What's this?”，你回答是只猫，应说？",o:["It's a cat.","This is cat.","I have a cat.","Cat is it."],a:0,k:"句型：What's this? — It's a...",e:"解析：What's this? 问'这是什么？'，回答用 It's a/an...，所以是 It's a cat.（这是一只猫）。"},
{i:39,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“tiger”的意思是？",o:["老虎","大象","熊猫","鸟"],a:0,k:"动物：tiger",e:"解析：tiger 表示'老虎'。"},
{i:40,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:0,q:"“rabbit”的意思是？",o:["兔子","鸭子","猪","熊"],a:0,k:"动物：rabbit",e:"解析：rabbit 表示'兔子'。"},
{i:41,c:"3en-4",ch:"三上·Unit 4 We love animals 动物",f:1,q:"“熊猫”用英语说是 ____。",o:[],a:"panda",k:"动物：panda",e:"解析：'熊猫'的英语是 panda。"},

{i:42,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“egg”的意思是？",o:["鸡蛋","面包","牛奶","蛋糕"],a:0,k:"食物：egg",e:"解析：egg 表示'鸡蛋'。"},
{i:43,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“bread”的意思是？",o:["面包","米饭","水","果汁"],a:0,k:"食物：bread",e:"解析：bread 表示'面包'。"},
{i:44,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“milk”的意思是？",o:["牛奶","水","果汁","茶"],a:0,k:"食物：milk",e:"解析：milk 表示'牛奶'。"},
{i:45,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“juice”的意思是？",o:["果汁","牛奶","水","咖啡"],a:0,k:"食物：juice",e:"解析：juice 表示'果汁'。"},
{i:46,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“cake”的意思是？",o:["蛋糕","鸡蛋","面包","米饭"],a:0,k:"食物：cake",e:"解析：cake 表示'蛋糕'。"},
{i:47,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“rice”的意思是？",o:["米饭","面条","面包","肉"],a:0,k:"食物：rice",e:"解析：rice 表示'米饭'。"},
{i:48,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“water”的意思是？",o:["水","牛奶","果汁","茶"],a:0,k:"食物：water",e:"解析：water 表示'水'。"},
{i:49,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“apple”的意思是？",o:["苹果","香蕉","橙子","梨"],a:0,k:"食物：apple",e:"解析：apple 表示'苹果'。"},
{i:50,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"你想吃点蛋糕，会说？",o:["I'd like some cake.","I have a cake.","This is cake.","I am cake."],a:0,k:"句型：I'd like some...",e:"解析：I'd like some cake. 意思是'我想要一些蛋糕'，I'd like = I would like（我想要）。"},
{i:51,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:0,q:"“banana”的意思是？",o:["香蕉","苹果","葡萄","橙子"],a:0,k:"食物：banana",e:"解析：banana 表示'香蕉'。"},
{i:52,c:"3en-5",ch:"三上·Unit 5 Let's eat! 食物",f:1,q:"“牛奶”用英语说是 ____。",o:[],a:"milk",k:"食物：milk",e:"解析：'牛奶'的英语是 milk。"},

{i:53,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“one”的意思是？",o:["一","二","三","十"],a:0,k:"数字：one",e:"解析：one 表示数字'一'。"},
{i:54,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“three”的意思是？",o:["三","二","四","五"],a:0,k:"数字：three",e:"解析：three 表示数字'三'。"},
{i:55,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“five”的意思是？",o:["五","四","六","七"],a:0,k:"数字：five",e:"解析：five 表示数字'五'。"},
{i:56,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“ten”的意思是？",o:["十","九","八","七"],a:0,k:"数字：ten",e:"解析：ten 表示数字'十'。"},
{i:57,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“seven”的意思是？",o:["七","六","八","九"],a:0,k:"数字：seven",e:"解析：seven 表示数字'七'。"},
{i:58,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"别人问“How old are you?”，你7岁，应回答？",o:["I'm seven.","I'm six.","I'm ten.","I'm five."],a:0,k:"问年龄：How old are you?",e:"解析：How old are you? 问'你几岁了？'，7岁回答 I'm seven.（我七岁）。"},
{i:59,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“Happy birthday!”的意思是？",o:["生日快乐！","新年好！","恭喜！","你好！"],a:0,k:"祝福：Happy birthday",e:"解析：Happy birthday! 是'生日快乐！'的祝福语。"},
{i:60,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“two”的意思是？",o:["二","一","三","四"],a:0,k:"数字：two",e:"解析：two 表示数字'二'。"},
{i:61,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:0,q:"“eight”的意思是？",o:["八","七","九","六"],a:0,k:"数字：eight",e:"解析：eight 表示数字'八'。"},
{i:62,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:1,q:"“六”用英语说是 ____。",o:[],a:"six",k:"数字：six",e:"解析：数字'六'的英语是 six。"},
{i:63,c:"3en-6",ch:"三上·Unit 6 Happy birthday! 数字1-10与年龄",f:1,q:"你八岁，用英语说：I'm ____ .",o:[],a:"eight",k:"数字/年龄：eight",e:"解析：eight 表示'八'，I'm eight. 意思是'我八岁'。"},

{i:64,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“China”的意思是？",o:["中国","美国","英国","加拿大"],a:0,k:"国家：China",e:"解析：China 表示'中国'。"},
{i:65,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“USA”的意思是？",o:["美国","英国","中国","日本"],a:0,k:"国家：USA",e:"解析：USA 是 the United States of America 的缩写，表示'美国'。"},
{i:66,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“UK”的意思是？",o:["英国","美国","中国","加拿大"],a:0,k:"国家：UK",e:"解析：UK 是 the United Kingdom 的缩写，表示'英国'。"},
{i:67,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“Canada”的意思是？",o:["加拿大","中国","英国","美国"],a:0,k:"国家：Canada",e:"解析：Canada 表示'加拿大'。"},
{i:68,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“teacher”的意思是？",o:["老师","学生","朋友","医生"],a:0,k:"人物：teacher",e:"解析：teacher 表示'老师'。"},
{i:69,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“student”的意思是？",o:["学生","老师","朋友","工人"],a:0,k:"人物：student",e:"解析：student 表示'学生'。"},
{i:70,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"介绍女孩 Amy，她是个学生，应说？",o:["This is Amy. She's a student.","This is Amy. He's a student.","Amy is a teacher.","She is a teacher."],a:0,k:"句型：This is... She's...",e:"解析：介绍别人用 This is...；Amy 是女孩用 she（她），所以是 This is Amy. She's a student."},
{i:71,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"介绍男孩 Tom，应说？",o:["This is Tom. He's a boy.","This is Tom. She's a girl.","Tom is a girl.","He is Amy."],a:0,k:"句型：This is... He's...",e:"解析：Tom 是男孩用 he（他），所以是 This is Tom. He's a boy."},
{i:72,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:0,q:"“friend”的意思是？",o:["朋友","老师","学生","同学"],a:0,k:"人物：friend",e:"解析：friend 表示'朋友'。"},
{i:73,c:"3en-7",ch:"三下·Unit 1 Welcome back to school! 国家与同学",f:1,q:"“中国”用英语说是 ____。",o:[],a:"China",k:"国家：China",e:"解析：'中国'的英语是 China。"},

{i:74,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“father”的意思是？",o:["父亲/爸爸","母亲/妈妈","兄弟","姐妹"],a:0,k:"家庭：father",e:"解析：father 表示'父亲/爸爸'，口语常说 dad。"},
{i:75,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“mother”的意思是？",o:["母亲/妈妈","父亲/爸爸","爷爷","奶奶"],a:0,k:"家庭：mother",e:"解析：mother 表示'母亲/妈妈'，口语常说 mum。"},
{i:76,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“grandfather”的意思是？",o:["祖父/爷爷","祖母/奶奶","父亲","母亲"],a:0,k:"家庭：grandfather",e:"解析：grandfather 表示'祖父/爷爷'，口语常说 grandpa。"},
{i:77,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“grandmother”的意思是？",o:["祖母/奶奶","祖父/爷爷","母亲","父亲"],a:0,k:"家庭：grandmother",e:"解析：grandmother 表示'祖母/奶奶'，口语常说 grandma。"},
{i:78,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“brother”的意思是？",o:["兄弟","姐妹","父亲","母亲"],a:0,k:"家庭：brother",e:"解析：brother 表示'兄弟（哥哥/弟弟）'。"},
{i:79,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“sister”的意思是？",o:["姐妹","兄弟","奶奶","爷爷"],a:0,k:"家庭：sister",e:"解析：sister 表示'姐妹（姐姐/妹妹）'。"},
{i:80,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"别人问“Who's that man?”，那是你爸爸，应说？",o:["He's my father.","She's my mother.","He's my brother.","She's my sister."],a:0,k:"句型：Who's that man? — He's...",e:"解析：man 是'男人'，爸爸是男性用 he，所以是 He's my father.（他是我的爸爸）。"},
{i:81,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"别人问“Who's that woman?”，那是你妈妈，应说？",o:["She's my mother.","He's my father.","She's my sister.","He's my brother."],a:0,k:"句型：Who's that woman? — She's...",e:"解析：woman 是'女人'，妈妈是女性用 she，所以是 She's my mother.（她是我的妈妈）。"},
{i:82,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:0,q:"“family”的意思是？",o:["家庭","学校","朋友","班级"],a:0,k:"家庭：family",e:"解析：family 表示'家庭'。"},
{i:83,c:"3en-8",ch:"三下·Unit 2 My family 家庭成员",f:1,q:"“妈妈”用英语说是 ____（mother/mum）。",o:[],a:"mother",k:"家庭：mother",e:"解析：'妈妈'的英语是 mother，口语常说 mum。"},

{i:84,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“big”的意思是？",o:["大的","小的","长的","短的"],a:0,k:"形容：big",e:"解析：big 表示'大的'。"},
{i:85,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“small”的意思是？",o:["小的","大的","高的","矮的"],a:0,k:"形容：small",e:"解析：small 表示'小的'。"},
{i:86,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“tall”的意思是？",o:["高的","矮的","胖的","瘦的"],a:0,k:"形容：tall",e:"解析：tall 表示'高的'（形容人或长颈鹿等）。"},
{i:87,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“short”的意思是？",o:["矮的/短的","高的","长的","大的"],a:0,k:"形容：short",e:"解析：short 表示'矮的'或'短的'。"},
{i:88,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“fat”的意思是？",o:["胖的","瘦的","高的","矮的"],a:0,k:"形容：fat",e:"解析：fat 表示'胖的'。"},
{i:89,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“thin”的意思是？",o:["瘦的","胖的","高的","矮的"],a:0,k:"形容：thin",e:"解析：thin 表示'瘦的'。"},
{i:90,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“long”的意思是？",o:["长的","短的","高的","矮的"],a:0,k:"形容：long",e:"解析：long 表示'长的'。"},
{i:91,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"“giraffe”的意思是？",o:["长颈鹿","大象","熊","猴子"],a:0,k:"动物：giraffe",e:"解析：giraffe 表示'长颈鹿'。"},
{i:92,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:0,q:"描述长颈鹿很高，应说？",o:["It's so tall.","It's so small.","It's fat.","It's short."],a:0,k:"句型：It's so tall.",e:"解析：长颈鹿很高，用 tall（高的），It's so tall. 意思是'它真高'。"},
{i:93,c:"3en-9",ch:"三下·Unit 3 At the zoo 动物描述",f:1,q:"“大象”用英语说是 ____。",o:[],a:"elephant",k:"动物：elephant",e:"解析：'大象'的英语是 elephant。"},

{i:94,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“in”的意思是？",o:["在……里面","在……上面","在……下面","在……旁边"],a:0,k:"方位：in",e:"解析：in 表示'在……里面'。"},
{i:95,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“on”的意思是？",o:["在……上面","在……里面","在……下面","在……后面"],a:0,k:"方位：on",e:"解析：on 表示'在……上面'。"},
{i:96,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“under”的意思是？",o:["在……下面","在……上面","在……里面","在……前面"],a:0,k:"方位：under",e:"解析：under 表示'在……下面'。"},
{i:97,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“desk”的意思是？",o:["书桌","椅子","床","门"],a:0,k:"物品：desk",e:"解析：desk 表示'书桌'。"},
{i:98,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“chair”的意思是？",o:["椅子","书桌","桌子","沙发"],a:0,k:"物品：chair",e:"解析：chair 表示'椅子'。"},
{i:99,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“car”的意思是？",o:["小汽车","船","飞机","公交车"],a:0,k:"物品：car",e:"解析：car 表示'小汽车'。"},
{i:100,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“boat”的意思是？",o:["小船","汽车","飞机","火车"],a:0,k:"物品：boat",e:"解析：boat 表示'小船'。"},
{i:101,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"书在桌子下面，应说？",o:["The book is under the desk.","The book is on the desk.","The book is in the desk.","The book is the desk."],a:0,k:"句型：方位介词",e:"解析：'在……下面'用 under，所以是 The book is under the desk."},
{i:102,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“cap”的意思是？",o:["帽子","地图","盒子","玩具"],a:0,k:"物品：cap",e:"解析：cap 表示'帽子'。"},
{i:103,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:0,q:"“map”的意思是？",o:["地图","帽子","球","盒子"],a:0,k:"物品：map",e:"解析：map 表示'地图'。"},
{i:104,c:"3en-10",ch:"三下·Unit 4 Where is my car? 方位与文具",f:1,q:"“在……里面”用英语说是 ____。",o:[],a:"in",k:"方位：in",e:"解析：'在……里面'的英语是 in。"},

{i:105,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“pear”的意思是？",o:["梨","苹果","香蕉","橙子"],a:0,k:"水果：pear",e:"解析：pear 表示'梨'。"},
{i:106,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“apple”的意思是？",o:["苹果","梨","葡萄","西瓜"],a:0,k:"水果：apple",e:"解析：apple 表示'苹果'。"},
{i:107,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“banana”的意思是？",o:["香蕉","橘子","梨","桃"],a:0,k:"水果：banana",e:"解析：banana 表示'香蕉'。"},
{i:108,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“orange”的意思是？",o:["橙子/橘子","苹果","西瓜","草莓"],a:0,k:"水果：orange",e:"解析：orange 表示'橙子/橘子'。"},
{i:109,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“watermelon”的意思是？",o:["西瓜","草莓","葡萄","梨"],a:0,k:"水果：watermelon",e:"解析：watermelon 表示'西瓜'，由 water（水）+ melon（瓜）组成。"},
{i:110,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“grape”的意思是？",o:["葡萄","香蕉","苹果","橙子"],a:0,k:"水果：grape",e:"解析：grape 表示'葡萄'。"},
{i:111,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"“strawberry”的意思是？",o:["草莓","西瓜","梨","橙子"],a:0,k:"水果：strawberry",e:"解析：strawberry 表示'草莓'。"},
{i:112,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"别人问“Do you like apples?”，你喜欢，应回答？",o:["Yes, I do.","No, I don't.","Yes, I am.","No, I am."],a:0,k:"句型：Do you like...? — Yes, I do.",e:"解析：Do you like...? 问'你喜欢……吗？'，肯定回答用 Yes, I do."},
{i:113,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:0,q:"别人问“Do you like pears?”，你不喜欢，应回答？",o:["No, I don't.","Yes, I do.","No, I do.","Yes, I don't."],a:0,k:"句型：Do you like...? — No, I don't.",e:"解析：否定回答用 No, I don't.（不，我不喜欢）。"},
{i:114,c:"3en-11",ch:"三下·Unit 5 Do you like pears? 水果",f:1,q:"“葡萄”用英语说是 ____。",o:[],a:"grape",k:"水果：grape",e:"解析：'葡萄'的英语是 grape。"},

{i:115,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“eleven”的意思是？",o:["十一","十二","十三","十"],a:0,k:"数字：eleven",e:"解析：eleven 表示数字'十一'。"},
{i:116,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“twelve”的意思是？",o:["十二","十一","二十","十三"],a:0,k:"数字：twelve",e:"解析：twelve 表示数字'十二'。"},
{i:117,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“thirteen”的意思是？",o:["十三","十四","十二","十五"],a:0,k:"数字：thirteen",e:"解析：thirteen 表示数字'十三'。"},
{i:118,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“fifteen”的意思是？",o:["十五","十四","十六","十三"],a:0,k:"数字：fifteen",e:"解析：fifteen 表示数字'十五'。"},
{i:119,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“twenty”的意思是？",o:["二十","十九","十八","十"],a:0,k:"数字：twenty",e:"解析：twenty 表示数字'二十'。"},
{i:120,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“nineteen”的意思是？",o:["十九","十八","十七","二十"],a:0,k:"数字：nineteen",e:"解析：nineteen 表示数字'十九'。"},
{i:121,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“fourteen”的意思是？",o:["十四","十三","十五","十二"],a:0,k:"数字：fourteen",e:"解析：fourteen 表示数字'十四'。"},
{i:122,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“sixteen”的意思是？",o:["十六","十五","十七","十四"],a:0,k:"数字：sixteen",e:"解析：sixteen 表示数字'十六'。"},
{i:123,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:0,q:"“eighteen”的意思是？",o:["十八","十七","十九","十六"],a:0,k:"数字：eighteen",e:"解析：eighteen 表示数字'十八'。"},
{i:124,c:"3en-12",ch:"三下·Unit 6 How many? 数字11-20",f:1,q:"“十七”用英语说是 ____。",o:[],a:"seventeen",k:"数字：seventeen",e:"解析：数字'十七'的英语是 seventeen。"}
);
