if(!global.QA)global.QA={};
if(!QA["4en"])QA["4en"]=[];
QA["4en"].push(
{i:0,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"—Where is the green book? —____",o:["It is on the teacher's desk.","It is in the desk.","It is under the chair.","It is near the window."],a:0,k:"句型：Where is...? 询问物品位置",e:"解析：问句是 Where is...?（某物在哪里），回答用 It is + 方位介词短语。书通常放在老师的桌子上，故选 on the teacher's desk。"},
{i:1,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"—What's in the classroom? —____",o:["One blackboard, many desks and chairs.","Many books and a pen.","A bed and a sofa.","Some rice and soup."],a:0,k:"词汇：classroom 教室里的物品",e:"解析：教室里有黑板、课桌和椅子。bed/sofa 是家里家具，rice/soup 是食物，都不属于教室，故选第一项。"},
{i:2,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"“黑板”的英文是？",o:["blackboard","window","fan","door"],a:0,k:"词汇：blackboard 黑板",e:"解析：black（黑）+ board（板）= blackboard 黑板。window 窗户、fan 风扇、door 门。"},
{i:3,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"表示“在……上面（接触表面）”的方位介词是？",o:["on","in","under","near"],a:0,k:"介词：on 在上面",e:"解析：on 表示“在……表面之上”，如 on the wall（在墙上）；in 在……里，under 在……下，near 在……附近。"},
{i:4,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"We can see a big ____ on the wall.",o:["blackboard","desk","chair","fan"],a:0,k:"词汇：blackboard 在墙上",e:"解析：挂在墙上的是黑板 blackboard。desk/chair 在地面，fan 在天花板上，故选 blackboard。"},
{i:5,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"—Open the ____, please. Let fresh air in. —OK.",o:["window","blackboard","light","floor"],a:0,k:"词汇：window 窗户",e:"解析：开窗通风应打开 window（窗户）。blackboard 黑板、light 灯、floor 地板都不能放进新鲜空气。"},
{i:6,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"“关上门”应说：Close the ____.",o:["door","window","light","fan"],a:0,k:"词汇：door 门",e:"解析：door 是门，close the door 关上门。其余三项都不是“门”。"},
{i:7,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:1,q:"—Where is the picture? —It is ____ the wall.（在墙上）",o:[],a:"on",k:"介词填空：on the wall",e:"解析：图片、地图等“贴在/挂在墙表面”用 on the wall。on 表示在表面上。"},
{i:8,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"“computer”的意思是？",o:["计算机；电脑","黑板","风扇","门"],a:0,k:"词汇：computer 电脑",e:"解析：computer 意为计算机/电脑。其余三项分别是 blackboard、fan、door。"},
{i:9,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"—Let's clean the classroom! —____",o:["OK.","No.","Yes, I am.","Thank you."],a:0,k:"交际：应答建议",e:"解析：别人提议 Let's...（我们一起……），肯定应答用 OK. 或 Great.。No. 不礼貌，Yes, I am. 答非所问。"},
{i:10,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,q:"“floor”的意思是？",o:["地板","墙","灯","课桌"],a:0,k:"词汇：floor 地板",e:"解析：floor 是地板。wall 墙、light 灯、desk 课桌。"},
{i:11,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:1,q:"Turn on the ____, please. It's dark in the room.（开灯）",o:[],a:"light",k:"词汇填空：light 灯",e:"解析：房间暗要开灯，turn on the light 开灯。light 此处意为电灯。"},

{i:12,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"“书包”的英文是？",o:["schoolbag","book","pen","desk"],a:0,k:"词汇：schoolbag 书包",e:"解析：school（学校）+ bag（包）= schoolbag 书包。book 书、pen 钢笔、desk 课桌。"},
{i:13,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"—What's in your schoolbag? —____",o:["An English book and a maths book.","A bed and a sofa.","Some beef.","A red door."],a:0,k:"句型：What's in...? 书包里有什么",e:"解析：问句问书包里有什么，应回答书本文具。English book 英语书、maths book 数学书符合。其余是家具、食物、门。"},
{i:14,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"“storybook”的意思是？",o:["故事书","数学书","英语书","笔记本"],a:0,k:"词汇：storybook 故事书",e:"解析：story（故事）+ book（书）= storybook 故事书。"},
{i:15,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"—What colour is it? —____",o:["It's blue and white.","It's a book.","I'm fine.","Thank you."],a:0,k:"句型：What colour...? 问颜色",e:"解析：What colour 问颜色，回答用 It's + 颜色。blue and white 蓝白相间正确。"},
{i:16,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"“Put your ____ in your schoolbag.” 最合适的是？",o:["maths book","chair","door","window"],a:0,k:"词汇：maths book 数学书",e:"解析：能放进书包的应是书，maths book（数学书）正确。chair/door/window 是家具，不能放进书包。"},
{i:17,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"“notebook”的意思是？",o:["笔记本","故事书","糖果","钥匙"],a:0,k:"词汇：notebook 笔记本",e:"解析：note（笔记）+ book（本）= notebook 笔记本。"},
{i:18,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"“candy”的意思是？",o:["糖果","玩具","钥匙","笔记本"],a:0,k:"词汇：candy 糖果",e:"解析：candy 是糖果。toy 玩具、key 钥匙、notebook 笔记本。"},
{i:19,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:1,q:"—What colour is your schoolbag? —It's ____ and white.（黑和白）",o:[],a:"black",k:"颜色填空：black 黑色",e:"解析：常见书包配色是黑白相间，black and white 黑白色。black 黑色。"},
{i:20,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"“key”的意思是？",o:["钥匙","糖果","笔记本","玩具"],a:0,k:"词汇：key 钥匙",e:"解析：key 是钥匙。其余分别为 candy、notebook、toy。"},
{i:21,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"“Chinese book”的意思是？",o:["语文书","英语书","数学书","故事书"],a:0,k:"词汇：Chinese book 语文书",e:"解析：Chinese 语文/中文，Chinese book 语文书。"},
{i:22,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,q:"—What's in your schoolbag? —____",o:["Three storybooks.","A red apple.","It's on the desk.","I'm nine."],a:0,k:"句型：What's in...? 回答内容",e:"解析：回答书包里有什么，Three storybooks（三本故事书）符合。其余答非所问。"},
{i:23,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:1,q:"I have a ____ in my schoolbag.（玩具）",o:[],a:"toy",k:"词汇填空：toy 玩具",e:"解析：toy 是玩具，可以放在书包里。与 candy、key 同属小物件词汇。"},

{i:24,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"—What's his name? —____",o:["His name is John.","Her name is John.","I am John.","It is John."],a:0,k:"句型：What's his name? 他的名字",e:"解析：his 指“他的”，回答用 His name is...。John 是男生名，用 his 正确。"},
{i:25,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"He is tall and ____.",o:["strong","small","red","three"],a:0,k:"词汇：strong 强壮的",e:"解析：形容身材 tall and strong（又高又壮）是固定搭配。small/red/three 都不与 tall 搭配形容人。"},
{i:26,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"“glasses”的意思是？",o:["眼镜","鞋子","头发","书"],a:0,k:"词汇：glasses 眼镜",e:"解析：glasses 是眼镜（常以复数形式出现）。shoe 鞋、hair 头发。"},
{i:27,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"He has short ____.",o:["hair","shoes","glasses","bag"],a:0,k:"词汇：hair 头发",e:"解析：has short hair 留短发，hair（头发）不可数。shoes/glasses 用 have 但 short 不修饰；bag 不对。"},
{i:28,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"“friendly”的意思是？",o:["友好的","强壮的","安静的","高的"],a:0,k:"词汇：friendly 友好的",e:"解析：friend（朋友）+ ly = friendly 友好的。strong 强壮、quiet 安静、tall 高。"},
{i:29,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"“安静的”的英文是？",o:["quiet","strong","friendly","tall"],a:0,k:"词汇：quiet 安静的",e:"解析：quiet 安静的。其余分别为 strong、friendly、tall。"},
{i:30,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"She's cute. ____ name is Sarah.",o:["Her","His","My","Your"],a:0,k:"代词：her 她的",e:"解析：Sarah 是女生，用形容词性物主代词 her（她的）。his 他的，my 我的，your 你的。"},
{i:31,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:1,q:"He has black ____.（头发）",o:[],a:"hair",k:"词汇填空：hair 头发",e:"解析：has black hair 有一头黑发。hair 作“头发”统称时不可数，不用复数。"},
{i:32,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"He is ____ and thin.",o:["tall","strong","quiet","hair"],a:0,k:"词汇：tall and thin 又高又瘦",e:"解析：tall and thin（又高又瘦）形容人。strong 强壮与 thin 矛盾；quiet 不接 thin；hair 是名词。"},
{i:33,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"“shoe”的意思是？",o:["鞋","眼镜","头发","书包"],a:0,k:"词汇：shoe 鞋",e:"解析：shoe 是鞋。glasses 眼镜、hair 头发、schoolbag 书包。"},
{i:34,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,q:"My friend is ____. She often helps me.",o:["friendly","strong","hair","glasses"],a:0,k:"词汇：friendly 友好的",e:"解析：经常帮助别人说明性格 friendly（友好的）。strong/hair/glasses 不能说明性格友善。"},
{i:35,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:1,q:"—What's ____ name? —His name is Mike.（他的）",o:[],a:"his",k:"代词填空：his 他的",e:"解析：Mike 是男生，用 his（他的）修饰 name。his 是形容词性物主代词。"},

{i:36,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"—Where is the cat? —____",o:["It's in the living room.","It's a cat.","Yes, it is.","I like cats."],a:0,k:"句型：Where is...? 回答位置",e:"解析：问猫在哪里，回答用 It's + 方位。in the living room（在客厅）正确。"},
{i:37,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"—Is she in the study? —____",o:["No, she isn't.","Yes, he is.","No, he isn't.","It's a study."],a:0,k:"句型：Is she...? 否定回答",e:"解析：问句主语 she，否定回答 No, she isn't.。he 主语不符，故选第一项。"},
{i:38,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"“去厨房”应说：____",o:["Go to the kitchen.","Go to the bedroom.","Go to the study.","Go to the bathroom."],a:0,k:"词汇：kitchen 厨房",e:"解析：kitchen 厨房，Go to the kitchen 去厨房。其余是卧室、书房、浴室。"},
{i:39,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"“沙发”的英文是？",o:["sofa","bed","table","fridge"],a:0,k:"词汇：sofa 沙发",e:"解析：sofa 沙发。bed 床、table 桌子、fridge 冰箱。"},
{i:40,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"I'm hungry. Go to the ____.",o:["kitchen","bedroom","study","bathroom"],a:0,k:"词汇：kitchen 厨房（饿了去）",e:"解析：饿了去厨房找吃的，kitchen 厨房。bedroom 卧室、study 书房、bathroom 浴室。"},
{i:41,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"读书通常在 ____。",o:["study","kitchen","bathroom","bedroom"],a:0,k:"词汇：study 书房",e:"解析：study 书房是读书的地方。kitchen 厨房、bathroom 浴室、bedroom 卧室（虽可读书但 study 最贴切）。"},
{i:42,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"I'm tired. I want to have a nap in the ____.",o:["bedroom","kitchen","living room","study"],a:0,k:"词汇：bedroom 卧室",e:"解析：have a nap 小睡，应在 bedroom（卧室）的床上。其余房间不适合睡觉。"},
{i:43,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:1,q:"—Where is the dog? —It's ____ the living room.（在……里）",o:[],a:"in",k:"介词填空：in 在……里",e:"解析：狗在客厅里面，用 in 表示“在……内部”。"},
{i:44,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"“fridge”的意思是？",o:["冰箱","沙发","床","桌子"],a:0,k:"词汇：fridge 冰箱",e:"解析：fridge 冰箱。sofa 沙发、bed 床、table 桌子。"},
{i:45,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"“bathroom”的意思是？",o:["浴室；洗手间","卧室","书房","厨房"],a:0,k:"词汇：bathroom 浴室",e:"解析：bath（洗澡）+ room = bathroom 浴室/洗手间。"},
{i:46,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,q:"“phone”的意思是？",o:["电话","电脑","风扇","桌子"],a:0,k:"词汇：phone 电话",e:"解析：phone 电话。computer 电脑、fan 风扇、table 桌子。"},
{i:47,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:1,q:"Go to the ____ and read a book.（书房）",o:[],a:"study",k:"词汇填空：study 书房",e:"解析：读书去书房 study。study 既是“学习”也是“书房”。"},

{i:48,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"—What would you like? —____",o:["I'd like some beef.","I like beef.","It's beef.","Yes, please."],a:0,k:"句型：What would you like? 想要什么",e:"解析：问“你想吃点什么”，用 I'd like...（我想要……）回答。I'd = I would。"},
{i:49,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"“我想喝点汤”应说：____",o:["I'd like some soup.","I like soup.","It's soup.","A soup."],a:0,k:"句型：I'd like some soup",e:"解析：想喝汤用 I'd like some soup.。soup 不可数，不加 a，也不说 I like（那是“喜欢”不是“想要”）。"},
{i:50,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"“noodles”的意思是？",o:["面条","牛肉","鸡肉","汤"],a:0,k:"词汇：noodles 面条",e:"解析：noodles 面条（常以复数）。beef 牛肉、chicken 鸡肉、soup 汤。"},
{i:51,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"吃饭用的“筷子”是？",o:["chopsticks","fork","knife","spoon"],a:0,k:"词汇：chopsticks 筷子",e:"解析：chopsticks 筷子（常以复数）。fork 叉、knife 刀、spoon 勺。"},
{i:52,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"Help yourself. 的意思是？",o:["请自便；随便吃","帮助你自己","帮我一下","谢谢你"],a:0,k:"交际：Help yourself 请自便",e:"解析：用餐时主人说 Help yourself 是“请随便吃/自便”。不是字面“帮助自己”。"},
{i:53,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"“蔬菜”的英文是？",o:["vegetable","beef","chicken","soup"],a:0,k:"词汇：vegetable 蔬菜",e:"解析：vegetable 蔬菜。beef 牛肉、chicken 鸡肉、soup 汤。"},
{i:54,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"“fork”的意思是？",o:["餐叉","勺子","刀","筷子"],a:0,k:"词汇：fork 餐叉",e:"解析：fork 餐叉。spoon 勺、knife 刀、chopsticks 筷子。"},
{i:55,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:1,q:"—What would you like? —I'd like some ____.（汤）",o:[],a:"soup",k:"词汇填空：soup 汤",e:"解析：soup 汤，不可数名词，some soup 一些汤。回答用 I'd like... 对应问句 What would you like?"},
{i:56,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"“knife”的意思是？",o:["刀","叉","勺","碗"],a:0,k:"词汇：knife 刀",e:"解析：knife 刀。fork 叉、spoon 勺、bowl 碗。"},
{i:57,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"Pass me the ____, please. I want to drink the soup.",o:["spoon","fork","knife","chopsticks"],a:0,k:"词汇：spoon 勺子",e:"解析：喝汤用 spoon（勺子）。fork 叉、knife 刀、chopsticks 筷子都不适合喝汤。"},
{i:58,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,q:"“chicken”的意思是？",o:["鸡肉","牛肉","面条","蔬菜"],a:0,k:"词汇：chicken 鸡肉",e:"解析：chicken 鸡肉（也可指“鸡”这种动物）。beef 牛肉、noodles 面条、vegetable 蔬菜。"},
{i:59,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:1,q:"Dinner's ____. Let's eat!（准备好的）",o:[],a:"ready",k:"词汇填空：ready 准备好的",e:"解析：Dinner's ready. 晚饭准备好了。ready 准备好的，是形容词。"},

{i:60,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"—Where is the library? —____",o:["It's on the first floor.","It's a library.","Yes, it is.","I like library."],a:0,k:"句型：Where is...? 楼层",e:"解析：问图书馆在哪，回答用 It's on the + 序数词 + floor。first floor 一楼。"},
{i:61,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"—Is this the teachers' office? —____",o:["Yes, it is.","No, it is.","Yes, he is.","It's a teacher."],a:0,k:"句型：Is this...? 肯定回答",e:"解析：问句主语 this，肯定回答 Yes, it is.。he 是“他”不符；No, it is. 自相矛盾。"},
{i:62,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"“去操场玩”应说：____",o:["Go to the playground.","Go to the library.","Go to the gym.","Go to the art room."],a:0,k:"词汇：playground 操场",e:"解析：playground 操场，Go to the playground 去操场。library 图书馆、gym 体育馆、art room 美术教室。"},
{i:63,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"“library”的意思是？",o:["图书馆","操场","办公室","电脑室"],a:0,k:"词汇：library 图书馆",e:"解析：library 图书馆。playground 操场、teachers' office 办公室、computer room 电脑室。"},
{i:64,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"“二楼”的英文是？",o:["second floor","first floor","teachers' office","library"],a:0,k:"词汇：second floor 二楼",e:"解析：second 第二，second floor 二楼。first floor 一楼。"},
{i:65,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"画画应去 ____。",o:["art room","music room","computer room","gym"],a:0,k:"词汇：art room 美术教室",e:"解析：art 美术，art room 美术教室。music room 音乐教室、computer room 电脑室、gym 体育馆。"},
{i:66,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"上音乐课应去 ____。",o:["music room","art room","library","playground"],a:0,k:"词汇：music room 音乐教室",e:"解析：music 音乐，music room 音乐教室。art room 美术教室、library 图书馆、playground 操场。"},
{i:67,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:1,q:"—Where is the computer room? —It's on the ____.（二楼）",o:[],a:"second floor",k:"词汇填空：second floor 二楼",e:"解析：电脑室在二楼，用 second floor。first floor 是一楼。"},
{i:68,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"“gym”的意思是？",o:["体育馆","图书馆","办公室","楼梯"],a:0,k:"词汇：gym 体育馆",e:"解析：gym 体育馆/健身房。library 图书馆、teachers' office 办公室。"},
{i:69,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"—Is that the computer room? —No, it's the ____.",o:["library","gym","playground","office"],a:0,k:"词汇：library 图书馆",e:"解析：否定回答说明那不是电脑室而是图书馆 library。其余都不构成对应否定。"},
{i:70,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,q:"“teachers' office”的意思是？",o:["教师办公室","图书馆","操场","音乐教室"],a:0,k:"词汇：teachers' office 教师办公室",e:"解析：teachers' office 教师办公室。其余分别为 library、playground、music room。"},
{i:71,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:1,q:"This is the ____. We can read books here.（图书馆）",o:[],a:"library",k:"词汇填空：library 图书馆",e:"解析：能读书的地方是 library（图书馆）。read books 读书对应图书馆。"},

{i:72,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"—What time is it? —____",o:["It's six o'clock.","It's a clock.","Yes, it is.","I'm six."],a:0,k:"句型：What time is it? 几点了",e:"解析：问时间回答 It's + 时刻。six o'clock 六点整。a clock 是“一个钟”，答非所问。"},
{i:73,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"“该吃早饭了”应说：____",o:["It's time for breakfast.","It's time for lunch.","It's time for dinner.","It's time for bed."],a:0,k:"句型：It's time for... 到…时间",e:"解析：breakfast 早饭，It's time for breakfast 该吃早饭了。lunch 午饭、dinner 晚饭、bed 睡觉。"},
{i:74,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"“get up”的意思是？",o:["起床","上学","回家","睡觉"],a:0,k:"词汇：get up 起床",e:"解析：get up 起床。go to school 上学、go home 回家、go to bed 睡觉。"},
{i:75,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"It's 7:30. It's time to ____.",o:["go to school","go home","go to bed","get up"],a:0,k:"常识：7:30 上学",e:"解析：早上 7:30 通常去上学 go to school。go home 回家、go to bed 睡觉、get up 起床（一般更早）。"},
{i:76,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"“上英语课”用 ____。",o:["English class","music class","PE class","lunch"],a:0,k:"词汇：English class 英语课",e:"解析：English class 英语课。music class 音乐课、PE class 体育课、lunch 午饭。"},
{i:77,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"“go to bed”的意思是？",o:["上床睡觉","起床","回家","吃午饭"],a:0,k:"词汇：go to bed 睡觉",e:"解析：go to bed 上床睡觉。get up 起床、go home 回家、lunch 午饭。"},
{i:78,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"It's 12:00. It's time for ____.",o:["lunch","breakfast","dinner","PE class"],a:0,k:"常识：12:00 午饭",e:"解析：中午 12 点吃午饭 lunch。breakfast 早饭、dinner 晚饭、PE class 体育课。"},
{i:79,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:1,q:"—What time is it? —It's ____ o'clock.（七）",o:[],a:"seven",k:"数字填空：seven 七",e:"解析：seven 七，seven o'clock 七点钟。注意拼写 s-e-v-e-n。"},
{i:80,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"“dinner”的意思是？",o:["晚餐；正餐","早餐","午餐","体育课"],a:0,k:"词汇：dinner 晚餐",e:"解析：dinner 晚餐/正餐。breakfast 早餐、lunch 午餐。"},
{i:81,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"It's 9:00 p.m. It's time to ____.",o:["go to bed","go to school","get up","go home"],a:0,k:"常识：晚上9点睡觉",e:"解析：晚上 9 点该睡觉 go to bed。go to school/get up 是早晨，go home 不一定 9 点。"},
{i:82,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,q:"“music class”的意思是？",o:["音乐课","英语课","体育课","午饭"],a:0,k:"词汇：music class 音乐课",e:"解析：music class 音乐课。English class 英语课、PE class 体育课、lunch 午饭。"},
{i:83,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:1,q:"It's time ____ go to school.（to/for）",o:[],a:"to",k:"结构填空：It's time to + 动词",e:"解析：It's time to + 动词原形，go to school 是动词短语，用 to。It's time for + 名词。"},

{i:84,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"—What's the weather like in Beijing? —____",o:["It's sunny and warm.","It's a sun.","Yes, it is.","I like warm."],a:0,k:"句型：What's the weather like? 天气",e:"解析：问天气回答用 It's + 表示天气的形容词。sunny and warm 晴朗温暖正确。"},
{i:85,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"“寒冷的”英文是？",o:["cold","hot","warm","cool"],a:0,k:"词汇：cold 寒冷的",e:"解析：cold 寒冷的。hot 热、warm 温暖、cool 凉爽。"},
{i:86,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"It's ____ today. Let's make a snowman.",o:["snowy","rainy","sunny","windy"],a:0,k:"词汇：snowy 下雪的",e:"解析：堆雪人 make a snowman 需要下雪 snowy。rainy 下雨、sunny 晴、windy 有风都不适合。"},
{i:87,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"“炎热的”英文是？",o:["hot","cold","cool","warm"],a:0,k:"词汇：hot 炎热的",e:"解析：hot 炎热的。cold 寒冷、cool 凉爽、warm 温暖。"},
{i:88,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"“windy”的意思是？",o:["有风的","多云的","下雪的","下雨的"],a:0,k:"词汇：windy 有风的",e:"解析：wind（风）+ y = windy 有风的。cloudy 多云、snowy 下雪、rainy 下雨。"},
{i:89,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"—Can I go outside? —No, you ____.",o:["can't","can","do","don't"],a:0,k:"情态动词：can 的否定",e:"解析：Can I...? 否定回答 No, you can't.。can't = can not。"},
{i:90,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"“cloudy”的意思是？",o:["多云的","晴朗的","有风的","下雪的"],a:0,k:"词汇：cloudy 多云的",e:"解析：cloud（云）+ y = cloudy 多云的。sunny 晴朗、windy 有风、snowy 下雪。"},
{i:91,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:1,q:"—What's the weather like? —It's ____ and windy.（温暖）",o:[],a:"warm",k:"词汇填空：warm 温暖",e:"解析：warm 温暖的，与 windy 并列描述天气。注意 warm 不是 hot。"},
{i:92,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"“rainy”的意思是？",o:["下雨的","下雪的","晴朗的","多云的"],a:0,k:"词汇：rainy 下雨的",e:"解析：rain（雨）+ y = rainy 下雨的。snowy 下雪、sunny 晴朗、cloudy 多云。"},
{i:93,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"It's cold outside. Put on your ____.",o:["coat","shirt","dress","skirt"],a:0,k:"词汇：coat 外套",e:"解析：天冷穿外套 coat 保暖。shirt 衬衫、dress 连衣裙、skirt 裙子都较薄。"},
{i:94,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,q:"“cool”的意思是？",o:["凉爽的","寒冷的","炎热的","温暖的"],a:0,k:"词汇：cool 凉爽的",e:"解析：cool 凉爽的（比 cold 温和）。cold 寒冷、hot 炎热、warm 温暖。"},
{i:95,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:1,q:"It's ____ in Harbin. It's white everywhere.（下雪的）",o:[],a:"snowy",k:"词汇填空：snowy 下雪的",e:"解析：哈尔滨冬天多雪，snowy 下雪的，到处白茫茫。snow 是雪（名词），此处需形容词 snowy。"},

{i:96,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"—Whose dress is this? —____",o:["It's Amy's.","It's Amy.","Yes, it is.","A red dress."],a:0,k:"句型：Whose...? 谁的",e:"解析：Whose 问“谁的”，回答用名词所有格 ...'s。It's Amy's 是 Amy 的。It's Amy 是人名不对。"},
{i:97,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"—Is this yours? —Yes, ____.",o:["it is","it isn't","he is","they are"],a:0,k:"代词：yours 名词性物主代词",e:"解析：yours = your + 名词，问句主语 this 用 it 回指，肯定 Yes, it is.。"},
{i:98,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"“连衣裙”的英文是？",o:["dress","skirt","coat","shirt"],a:0,k:"词汇：dress 连衣裙",e:"解析：dress 连衣裙。skirt 短裙、coat 外套、shirt 衬衫。"},
{i:99,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"I like that red ____.",o:["sweater","shirt","coat","jacket"],a:0,k:"词汇：sweater 毛衣",e:"解析：sweater 毛衣，that red sweater 那件红毛衣。其余虽是衣物但题干语境常指毛衣，且四项中只有 sweater 最常被 that 指代。此处以 sweater 为正确项。"},
{i:100,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"“shorts”的意思是？",o:["短裤","袜子","裤子","外套"],a:0,k:"词汇：shorts 短裤",e:"解析：shorts 短裤（常以复数）。sock 袜子、pants 裤子、coat 外套。"},
{i:101,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"外面冷，应说：____",o:["Put on your coat.","Take off your coat.","Put on your shirt.","Take off your hat."],a:0,k:"交际：Put on 穿上",e:"解析：天冷要穿上外套 Put on your coat.。Take off 是脱下，方向相反。"},
{i:102,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"These are my ____.",o:["socks","shoe","shirt","coat"],a:0,k:"名词单复数：these 接复数",e:"解析：These are 后接复数名词，socks 袜子（复数）正确。shoe/shirt/coat 是单数。"},
{i:103,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:1,q:"—Whose ____ is this? —It's John's.（衬衫）",o:[],a:"shirt",k:"词汇填空：shirt 衬衫",e:"解析：shirt 衬衫，Whose shirt 谁的衬衫。回答 It's John's 用单数 shirt 对应 it。"},
{i:104,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"“jacket”的意思是？",o:["夹克衫","毛衣","裙子","帽子"],a:0,k:"词汇：jacket 夹克衫",e:"解析：jacket 夹克衫/短上衣。sweater 毛衣、skirt 裙子、hat 帽子。"},
{i:105,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"—Is this your skirt? —Yes, it's ____.",o:["mine","my","your","yours"],a:0,k:"代词：mine 我的（名词性）",e:"解析：mine = my skirt，名词性物主代词单独使用，不加名词。my 后须接名词。"},
{i:106,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,q:"“pants”的意思是？",o:["裤子","短裤","袜子","鞋子"],a:0,k:"词汇：pants 裤子",e:"解析：pants 裤子（常以复数）。shorts 短裤、socks 袜子、shoes 鞋子。"},
{i:107,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:1,q:"These blue shoes are ____.（你的）",o:[],a:"yours",k:"代词填空：yours 你的",e:"解析：yours = your shoes，名词性物主代词，单独作表语。These shoes 是复数，对应 yours。"},

{i:108,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"—How much is the scarf? —____",o:["It's ten yuan.","It's ten.","Yes, it is.","A scarf."],a:0,k:"句型：How much...? 问价格",e:"解析：How much 问价格/不可数数量，回答用 It's + 钱数。ten yuan 十元。必须有货币单位 yuan。"},
{i:109,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"“这把雨伞多少钱？”应说：____",o:["How much is the umbrella?","How much are the umbrella?","What is the umbrella?","How many is the umbrella?"],a:0,k:"句型：How much is + 单数",e:"解析：umbrella 单数用 is，How much is the umbrella? 正确。are 用于复数，What 问“是什么”不对。"},
{i:110,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"“expensive”的意思是？",o:["昂贵的","便宜的","漂亮的","好的"],a:0,k:"词汇：expensive 昂贵的",e:"解析：expensive 昂贵的。cheap 便宜、pretty 漂亮、nice 好。"},
{i:111,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"The gloves are nice. Can I ____?",o:["try them on","try it on","try on them","try on it"],a:0,k:"短语：try on 代词位置",e:"解析：gloves 复数用 them；try on 的宾语是代词时必须放在中间，try them on 试穿它们。名词才可放后：try on the gloves。"},
{i:112,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"“便宜的”英文是？",o:["cheap","expensive","pretty","nice"],a:0,k:"词汇：cheap 便宜的",e:"解析：cheap 便宜的。expensive 昂贵、pretty 漂亮、nice 好。"},
{i:113,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"—How much are these socks? —____",o:["They're five yuan.","It's five yuan.","Yes, they are.","Five socks."],a:0,k:"句型：How much are + 复数",e:"解析：socks 复数用 are，回答 They're + 钱数。It's 用于单数，故选 They're five yuan。"},
{i:114,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"“sunglasses”的意思是？",o:["太阳镜","手套","围巾","雨伞"],a:0,k:"词汇：sunglasses 太阳镜",e:"解析：sunglasses 太阳镜（复数）。gloves 手套、scarf 围巾、umbrella 雨伞。"},
{i:115,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:1,q:"—How much ____ the dress? —It's eighty yuan.（be动词）",o:[],a:"is",k:"动词填空：is 单数",e:"解析：the dress 单数，be 动词用 is。How much is...? 问单数物品价格。"},
{i:116,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"“scarf”的意思是？",o:["围巾","手套","太阳镜","雨伞"],a:0,k:"词汇：scarf 围巾",e:"解析：scarf 围巾。gloves 手套、sunglasses 太阳镜、umbrella 雨伞。"},
{i:117,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"“pretty”的意思是？",o:["美观的；漂亮的","便宜的","昂贵的","大的"],a:0,k:"词汇：pretty 漂亮的",e:"解析：pretty 漂亮的/美观的。cheap 便宜、expensive 昂贵。常用来形容衣物好看。"},
{i:118,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,q:"“glove”的意思是？",o:["手套","围巾","太阳镜","雨伞"],a:0,k:"词汇：glove 手套",e:"解析：glove 手套（常用复数 gloves）。scarf 围巾、sunglasses 太阳镜、umbrella 雨伞。"},
{i:119,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:1,q:"—Can I help you? —Yes. I want a ____, please.（围巾）",o:[],a:"scarf",k:"词汇填空：scarf 围巾",e:"解析：scarf 围巾，a scarf 一条围巾。购物场景常用 I want a + 衣物。"}
);
