if(!global.QA)global.QA={};
if(!QA["4en"])QA["4en"]=[];
QA["4en"].push(
{i:9000,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,d:2,q:"I'd like ______ a cup of tea.",o:["to have","have","having","has"],a:0,k:"语法：would like",e:"解析：would like to do sth. 是固定结构，意为“想要做某事”。"},
{i:9001,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,d:2,q:"— ______ do you go to the library? — Twice a week.",o:["How often","How long","How soon","How far"],a:0,k:"疑问词辨析",e:"解析：答语 Twice a week 表频率，用 How often 提问。"},
{i:9002,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,d:2,q:"This is the boy ______ father is a doctor.",o:["whose","who","which","whom"],a:0,k:"语法：定语从句",e:"解析：表示“谁的”（所属关系）用 whose 引导定语从句，相当于 the boy's father。"},
{i:9003,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,d:2,q:"My mother is ______ than my father.",o:["taller","tall","tallest","more tall"],a:0,k:"语法：比较级",e:"解析：than 前用比较级。tall 的比较级是 taller，不是 more tall。"},
{i:9004,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,d:2,q:"The book ______ by Lu Xun.",o:["was written","wrote","is writing","writes"],a:0,k:"语法：被动语态",e:"解析：书是被写的，用被动语态 be + 过去分词，write 的过去分词是 written。"},
{i:9005,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,d:2,q:"She ______ English for three years.",o:["has learned","learned","learns","is learning"],a:0,k:"语法：现在完成时",e:"解析：for three years 表示持续一段时间，与现在完成时连用，用 has learned。"},
{i:9006,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,d:2,q:"He ______ his homework at this time yesterday.",o:["was doing","did","does","is doing"],a:0,k:"语法：过去进行时",e:"解析：at this time yesterday 是过去进行时的标志，用 was doing。"},
{i:9007,c:"4en-1",ch:"四上·第1单元 My classroom（教室与方位）",f:0,d:2,q:"I have ______ to tell you.",o:["something important","important something","anything important","important anything"],a:0,k:"不定代词",e:"解析：形容词修饰不定代词（something/anything）时要后置，肯定句用 something。"},
{i:9008,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,d:2,q:"The book ______ by Lu Xun.",o:["was written","wrote","is writing","writes"],a:0,k:"语法：被动语态",e:"解析：书是被写的，用被动语态 be + 过去分词，write 的过去分词是 written。"},
{i:9009,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,d:2,q:"This is the boy ______ father is a doctor.",o:["whose","who","which","whom"],a:0,k:"语法：定语从句",e:"解析：表示“谁的”（所属关系）用 whose 引导定语从句，相当于 the boy's father。"},
{i:9010,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,d:2,q:"He is interested ______ science.",o:["in","at","on","for"],a:0,k:"介词搭配",e:"解析：be interested in 是固定搭配，意为“对……感兴趣”。"},
{i:9011,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,d:2,q:"He ______ his homework at this time yesterday.",o:["was doing","did","does","is doing"],a:0,k:"语法：过去进行时",e:"解析：at this time yesterday 是过去进行时的标志，用 was doing。"},
{i:9012,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,d:2,q:"— ______ do you go to the library? — Twice a week.",o:["How often","How long","How soon","How far"],a:0,k:"疑问词辨析",e:"解析：答语 Twice a week 表频率，用 How often 提问。"},
{i:9013,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,d:2,q:"He ______ in Beijing since 2010.",o:["has lived","lived","lives","is living"],a:0,k:"语法：现在完成时",e:"解析：since 引导的时间状语与现在完成时连用，表示从过去持续到现在。"},
{i:9014,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,d:2,q:"I'm not good ______ English.",o:["at","in","on","for"],a:0,k:"介词搭配",e:"解析：be good at 是固定搭配，意为“擅长……”，后接名词或动名词。"},
{i:9015,c:"4en-10",ch:"四下·第6单元 Shopping（购物）",f:0,d:2,q:"We should ______ our hands before meals.",o:["wash","washing","to wash","washes"],a:0,k:"情态动词",e:"解析：情态动词 should 后接动词原形。"},
{i:9016,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,d:2,q:"I'm not good ______ English.",o:["at","in","on","for"],a:0,k:"介词搭配",e:"解析：be good at 是固定搭配，意为“擅长……”，后接名词或动名词。"},
{i:9017,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,d:2,q:"He is too tired ______ any more.",o:["to walk","walking","walk","walks"],a:0,k:"语法：too...to",e:"解析：too + 形容词 + to do 意为“太……而不能”，后接动词原形。"},
{i:9018,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,d:2,q:"He runs ______ than anyone else in his class.",o:["faster","fast","fastest","more fast"],a:0,k:"语法：比较级",e:"解析：than 前用比较级，fast 的比较级是 faster。"},
{i:9019,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,d:2,q:"This is the boy ______ father is a doctor.",o:["whose","who","which","whom"],a:0,k:"语法：定语从句",e:"解析：表示“谁的”（所属关系）用 whose 引导定语从句，相当于 the boy's father。"},
{i:9020,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,d:2,q:"— I'm sorry I'm late. — ______.",o:["That's all right","You're welcome","All right","That's right"],a:0,k:"情景交际",e:"解析：回应道歉用 That's all right / Never mind / It doesn't matter。You're welcome 是回应感谢。"},
{i:9021,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,d:2,q:"This book is ______ of the three.",o:["the most interesting","more interesting","interesting","most interesting"],a:0,k:"语法：最高级",e:"解析：三者比较用最高级，interesting 是多音节词，最高级为 the most interesting（最高级前要加 the）。"},
{i:9022,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,d:2,q:"She speaks English ______ than me.",o:["better","well","good","best"],a:0,k:"语法：比较级",e:"解析：than 前用比较级，well 的比较级是 better（不规则变化）。"},
{i:9023,c:"4en-2",ch:"四上·第2单元 My schoolbag（书包与颜色）",f:0,d:2,q:"He is ______ honest boy.",o:["an","a","the","/"],a:0,k:"冠词",e:"解析：honest 首字母 h 不发音，第一个音素是元音 /ɒ/，所以用 an。"},
{i:9024,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,d:2,q:"The little boy is afraid ______ dogs.",o:["of","with","at","for"],a:0,k:"介词搭配",e:"解析：be afraid of 是固定搭配，意为“害怕……”。"},
{i:9025,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,d:2,q:"The movie was ______ boring ______ I fell asleep.",o:["so...that","too...to","such...that","very...that"],a:0,k:"语法：结果状语从句",e:"解析：so + 形容词/副词 + that 引导结果状语从句，意为“如此……以至于”。"},
{i:9026,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,d:2,q:"This is the boy ______ father is a doctor.",o:["whose","who","which","whom"],a:0,k:"语法：定语从句",e:"解析：表示“谁的”（所属关系）用 whose 引导定语从句，相当于 the boy's father。"},
{i:9027,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,d:2,q:"He runs ______ than anyone else in his class.",o:["faster","fast","fastest","more fast"],a:0,k:"语法：比较级",e:"解析：than 前用比较级，fast 的比较级是 faster。"},
{i:9028,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,d:2,q:"— What's the weather ______ today? — It's sunny.",o:["like","likes","liking","about"],a:0,k:"句型：问天气",e:"解析：问天气用 What's the weather like? 或 How's the weather? like 在这里是介词。"},
{i:9029,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,d:2,q:"It took me two hours ______ my homework.",o:["to finish","finishing","finish","finished"],a:0,k:"句型：It takes sb. time to do",e:"解析：It takes sb. some time to do sth. 是固定句型，意为“做某事花费某人多长时间”。"},
{i:9030,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,d:2,q:"She asked me ______ I liked English.",o:["if","that","what","which"],a:0,k:"语法：宾语从句",e:"解析：表示“是否”用 if 或 whether 引导宾语从句；that 引导陈述内容，不表疑问。"},
{i:9031,c:"4en-3",ch:"四上·第3单元 My friends（描述朋友）",f:0,d:2,q:"I ______ my bike yesterday.",o:["lost","lose","loses","losing"],a:0,k:"语法：一般过去时",e:"解析：yesterday 是一般过去时的标志，lose 的过去式是 lost。"},
{i:9032,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,d:2,q:"— Must I finish it now? — No, you ______.",o:["needn't","mustn't","can't","shouldn't"],a:0,k:"情态动词",e:"解析：Must I...? 的否定回答用 needn't（不必）；mustn't 表示“禁止”。"},
{i:9033,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,d:2,q:"The little boy is afraid ______ dogs.",o:["of","with","at","for"],a:0,k:"介词搭配",e:"解析：be afraid of 是固定搭配，意为“害怕……”。"},
{i:9034,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,d:2,q:"The students ______ the classroom now.",o:["are cleaning","clean","cleans","is cleaning"],a:0,k:"语法：现在进行时",e:"解析：now 是现在进行时标志，主语 students 是复数，用 are cleaning。"},
{i:9035,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,d:2,q:"It's time ______ class.",o:["for","to","in","at"],a:0,k:"介词搭配",e:"解析：It's time for + 名词；It's time to + 动词原形。class 是名词，用 for。"},
{i:9036,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,d:2,q:"This is the museum ______ we visited last week.",o:["that","who","whose","what"],a:0,k:"语法：定语从句",e:"解析：先行词 museum 是物，用 that 或 which 引导；who 指人，whose 表所属。"},
{i:9037,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,d:2,q:"The hospital is ______ the bank and the school.",o:["between","among","in","next"],a:0,k:"介词辨析",e:"解析：between...and... 表示“在……和……之间”（两者）；among 用于三者以上。"},
{i:9038,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,d:2,q:"This book is ______ of the three.",o:["the most interesting","more interesting","interesting","most interesting"],a:0,k:"语法：最高级",e:"解析：三者比较用最高级，interesting 是多音节词，最高级为 the most interesting（最高级前要加 the）。"},
{i:9039,c:"4en-4",ch:"四上·第4单元 My home（房间与家具）",f:0,d:2,q:"She asked me ______ I liked English.",o:["if","that","what","which"],a:0,k:"语法：宾语从句",e:"解析：表示“是否”用 if 或 whether 引导宾语从句；that 引导陈述内容，不表疑问。"},
{i:9040,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,d:2,q:"The teacher told us ______ quiet.",o:["to keep","keep","keeping","kept"],a:0,k:"语法：tell sb. to do",e:"解析：tell sb. to do sth. 是固定结构，意为“告诉某人做某事”。"},
{i:9041,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,d:2,q:"We ______ to the park if it doesn't rain tomorrow.",o:["will go","go","went","going"],a:0,k:"语法：条件状语从句时态",e:"解析：if 引导条件句，遵循“主将从现”——主句用一般将来时 will go，从句用一般现在时。"},
{i:9042,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,d:2,q:"She ______ English for three years.",o:["has learned","learned","learns","is learning"],a:0,k:"语法：现在完成时",e:"解析：for three years 表示持续一段时间，与现在完成时连用，用 has learned。"},
{i:9043,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,d:2,q:"He has ______ finished his homework.",o:["already","yet","ever","never"],a:0,k:"语法：现在完成时",e:"解析：肯定句中表示“已经”用 already；yet 用于否定句和疑问句。"},
{i:9044,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,d:2,q:"I have two pens. One is red, ______ is blue.",o:["the other","other","another","others"],a:0,k:"不定代词",e:"解析：两者中的“一个……另一个”用 one...the other。"},
{i:9045,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,d:2,q:"He is too tired ______ any more.",o:["to walk","walking","walk","walks"],a:0,k:"语法：too...to",e:"解析：too + 形容词 + to do 意为“太……而不能”，后接动词原形。"},
{i:9046,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,d:2,q:"I'd like ______ a cup of tea.",o:["to have","have","having","has"],a:0,k:"语法：would like",e:"解析：would like to do sth. 是固定结构，意为“想要做某事”。"},
{i:9047,c:"4en-5",ch:"四上·第5单元 Dinner's ready（食物与用餐）",f:0,d:2,q:"______ you ______ your homework yet?",o:["Have...finished","Do...finish","Did...finish","Are...finishing"],a:0,k:"语法：现在完成时",e:"解析：yet 是现在完成时的标志，结构是 have/has + 过去分词。"},
{i:9048,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,d:2,q:"The teacher told us ______ quiet.",o:["to keep","keep","keeping","kept"],a:0,k:"语法：tell sb. to do",e:"解析：tell sb. to do sth. 是固定结构，意为“告诉某人做某事”。"},
{i:9049,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,d:2,q:"She ______ English for three years.",o:["has learned","learned","learns","is learning"],a:0,k:"语法：现在完成时",e:"解析：for three years 表示持续一段时间，与现在完成时连用，用 has learned。"},
{i:9050,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,d:2,q:"He ______ in Beijing since 2010.",o:["has lived","lived","lives","is living"],a:0,k:"语法：现在完成时",e:"解析：since 引导的时间状语与现在完成时连用，表示从过去持续到现在。"},
{i:9051,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,d:2,q:"There isn't ______ water in the bottle.",o:["any","some","many","a"],a:0,k:"some/any 用法",e:"解析：否定句中用 any；water 不可数，不能用 many。"},
{i:9052,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,d:2,q:"She speaks English ______ than me.",o:["better","well","good","best"],a:0,k:"语法：比较级",e:"解析：than 前用比较级，well 的比较级是 better（不规则变化）。"},
{i:9053,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,d:2,q:"She asked me ______ I liked English.",o:["if","that","what","which"],a:0,k:"语法：宾语从句",e:"解析：表示“是否”用 if 或 whether 引导宾语从句；that 引导陈述内容，不表疑问。"},
{i:9054,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,d:2,q:"It's time ______ class.",o:["for","to","in","at"],a:0,k:"介词搭配",e:"解析：It's time for + 名词；It's time to + 动词原形。class 是名词，用 for。"},
{i:9055,c:"4en-6",ch:"四下·第1单元 My school（学校场所与方位）",f:0,d:2,q:"— ______ do you go to the library? — Twice a week.",o:["How often","How long","How soon","How far"],a:0,k:"疑问词辨析",e:"解析：答语 Twice a week 表频率，用 How often 提问。"},
{i:9056,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,d:2,q:"— ______ do you go to the library? — Twice a week.",o:["How often","How long","How soon","How far"],a:0,k:"疑问词辨析",e:"解析：答语 Twice a week 表频率，用 How often 提问。"},
{i:9057,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,d:2,q:"This is the museum ______ we visited last week.",o:["that","who","whose","what"],a:0,k:"语法：定语从句",e:"解析：先行词 museum 是物，用 that 或 which 引导；who 指人，whose 表所属。"},
{i:9058,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,d:2,q:"— Must I finish it now? — No, you ______.",o:["needn't","mustn't","can't","shouldn't"],a:0,k:"情态动词",e:"解析：Must I...? 的否定回答用 needn't（不必）；mustn't 表示“禁止”。"},
{i:9059,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,d:2,q:"I ______ my bike yesterday.",o:["lost","lose","loses","losing"],a:0,k:"语法：一般过去时",e:"解析：yesterday 是一般过去时的标志，lose 的过去式是 lost。"},
{i:9060,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,d:2,q:"______ careful! The bus is coming.",o:["Be","Being","To be","Are"],a:0,k:"祈使句",e:"解析：祈使句用动词原形开头，be careful 意为“小心”。"},
{i:9061,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,d:2,q:"______ you ______ your homework yet?",o:["Have...finished","Do...finish","Did...finish","Are...finishing"],a:0,k:"语法：现在完成时",e:"解析：yet 是现在完成时的标志，结构是 have/has + 过去分词。"},
{i:9062,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,d:2,q:"It took me two hours ______ my homework.",o:["to finish","finishing","finish","finished"],a:0,k:"句型：It takes sb. time to do",e:"解析：It takes sb. some time to do sth. 是固定句型，意为“做某事花费某人多长时间”。"},
{i:9063,c:"4en-7",ch:"四下·第2单元 What time is it?（时间表达）",f:0,d:2,q:"He is ______ honest boy.",o:["an","a","the","/"],a:0,k:"冠词",e:"解析：honest 首字母 h 不发音，第一个音素是元音 /ɒ/，所以用 an。"},
{i:9064,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,d:2,q:"This is the boy ______ father is a doctor.",o:["whose","who","which","whom"],a:0,k:"语法：定语从句",e:"解析：表示“谁的”（所属关系）用 whose 引导定语从句，相当于 the boy's father。"},
{i:9065,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,d:2,q:"Let's ______ football after school.",o:["play","playing","to play","plays"],a:0,k:"语法：let 的用法",e:"解析：let sb. do sth. 是固定结构，let 后接动词原形。"},
{i:9066,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,d:2,q:"He is too tired ______ any more.",o:["to walk","walking","walk","walks"],a:0,k:"语法：too...to",e:"解析：too + 形容词 + to do 意为“太……而不能”，后接动词原形。"},
{i:9067,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,d:2,q:"There are two ______ in the picture.",o:["children","child","childs","childrens"],a:0,k:"名词复数",e:"解析：child 的复数是不规则变化 children，不是加 -s。"},
{i:9068,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,d:2,q:"It took me two hours ______ my homework.",o:["to finish","finishing","finish","finished"],a:0,k:"句型：It takes sb. time to do",e:"解析：It takes sb. some time to do sth. 是固定句型，意为“做某事花费某人多长时间”。"},
{i:9069,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,d:2,q:"He runs ______ than anyone else in his class.",o:["faster","fast","fastest","more fast"],a:0,k:"语法：比较级",e:"解析：than 前用比较级，fast 的比较级是 faster。"},
{i:9070,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,d:2,q:"The teacher told us ______ quiet.",o:["to keep","keep","keeping","kept"],a:0,k:"语法：tell sb. to do",e:"解析：tell sb. to do sth. 是固定结构，意为“告诉某人做某事”。"},
{i:9071,c:"4en-8",ch:"四下·第3单元 Weather（天气）",f:0,d:2,q:"She ______ English for three years.",o:["has learned","learned","learns","is learning"],a:0,k:"语法：现在完成时",e:"解析：for three years 表示持续一段时间，与现在完成时连用，用 has learned。"},
{i:9072,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,d:2,q:"The hospital is ______ the bank and the school.",o:["between","among","in","next"],a:0,k:"介词辨析",e:"解析：between...and... 表示“在……和……之间”（两者）；among 用于三者以上。"},
{i:9073,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,d:2,q:"The little boy is afraid ______ dogs.",o:["of","with","at","for"],a:0,k:"介词搭配",e:"解析：be afraid of 是固定搭配，意为“害怕……”。"},
{i:9074,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,d:2,q:"She is ______ girl in our class.",o:["the tallest","taller","tall","most tall"],a:0,k:"语法：最高级",e:"解析：in our class 表示范围，用最高级；tall 的最高级是 tallest，前面加 the。"},
{i:9075,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,d:2,q:"He ______ to school by bike every day.",o:["goes","go","going","is go"],a:0,k:"语法：一般现在时三单",e:"解析：主语 He 是第三人称单数，一般现在时动词要加 -s，用 goes。every day 是一般现在时的标志。"},
{i:9076,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,d:2,q:"This book is ______ of the three.",o:["the most interesting","more interesting","interesting","most interesting"],a:0,k:"语法：最高级",e:"解析：三者比较用最高级，interesting 是多音节词，最高级为 the most interesting（最高级前要加 the）。"},
{i:9077,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,d:2,q:"My father ______ a car to work every day.",o:["drives","drive","driving","is drive"],a:0,k:"语法：一般现在时三单",e:"解析：主语 My father 是三单，一般现在时用 drives。"},
{i:9078,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,d:2,q:"It's time ______ class.",o:["for","to","in","at"],a:0,k:"介词搭配",e:"解析：It's time for + 名词；It's time to + 动词原形。class 是名词，用 for。"},
{i:9079,c:"4en-9",ch:"四下·第5单元 My clothes（衣物）",f:0,d:2,q:"— Must I finish it now? — No, you ______.",o:["needn't","mustn't","can't","shouldn't"],a:0,k:"情态动词",e:"解析：Must I...? 的否定回答用 needn't（不必）；mustn't 表示“禁止”。"}
);
