// 四年级英语 · 人教PEP（三年级起点）
// 四上 Unit 1~6 + 四下 Unit 1~6，共 12 单元 × 20 题 = 240 题
// 每单元：14 选择题 + 2 填空题 + 4 拔高题（d:2）
// 2026-09-10 整套重写：
//   旧版 200 题 / 10 章（四上缺 Unit6、四下缺 Unit4），知识点重复 27.0%，
//   且夹杂定语从句×7、现在完成时×9、被动语态、过去进行时、宾语从句等严重超纲语法；
//   重写后 12 单元 240 题，知识点零重复，语法严格限定在 PEP 四年级范围内
//   （一般现在时三单、现在进行时、can、would like、there be、名词复数、物主代词、
//    介词 in/on/under/near/behind/next to、How much/How many、It's time for/to）。
if(!global.QA)global.QA={};
if(!QA["4en"])QA["4en"]=[];
QA["4en"].push(
// ══════════ 四上·Unit 1 My classroom 教室与方位 ══════════
{i:0,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“classroom”的中文意思是？",o:["教室","图书馆","操场","办公室"],a:0,k:"词汇：classroom 教室",e:"解析：class 意为“班级、课”，room 意为“房间”，classroom 合起来就是“教室”。"},
{i:1,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"你想告诉别人“这是我的教室”，应该说？",o:["This is my classroom.","This is my school.","This is my home.","This is my bedroom."],a:0,k:"句型：This is my classroom",e:"解析：This is... 用来介绍距离自己较近的事物，This is my classroom. 意为“这是我的教室”。"},
{i:2,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"教室里老师用来写字的那块黑板，英语是？",o:["blackboard","schoolbag","playground","picture"],a:0,k:"词汇：blackboard 黑板",e:"解析：blackboard 由 black（黑）+ board（板）组成，指教室前方的大黑板。"},
{i:3,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“窗户”的英语单词是？",o:["window","door","wall","floor"],a:0,k:"词汇：window 窗户",e:"解析：window 意为“窗户”，复数是 windows，如 clean the windows（擦窗户）。"},
{i:4,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“电灯”的英语单词是？",o:["light","fan","desk","picture"],a:0,k:"词汇：light 电灯",e:"解析：light 除了“电灯”，还可以表示“光、明亮的”。教室里常说 Turn on the light.（开灯）。"},
{i:5,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“图画、照片”的英语单词是？",o:["picture","window","computer","wall"],a:0,k:"词汇：picture 图画照片",e:"解析：picture 意为“图画、照片”，如 a picture of my family（一张我的全家福）。"},
{i:6,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“门”的英语单词是？",o:["door","window","wall","floor"],a:0,k:"词汇：door 门",e:"解析：door 意为“门”，常用短语 close the door（关门）、open the door（开门）。"},
{i:7,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“计算机、电脑”的英语单词是？",o:["computer","picture","blackboard","fan"],a:0,k:"词汇：computer 计算机",e:"解析：computer 意为“计算机”，教室里的计算机常放在讲台附近。"},
{i:8,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"教室前方老师用的讲台，英语是？",o:["teacher's desk","schoolbag","picture","light"],a:0,k:"词汇：teacher's desk 讲台",e:"解析：teacher's desk 意为“讲台”，其中 teacher's 是名词所有格，表示“老师的”。"},
{i:9,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“电扇”的英语单词是？",o:["fan","light","computer","door"],a:0,k:"词汇：fan 电扇",e:"解析：fan 意为“电扇”，也可以在口语中表示“粉丝、爱好者”。"},
{i:10,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“墙壁”的英语单词是？",o:["wall","floor","door","window"],a:0,k:"词汇：wall 墙壁",e:"解析：wall 意为“墙壁”，图画通常挂在墙上，所以说 on the wall。"},
{i:11,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“地板”的英语单词是？",o:["floor","wall","door","window"],a:0,k:"词汇：floor 地板",e:"解析：floor 意为“地板”，也可以表示“楼层”，如 on the first floor（在一楼）。"},
{i:12,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"同学问你 “What's in the classroom?” 最合适的回答是？",o:["A blackboard and some desks.","It's near the window.","Yes, it is.","Thank you."],a:0,k:"句型：What's in the classroom 的答语",e:"解析：What's in...? 问的是“里面有什么”，要用物品名称作答；Where is it? 才回答位置。"},
{i:13,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,q:"“It's near the window.” 中 near 的意思是？",o:["在……附近","在……上面","在……下面","在……里面"],a:0,k:"介词：near 在附近",e:"解析：near 意为“在……附近”，说明位置离某物很近；in 是在里面，on 是在上面。"},
{i:14,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:1,q:"“教室”的英语单词是____。",o:[],a:"classroom",k:"填空：教室 classroom",e:"解析：classroom = class + room，是四年级上册 Unit 1 的核心词汇。"},
{i:15,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:1,q:"“It's near the door.” 中 near 的意思是“在……____”。",o:[],a:"附近",k:"填空：near 意为附近",e:"解析：near 是方位介词，意为“在……附近”，用来描述物体的位置。"},
{i:16,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,d:2,q:"墙上的图画，下面表达正确的是？",o:["The picture is on the wall.","The picture is in the wall.","The picture is under the wall.","The picture is behind the wall."],a:0,k:"拔高：介词 on the wall",e:"解析：挂在墙的表面用 on the wall；in the wall 指嵌在墙体内部。这是方位介词最容易出错的地方。"},
{i:17,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,d:2,q:"“Let's clean the classroom.” 与 “Let me clean the windows.” 的区别是？",o:["前者是“让我们一起打扫教室”，后者是“让我来擦窗户”","两句意思完全一样","前者是问句，后者是祈使句","前者是过去发生的事，后者是现在的事"],a:0,k:"拔高：Let's 与 Let me 的区别",e:"解析：Let's = Let us，表示“让我们一起做”，包含说话人和对方；Let me 表示“让我来做”，只指说话人自己。"},
{i:18,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,d:2,q:"同学说 “Let's clean the classroom!”，你表示同意，最合适的回答是？",o:["Good idea!","I'm sorry.","No, you can't.","Thank you."],a:0,k:"拔高：对建议的应答",e:"解析：对 Let's... 的提议表示赞同，常用 Good idea!（好主意！）、OK!、Great! 等。"},
{i:19,c:"4en-1",ch:"四上·Unit 1 My classroom（教室与方位）",f:0,d:2,q:"你的图画不见了，想知道它在哪儿，应该问？",o:["Where is my picture?","What's in my picture?","How many pictures?","Whose picture is it?"],a:0,k:"拔高：Where is... 询问位置",e:"解析：询问物品的位置用 Where is...?，回答时可以用 It's + 方位短语。"},
// ══════════ 四上·Unit 2 My schoolbag 书包与颜色 ══════════
{i:20,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“schoolbag”的中文意思是？",o:["书包","铅笔盒","教科书","笔记本"],a:0,k:"词汇：schoolbag 书包",e:"解析：school（学校）+ bag（包）构成 schoolbag，意为“书包”。"},
{i:21,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“数学书”的英语是？",o:["maths book","English book","Chinese book","storybook"],a:0,k:"词汇：maths book 数学书",e:"解析：maths 是“数学”，maths book 就是“数学书”，也可以说 math book。"},
{i:22,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“英语书”的英语是？",o:["English book","maths book","Chinese book","notebook"],a:0,k:"词汇：English book 英语书",e:"解析：English book 意为“英语书”，注意 English 的首字母要大写。"},
{i:23,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“语文书”的英语是？",o:["Chinese book","English book","storybook","notebook"],a:0,k:"词汇：Chinese book 语文书",e:"解析：Chinese book 意为“语文书”，Chinese 的首字母也要大写。"},
{i:24,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“故事书”的英语是？",o:["storybook","notebook","schoolbag","picture"],a:0,k:"词汇：storybook 故事书",e:"解析：story（故事）+ book（书）构成 storybook，意为“故事书”。"},
{i:25,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“笔记本”的英语是？",o:["notebook","storybook","candy","key"],a:0,k:"词汇：notebook 笔记本",e:"解析：note（笔记）+ book（本子）构成 notebook，意为“笔记本”。"},
{i:26,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“糖果”的英语是？",o:["candy","toy","key","candle"],a:0,k:"词汇：candy 糖果",e:"解析：candy 意为“糖果”，是可数名词，复数为 candies。"},
{i:27,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“玩具”的英语是？",o:["toy","candy","key","notebook"],a:0,k:"词汇：toy 玩具",e:"解析：toy 意为“玩具”，复数为 toys，在词尾直接加 -s。"},
{i:28,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“钥匙”的英语是？",o:["key","candy","toy","light"],a:0,k:"词汇：key 钥匙",e:"解析：key 意为“钥匙”，复数为 keys，也可表示“答案、关键”。"},
{i:29,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"同学问你 “What's in your schoolbag?” 最合适的回答是？",o:["Three storybooks and a pencil box.","It's black and white.","Yes, it is.","It's near the door."],a:0,k:"句型：What's in your schoolbag 的答语",e:"解析：What's in...? 问的是里面有什么，要用物品名称作答；问颜色才回答 It's black and white."},
{i:30,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"想知道对方的书包是什么颜色，应该问？",o:["What colour is it?","What's in it?","Where is it?","How much is it?"],a:0,k:"句型：What colour is it",e:"解析：What colour is it? 意为“它是什么颜色的？”，用来询问颜色。"},
{i:31,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“It's black and white.” 的意思是？",o:["它是黑白相间的。","它是黑色的。","它是白色的。","它是又黑又脏的。"],a:0,k:"句型：It's black and white",e:"解析：A and B 用来描述两种颜色同时存在，black and white 就是“黑白相间的”。"},
{i:32,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“两本故事书”的英语是？",o:["two storybooks","two storybook","two storys","a storybook"],a:0,k:"语法：名词复数 two storybooks",e:"解析：数词 two 后面要用可数名词的复数形式，storybook 直接加 -s 变成 storybooks。"},
{i:33,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,q:"“我的书包很重。”的英语是？",o:["My schoolbag is heavy.","My schoolbag is light.","My schoolbag is new.","My schoolbag is nice."],a:0,k:"句型：My schoolbag is heavy",e:"解析：heavy 意为“重的”，light 意为“轻的”，两个词意思相反。"},
{i:34,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:1,q:"“书包”的英语单词是____。",o:[],a:"schoolbag",k:"填空：书包 schoolbag",e:"解析：schoolbag 是四年级上册 Unit 2 的核心单词，注意中间不用空格或连字符。"},
{i:35,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:1,q:"想知道颜色时，英语问句是 “What ____ is it?”。",o:[],a:"colour",k:"填空：What colour is it",e:"解析：colour（美式拼写 color）意为“颜色”，What colour is it? 用来询问颜色。"},
{i:36,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,d:2,q:"“What's in it?” 中的 it 指的是？",o:["前面提到过的书包","说话人自己","对方","教室"],a:0,k:"拔高：代词 it 的指代",e:"解析：it 是代词，用来代替前文提到过的单数事物。上句说的是 schoolbag，所以 it 指的就是这个书包。"},
{i:37,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,d:2,q:"下面哪个名词的复数形式是正确的？",o:["candy → candies","candy → candys","toy → toies","schoolbag → schoolbags 是错的"],a:0,k:"拔高：名词复数的拼写变化",e:"解析：以“辅音字母 + y”结尾的词变复数时，要把 y 变成 i 再加 -es，所以 candy → candies；toy 是“元音字母 + y”，直接加 -s 变成 toys。"},
{i:38,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,d:2,q:"读到 “I have a new schoolbag. It's black and white.”，下面说法正确的是？",o:["这个书包是黑白两种颜色","这个书包只有黑色","这个书包是旧的","这个书包里装着钥匙"],a:0,k:"拔高：阅读获取颜色信息",e:"解析：black and white 表明书包是黑白两色的，new 说明它是新的。"},
{i:39,c:"4en-2",ch:"四上·Unit 2 My schoolbag（书包与颜色）",f:0,d:2,q:"要同时描述两种颜色，英语应该怎么说？",o:["用 and 连接两种颜色，如 It's red and yellow.","用 or 连接两种颜色","把两种颜色写成两个句子","在两种颜色中间加 in"],a:0,k:"拔高：描述两种颜色的表达",e:"解析：描述物体的两种颜色用 A and B 的结构，如 It's blue and white.（它是蓝白相间的。）"},
// ══════════ 四上·Unit 3 My friends 描述朋友 ══════════
{i:40,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“friend”的中文意思是？",o:["朋友","同学","老师","家人"],a:0,k:"词汇：friend 朋友",e:"解析：friend 意为“朋友”，复数是 friends，如 my good friends（我的好朋友们）。"},
{i:41,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“长头发”的英语是？",o:["long hair","short hair","black hair","curly hair"],a:0,k:"词汇：long hair 长头发",e:"解析：long 意为“长的”，hair 意为“头发”，long hair 就是“长头发”。"},
{i:42,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“短头发”的英语是？",o:["short hair","long hair","thin hair","small hair"],a:0,k:"词汇：short hair 短头发",e:"解析：short hair 意为“短头发”，short 既可以表示“短的”，也可以表示“矮的”。"},
{i:43,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“thin”的中文意思是？",o:["瘦的","胖的","高的","安静的"],a:0,k:"词汇：thin 瘦的",e:"解析：thin 意为“瘦的”，它的反义词是 strong（强壮的）或 fat（胖的）。"},
{i:44,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“strong”的中文意思是？",o:["强壮的","瘦弱的","安静的","友好的"],a:0,k:"词汇：strong 强壮的",e:"解析：strong 意为“强壮的”，常用来形容体格结实的男生或女生。"},
{i:45,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“quiet”的中文意思是？",o:["安静的","吵闹的","友好的","聪明的"],a:0,k:"词汇：quiet 安静的",e:"解析：quiet 意为“安静的、文静的”，常用来描述性格，如 She is quiet.（她很文静。）"},
{i:46,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“眼镜”的英语是？",o:["glasses","shoes","hair","hat"],a:0,k:"词汇：glasses 眼镜",e:"解析：glasses 意为“眼镜”，表示眼镜时要一直用复数形式，如 He has glasses.（他戴眼镜。）"},
{i:47,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“鞋子”的英语是？",o:["shoes","glasses","hat","socks"],a:0,k:"词汇：shoes 鞋子",e:"解析：shoes 意为“鞋子”，成双出现，常用复数形式，如 My shoes are blue."},
{i:48,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"想询问照片里的男孩是谁，应该说？",o:["Who's he?","What's he?","How is he?","Where is he?"],a:0,k:"句型：Who's he",e:"解析：Who's he? 意为“他是谁？”，用来询问人的身份。"},
{i:49,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"想知道对方（男）的名字，应该说？",o:["What's his name?","What's her name?","What's your name?","What's my name?"],a:0,k:"句型：What's his name",e:"解析：his 是“他的”，问男孩或男性的名字用 What's his name?"},
{i:50,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“He's tall and strong.” 的意思是？",o:["他又高又壮。","他又高又瘦。","他很矮但很壮。","他又文静又友好。"],a:0,k:"句型：He's tall and strong",e:"解析：tall and strong 是两个形容词用 and 并列，共同描述同一个人的外貌。"},
{i:51,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“He has glasses and his shoes are blue.” 的意思是？",o:["他戴眼镜，他的鞋子是蓝色的。","他的眼镜和鞋子都是蓝色的。","他有蓝眼镜和蓝鞋子。","他的眼镜是蓝色的，鞋子是新的。"],a:0,k:"句型：He has glasses and his shoes are blue",e:"解析：has 表示“有、戴着”，his shoes are blue 则是用 be 动词描述颜色，两句用 and 连接。"},
{i:52,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“She ____ long hair.” 横线上应该填？",o:["has","have","is","are"],a:0,k:"语法：has 与 have",e:"解析：主语 She 是第三人称单数，表示“有”要用 has；have 用于 I、you、we、they 以及复数主语。"},
{i:53,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,q:"“My friend is quiet.” 的意思是？",o:["我的朋友很文静。","我的朋友很吵闹。","我的朋友很高。","我的朋友很强壮。"],a:0,k:"句型：My friend is quiet",e:"解析：quiet 是形容词，前面用 be 动词 is 构成“主语 + be + 形容词”的描述结构。"},
{i:54,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:1,q:"“朋友”的英语单词是____。",o:[],a:"friend",k:"填空：朋友 friend",e:"解析：friend 是四年级上册 Unit 3 的核心单词，复数为 friends。"},
{i:55,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:1,q:"“头发”的英语单词是____。",o:[],a:"hair",k:"填空：头发 hair",e:"解析：hair 意为“头发”。表示整体的头发时是不可数名词，如 long hair、short hair。"},
{i:56,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,d:2,q:"描述女孩的名字和她的头发，下面说法正确的是？",o:["Her name is Amy. She has long hair.","His name is Amy. He has long hair.","Her name is Amy. She have long hair.","Her name is Amy. She is long hair."],a:0,k:"拔高：her 与 has 的正确搭配",e:"解析：描述女孩用 her（她的），主语 She 后用 has，所以正确说法是 Her name is Amy. She has long hair."},
{i:57,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,d:2,q:"下面哪句话在语法上是正确的？",o:["He has short hair and big eyes.","He have short hair and big eyes.","He has short hair and big eye.","He have a short hair and big eyes."],a:0,k:"拔高：三单 has 与名词复数",e:"解析：主语 He 后用 has；眼睛是两只，要用复数 eyes。所以 He has short hair and big eyes. 正确。"},
{i:58,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,d:2,q:"“tall”的反义词是？",o:["short","long","thin","quiet"],a:0,k:"拔高：形容词的反义词",e:"解析：tall（高的）的反义词是 short（矮的）。注意 short 还可以表示“短的”，这时它反义于 long。"},
{i:59,c:"4en-3",ch:"四上·Unit 3 My friends（描述朋友）",f:0,d:2,q:"想介绍“这是我的好朋友，她又高又瘦”，应该怎么说？",o:["This is my good friend. She is tall and thin.","This is my good friend. She is tall and strong.","This is my good friend. He is tall and thin.","This is my good friend. She has tall and thin."],a:0,k:"拔高：介绍好友的综合表达",e:"解析：女孩用 she；描述外貌用“be + 形容词”；thin 是“瘦的”，与“又高又瘦”对应。"},
// ══════════ 四上·Unit 4 My home 房间与家具 ══════════
{i:60,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“home”的中文意思是？",o:["家","学校","教室","公园"],a:0,k:"词汇：home 家",e:"解析：home 意为“家”，强调温暖的生活场所；house 则侧重房屋本身。"},
{i:61,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“卧室”的英语是？",o:["bedroom","living room","study","kitchen"],a:0,k:"词汇：bedroom 卧室",e:"解析：bed（床）+ room（房间）构成 bedroom，意为“卧室”。"},
{i:62,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“客厅”的英语是？",o:["living room","bedroom","kitchen","bathroom"],a:0,k:"词汇：living room 客厅",e:"解析：living room 意为“客厅”，是一家人休息、看电视的地方。"},
{i:63,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“书房”的英语是？",o:["study","bedroom","kitchen","bathroom"],a:0,k:"词汇：study 书房",e:"解析：study 作名词时意为“书房”，作动词时意为“学习”，如 I study in the study.（我在书房学习。）"},
{i:64,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“厨房”的英语是？",o:["kitchen","bathroom","study","bedroom"],a:0,k:"词汇：kitchen 厨房",e:"解析：kitchen 意为“厨房”，是做饭的地方，妈妈常在厨房里做饭。"},
{i:65,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“浴室、卫生间”的英语是？",o:["bathroom","bedroom","kitchen","living room"],a:0,k:"词汇：bathroom 浴室",e:"解析：bath（洗澡）+ room（房间）构成 bathroom，意为“浴室、卫生间”。"},
{i:66,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“电话”的英语是？",o:["phone","fridge","table","sofa"],a:0,k:"词汇：phone 电话",e:"解析：phone 意为“电话”，是 telephone 的简略形式，如 answer the phone（接电话）。"},
{i:67,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“冰箱”的英语是？",o:["fridge","sofa","table","bed"],a:0,k:"词汇：fridge 冰箱",e:"解析：fridge 意为“冰箱”，是 refrigerator 的口语说法，一般放在厨房里。"},
{i:68,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"妈妈问你猫在哪里，你想说“它在客厅里”，应该说？",o:["It's in the living room.","It's on the living room.","It's under the living room.","It's the living room."],a:0,k:"句型：It's in the living room",e:"解析：表示“在某个房间里面”要用介词 in，所以是 in the living room。"},
{i:69,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“Is she in the study?” 的否定回答是？",o:["No, she isn't.","No, she doesn't.","No, she can't.","No, she is."],a:0,k:"句型：Is she ...? 的否定回答",e:"解析：以 Is 开头的一般疑问句，否定回答是 No, 主语 + isn't.，所以是 No, she isn't."},
{i:70,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“Are they in the kitchen?” 的肯定回答是？",o:["Yes, they are.","Yes, they do.","Yes, they is.","Yes, it is."],a:0,k:"句型：Are they ...? 的肯定回答",e:"解析：以 Are 开头的复数主语疑问句，肯定回答是 Yes, they are.，要用 are 与问句保持一致。"},
{i:71,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“The ball is behind the door.” 中 behind 的意思是？",o:["在……后面","在……前面","在……旁边","在……下面"],a:0,k:"介词：behind 在后面",e:"解析：behind 意为“在……后面”，是描述位置时常用的介词。"},
{i:72,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"“The cat is under the table.” 中 under 的意思是？",o:["在……下面","在……上面","在……附近","在……里面"],a:0,k:"介词：under 在下面",e:"解析：under 意为“在……下面”，如 under the bed（在床下）。"},
{i:73,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,q:"你找不到钥匙了，想问妈妈钥匙在哪里，应该说？",o:["Where is my key?","What is my key?","Who is my key?","How is my key?"],a:0,k:"句型：Where is my key",e:"解析：询问物品的位置要用 Where is...?，回答时用 It's + 方位短语。"},
{i:74,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:1,q:"“卧室”的英语单词是____。",o:[],a:"bedroom",k:"填空：卧室 bedroom",e:"解析：bedroom = bed + room，表示放床的房间，也就是卧室。"},
{i:75,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:1,q:"“厨房”的英语单词是____。",o:[],a:"kitchen",k:"填空：厨房 kitchen",e:"解析：kitchen 是四年级上册 Unit 4 的核心单词，注意拼写中有一个字母 t 和一个字母 ch。"},
{i:76,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,d:2,q:"“Are the books on the desk?” 的否定回答是？",o:["No, they aren't.","No, they don't.","No, it isn't.","No, they isn't."],a:0,k:"拔高：复数主语疑问句的否定回答",e:"解析：问句主语 the books 是复数，因此答语也必须用 they 和 aren't，不能换成 it。"},
{i:77,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,d:2,q:"“Where are the books?” 的正确回答是？",o:["They're on the table.","It's on the table.","They're table.","Yes, they are."],a:0,k:"拔高：复数问句用复数答语",e:"解析：问句用 books（复数）提问，答语要用 they 代替，并用 are。Where 提问不能用 Yes/No 回答。"},
{i:78,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,d:2,q:"“The picture is on the wall.” 和 “The picture is in the wall.” 的区别是？",o:["前者指画挂在墙面上，后者指画嵌在墙壁里面","两句意思完全一样","前者指画在墙后，后者指画在墙前","两句都是错的"],a:0,k:"拔高：on the wall 与 in the wall",e:"解析：on the wall 表示“在墙的表面上”（挂着），in the wall 表示“在墙体内部”（嵌着），如 a hole in the wall。"},
{i:79,c:"4en-4",ch:"四上·Unit 4 My home（房间与家具）",f:0,d:2,q:"读到 “My home is not big. There is a bed, a desk and a chair in my bedroom.”，下面说法正确的是？",o:["卧室里有床、书桌和椅子","家里有一间很大的卧室","卧室里只有一张床","书桌放在客厅里"],a:0,k:"拔高：阅读获取房间信息",e:"解析：not big 说明家不大；There is... 列举了卧室里的三件家具：床、书桌和椅子。"},
// ══════════ 四上·Unit 5 Dinner's ready 食物与用餐 ══════════
{i:80,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“dinner”的中文意思是？",o:["晚餐、正餐","早餐","午餐","点心"],a:0,k:"词汇：dinner 晚餐",e:"解析：dinner 意为“晚餐、正餐”，Dinner's ready! 就是“晚饭准备好了！”"},
{i:81,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“牛肉”的英语是？",o:["beef","chicken","fish","bread"],a:0,k:"词汇：beef 牛肉",e:"解析：beef 意为“牛肉”，是不可数名词，不能说 a beef。"},
{i:82,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“鸡肉”的英语是？",o:["chicken","beef","fish","soup"],a:0,k:"词汇：chicken 鸡肉",e:"解析：chicken 指“鸡肉”时不可数；指“小鸡”这种动物时是可数名词，复数为 chickens。"},
{i:83,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“面条”的英语是？",o:["noodles","rice","soup","vegetable"],a:0,k:"词汇：noodles 面条",e:"解析：noodles 意为“面条”，总是以复数形式出现，如 some noodles（一些面条）。"},
{i:84,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“汤”的英语是？",o:["soup","rice","milk","bread"],a:0,k:"词汇：soup 汤",e:"解析：soup 意为“汤”，是不可数名词，常用 a bowl of soup（一碗汤）来计数。"},
{i:85,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“蔬菜”的英语是？",o:["vegetable","fruit","bread","beef"],a:0,k:"词汇：vegetable 蔬菜",e:"解析：vegetable 意为“蔬菜”，是可数名词，复数为 vegetables。"},
{i:86,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“刀叉”的英语是？",o:["knife and fork","chopsticks","spoon","bowl"],a:0,k:"词汇：knife and fork 刀叉",e:"解析：knife 是“刀”，fork 是“叉”，西餐常用 knife and fork，中餐常用 chopsticks（筷子）。"},
{i:87,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“筷子”的英语是？",o:["chopsticks","knife and fork","spoon","bowl"],a:0,k:"词汇：chopsticks 筷子",e:"解析：chopsticks 意为“筷子”，总是用复数形式，如 I can use chopsticks.（我会用筷子。）"},
{i:88,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“勺子”的英语是？",o:["spoon","bowl","fork","knife"],a:0,k:"词汇：spoon 勺子",e:"解析：spoon 意为“勺子”，用来喝汤或舀食物；bowl 是“碗”，注意两者别混淆。"},
{i:89,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"妈妈问你晚饭想吃什么，她应该问？",o:["What would you like to eat?","What would you like to drink?","What colour is it?","Where is the dinner?"],a:0,k:"句型：What would you like to eat",e:"解析：问“想吃什么”用 What would you like to eat?；问“想喝什么”则把 eat 换成 drink。"},
{i:90,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"你想说“我想要一些汤和面包”，应该说？",o:["I'd like some soup and bread.","I'd like some soup and a bread.","I like soup and bread now.","I'd like any soup and bread."],a:0,k:"句型：I'd like some soup and bread",e:"解析：I'd like = I would like，表示“我想要”，后面接 some + 名词；soup 和 bread 都是不可数名词，不能加 a。"},
{i:91,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“What would you like to drink?” 最合适的回答是？",o:["I'd like some milk.","I'd like some rice.","I'd like a bowl.","I'd like a spoon."],a:0,k:"句型：What would you like to drink 的答语",e:"解析：drink 意为“喝”，所以要回答喝的饮料，如 milk、juice、water 等；rice 是吃的主食。"},
{i:92,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"别人问 “Would you like a knife and fork?”，你不需要，应该说？",o:["No, thanks. I can use chopsticks.","Yes, please.","No, I don't like it.","Thank you very much."],a:0,k:"句型：Would you like ...? 的应答",e:"解析：Would you like...? 是委婉的提议，接受说 Yes, please.，不接受说 No, thanks.，并可以补充原因。"},
{i:93,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,q:"“I can use chopsticks.” 中 can 的意思是？",o:["能、会","必须","想要","应该"],a:0,k:"语法：can 表示能力",e:"解析：can 是情态动词，表示“能够、会”，后面直接跟动词原形，没有人称和数的变化。"},
{i:94,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:1,q:"“晚餐、正餐”的英语单词是____。",o:[],a:"dinner",k:"填空：晚餐 dinner",e:"解析：dinner 意为“晚餐、正餐”，课文标题 Dinner's ready! 意为“晚饭准备好了！”"},
{i:95,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:1,q:"“筷子”的英语单词是____（复数形式）。",o:[],a:"chopsticks",k:"填空：筷子 chopsticks",e:"解析：筷子成双使用，所以要用复数形式 chopsticks，不能说 a chopstick。"},
{i:96,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,d:2,q:"主人对客人说 “Help yourself!”，这句话的意思是？",o:["请随便吃（别客气）！","请帮帮我！","请照顾好你自己！","请自己动手做菜！"],a:0,k:"拔高：Help yourself 的含义",e:"解析：Help yourself! 是餐桌上主人请客人“随便吃、别客气”的常用语，不是“帮助”的意思。"},
{i:97,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,d:2,q:"下面各组食物中，两个词都属于“不可数名词”的是？",o:["soup 和 bread","noodles 和 vegetable","candy 和 vegetable","noodles 和 candy"],a:0,k:"拔高：可数与不可数名词的区分",e:"解析：soup（汤）和 bread（面包）都是不可数名词，前面用 some 修饰；noodles、vegetables、candies 都是复数可数名词。"},
{i:98,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,d:2,q:"想知道对方想吃什么，下面问法正确的是？",o:["What would you like to eat?","What would you like eat?","What do you like to eating?","What are you like to eat?"],a:0,k:"拔高：would like to do 结构",e:"解析：would like 后面接不定式 to do，所以是 What would you like to eat?，to 不能省略。"},
{i:99,c:"4en-5",ch:"四上·Unit 5 Dinner's ready（食物与用餐）",f:0,d:2,q:"客人说 “I'd like some beef and rice.”，下面理解正确的是？",o:["客人想吃牛肉和米饭","客人想喝牛肉汤","客人只想要米饭","客人不想吃东西"],a:0,k:"拔高：理解点餐表达",e:"解析：I'd like... 表示“我想要……”，beef and rice 用 and 并列，说明客人要的是牛肉和米饭两样食物。"},
// ══════════ 四上·Unit 6 Meet my family! 家人与职业 ══════════
{i:100,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“family”的中文意思是？",o:["家庭、家人","朋友","同学","邻居"],a:0,k:"词汇：family 家庭",e:"解析：family 意为“家庭、家人”，既可指整个家庭，也可指家庭里的成员。"},
{i:101,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“父母”的英语是？",o:["parents","grandparents","cousins","uncles"],a:0,k:"词汇：parents 父母",e:"解析：parents 意为“父母（双亲）”，是 father 和 mother 的合称；grandparents 是“祖父母”。"},
{i:102,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“叔叔、舅舅”的英语是？",o:["uncle","aunt","cousin","brother"],a:0,k:"词汇：uncle 叔叔舅舅",e:"解析：uncle 意为“叔叔、舅舅、伯父”，英语中不区分父方还是母方的长辈男性。"},
{i:103,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“阿姨、姑姑”的英语是？",o:["aunt","uncle","cousin","sister"],a:0,k:"词汇：aunt 阿姨姑姑",e:"解析：aunt 意为“阿姨、姑姑、伯母”，与 uncle 相对应。"},
{i:104,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“小弟弟”的英语是？",o:["baby brother","cousin","uncle","brother"],a:0,k:"词汇：baby brother 小弟弟",e:"解析：baby 意为“婴儿、宝宝”，baby brother 就是家里的小弟弟。"},
{i:105,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“堂（表）兄弟姐妹”的英语是？",o:["cousin","uncle","aunt","parents"],a:0,k:"词汇：cousin 堂表兄弟姐妹",e:"解析：cousin 意为“堂兄弟姐妹、表兄弟姐妹”，不分男女，也不用区分父方母方。"},
{i:106,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“医生”的英语是？",o:["doctor","driver","farmer","nurse"],a:0,k:"词汇：doctor 医生",e:"解析：doctor 意为“医生”，也可以用作称呼，如 Doctor Li（李医生）。"},
{i:107,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“司机”的英语是？",o:["driver","doctor","cook","farmer"],a:0,k:"词汇：driver 司机",e:"解析：drive 是“驾驶”，加上 -r 变成 driver，意为“司机、驾驶员”。"},
{i:108,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“农民”的英语是？",o:["farmer","cook","nurse","driver"],a:0,k:"词汇：farmer 农民",e:"解析：farm 是“农场”，加上 -er 变成 farmer，意为“农民、农场主”。"},
{i:109,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“护士”的英语是？",o:["nurse","doctor","cook","driver"],a:0,k:"词汇：nurse 护士",e:"解析：nurse 意为“护士”，在医院里配合医生照顾病人。"},
{i:110,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"想知道对方家里有几口人，应该问？",o:["How many people are there in your family?","How much is your family?","Where is your family?","Who is your family?"],a:0,k:"句型：How many people in your family",e:"解析：How many 用来问可数名词的数量，people 是 person 的复数，问“几口人”要用它。"},
{i:111,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"想知道对方爸爸做什么工作，应该问？",o:["What's your father's job?","What's your father's name?","Where is your father?","How old is your father?"],a:0,k:"句型：What's your father's job",e:"解析：What's ... job? 用来询问职业，your father's 是名词所有格，表示“你爸爸的”。"},
{i:112,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“Is this your uncle?” 的肯定回答是？",o:["Yes, it is.","Yes, he is.","Yes, this is.","Yes, I am."],a:0,k:"句型：Is this ...? 的答语",e:"解析：问句的主语是 this，答语里要用 it 代替 this，所以肯定回答是 Yes, it is."},
{i:113,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,q:"“my father's job” 中 father's 表示的意思是？",o:["爸爸的","爸爸们","爸爸是","和爸爸一起的"],a:0,k:"语法：名词所有格 's",e:"解析：在表示人的名词后加 's，构成名词所有格，表示“……的”，father's job 就是“爸爸的工作”。"},
{i:114,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:1,q:"“家庭、家人”的英语单词是____。",o:[],a:"family",k:"填空：家庭 family",e:"解析：family 是四年级上册 Unit 6 的核心单词，复数为 families（把 y 变 i 再加 -es）。"},
{i:115,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:1,q:"“医生”的英语单词是____。",o:[],a:"doctor",k:"填空：医生 doctor",e:"解析：doctor 意为“医生”，回答职业时常用 He's a doctor. / She's a doctor."},
{i:116,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,d:2,q:"下面哪个句子在语法上是正确的？",o:["How many people are there in your family?","How many peoples are there in your family?","How much people are there in your family?","How many person are there in your family?"],a:0,k:"拔高：How many 与 people",e:"解析：How many 后接可数名词复数；people 本身就是复数形式，不能加 -s，也不能换成人单数 person。"},
{i:117,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,d:2,q:"“我妈妈是一名护士。”的英语是？",o:["My mother is a nurse.","My mother is a doctor.","My mother is nurse.","My mother is an nurse."],a:0,k:"拔高：介绍职业的句型",e:"解析：介绍职业用“主语 + be + a/an + 职业”，nurse 以辅音音素开头，用 a 而不是 an。"},
{i:118,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,d:2,q:"读到 “This is my family. There are four people in my family: my parents, my sister and me.”，下面说法正确的是？",o:["家里共有四口人","家里共有三个人","这个家庭里没有姐妹","作者的父母不在家里"],a:0,k:"拔高：阅读获取家庭信息",e:"解析：four people 说明共四口人，后面列出了父母、姐姐（妹妹）和作者本人，正好对应四个人。"},
{i:119,c:"4en-6",ch:"四上·Unit 6 Meet my family!（家人与职业）",f:0,d:2,q:"向别人介绍自己的家人和职业时，最合适的说法是？",o:["This is my father. He is a doctor.","This is my father. He is doctor.","This is my father. He doctor.","This is my father. He have a doctor."],a:0,k:"拔高：介绍家人职业的综合表达",e:"解析：介绍家人的职业要用“This is + 家人. He/She is a + 职业.”的结构，be 动词和冠词都不能省略。"},
// ══════════ 四下·Unit 1 My school 学校场所与方位 ══════════
{i:120,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“school”的中文意思是？",o:["学校","教室","图书馆","操场"],a:0,k:"词汇：school 学校",e:"解析：school 意为“学校”，go to school 就是“去上学”。"},
{i:121,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“操场”的英语是？",o:["playground","garden","library","gym"],a:0,k:"词汇：playground 操场",e:"解析：playground 由 play（玩）+ ground（场地）构成，意为“操场”，是同学们做操、玩耍的地方。"},
{i:122,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“花园”的英语是？",o:["garden","playground","canteen","library"],a:0,k:"词汇：garden 花园",e:"解析：garden 意为“花园”，学校里的小花园常种着各种花草。"},
{i:123,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“图书馆”的英语是？",o:["library","canteen","gym","art room"],a:0,k:"词汇：library 图书馆",e:"解析：library 意为“图书馆”，是借书、看书的地方，复数为 libraries。"},
{i:124,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“食堂”的英语是？",o:["canteen","library","gym","garden"],a:0,k:"词汇：canteen 食堂",e:"解析：canteen 意为“食堂”，是学校里吃饭的地方，中午同学们在这里吃午饭。"},
{i:125,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“美术教室”的英语是？",o:["art room","music room","computer room","library"],a:0,k:"词汇：art room 美术教室",e:"解析：art 意为“美术、艺术”，art room 就是上美术课的专用教室。"},
{i:126,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“计算机房”的英语是？",o:["computer room","art room","music room","canteen"],a:0,k:"词汇：computer room 计算机房",e:"解析：computer room 意为“计算机房”，是上信息技术课的地方。"},
{i:127,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“音乐教室”的英语是？",o:["music room","art room","computer room","gym"],a:0,k:"词汇：music room 音乐教室",e:"解析：music room 意为“音乐教室”，同学们在里面唱歌、上音乐课。"},
{i:128,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“体育馆”的英语是？",o:["gym","playground","canteen","garden"],a:0,k:"词汇：gym 体育馆",e:"解析：gym 意为“体育馆”，是室内运动的地方，与室外的 playground（操场）不同。"},
{i:129,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“图书馆在哪里？”的英语是？",o:["Where is the library?","What is the library?","Who is in the library?","How is the library?"],a:0,k:"句型：Where is the library",e:"解析：询问场所的位置用 Where is...?，答语常用 It's on the ... floor."},
{i:130,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“It's on the second floor.” 中 second 的意思是？",o:["第二","第一","第三","两层"],a:0,k:"序数词：second 第二",e:"解析：second 是序数词，意为“第二”，on the second floor 就是“在二楼（第二层）”。"},
{i:131,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“Is this the teachers' office?” 的肯定回答是？",o:["Yes, it is.","Yes, this is.","Yes, they are.","Yes, we are."],a:0,k:"句型：Is this ...? 的肯定回答",e:"解析：问句主语是 this，答语中用 it 代替，因此是 Yes, it is."},
{i:132,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“Do you have a library?” 的肯定回答是？",o:["Yes, we do.","Yes, we are.","Yes, it is.","Yes, I have."],a:0,k:"句型：Do you have ...? 的答语",e:"解析：Do you...? 的肯定回答是 Yes, we do.，否定回答是 No, we don't.，用助动词 do 呼应问句。"},
{i:133,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,q:"“The art room is next to the music room.” 中 next to 的意思是？",o:["在……旁边","在……上面","在……前面","在……对面"],a:0,k:"短语：next to 在旁边",e:"解析：next to 意为“在……旁边、紧挨着”，用来描述两个场所相邻的位置关系。"},
{i:134,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:1,q:"“图书馆”的英语单词是____。",o:[],a:"library",k:"填空：图书馆 library",e:"解析：library 是四年级下册 Unit 1 的核心单词，复数为 libraries。"},
{i:135,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:1,q:"“操场”的英语单词是____。",o:[],a:"playground",k:"填空：操场 playground",e:"解析：playground 是同学们做操、上体育课的地方，由 play + ground 合成。"},
{i:136,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,d:2,q:"“第一、第二、第三”的英语分别是？",o:["first, second, third","one, two, three","first, two, third","one, second, three"],a:0,k:"拔高：序数词 first second third",e:"解析：one、two、three 是基数词（表示数量），first、second、third 是序数词（表示顺序），描述楼层要用序数词。"},
{i:137,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,d:2,q:"“Do you have an art room?” 的否定回答是？",o:["No, we don't.","No, we aren't.","No, it isn't.","No, I don't have."],a:0,k:"拔高：Do you have ...? 的否定回答",e:"解析：以 Do 开头的问句，否定回答是 No, we don't.。答语中要用助动词 don't，不能换成 be 动词。"},
{i:138,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,d:2,q:"读到 “My school is big. The library is on the first floor. The computer room is next to it.”，下面说法正确的是？",o:["图书馆和计算机房在同一层且相邻","图书馆在二楼","计算机房在图书馆的楼上","学校里没有图书馆"],a:0,k:"拔高：阅读获取校园场所位置",e:"解析：next to it 表示计算机房紧挨着图书馆，而图书馆在第一层，可见两者都在第一层且相邻。"},
{i:139,c:"4en-7",ch:"四下·Unit 1 My school（学校场所与方位）",f:0,d:2,q:"想告诉别人“教室在二楼”，最合适的说法是？",o:["The classroom is on the second floor.","The classroom is in the second floor.","The classroom is at the second floor.","The classroom is second floor."],a:0,k:"拔高：描述楼层的介词搭配",e:"解析：表示“在第几层”要用 on the ... floor，不能用 in 或 at，floor 前的 the 也不能省略。"},
// ══════════ 四下·Unit 2 What time is it? 时间表达 ══════════
{i:140,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“time”的中文意思是？",o:["时间","时候的人","次数很多","时刻表"],a:0,k:"词汇：time 时间",e:"解析：time 意为“时间”，What time is it? 就是最常用的问时间的句子。"},
{i:141,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“o'clock”在英语中用来表示？",o:["整点","半点","一刻钟","分钟"],a:0,k:"词汇：o'clock 整点",e:"解析：o'clock 意为“……点钟”，只用于整点，如 It's seven o'clock.（现在七点钟。）"},
{i:142,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“早餐”的英语是？",o:["breakfast","lunch","dinner","supper"],a:0,k:"词汇：breakfast 早餐",e:"解析：breakfast 意为“早餐”，have breakfast 是“吃早餐”，通常在早上七点左右。"},
{i:143,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“午餐”的英语是？",o:["lunch","breakfast","dinner","meal"],a:0,k:"词汇：lunch 午餐",e:"解析：lunch 意为“午餐”，have lunch 是“吃午饭”，一般在中午十二点左右。"},
{i:144,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"一天三餐中，晚饭的英语是？",o:["dinner","lunch","breakfast","snack"],a:0,k:"词汇：dinner 晚饭",e:"解析：dinner 表示“晚餐、正餐”，通常是一天中最正式的一餐。"},
{i:145,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“起床”的英语是？",o:["get up","go to bed","go home","stand up"],a:0,k:"短语：get up 起床",e:"解析：get up 意为“起床”，反义短语是 go to bed（上床睡觉）。"},
{i:146,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“去上学”的英语是？",o:["go to school","go home","go to bed","go out"],a:0,k:"短语：go to school 去上学",e:"解析：go to school 意为“去上学”，注意 school 前不加 the；go home 则是“回家”，home 前也不加 to。"},
{i:147,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“回家”的英语是？",o:["go home","go to home","go to house","come school"],a:0,k:"短语：go home 回家",e:"解析：home 在这里是副词，前面不加 to，所以是 go home，不能写成 go to home。"},
{i:148,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“上床睡觉”的英语是？",o:["go to bed","get up","go home","go to school"],a:0,k:"短语：go to bed 上床睡觉",e:"解析：go to bed 意为“上床睡觉”，注意 bed 前有 the；而 get up 是“起床”，意思相反。"},
{i:149,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"想知道现在几点了，应该问？",o:["What time is it?","What day is it?","What's the weather like?","How are you?"],a:0,k:"句型：What time is it",e:"解析：What time is it? 意为“现在几点了？”，答语是 It's + 时间。"},
{i:150,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“It's time for English class.” 的意思是？",o:["该上英语课了。","英语课很有趣。","现在是英语时间吗？","我不喜欢英语课。"],a:0,k:"句型：It's time for + 课程",e:"解析：It's time for + 名词，表示“到……的时间了”，for 后面接名词或名词短语。"},
{i:151,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“该睡觉了。”的英语是？",o:["It's time to go to bed.","It's time for go to bed.","It's time go to bed.","It's time to bed."],a:0,k:"句型：It's time to do",e:"解析：It's time to + 动词原形，表示“该做某事了”。go to bed 是动词短语，所以要用 to。"},
{i:152,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"“Hurry up!” 的意思是？",o:["快点！","慢一点！","别动！","安静！"],a:0,k:"短语：Hurry up 快点",e:"解析：Hurry up! 意为“快点！”，常用来催促别人加快速度。"},
{i:153,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,q:"别人催你快一点，你想说“稍等一下”，应该说？",o:["Just a minute.","Hurry up.","Come on.","Here you are."],a:0,k:"短语：Just a minute 稍等一下",e:"解析：Just a minute. 意为“稍等一下、马上就好”，用来回应别人的催促。"},
{i:154,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:1,q:"表示整点时，英语中常用“It's seven ____.”。",o:[],a:"o'clock",k:"填空：整点 o'clock",e:"解析：o'clock 只能用于整点，如 seven o'clock（七点整）。"},
{i:155,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:1,q:"“早餐”的英语单词是____。",o:[],a:"breakfast",k:"填空：早餐 breakfast",e:"解析：breakfast 是四年级下册 Unit 2 的核心单词，常用 have breakfast（吃早餐）。"},
{i:156,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,d:2,q:"“It's time for lunch.” 和 “It's time to have lunch.” 的关系是？",o:["两句意思相同，只是 for 后面接名词、to 后面接动词","两句意思完全不同","前者是问句，后者是陈述句","后者是错的，英语中不存在这种说法"],a:0,k:"拔高：It's time for 与 It's time to",e:"解析：It's time for + 名词 与 It's time to + 动词原形 意思相同，可以互相转换：for lunch = to have lunch。"},
{i:157,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,d:2,q:"读到作息表 “6:30 get up; 7:00 go to school; 12:00 have lunch; 9:00 go to bed.”，下面说法正确的是？",o:["七点去上学，九点睡觉","六点半去上学，七点起床","十二点起床","九点吃午饭"],a:0,k:"拔高：阅读作息时间表",e:"解析：时间与活动要一一对应：6:30 起床、7:00 上学、12:00 吃午饭、9:00 睡觉。"},
{i:158,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,d:2,q:"早上七点了，妈妈提醒你该去上学，她应该说？",o:["It's time to go to school.","It's time for go school.","It's time to go to bed.","It's time for lunch."],a:0,k:"拔高：用 It's time to 提醒做某事",e:"解析：去上学是动词短语，所以用 It's time to go to school.。to 后面必须跟动词原形。"},
{i:159,c:"4en-8",ch:"四下·Unit 2 What time is it?（时间表达）",f:0,d:2,q:"回答 “What time is it?” 时，下面答语正确的是？",o:["It's 9 o'clock.","It's Monday.","It's sunny.","I'm nine."],a:0,k:"拔高：正确回答时间问句",e:"解析：What time is it? 问的是时刻，要用 It's + 时间 作答。It's Monday 回答的是星期，It's sunny 回答的是天气。"},
// ══════════ 四下·Unit 3 Weather 天气 ══════════
{i:160,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“weather”的中文意思是？",o:["天气","星期","温度计","季节"],a:0,k:"词汇：weather 天气",e:"解析：weather 意为“天气”，What's the weather like? 就是询问天气的常用句型。"},
{i:161,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“寒冷的”英语是？",o:["cold","cool","warm","hot"],a:0,k:"词汇：cold 寒冷的",e:"解析：cold 意为“寒冷的”，是描述天气时表示温度最低的词。"},
{i:162,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“凉爽的”英语是？",o:["cool","cold","warm","hot"],a:0,k:"词汇：cool 凉爽的",e:"解析：cool 意为“凉爽的”，比 cold 温和，常用于秋天的天气。"},
{i:163,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“温暖的”英语是？",o:["warm","cool","hot","cold"],a:0,k:"词汇：warm 温暖的",e:"解析：warm 意为“温暖的”，常用来描述春天的天气。"},
{i:164,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“炎热的”英语是？",o:["hot","warm","cool","cold"],a:0,k:"词汇：hot 炎热的",e:"解析：hot 意为“炎热的”，是描述天气时表示温度最高的词。"},
{i:165,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“晴朗的”英语是？",o:["sunny","cloudy","rainy","windy"],a:0,k:"词汇：sunny 晴朗的",e:"解析：sunny 由 sun（太阳）+ ny 构成，意为“晴朗的”。"},
{i:166,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“下雨的”英语是？",o:["rainy","snowy","windy","cloudy"],a:0,k:"词汇：rainy 下雨的",e:"解析：rainy 由 rain（雨）+ y 构成，意为“下雨的”，如 a rainy day（下雨天）。"},
{i:167,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“有风的、刮风的”英语是？",o:["windy","rainy","sunny","cloudy"],a:0,k:"词汇：windy 刮风的",e:"解析：windy 由 wind（风）+ y 构成，意为“有风的”，如 It's windy today."},
{i:168,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“多云的”英语是？",o:["cloudy","sunny","snowy","rainy"],a:0,k:"词汇：cloudy 多云的",e:"解析：cloudy 由 cloud（云）+ y 构成，意为“多云的、阴天的”。"},
{i:169,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“下雪的”英语是？",o:["snowy","rainy","windy","cloudy"],a:0,k:"词汇：snowy 下雪的",e:"解析：snowy 由 snow（雪）+ y 构成，意为“下雪的”，如 a snowy day（下雪天）。"},
{i:170,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"想知道北京的天气怎么样，应该问？",o:["What's the weather like in Beijing?","Where is Beijing?","What time is it in Beijing?","How many people in Beijing?"],a:0,k:"句型：What's the weather like",e:"解析：What's the weather like? 意为“……天气怎么样？”，后面可以接 in + 地点。"},
{i:171,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“It's sunny and warm.” 的意思是？",o:["天气晴朗又温暖。","天气晴朗又寒冷。","天气多风又凉爽。","天气下雨又温暖。"],a:0,k:"句型：It's sunny and warm",e:"解析：两个天气形容词用 and 并列，共同描述同一天的天气状况。"},
{i:172,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“Can I go outside now?” 的肯定回答是？",o:["Yes, you can.","Yes, I can.","Yes, you are.","Yes, you do."],a:0,k:"句型：Can I ...? 的答语",e:"解析：以 Can I 开头的问句，肯定回答用 Yes, you can.，不能回答 Yes, I can.（那是自己回答自己）。"},
{i:173,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,q:"“degree”在描述天气时表示？",o:["度（温度单位）","等级","程度","步"],a:0,k:"词汇：degree 度",e:"解析：degree 意为“度”，描述气温时常用，如 25 degrees（25 度）。"},
{i:174,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:1,q:"“天气”的英语单词是____。",o:[],a:"weather",k:"填空：天气 weather",e:"解析：weather 是四年级下册 Unit 3 的核心单词，注意与 whether 的拼写区别。"},
{i:175,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:1,q:"“晴朗的”英语单词是____（由 sun 加后缀构成）。",o:[],a:"sunny",k:"填空：晴朗的 sunny",e:"解析：sunny 由 sun 双写 n 再加 -y 构成，意为“晴朗的”。"},
{i:176,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,d:2,q:"“Can I go outside now?” 的否定回答是？",o:["No, you can't.","No, I can't.","No, you don't.","No, you aren't."],a:0,k:"拔高：Can I ...? 的否定回答",e:"解析：Can I...? 的否定回答是 No, you can't.，与肯定回答 Yes, you can. 一样，人称都用 you。"},
{i:177,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,d:2,q:"读到 “It's snowy in Harbin and it's hot in Sanya.”，下面说法正确的是？",o:["哈尔滨下雪，三亚炎热","哈尔滨炎热，三亚下雪","两地都是阴天","两地都下雨"],a:0,k:"拔高：阅读比较两地天气",e:"解析：snowy 表示“下雪的”，hot 表示“炎热的”，两个城市一冷一热，对比明显。"},
{i:178,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,d:2,q:"把 cold、cool、warm、hot 按气温从低到高排列，正确的是？",o:["cold → cool → warm → hot","hot → warm → cool → cold","cool → cold → warm → hot","warm → cool → cold → hot"],a:0,k:"拔高：天气形容词的程度排序",e:"解析：cold（寒冷）＜ cool（凉爽）＜ warm（温暖）＜ hot（炎热），这是按温度由低到高的正确顺序。"},
{i:179,c:"4en-9",ch:"四下·Unit 3 Weather（天气）",f:0,d:2,q:"“How's the weather today?” 与下面哪一句意思最接近？",o:["What's the weather like today?","What time is it today?","What day is it today?","How are you today?"],a:0,k:"拔高：询问天气的两种说法",e:"解析：How's the weather? 与 What's the weather like? 都用来询问天气状况，意思基本相同。"},
// ══════════ 四下·Unit 4 At the farm 农场与动物 ══════════
{i:180,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“farm”的中文意思是？",o:["农场","花园","公园","工厂"],a:0,k:"词汇：farm 农场",e:"解析：farm 意为“农场”，在农场里种菜、养牲畜的人叫 farmer（农民）。"},
{i:181,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“西红柿”的英语是？",o:["tomato","potato","carrot","green beans"],a:0,k:"词汇：tomato 西红柿",e:"解析：tomato 意为“西红柿”，复数是 tomatoes，要加 -es。"},
{i:182,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“土豆”的英语是？",o:["potato","tomato","carrot","onion"],a:0,k:"词汇：potato 土豆",e:"解析：potato 意为“土豆、马铃薯”，复数是 potatoes，同样加 -es。"},
{i:183,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“四季豆”的英语是？",o:["green beans","carrots","tomatoes","potatoes"],a:0,k:"词汇：green beans 四季豆",e:"解析：green beans 意为“四季豆、青豆角”，总是用复数形式。"},
{i:184,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“胡萝卜”的英语是？",o:["carrot","tomato","potato","bean"],a:0,k:"词汇：carrot 胡萝卜",e:"解析：carrot 意为“胡萝卜”，复数是 carrots，在词尾直接加 -s。"},
{i:185,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“马”的英语是？",o:["horse","cow","sheep","goat"],a:0,k:"词汇：horse 马",e:"解析：horse 意为“马”，复数是 horses，如 How many horses?（有多少匹马？）"},
{i:186,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“奶牛”的英语是？",o:["cow","horse","hen","goat"],a:0,k:"词汇：cow 奶牛",e:"解析：cow 意为“奶牛”，农场里养奶牛主要是为了产牛奶。"},
{i:187,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“绵羊”的英语是？",o:["sheep","goat","hen","cow"],a:0,k:"词汇：sheep 绵羊",e:"解析：sheep 意为“绵羊”，单数和复数形式相同，如 three sheep（三只绵羊）。"},
{i:188,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“母鸡”的英语是？",o:["hen","cow","horse","sheep"],a:0,k:"词汇：hen 母鸡",e:"解析：hen 意为“母鸡”，主要用来下蛋；小鸡则是 chicken。"},
{i:189,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“山羊”的英语是？",o:["goat","sheep","cow","hen"],a:0,k:"词汇：goat 山羊",e:"解析：goat 意为“山羊”，与 sheep（绵羊）不同，山羊通常长着向后弯的角。"},
{i:190,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"指着手边的几个西红柿问“这些是什么”，应该说？",o:["What are these?","What are those?","What is this?","What is that?"],a:0,k:"句型：What are these",e:"解析：these 指离说话人较近的多个事物，是 this 的复数；those 指较远的多个事物。"},
{i:191,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"远处有几匹马，想问“那些是什么”，应该说？",o:["What are those?","What are these?","What is that?","What is this?"],a:0,k:"句型：What are those",e:"解析：those 是 that 的复数形式，指离说话人较远的多个事物，所以问远处的东西用 What are those?"},
{i:192,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“Are these carrots?” 的肯定回答是？",o:["Yes, they are.","Yes, these are.","Yes, it is.","Yes, we are."],a:0,k:"句型：Are these ...? 的答语",e:"解析：问句主语是 these，答语中要用 they 代替，所以是 Yes, they are."},
{i:193,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,q:"“animal”的中文意思是？",o:["动物","植物","蔬菜","农场"],a:0,k:"词汇：animal 动物",e:"解析：animal 意为“动物”，复数是 animals，农场里的马、牛、羊、鸡都属于 animals。"},
{i:194,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:1,q:"“农场”的英语单词是____。",o:[],a:"farm",k:"填空：农场 farm",e:"解析：farm 是四年级下册 Unit 4 的核心单词，farmer 就是“农民”。"},
{i:195,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:1,q:"“西红柿”的英语单词是 tomato，它的复数形式是____。",o:[],a:"tomatoes",k:"填空：tomato 的复数",e:"解析：以字母 o 结尾的部分名词（tomato、potato）变复数时要在词尾加 -es。"},
{i:196,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,d:2,q:"these 和 those 的主要区别是？",o:["these 指较近的多个事物，those 指较远的多个事物","these 指一个，those 指很多","these 指人，those 指物","两者没有区别，可以随意替换"],a:0,k:"拔高：these 与 those 的区别",e:"解析：this/these 指空间上较近的人或物，that/those 指较远的；these 和 those 都是复数形式。"},
{i:197,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,d:2,q:"“农场里有三只绵羊”的英语是？",o:["There are three sheep on the farm.","There are three sheeps on the farm.","There are three sheep on farm.","There is three sheep on the farm."],a:0,k:"拔高：sheep 单复数同形",e:"解析：sheep 的复数与单数形式相同，不能加 -s；同时主语是复数，be 动词要用 are。"},
{i:198,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,d:2,q:"想知道对方有多少匹马，应该问？",o:["How many horses do you have?","How much horses do you have?","How many horse do you have?","How many horses you have?"],a:0,k:"拔高：How many + 复数名词",e:"解析：How many 后面必须接可数名词的复数形式 horses；How much 用来问不可数名词的量或价格。"},
{i:199,c:"4en-10",ch:"四下·Unit 4 At the farm（农场与动物）",f:0,d:2,q:"读到 “Welcome to my farm! These are tomatoes and those are potatoes. There are also twelve sheep and ten hens.”，下面说法正确的是？",o:["农场里既有蔬菜又有家畜，绵羊有十二只","农场里只有蔬菜，没有动物","农场里养了十只绵羊","这些是土豆，那些是西红柿"],a:0,k:"拔高：阅读获取农场信息",e:"解析：these 指近处的西红柿、those 指远处的土豆，此外还有十二只绵羊和十只母鸡，既有植物也有动物。"},
// ══════════ 四下·Unit 5 My clothes 衣物 ══════════
{i:200,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“clothes”的中文意思是？",o:["衣服（总称）","布","衣柜","雨伞"],a:0,k:"词汇：clothes 衣服",e:"解析：clothes 意为“衣服”，是复数名词，永远不能加 a，也不能说 a clothes。"},
{i:201,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“裤子”的英语是？",o:["pants","shorts","socks","shoes"],a:0,k:"词汇：pants 裤子",e:"解析：pants 意为“裤子”，英语中裤子有两条腿，所以一直用复数形式。"},
{i:202,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“连衣裙”的英语是？",o:["dress","skirt","coat","shirt"],a:0,k:"词汇：dress 连衣裙",e:"解析：dress 意为“连衣裙”，是上下连在一起的女性服装，与只有下半身的 skirt 不同。"},
{i:203,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“短裙”的英语是？",o:["skirt","dress","shorts","sweater"],a:0,k:"词汇：skirt 短裙",e:"解析：skirt 意为“短裙、裙子”，只覆盖腰部以下的部分。"},
{i:204,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“外套”的英语是？",o:["coat","sweater","jacket","shirt"],a:0,k:"词汇：coat 外套",e:"解析：coat 意为“外套、大衣”，通常穿在最外面，天冷时用来保暖。"},
{i:205,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“毛衣”的英语是？",o:["sweater","coat","jacket","dress"],a:0,k:"词汇：sweater 毛衣",e:"解析：sweater 意为“毛衣、厚运动衫”，是秋冬常穿的针织衣物。"},
{i:206,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“袜子”的英语是？",o:["socks","shoes","pants","gloves"],a:0,k:"词汇：socks 袜子",e:"解析：socks 意为“袜子”，成双穿用，常用复数形式，如 a pair of socks（一双袜子）。"},
{i:207,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“短裤”的英语是？",o:["shorts","pants","socks","skirts"],a:0,k:"词汇：shorts 短裤",e:"解析：shorts 意为“短裤”，同样以复数形式出现，与长的 pants 相对。"},
{i:208,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“夹克衫”的英语是？",o:["jacket","coat","shirt","sweater"],a:0,k:"词汇：jacket 夹克衫",e:"解析：jacket 意为“夹克衫”，比较轻便，通常和 jeans 一起穿。"},
{i:209,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“衬衫”的英语是？",o:["shirt","skirt","shorts","socks"],a:0,k:"词汇：shirt 衬衫",e:"解析：shirt 意为“衬衫”，注意与 skirt（短裙）的拼写只差一个字母，不要混淆。"},
{i:210,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“whose”的中文意思是？",o:["谁的","什么","哪一个","多少"],a:0,k:"词汇：whose 谁的",e:"解析：whose 意为“谁的”，专门用来询问物品的归属，如 Whose book is this?"},
{i:211,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“Whose pants are these?” 最合适的回答是？",o:["They're mine.","It's mine.","Yes, they are.","They're on the bed."],a:0,k:"句型：Whose ... are these 的答语",e:"解析：问句用 are these（复数），答语要用 they；Whose 问归属，答语要说明是谁的，mine 意为“我的”。"},
{i:212,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“Are these your shoes?” 的否定回答是？",o:["No, they aren't.","No, it isn't.","No, these aren't.","No, I'm not."],a:0,k:"句型：Are these ...? 的否定回答",e:"解析：问句主语 these 在答语中换成 they，所以否定回答是 No, they aren't."},
{i:213,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,q:"“Put on your jacket.” 的意思是？",o:["穿上你的夹克衫。","脱下你的夹克衫。","把你的夹克衫挂起来。","把你的夹克衫洗一洗。"],a:0,k:"短语：put on 穿上",e:"解析：put on 意为“穿上、戴上”，反义短语是 take off（脱下）。"},
{i:214,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:1,q:"“衣服（总称）”的英语单词是____。",o:[],a:"clothes",k:"填空：衣服 clothes",e:"解析：clothes 是复数名词，表示衣服的总称，前面不能用 a，但可以说 my clothes。"},
{i:215,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:1,q:"询问物品“是谁的”，英语用疑问词____。",o:[],a:"whose",k:"填空：疑问词 whose",e:"解析：whose 意为“谁的”，用来询问物品的归属，后面直接接名词，如 Whose coat is this?"},
{i:216,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,d:2,q:"“It's my coat.” 和 “It's mine.” 的关系是？",o:["两句意思相同，mine 相当于 my coat","两句意思相反","my 用来代替 mine","后者是错的"],a:0,k:"拔高：my 与 mine 的区别",e:"解析：my 是形容词性物主代词，后面必须接名词；mine 是名词性物主代词，本身就相当于 my + 名词，后面不能再接名词。"},
{i:217,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,d:2,q:"天气很热，进门后你应该做什么？",o:["Take off your coat.","Put on your coat.","Wash your coat.","Buy a new coat."],a:0,k:"拔高：put on 与 take off 的使用情境",e:"解析：天热时应该脱下外套，所以用 take off；天冷或出门时才用 put on。"},
{i:218,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,d:2,q:"读到 “Whose skirt is this? It's Sarah's. Those pants are John's.”，下面说法正确的是？",o:["短裙是 Sarah 的，裤子是 John 的","短裙是 John 的，裤子是 Sarah 的","两件都是 Sarah 的","两件都是 John 的"],a:0,k:"拔高：阅读判断衣物归属",e:"解析：Sarah's 表示“Sarah 的”，John's 表示“John 的”，分别对应裙子和裤子。"},
{i:219,c:"4en-11",ch:"四下·Unit 5 My clothes（衣物）",f:0,d:2,q:"“Whose dress is this? It's ____.” 如果裙子是 Amy 的，横线上最合适的词是？",o:["hers","her","she","she's"],a:0,k:"拔高：名词性物主代词 hers",e:"解析：hers 相当于 her dress，意为“她的（裙子）”，后面不能再接名词；her 后面必须跟名词。"},
// ══════════ 四下·Unit 6 Shopping 购物 ══════════
{i:220,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“shopping”的中文意思是？",o:["购物","商店","售货员","零钱"],a:0,k:"词汇：shopping 购物",e:"解析：shopping 意为“购物”，go shopping 就是“去购物”，shop 是“商店”。"},
{i:221,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“漂亮的”英语是？",o:["pretty","cheap","expensive","nice"],a:0,k:"词汇：pretty 漂亮的",e:"解析：pretty 意为“漂亮的、可爱的”，常用来形容衣物、饰品等。"},
{i:222,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“昂贵的”英语是？",o:["expensive","cheap","pretty","big"],a:0,k:"词汇：expensive 昂贵的",e:"解析：expensive 意为“昂贵的”，它的反义词是 cheap（便宜的）。"},
{i:223,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“便宜的”英语是？",o:["cheap","expensive","pretty","nice"],a:0,k:"词汇：cheap 便宜的",e:"解析：cheap 意为“便宜的”，与 expensive 意思相反。"},
{i:224,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"买衣服时说的“尺码、大小”用哪个词？",o:["size","price","colour","number"],a:0,k:"词汇：size 尺码",e:"解析：size 意为“尺码、大小”，买衣服时可以说 What size?（要多大尺码？）"},
{i:225,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“try on” 的意思是？",o:["试穿","脱下","买下","扔掉"],a:0,k:"短语：try on 试穿",e:"解析：try on 意为“试穿”，是“动词 + 副词”型短语，代词要放在中间，如 try them on。"},
{i:226,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"询问价格时，用哪个短语？",o:["how much","how many","how old","how long"],a:0,k:"短语：how much 多少钱",e:"解析：how much 意为“多少钱”，用来询问价格；how many 用来询问可数名词的数量。"},
{i:227,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“手套”的英语是？",o:["gloves","socks","shoes","scarf"],a:0,k:"词汇：gloves 手套",e:"解析：gloves 意为“手套”，和 socks 一样成双出现，常用复数形式。"},
{i:228,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“围巾”的英语是？",o:["scarf","gloves","umbrella","shirt"],a:0,k:"词汇：scarf 围巾",e:"解析：scarf 意为“围巾”，冬天戴在脖子上保暖。"},
{i:229,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“雨伞”的英语是？",o:["umbrella","scarf","gloves","coat"],a:0,k:"词汇：umbrella 雨伞",e:"解析：umbrella 意为“雨伞”，下雨天出门要带 umbrella。"},
{i:230,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“太阳镜”的英语是？",o:["sunglasses","glasses","hat","scarf"],a:0,k:"词汇：sunglasses 太阳镜",e:"解析：sunglasses 意为“太阳镜、墨镜”，夏天阳光强的时候用来保护眼睛。"},
{i:231,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"想知道一件衣服多少钱，应该问？",o:["How much is it?","How many is it?","How old is it?","What size is it?"],a:0,k:"句型：How much is it",e:"解析：How much is it? 用来询问单件物品的价格，答语是 It's + 金额。"},
{i:232,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"“How much are they?” 的正确回答是？",o:["They're fifty yuan.","It's fifty yuan.","Yes, they are.","They're on the desk."],a:0,k:"句型：How much are they 的答语",e:"解析：问句主语是 they（复数），答语也要用 They're 而不能用 It's。"},
{i:233,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,q:"售货员招呼顾客时说的 “Can I help you?” 意思是？",o:["您想买点什么？","你能帮我吗？","你能救我吗？","我可以帮你写作业吗？"],a:0,k:"句型：Can I help you",e:"解析：Can I help you? 是商店售货员的招呼用语，意为“您想买点什么？”，顾客可以回答 Yes, please."},
{i:234,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:1,q:"询问价格多少，英语用 “____ is it?”。",o:[],a:"How much",k:"填空：How much 问价格",e:"解析：How much 意为“多少钱”，用来询问价格，主语是复数时要用 are，如 How much are they?"},
{i:235,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:1,q:"人民币“元”的英语说法是____。",o:[],a:"yuan",k:"填空：元 yuan",e:"解析：yuan 是人民币单位，单复数同形，如 30 yuan（30 元）。"},
{i:236,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,d:2,q:"下面关于价格问句的说法，正确的是？",o:["单件用 How much is it，多件用 How much are they","单件用 How much are they，多件用 How much is it","不论几件都用 How much is it","不论几件都用 How many"],a:0,k:"拔高：价格问句的单复数",e:"解析：be 动词要与主语一致：单数用 is it，复数用 are they；How many 用于询问数量而不是价格。"},
{i:237,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,d:2,q:"“This coat is too expensive. That one is cheap.” 这句话的意思是？",o:["这件外套太贵了，那一件很便宜","这件外套很便宜，那一件很贵","两件外套都很贵","两件外套都很便宜"],a:0,k:"拔高：expensive 与 cheap 的对比",e:"解析：too expensive 表示“太贵”，cheap 表示“便宜”，两个词意思相反，形成对比。"},
{i:238,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,d:2,q:"读到 “Can I help you? Yes, please. How much is this skirt? It's 40 yuan. Oh, it's cheap. I'll take it.”，下面说法正确的是？",o:["这条短裙 40 元，顾客觉得便宜就买了","这条短裙太贵，顾客没有买","顾客买了两条短裙","这条短裙只要 4 元"],a:0,k:"拔高：阅读购物对话",e:"解析：It's 40 yuan. 说明价格是 40 元，cheap 表示觉得便宜，I'll take it 表示决定买下。"},
{i:239,c:"4en-12",ch:"四下·Unit 6 Shopping（购物）",f:0,d:2,q:"在商店里，顾客想试穿一双鞋，下面说法最合适的是？",o:["Can I try them on?","Can I try on they?","Can I try on it?","Can I try them on it?"],a:0,k:"拔高：try on 中代词的位置",e:"解析：try on 是“动词 + 副词”型短语，代词 them 必须放在 try 和 on 之间，所以是 try them on。"}
);


