if(!global.QA)global.QA={};
if(!QA["6en"])QA["6en"]=[];
QA["6en"].push(
{i:0,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"—Where is the cinema? —____",o:["It's next to the bookstore.","It's a cinema.","Yes, it is.","I like cinema."],a:0,k:"句型：Where is...? 地点",e:"解析：问电影院在哪，回答用 It's + 方位/邻近。next to the bookstore 在书店旁边正确。"},
{i:1,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"—How can I get to the park? —____",o:["Turn left at the crossing.","Turn left at the park.","Go straight to the left.","It's a park."],a:0,k:"句型：How can I get to...? 问路线",e:"解析：问怎么到公园，回答指路 Turn left at the crossing（在十字路口左转）。不能“在公园左转”因为那是目的地。"},
{i:2,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"“science museum”的意思是？",o:["科学博物馆","邮局","书店","医院"],a:0,k:"词汇：science museum 科学博物馆",e:"解析：science 科学 + museum 博物馆 = science museum。post office 邮局、bookstore 书店、hospital 医院。"},
{i:3,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"“直走”应说：____",o:["go straight","turn left","turn right","stop"],a:0,k:"短语：go straight 直走",e:"解析：go straight 直走。turn left 左转、turn right 右转、stop 停。"},
{i:4,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"“在书店左转”应说：____",o:["Turn left at the bookstore.","Turn right at the bookstore.","Turn left at the hospital.","Go straight at the bookstore."],a:0,k:"短语：turn left at...",e:"解析：在某一地点转弯用 turn + 方向 + at + 地点。bookstore 书店，故选第一项。"},
{i:5,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"“post office”的意思是？",o:["邮局","医院","电影院","博物馆"],a:0,k:"词汇：post office 邮局",e:"解析：post office 邮局。hospital 医院、cinema 电影院、museum 博物馆。"},
{i:6,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"—Is there a hospital near here? —____",o:["Yes, there is.","Yes, it is.","No, it isn't.","It's a hospital."],a:0,k:"句型：Is there...? 回答",e:"解析：There be 句型疑问，肯定回答 Yes, there is.。不能用 it is 回答 there be 问句。"},
{i:7,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:1,q:"—Where is the ____? —It's behind the school.（书店）",o:[],a:"bookstore",k:"词汇填空：bookstore 书店",e:"解析：bookstore 书店，Where is the bookstore? 书店在哪？behind the school 在学校后面。"},
{i:8,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"“crossing”的意思是？",o:["十字路口","电影院","博物馆","邮局"],a:0,k:"词汇：crossing 十字路口",e:"解析：crossing 十字路口（过马路/转弯处）。其余分别为 cinema、museum、post office。"},
{i:9,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"—How can I get to the library? —Go straight and ____ left.",o:["turn","turns","turning","turned"],a:0,k:"动词：turn left 原形",e:"解析：祈使句用动词原形 turn。Go straight and turn left 直走然后左转。"},
{i:10,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:0,q:"“hospital”的意思是？",o:["医院","邮局","书店","博物馆"],a:0,k:"词汇：hospital 医院",e:"解析：hospital 医院。post office 邮局、bookstore 书店、museum 博物馆。"},
{i:11,c:"6en-1",ch:"六上·第1单元 How can I get there?（问路与方位）",f:1,q:"Turn ____ at the cinema, then you can see the school.（右）",o:[],a:"right",k:"方向填空：turn right 右转",e:"解析：right 右边，turn right 右转。与 turn left（左转）相对。"},

{i:12,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"—How do you come to school? —____",o:["I come to school by bike.","I go to school bike.","I by bike come.","By bike I come school."],a:0,k:"句型：How do you...? by + 工具",e:"解析：问交通方式，回答用 by + 交通工具（无冠词）。by bike 骑自行车，结构正确。"},
{i:13,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"“步行”的英文是？",o:["on foot","by bus","by bike","by subway"],a:0,k:"短语：on foot 步行",e:"解析：步行用 on foot（固定搭配，不用 by foot）。by bus 公交、by bike 骑车、by subway 地铁。"},
{i:14,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"—How does Amy go home? —She goes ____ subway.",o:["by","on","in","with"],a:0,k:"介词：by + 交通工具",e:"解析：乘坐交通工具用 by，by subway 乘地铁。go by subway 正确。"},
{i:15,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"“traffic lights”的意思是？",o:["交通信号灯","公交车","地铁","飞机"],a:0,k:"词汇：traffic lights 交通灯",e:"解析：traffic 交通 + lights 灯 = traffic lights 交通信号灯。bus 公交、subway 地铁、plane 飞机。"},
{i:16,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"Don't go at the ____ light.",o:["red","yellow","green","blue"],a:0,k:"常识：红灯停",e:"解析：红灯停，Don't go at the red light 红灯时不要走。green 绿灯行、yellow 黄灯等。"},
{i:17,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"We must ____ down and stop at a yellow light.",o:["slow","stop","go","wait"],a:0,k:"短语：slow down 慢下来",e:"解析：黄灯要 slow down（慢下来）并停下。slow down 是固定短语。"},
{i:18,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"“by plane”的意思是？",o:["乘飞机","乘火车","乘船","乘地铁"],a:0,k:"短语：by plane 乘飞机",e:"解析：plane 飞机，by plane 乘飞机。by train 火车、by ship 船、by subway 地铁。"},
{i:19,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:1,q:"—How do you go to the park? —I go there ____.（步行）",o:[],a:"on foot",k:"短语填空：on foot 步行",e:"解析：步行 on foot，固定搭配，前面不加 by。I go there on foot 我步行去。"},
{i:20,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"“subway”的意思是？",o:["地铁","公交车","火车","轮船"],a:0,k:"词汇：subway 地铁",e:"解析：subway 地铁。bus 公交、train 火车、ship 轮船。"},
{i:21,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"You must ____ at a red light.",o:["stop","wait","go","slow"],a:0,k:"常识：红灯停 stop",e:"解析：红灯必须停下 stop。go 走是错的，slow 是慢行（黄灯）。"},
{i:22,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:0,q:"“by ship”的意思是？",o:["乘船","乘飞机","乘火车","乘地铁"],a:0,k:"短语：by ship 乘船",e:"解析：ship 船，by ship 乘船。plane 飞机、train 火车、subway 地铁。"},
{i:23,c:"6en-2",ch:"六上·第2单元 Ways to go to school（交通方式）",f:1,q:"We must ____ at the yellow light.（等待）",o:[],a:"wait",k:"动词填空：wait 等待",e:"解析：黄灯时停下等待 wait。wait 等待，与 stop 并列的交通规则用语。"},

{i:24,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"—What are your hobbies? —____",o:["I like reading stories.","I like read stories.","I am reading stories.","I reads stories."],a:0,k:"句型：like + doing 爱好",e:"解析：爱好用 like + 动词-ing。reading stories 读故事正确。like 后接动名词不是原形，也不是第三人称 reads（I 不是三单）。"},
{i:25,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"“他喜欢唱歌”应说：____",o:["He likes singing.","He like singing.","He likes sing.","He liking singing."],a:0,k:"语法：三单 likes + doing",e:"解析：He 是第三人称单数，like 变 likes；喜欢做某事 like doing。He likes singing 正确。"},
{i:26,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"“hobby”的复数是？",o:["hobbies","hobbys","hobbyes","hobies"],a:0,k:"名词复数：hobby→hobbies",e:"解析：以辅音+y 结尾，变 y 为 i 加 es，hobbies。这是规则变化。"},
{i:27,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"—What are Peter's hobbies? —____",o:["He likes doing kung fu.","He like doing kung fu.","He likes do kung fu.","He is doing kung fu."],a:0,k:"语法：三单 likes doing",e:"解析：Peter's 第三人称单数，用 He likes + doing。doing kung fu 练功夫。"},
{i:28,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"“playing football”的意思是？",o:["踢足球","唱歌","远足","读故事"],a:0,k:"词汇：playing football 踢足球",e:"解析：play football 踢足球，playing 是 -ing 形式。singing 唱歌、hiking 远足、reading stories 读故事。"},
{i:29,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"My pen pal ____ in Beijing.",o:["lives","live","living","lived"],a:0,k:"语法：三单 lives",e:"解析：My pen pal 第三人称单数，一般现在时动词加 s，live→lives。lived 是过去式。"},
{i:30,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"“hiking”的意思是？",o:["远足；徒步","唱歌","拼图","功夫"],a:0,k:"词汇：hiking 远足",e:"解析：hike 远足，hiking 是 -ing 形式。singing 唱歌、puzzle 拼图、kung fu 功夫。"},
{i:31,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:1,q:"—What are your hobbies? —I like ____.（读故事）",o:[],a:"reading stories",k:"短语填空：reading stories",e:"解析：like + doing，read 双写 t 加 ing = reading，stories 故事（story 复数）。读故事 reading stories。"},
{i:32,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"“does”用于 ____。",o:["第三人称单数","第一人称","复数","过去式"],a:0,k:"助动词：does 三单",e:"解析：does 是 do 的第三人称单数形式，用于 he/she/it。I/you/we/they 用 do。"},
{i:33,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"She ____ word puzzles every day.",o:["does","do","doing","did"],a:0,k:"语法：三单 does",e:"解析：She 三单，一般现在时用 does。do word puzzles 玩拼图，是固定搭配。"},
{i:34,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:0,q:"“pen pal”的意思是？",o:["笔友","朋友","同学","老师"],a:0,k:"词汇：pen pal 笔友",e:"解析：pen pal 笔友（通过信件/邮件交友的人）。"},
{i:35,c:"6en-3",ch:"六上·第4单元 I have a pen pal（爱好与一般现在时）",f:1,q:"He ____ playing basketball.（喜欢，三单）",o:[],a:"likes",k:"动词填空：likes 三单",e:"解析：He 第三人称单数，like 加 s = likes。like doing 喜欢做某事。"},

{i:36,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"—What does your father do? —____",o:["He's a doctor.","He's doctor.","He do a doctor.","He is doctor."],a:0,k:"句型：What does he do? 职业",e:"解析：问职业回答 He's/She's a + 职业。a doctor 前面必须有 a。doctor 医生。"},
{i:37,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"“她是一名飞行员”应说：____",o:["She's a pilot.","She's pilot.","She is pilot.","She pilot."],a:0,k:"句型：She's a pilot",e:"解析：职业前加 a/an，pilot 以辅音开头用 a。She's a pilot 正确。"},
{i:38,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"“factory worker”的意思是？",o:["工厂工人","邮递员","商人","渔民"],a:0,k:"词汇：factory worker 工厂工人",e:"解析：factory 工厂 + worker 工人 = factory worker。postman 邮递员、businessman 商人、fisherman 渔民。"},
{i:39,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"—Where does he work? —____",o:["He works at a hospital.","He work at a hospital.","He working at a hospital.","He is work."],a:0,k:"语法：三单 works",e:"解析：He 三单，work 加 s = works。at a hospital 在医院（工作）。"},
{i:40,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"“postman”的意思是？",o:["邮递员","警察","科学家","教练"],a:0,k:"词汇：postman 邮递员",e:"解析：postman 邮递员。police officer 警察、scientist 科学家、coach 教练。"},
{i:41,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"What ____ your mother do?",o:["does","do","is","are"],a:0,k:"助动词：三单 does",e:"解析：your mother 第三人称单数，疑问句用 does。do 用于非三单。"},
{i:42,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"“police officer”的意思是？",o:["警察","渔民","商人","飞行员"],a:0,k:"词汇：police officer 警察",e:"解析：police officer 警察（警官）。fisherman 渔民、businessman 商人、pilot 飞行员。"},
{i:43,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:1,q:"—What does he do? —He is a ____.（科学家）",o:[],a:"scientist",k:"词汇填空：scientist 科学家",e:"解析：scientist 科学家，以辅音开头，a scientist。回答 He is a scientist。"},
{i:44,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"“fisherman”的意思是？",o:["渔民","商人","工人","邮递员"],a:0,k:"词汇：fisherman 渔民",e:"解析：fish 鱼 + man 人 = fisherman 渔民。businessman 商人、worker 工人、postman 邮递员。"},
{i:45,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"He is a ____. He teaches us football.",o:["coach","scientist","pilot","postman"],a:0,k:"词汇：coach 教练",e:"解析：教足球的是 coach（教练）。scientist 科学家、pilot 飞行员、postman 邮递员。"},
{i:46,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:0,q:"“businessman”的意思是？",o:["商人","工人","渔民","警察"],a:0,k:"词汇：businessman 商人",e:"解析：business 生意 + man = businessman 商人。worker 工人、fisherman 渔民、police officer 警察。"},
{i:47,c:"6en-4",ch:"六上·第5单元 What does he do?（职业）",f:1,q:"My uncle is a ____. He flies a plane.（飞行员）",o:[],a:"pilot",k:"词汇填空：pilot 飞行员",e:"解析：pilot 飞行员，开飞机 fly a plane。a pilot 一名飞行员。"},

{i:48,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"—What are you going to do tomorrow? —____",o:["I'm going to see a film.","I see a film.","I'm seeing a film.","I goes to see a film."],a:0,k:"句型：be going to 将来",e:"解析：问将来打算，回答 I'm going to + 动词原形。see a film 看电影正确。"},
{i:49,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"“打算去旅行”应说：____",o:["I'm going to take a trip.","I take a trip.","I taking a trip.","I'm take a trip."],a:0,k:"句型：be going to take a trip",e:"解析：be going to + 动词原形 take a trip 去旅行。going to 后接原形，不是 taking。"},
{i:50,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"“tonight”的意思是？",o:["今晚","明天","下周","今天"],a:0,k:"词汇：tonight 今晚",e:"解析：tonight 今晚。tomorrow 明天、next week 下周、today 今天。"},
{i:51,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"We ____ going to the supermarket.",o:["are","am","is","be"],a:0,k:"语法：We are going to",e:"解析：We 复数，be 动词用 are。I 用 am、He/She 用 is。"},
{i:52,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"“next week”的意思是？",o:["下周","上周","这周","明天"],a:0,k:"词汇：next week 下周",e:"解析：next week 下周。last week 上周、this week 这周、tomorrow 明天。"},
{i:53,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"He ____ going to buy a comic book.",o:["is","am","are","be"],a:0,k:"语法：He is going to",e:"解析：He 三单，be 动词用 is。is going to + 原形 buy。"},
{i:54,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"“visit my grandparents”的意思是？",o:["看望祖父母","看电影","去旅行","去超市"],a:0,k:"短语：visit my grandparents",e:"解析：visit 看望，grandparents 祖父母。see a film 看电影、take a trip 旅行、supermarket 超市。"},
{i:55,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:1,q:"—What are you going to do ____? —I'm going to visit my friend.（明天）",o:[],a:"tomorrow",k:"词汇填空：tomorrow 明天",e:"解析：tomorrow 明天，常与 be going to 连用表将来计划。问句 What are you going to do tomorrow?"},
{i:56,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"—Are you going to the park? —____",o:["Yes, I am.","Yes, I'm.","No, I am.","Yes, I do."],a:0,k:"句型：Are you going to...? 回答",e:"解析：be going to 疑问句，肯定回答 Yes, I am.。不可用 I'm 单独结尾（口语可，但书面用 I am），也不用 do 回答。"},
{i:57,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"“dictionary”的意思是？",o:["词典","漫画书","电影","旅行"],a:0,k:"词汇：dictionary 词典",e:"解析：dictionary 词典。comic book 漫画书、film 电影、trip 旅行。"},
{i:58,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:0,q:"“comic book”的意思是？",o:["连环画册；漫画书","词典","杂志","报纸"],a:0,k:"词汇：comic book 漫画书",e:"解析：comic 滑稽/连环 + book = comic book 连环画册。dictionary 词典、magazine 杂志、newspaper 报纸。"},
{i:59,c:"6en-5",ch:"六上·第3单元 My weekend plan（一般将来时）",f:1,q:"I'm going to ____ a film this evening.（看）",o:[],a:"see",k:"动词填空：see a film",e:"解析：see a film 看电影，be going to 后接动词原形 see。"},

{i:60,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"—How do you feel? —____",o:["I'm happy.","I'm nine.","I'm fine, thank you.","I like happy."],a:0,k:"句型：How do you feel? 感受",e:"解析：问感受，回答 I'm + 表示情绪的形容词。happy 高兴正确。nine 是年龄，fine 是身体好但此处要情绪词。"},
{i:61,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"“你生病了，应该去看医生”应说：____",o:["You should see a doctor.","You should see doctor.","You should to see a doctor.","You should seeing a doctor."],a:0,k:"句型：should + 原形",e:"解析：should 是情态动词，后接动词原形 see。see a doctor 看医生，doctor 前加 a。"},
{i:62,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"“afraid”的意思是？",o:["害怕","生气","难过","担心"],a:0,k:"词汇：afraid 害怕",e:"解析：afraid 害怕的。angry 生气、sad 难过、worried 担心。"},
{i:63,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"If you are cold, you should ____.",o:["wear warm clothes","wear warm cloth","wears warm clothes","wearing warm clothes"],a:0,k:"句型：should + 原形 wear",e:"解析：should 后接原形 wear（穿）。warm clothes 暖和的衣服。主语 you 不用 wears。"},
{i:64,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"“angry”的意思是？",o:["生气的","高兴的","悲伤的","担心的"],a:0,k:"词汇：angry 生气的",e:"解析：angry 生气的。happy 高兴、sad 悲伤、worried 担心。"},
{i:65,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"“难过的”英文是？",o:["sad","angry","happy","worried"],a:0,k:"词汇：sad 难过的",e:"解析：sad 难过的/悲伤的。angry 生气、happy 高兴、worried 担心。"},
{i:66,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"“担心”的英文是？",o:["worried","afraid","angry","sad"],a:0,k:"词汇：worried 担心的",e:"解析：worried 担心的/焦虑的。afraid 害怕、angry 生气、sad 难过。"},
{i:67,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:1,q:"—How do you feel? —I'm ____ because he broke my pen.（生气的）",o:[],a:"angry",k:"词汇填空：angry 生气的",e:"解析：angry 生气的，因为笔被弄坏而生气。broken 是 break 的过去分词。"},
{i:68,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"“do more exercise”的意思是？",o:["多做运动","看医生","穿暖衣服","数到十"],a:0,k:"短语：do more exercise",e:"解析：exercise 锻炼，do more exercise 多做运动。see a doctor 看医生、wear warm clothes 穿暖衣。"},
{i:69,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"—I'm ill. —You should ____ a doctor.",o:["see","look","watch","meet"],a:0,k:"搭配：see a doctor",e:"解析：看医生用 see a doctor（固定搭配）。look/watch 不接 doctor。"},
{i:70,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:0,q:"“happy”的意思是？",o:["高兴的","生气的","担心的","害怕的"],a:0,k:"词汇：happy 高兴的",e:"解析：happy 高兴的/快乐的。angry 生气、worried 担心、afraid 害怕。"},
{i:71,c:"6en-6",ch:"六上·第6单元 How do you feel?（情绪与建议）",f:1,q:"You should ____ warm clothes. It's cold outside.（穿）",o:[],a:"wear",k:"动词填空：wear 穿",e:"解析：wear 穿，should 后接原形。wear warm clothes 穿暖和的衣服。"},

{i:72,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"—How tall are you? —____",o:["I'm 1.60 metres.","I'm 1.60 metre.","I'm 1.60.","I'm tall."],a:0,k:"句型：How tall 身高",e:"解析：问身高回答 I'm + 数字 + metres（复数）。1.60 metres 一点六米。metre 单数不用于带数字的身高。"},
{i:73,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"“我比你高”应说：____",o:["I'm taller than you.","I'm tall than you.","I'm taller you.","I'm tallest than you."],a:0,k:"语法：比较级 taller than",e:"解析：比较级 + than 表示“比……更”。tall 比较级 taller，I'm taller than you 正确。"},
{i:74,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"“tall”的比较级是？",o:["taller","tallest","tall","most tall"],a:0,k:"比较级：tall→taller",e:"解析：单音节词直接加 -er，taller。tallest 最高级。"},
{i:75,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"He is only 7. He is ____ than me.",o:["younger","older","taller","shorter"],a:0,k:"词汇：younger 更年轻",e:"解析：7 岁比“我”小/年轻，younger 更年轻。older 更年长、taller 更高、shorter 更矮。"},
{i:76,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"“heavy”的比较级是？",o:["heavier","heavyer","heavy","heaviest"],a:0,k:"比较级：heavy→heavier",e:"解析：辅音+y 结尾，变 y 为 i 加 er，heavier。heaviest 最高级。"},
{i:77,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"Your hair is ____ than mine.",o:["longer","longest","long","most long"],a:0,k:"比较级：long→longer",e:"解析：long 比较级 longer，than 前用比较级。longest 最高级。"},
{i:78,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"“thin”的比较级是？",o:["thinner","thiner","thinnest","thin"],a:0,k:"比较级：thin→thinner",e:"解析：重读闭音节辅元辅结尾，双写尾字母加 er，thinner。thinnest 最高级。"},
{i:79,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:1,q:"I'm ____ than my sister.（更高的）",o:[],a:"taller",k:"比较级填空：taller",e:"解析：than 前用比较级，tall 比较级 taller。I'm taller than... 我比……高。"},
{i:80,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"“strong”的比较级是？",o:["stronger","strongest","strong","more strong"],a:0,k:"比较级：strong→stronger",e:"解析：单音节加 -er，stronger。strongest 最高级。"},
{i:81,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"—Who is ____, your father or your uncle? —My father.",o:["older","old","oldest","most old"],a:0,k:"比较级：old→older",e:"解析：两者比较用 older（更年长）。oldest 最高级用于三者以上。"},
{i:82,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:0,q:"“shorter”的意思是？",o:["更矮的；更短的","更高的","更强的","更重的"],a:0,k:"词汇：shorter 更矮/更短",e:"解析：short 比较级 shorter，可指更矮或更短。taller 更高、stronger 更强、heavier 更重。"},
{i:83,c:"6en-7",ch:"六下·第1单元 How tall are you?（比较级）",f:1,q:"The elephant is ____ than the dog.（更重的）",o:[],a:"heavier",k:"比较级填空：heavier",e:"解析：heavy 比较级 heavier（y 变 i 加 er）。大象比狗重，用 heavier。"},

{i:84,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"—What did you do last weekend? —____",o:["I cleaned my room.","I clean my room.","I cleaning my room.","I cleans my room."],a:0,k:"句型：一般过去时",e:"解析：last weekend 用一般过去时，clean 过去式 cleaned。疑问句 did 已表过去，主句动词用原形过去式。"},
{i:85,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"“watch”的过去式是？",o:["watched","watch","watching","watches"],a:0,k:"过去式：watch→watched",e:"解析：规则动词加 -ed，watched。watches 是三单现在式。"},
{i:86,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"I ____ my clothes yesterday.",o:["washed","wash","washing","washes"],a:0,k:"过去式：wash→washed",e:"解析：yesterday 昨天用过去时，wash 加 -ed = washed。"},
{i:87,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"“go”的过去式是？",o:["went","go","goed","gone"],a:0,k:"过去式：go→went",e:"解析：go 是不规则动词，过去式 went。gone 是过去分词。"},
{i:88,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"—Did you see a film? —____",o:["Yes, I did.","Yes, I do.","Yes, I saw.","No, I did."],a:0,k:"句型：Did you...? 回答",e:"解析：Did 引导的疑问句，肯定回答 Yes, I did.。do 是现在时，不对。"},
{i:89,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"“read”的过去式拼写是？",o:["read（同形）","readed","reads","reading"],a:0,k:"过去式：read 同形",e:"解析：read 过去式拼写仍为 read，但读音变为 /red/。readed 是错误形式。"},
{i:90,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"We ____ at home and watched TV.",o:["stayed","stay","staying","stays"],a:0,k:"过去式：stay→stayed",e:"解析：and 连接并列过去时，watched 提示用 stayed。stay 加 -ed。"},
{i:91,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:1,q:"—What did you do? —I ____ my clothes.（洗）",o:[],a:"washed",k:"过去式填空：washed",e:"解析：wash 的过去式 washed，yesterday/last weekend 等用过去时。"},
{i:92,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"“have”的过去式是？",o:["had","has","having","have"],a:0,k:"过去式：have→had",e:"解析：have 不规则过去式 had。has 是三单现在式。"},
{i:93,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"She ____ a book last night.",o:["read","reads","readed","reading"],a:0,k:"过去式：read 同形",e:"解析：last night 用过去时，read 过去式同形 read（读 /red/）。reads 是现在三单。"},
{i:94,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:0,q:"“drink”的过去式是？",o:["drank","drinked","drinks","drinking"],a:0,k:"过去式：drink→drank",e:"解析：drink 不规则过去式 drank。drinked 错误。"},
{i:95,c:"6en-8",ch:"六下·第2单元 Last weekend（一般过去时）",f:1,q:"They ____ to the park and played football.（去）",o:[],a:"went",k:"过去式填空：went",e:"解析：go 的过去式 went，与 played 并列用过去时。and 连接两个过去动作。"},

{i:96,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"—Where did you go over the holiday? —____",o:["I went to Xinjiang.","I go to Xinjiang.","I went Xinjiang.","I going to Xinjiang."],a:0,k:"句型：Where did you go? 过去",e:"解析：did 表过去，回答用 went to + 地点。go to 某地要加 to。I went to Xinjiang 正确。"},
{i:97,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"“go camping”的过去式是？",o:["went camping","go camping","went camp","went camped"],a:0,k:"过去式：go camping→went camping",e:"解析：go 变 went，camping 保留，went camping 去野营。"},
{i:98,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"“ride a horse”的过去式是？",o:["rode a horse","rided a horse","rode horse","ride a horse"],a:0,k:"过去式：ride→rode",e:"解析：ride 不规则过去式 rode，rode a horse 骑马。"},
{i:99,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"“take pictures”的过去式是？",o:["took pictures","taked pictures","took picture","tooked pictures"],a:0,k:"过去式：take→took",e:"解析：take 过去式 took，took pictures 拍照。taked 错误。"},
{i:100,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"—What did you do there? —I ____ gifts for my friends.",o:["bought","buy","buied","buying"],a:0,k:"过去式：buy→bought",e:"解析：buy 不规则过去式 bought，bought gifts 买礼物。buied 错误。"},
{i:101,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"“eat”的过去式是？",o:["ate","eated","eats","eating"],a:0,k:"过去式：eat→ate",e:"解析：eat 不规则过去式 ate。eated 错误。"},
{i:102,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"We ____ a bike in the park.",o:["rode","ride","rodee","riding"],a:0,k:"过去式：ride→rode",e:"解析：rode a bike 骑自行车（过去时）。ride 是现在式。"},
{i:103,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:1,q:"—Where did you go? —I ____ to the zoo.（去）",o:[],a:"went",k:"过去式填空：went",e:"解析：go 的过去式 went，Where did you go 回答 I went to...。"},
{i:104,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"“buy”的过去式是？",o:["bought","buyed","buys","buying"],a:0,k:"过去式：buy→bought",e:"解析：buy 不规则过去式 bought。buyed 错误。"},
{i:105,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"—Did you go to Turpan? —____",o:["Yes, we did.","Yes, we do.","No, we did.","Yes, we went."],a:0,k:"句型：Did you...? 回答",e:"解析：Did 疑问句肯定回答 Yes, we did.。do 是现在时不对。"},
{i:106,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:0,q:"“fell”是 ____ 的过去式。",o:["fall","fell","falling","felt"],a:0,k:"过去式：fall→fell",e:"解析：fall 摔倒/落下，过去式 fell。felt 是 feel 的过去式。"},
{i:107,c:"6en-9",ch:"六下·第3单元 Where did you go?（过去时·旅行）",f:1,q:"I took many ____ on the Great Wall.（照片）",o:[],a:"pictures",k:"词汇填空：pictures 照片",e:"解析：take pictures 拍照，many 后接复数 pictures。took 是 take 的过去式。"},

{i:108,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"一年有几个季节？",o:["Four.","Three.","Two.","Five."],a:0,k:"常识：四季",e:"解析：一年有春夏秋冬四个季节 Four seasons。spring/summer/autumn/fall/winter。"},
{i:109,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"—Which season do you like ____? —Spring.",o:["best","better","good","well"],a:0,k:"副词：like best 最喜欢",e:"解析：like...best 最喜欢，用于三者及以上比较。better 是比较级（两者）。"},
{i:110,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"In summer, I often ____.",o:["go swimming","go swim","goes swimming","going swimming"],a:0,k:"短语：go swimming 去游泳",e:"解析：go + doing 表去从事某项活动，go swimming 去游泳。often 用一般现在时，I 后 go 用原形。"},
{i:111,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"Look! The boy ____ a snowman.",o:["is making","makes","making","make"],a:0,k:"时态：现在进行时",e:"解析：Look! 提示此刻正在发生，用现在进行时 be + doing。The boy 用 is making。"},
{i:112,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"Yesterday I ____ apples on the farm.",o:["picked","pick","picks","picking"],a:0,k:"时态：一般过去时",e:"解析：yesterday 昨天用过去时，pick 加 -ed = picked 摘。"},
{i:113,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"“winter”的意思是？",o:["冬天","夏天","春天","秋天"],a:0,k:"词汇：winter 冬天",e:"解析：winter 冬天。summer 夏、spring 春、autumn/fall 秋。"},
{i:114,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"Because it's ____ in spring.",o:["warm","hot","cold","cool"],a:0,k:"词汇：warm 温暖",e:"解析：春天温暖 warm。hot 夏、cold 冬、cool 秋/凉爽。"},
{i:115,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:1,q:"—Which season do you like best? —____, because I can pick apples.（秋天）",o:[],a:"Autumn",k:"词汇填空：Autumn 秋天",e:"解析：Autumn 秋天（美式也用 fall）。秋天摘苹果 pick apples，故答 Autumn。"},
{i:116,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"“plant trees”的意思是？",o:["种树","摘苹果","堆雪人","去游泳"],a:0,k:"短语：plant trees 种树",e:"解析：plant 种植，plant trees 种树。pick apples 摘苹果、make a snowman 堆雪人、go swimming 游泳。"},
{i:117,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"He usually ____ to school by bike.",o:["goes","go","going","went"],a:0,k:"时态：一般现在时三单",e:"解析：usually 表习惯用一般现在时，He 三单，go→goes。went 是过去式。"},
{i:118,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:0,q:"“make a snowman”的意思是？",o:["堆雪人","种树","去游泳","摘苹果"],a:0,k:"短语：make a snowman 堆雪人",e:"解析：snowman 雪人，make a snowman 堆雪人。其余为 plant trees、go swimming、pick apples。"},
{i:119,c:"6en-10",ch:"六下·季节与活动（综合时态·简短阅读）",f:1,q:"Look! They are ____ football on the playground.（play的-ing）",o:[],a:"playing",k:"时态填空：现在进行时 playing",e:"解析：Look! 提示正在进行的动作，用 be + doing。play 直接加 ing = playing。are playing 正在踢球。"}
);
