// 六年级英语 · 拔高题整套换新（2026-09-11）
// 背景：6en 原有 80 道拔高题（i=9000~9079）是一个「通用拔高题池」，三个毛病：
//   1) 大量超纲 —— 现在完成时、定语从句、宾语从句、过去进行时、条件/结果状语从句、
//      too...to、不定代词、最高级、It takes sb. time to do 都不在人教 PEP 小学范围内；
//   2) 被复制到多个单元 —— 同一道题出现在 4~5 个单元（如过去进行时那道）；
//   3) 与单元主题无关 ——「This is the museum...」这类定语从句题跟「问路与方位」没关系。
// 本文件按单元重出 8 道在纲内的拔高题（d:2），共 10 单元 × 8 = 80 道，
// 使每单元回到 20 题（12 基础 + 8 拔高）。题号从 613000 起。
// 范围限定：一般现在时（含三单）、一般将来时（be going to）、一般过去时、
//          形容词比较级、情态动词 should/can/must、there was/were。
if(!global.QA)global.QA={};
if(!QA["6en"])QA["6en"]=[];
QA["6en"].push(
// ══════════ 六上·第1单元 How can I get there?（问路与方位）══════════
{"i":613000,"c":"6en-1","ch":"六上·第1单元 How can I get there?（问路与方位）","f":0,"d":2,"q":"—____? —It's next to the science museum.","o":["How can I get to the library?","Is there a library?","Where is the library?","What do you like?"],"a":2,"k":"问路：根据方位答语选问句 Where is...?","e":"解析：答语说在科学博物馆旁边，问句应用 Where is...? 问地点。"},
{"i":613001,"c":"6en-1","ch":"六上·第1单元 How can I get there?（问路与方位）","f":0,"d":2,"q":"The school is ____ the park and the zoo.","o":["behind","between","beside","in front of"],"a":1,"k":"方位介词：between 用于两者之间","e":"解析：公园和动物园两个地点之间，用 between。"},
{"i":613002,"c":"6en-1","ch":"六上·第1单元 How can I get there?（问路与方位）","f":0,"d":2,"q":"—Excuse me, how can I get to the hospital? —____","o":["It's next to the bank.","Yes, there is.","I'm a doctor.","Go straight and turn right at the crossing."],"a":3,"k":"问路：How can I get to...? 用指路指令回答","e":"解析：问“怎么去”，要用 Go straight 这类指路指令回答。"},
{"i":613003,"c":"6en-1","ch":"六上·第1单元 How can I get there?（问路与方位）","f":0,"d":2,"q":"The restaurant is beside the school. 也就是 The restaurant is ____ the school.","o":["next to","in front of","behind","between"],"a":0,"k":"方位介词：next to 与 beside 同义","e":"解析：beside 和 next to 都表示“在……旁边”，可以互换。"},
{"i":613004,"c":"6en-1","ch":"六上·第1单元 How can I get there?（问路与方位）","f":0,"d":2,"q":"—How do I get to the museum? —Turn left ____ the post office.","o":["in","on","at","of"],"a":2,"k":"指路：turn left at + 地点","e":"解析：在某处转弯用介词 at，即 turn left at..."},
{"i":613005,"c":"6en-1","ch":"六上·第1单元 How can I get there?（问路与方位）","f":0,"d":2,"q":"—Where is the tree? —It's ____ the house.（从树那儿能看到大门）","o":["behind","in front of","between","beside"],"a":1,"k":"方位介词：in front of 辨析","e":"解析：能看到大门，说明树在房子前面，用 in front of。"},
{"i":613006,"c":"6en-1","ch":"六上·第1单元 How can I get there?（问路与方位）","f":0,"d":2,"q":"—Is there a cinema near here? —____. It's behind the supermarket.","o":["No, there isn't","Yes, it is","No, it isn't","Yes, there is"],"a":3,"k":"问路：Is there...? 的肯定回答","e":"解析：后面说出了电影院位置，是肯定回答 Yes, there is。"},
{"i":613007,"c":"6en-1","ch":"六上·第1单元 How can I get there?（问路与方位）","f":0,"d":2,"q":"—Where is the library? —Go straight, turn left ____ the crossing, then it's ____ the park.","o":["on; next to","at; next to","at; under","in; behind"],"a":1,"k":"综合：指路介词 at 与方位介词 next to","e":"解析：在路口左转用 at，在公园旁边用 next to。"},
// ══════════ 六上·第2单元 Ways to go to school（交通方式）══════════
{"i":613008,"c":"6en-2","ch":"六上·第2单元 Ways to go to school（交通方式）","f":0,"d":2,"q":"—How does Amy go to school? —She ____ to school by bus.","o":["go","goes","going","went"],"a":1,"k":"交通方式：三单 goes + by bus","e":"解析：Amy 是第三人称单数，go 要变成 goes。"},
{"i":613009,"c":"6en-2","ch":"六上·第2单元 Ways to go to school（交通方式）","f":0,"d":2,"q":"I ____ a bus to the park on Sunday.","o":["take","by","on","in"],"a":0,"k":"交通方式：take a bus 与 by bus 辨析","e":"解析：句子缺谓语动词，用 take a bus；by bus 不能作谓语。"},
{"i":613010,"c":"6en-2","ch":"六上·第2单元 Ways to go to school（交通方式）","f":0,"d":2,"q":"—____? —I go to school on foot.","o":["What do you do?","Where is the school?","How do you go to school?","Do you like school?"],"a":2,"k":"交通方式：根据答语选问句 How...?","e":"解析：答语说的是上学方式，问句用 How do you go to school?"},
{"i":613011,"c":"6en-2","ch":"六上·第2单元 Ways to go to school（交通方式）","f":0,"d":2,"q":"We must ____ and stop at a yellow light.","o":["go","wait","stop","slow down"],"a":3,"k":"交通规则：黄灯要 slow down and stop","e":"解析：黄灯时要减速停下，即 slow down and stop。"},
{"i":613012,"c":"6en-2","ch":"六上·第2单元 Ways to go to school（交通方式）","f":0,"d":2,"q":"You ____ run in the street. It's dangerous!","o":["can","must not","must","should"],"a":1,"k":"交通规则：must not 表示禁止","e":"解析：在街上跑很危险，用 must not 表示“禁止”。"},
{"i":613013,"c":"6en-2","ch":"六上·第2单元 Ways to go to school（交通方式）","f":0,"d":2,"q":"—How does your father go to work? —He goes ____ foot.","o":["on","by","in","with"],"a":0,"k":"交通方式：on foot 固定搭配","e":"解析：“步行”固定说 on foot，不用 by。"},
{"i":613014,"c":"6en-2","ch":"六上·第2单元 Ways to go to school（交通方式）","f":0,"d":2,"q":"—Don't go at the red light! —____","o":["Thank you.","You're welcome.","I'm sorry.","OK, I can."],"a":2,"k":"交通规则：闯红灯被提醒时的应答","e":"解析：被提醒不要闯红灯，应道歉并表示会遵守。"},
{"i":613015,"c":"6en-2","ch":"六上·第2单元 Ways to go to school（交通方式）","f":0,"d":2,"q":"My brother ____ to the park by bike every Sunday.","o":["go","going","went","goes"],"a":3,"k":"交通方式：三单 goes 的一般现在时","e":"解析：every Sunday 表习惯，主语三单，用 goes。"},
// ══════════ 六上·第4单元 I have a pen pal（爱好与一般现在时）══════════
{"i":613016,"c":"6en-3","ch":"六上·第4单元 I have a pen pal（爱好与一般现在时）","f":0,"d":2,"q":"—What are your brother's hobbies? —He ____ reading stories.","o":["like","likes","liking","liked"],"a":1,"k":"爱好：三单 likes + doing","e":"解析：主语三单，like 要加 s，后接动词-ing。"},
{"i":613017,"c":"6en-3","ch":"六上·第4单元 I have a pen pal（爱好与一般现在时）","f":0,"d":2,"q":"—Does she like doing word puzzles? —____","o":["Yes, she like.","No, she don't.","Yes, she does.","Yes, she do."],"a":2,"k":"爱好：Does 问句的肯定回答","e":"解析：Does 提问就用 does 回答，Yes, she does."},
{"i":613018,"c":"6en-3","ch":"六上·第4单元 I have a pen pal（爱好与一般现在时）","f":0,"d":2,"q":"My pen pal ____ in Canberra.","o":["live","lives","living","lived"],"a":1,"k":"一般现在时：三单 live→lives","e":"解析：主语 pen pal 是三单，live 要加 s。"},
{"i":613019,"c":"6en-3","ch":"六上·第4单元 I have a pen pal（爱好与一般现在时）","f":0,"d":2,"q":"My pen pal ____ Chinese every day.","o":["study","studies","studying","studied"],"a":1,"k":"一般现在时：study 三单变 studies","e":"解析：主语三单，study 以辅音加 y 结尾，变 y 为 i 加 es。"},
{"i":613020,"c":"6en-3","ch":"六上·第4单元 I have a pen pal（爱好与一般现在时）","f":0,"d":2,"q":"—____ your mother like cooking? —Yes, she does.","o":["Do","Does","Is","Are"],"a":1,"k":"爱好：三单一般疑问句用 Does 引导","e":"解析：答语是 Yes, she does，说明问句用 Does 引导。"},
{"i":613021,"c":"6en-3","ch":"六上·第4单元 I have a pen pal（爱好与一般现在时）","f":0,"d":2,"q":"They ____ like playing football, but they like basketball.","o":["doesn't","don't","isn't","aren't"],"a":1,"k":"爱好：复数主语否定用 don't like","e":"解析：They 是复数，否定用 don't like。"},
{"i":613022,"c":"6en-3","ch":"六上·第4单元 I have a pen pal（爱好与一般现在时）","f":0,"d":2,"q":"—What are your hobbies? —I like ____ and ____.","o":["read; dance","reading; dancing","reads; dances","to read; to dance"],"a":1,"k":"爱好：like 后接两个并列的动名词","e":"解析：like 后接动词-ing，并列时用 reading and dancing。"},
{"i":613023,"c":"6en-3","ch":"六上·第4单元 I have a pen pal（爱好与一般现在时）","f":0,"d":2,"q":"My sister ____ like singing. She likes dancing.","o":["like","likes","don't","doesn't"],"a":3,"k":"爱好：三单否定 doesn't like","e":"解析：后句说她喜欢跳舞，前句是否定，三单用 doesn't like。"},
// ══════════ 六上·第5单元 What does he do?（职业）══════════
{"i":613024,"c":"6en-4","ch":"六上·第5单元 What does he do?（职业）","f":0,"d":2,"q":"—____? —He is a businessman.","o":["What does he do?","Where does he work?","How does he go to work?","How old is he?"],"a":0,"k":"职业：根据答语选问句 What does he do?","e":"解析：答语说的是职业，问句用 What does he do?"},
{"i":613025,"c":"6en-4","ch":"六上·第5单元 What does he do?（职业）","f":0,"d":2,"q":"—Where does your brother work? —____","o":["He is a doctor.","He works at a university.","He goes by car.","He is 40."],"a":1,"k":"职业：Where does he work? 回答工作地点","e":"解析：问在哪里工作，回答 He works at a university."},
{"i":613026,"c":"6en-4","ch":"六上·第5单元 What does he do?（职业）","f":0,"d":2,"q":"My uncle is a ____. He works at sea.","o":["fisherman","postman","coach","pilot"],"a":0,"k":"职业：在海上工作的是 fisherman","e":"解析：works at sea 在海上工作，对应渔民 fisherman。"},
{"i":613027,"c":"6en-4","ch":"六上·第5单元 What does he do?（职业）","f":0,"d":2,"q":"She ____ a police officer.","o":["am","is","are","be"],"a":1,"k":"职业：She is a + 职业","e":"解析：She 搭配 is，后接 a police officer 表示职业。"},
{"i":613028,"c":"6en-4","ch":"六上·第5单元 What does he do?（职业）","f":0,"d":2,"q":"—Does your mother work in a factory? —____. She is a factory worker.","o":["Yes, she is","No, she doesn't","Yes, she does","No, she isn't"],"a":2,"k":"职业：Does 问句的肯定回答","e":"解析：后面说她是工人，是肯定，Does 提问用 Yes, she does."},
{"i":613029,"c":"6en-4","ch":"六上·第5单元 What does he do?（职业）","f":0,"d":2,"q":"My brother is a ____. He teaches football in a school.","o":["scientist","coach","fisherman","postman"],"a":1,"k":"职业：教足球的是 coach","e":"解析：teaches football 教足球，对应教练 coach。"},
{"i":613030,"c":"6en-4","ch":"六上·第5单元 What does he do?（职业）","f":0,"d":2,"q":"The ____ works in a university. He is a scientist.","o":["scientist","businessman","pilot","postman"],"a":0,"k":"职业：在大学工作的是 scientist","e":"解析：后句说他是科学家，科学家在大学工作。"},
{"i":613031,"c":"6en-4","ch":"六上·第5单元 What does he do?（职业）","f":0,"d":2,"q":"—What does your aunt do? —____","o":["She goes to work by bus.","She works in a hospital.","She is a nurse.","She likes singing."],"a":2,"k":"职业：What does...do? 回答职业名称","e":"解析：问职业，应直接回答 She is a nurse."},
// ══════════ 六上·第3单元 My weekend plan（一般将来时）══════════
{"i":613032,"c":"6en-5","ch":"六上·第3单元 My weekend plan（一般将来时）","f":0,"d":2,"q":"—When are you going to the bookstore? —____","o":["Tomorrow morning.","I bought a book.","I like reading.","By bus."],"a":0,"k":"将来时：When 问将来的时间","e":"解析：be going to 表将来，答语应是表示将来的时间。"},
{"i":613033,"c":"6en-5","ch":"六上·第3单元 My weekend plan（一般将来时）","f":0,"d":2,"q":"—____? —I'm going to buy a comic book.","o":["What do you do?","Where are you?","How do you go?","What are you going to do?"],"a":3,"k":"将来时：根据答语选问句 What are you going to do?","e":"解析：答语说打算买漫画书，问句用 What are you going to do?"},
{"i":613034,"c":"6en-5","ch":"六上·第3单元 My weekend plan（一般将来时）","f":0,"d":2,"q":"He ____ going to visit his grandparents next week.","o":["am","is","are","be"],"a":1,"k":"将来时：He is going to 结构","e":"解析：He 是三单，be 动词用 is。"},
{"i":613035,"c":"6en-5","ch":"六上·第3单元 My weekend plan（一般将来时）","f":0,"d":2,"q":"We ____ going to the cinema this evening.","o":["am","is","are","be"],"a":2,"k":"将来时：We are going to 结构","e":"解析：We 是复数，be 动词用 are。"},
{"i":613036,"c":"6en-5","ch":"六上·第3单元 My weekend plan（一般将来时）","f":0,"d":2,"q":"—Are you going to take a trip? —____. We are going to Beijing.","o":["No, we aren't","Yes, we are","Yes, we do","No, we don't"],"a":1,"k":"将来时：Are you going to...? 肯定回答","e":"解析：后面说要去北京，是肯定，用 Yes, we are."},
{"i":613037,"c":"6en-5","ch":"六上·第3单元 My weekend plan（一般将来时）","f":0,"d":2,"q":"My sister ____ going to read a book tonight.","o":["am","are","be","is"],"a":3,"k":"将来时：三单用 is going to","e":"解析：My sister 是单数，用 is going to。"},
{"i":613038,"c":"6en-5","ch":"六上·第3单元 My weekend plan（一般将来时）","f":0,"d":2,"q":"—What is he going to do? —____","o":["He goes to school.","He is going to play football.","He played football.","He likes football."],"a":1,"k":"将来时：What is he going to do? 的答语","e":"解析：问将来做什么，回答用 is going to + 动词原形。"},
{"i":613039,"c":"6en-5","ch":"六上·第3单元 My weekend plan（一般将来时）","f":0,"d":2,"q":"They ____ going to have a picnic tomorrow.","o":["am","is","are","be"],"a":2,"k":"将来时：They are going to 结构","e":"解析：They 是复数，be 动词用 are。"},
// ══════════ 六上·第6单元 How do you feel?（情绪与建议）══════════
{"i":613040,"c":"6en-6","ch":"六上·第6单元 How do you feel?（情绪与建议）","f":0,"d":2,"q":"—____ are you sad? —Because I lost my book.","o":["What","Who","Why","Where"],"a":2,"k":"情绪建议：Why 问原因配 Because 回答","e":"解析：答语 Because 表原因，问句用 Why。"},
{"i":613041,"c":"6en-6","ch":"六上·第6单元 How do you feel?（情绪与建议）","f":0,"d":2,"q":"—What's wrong? —____","o":["I'm worried. My cat is lost.","I'm ten years old.","I like apples.","It is blue."],"a":0,"k":"情绪建议：What's wrong? 回答自己的困扰","e":"解析：What's wrong 问怎么了，应回答烦恼的事。"},
{"i":613042,"c":"6en-6","ch":"六上·第6单元 How do you feel?（情绪与建议）","f":0,"d":2,"q":"—____? —I feel happy.","o":["How do you feel?","What do you do?","Where are you?","How old are you?"],"a":0,"k":"情绪建议：根据答语选问句 How do you feel?","e":"解析：答语说的是感受，问句用 How do you feel?"},
{"i":613043,"c":"6en-6","ch":"六上·第6单元 How do you feel?（情绪与建议）","f":0,"d":2,"q":"—I'm ill. —____","o":["What's your name?","You should see a doctor.","How old are you?","I am a doctor."],"a":1,"k":"情绪建议：生病时建议看医生","e":"解析：对方说生病了，应建议 You should see a doctor."},
{"i":613044,"c":"6en-6","ch":"六上·第6单元 How do you feel?（情绪与建议）","f":0,"d":2,"q":"The boy is afraid of the dog. You can say: ____","o":["Be afraid.","The dog is small.","Don't be afraid.","You are a dog."],"a":2,"k":"情绪建议：安慰害怕用 Don't be afraid","e":"解析：安慰害怕的人要说 Don't be afraid."},
{"i":613045,"c":"6en-6","ch":"六上·第6单元 How do you feel?（情绪与建议）","f":0,"d":2,"q":"Tom is sad because he failed the test. You say: ____","o":["You should be sad.","You should study hard.","Don't study.","He is a teacher."],"a":1,"k":"情绪建议：对沮丧的人给积极建议","e":"解析：考试失利，应鼓励并建议努力学习。"},
{"i":613046,"c":"6en-6","ch":"六上·第6单元 How do you feel?（情绪与建议）","f":0,"d":2,"q":"Mum isn't at home. The girl looks ____.","o":["tall","old","worried","happy"],"a":2,"k":"情绪词汇：妈妈不在家时是 worried","e":"解析：妈妈不在家，女孩会担心，用 worried。"},
{"i":613047,"c":"6en-6","ch":"六上·第6单元 How do you feel?（情绪与建议）","f":0,"d":2,"q":"—I'm angry. —____","o":["Be angry.","You are angry.","Don't be angry.","Are you angry?"],"a":2,"k":"情绪建议：劝阻生气用 Don't be angry","e":"解析：对方生气，应劝他 Don't be angry."},
// ══════════ 六下·第1单元 How tall are you?（比较级）══════════
{"i":613048,"c":"6en-7","ch":"六下·第1单元 How tall are you?（比较级）","f":0,"d":2,"q":"—____? —I'm 1.6 metres.","o":["How old are you?","How heavy are you?","What are you?","How tall are you?"],"a":3,"k":"比较级：根据身高答语选问句 How tall","e":"解析：答语是身高，问句用 How tall are you?"},
{"i":613049,"c":"6en-7","ch":"六下·第1单元 How tall are you?（比较级）","f":0,"d":2,"q":"—How heavy are you? —____","o":["I'm 12 years old.","I'm tall.","I'm 45 kilograms.","I'm happy."],"a":2,"k":"比较级：How heavy 问体重的答语","e":"解析：How heavy 问体重，回答多少公斤。"},
{"i":613050,"c":"6en-7","ch":"六下·第1单元 How tall are you?（比较级）","f":0,"d":2,"q":"The giraffe is ____ than the deer.","o":["tall","taller","talling","so tall"],"a":1,"k":"比较级：than 前用比较级 taller","e":"解析：有 than 就要用比较级，tall 变 taller。"},
{"i":613051,"c":"6en-7","ch":"六下·第1单元 How tall are you?（比较级）","f":0,"d":2,"q":"My brother is ____ and ____ than me.","o":["old and strong","older and stronger","old and stronger","older and strong"],"a":1,"k":"比较级：并列两个比较级","e":"解析：两处都比，都要用比较级 older and stronger。"},
{"i":613052,"c":"6en-7","ch":"六下·第1单元 How tall are you?（比较级）","f":0,"d":2,"q":"The elephant is ____ than the cat.","o":["heavy","heavier","heavies","more heavy"],"a":1,"k":"比较级：heavy 变 y 为 i 加 er","e":"解析：heavy 以辅音加 y 结尾，变 y 为 i 再加 er。"},
{"i":613053,"c":"6en-7","ch":"六下·第1单元 How tall are you?（比较级）","f":0,"d":2,"q":"—____? —John is taller than Mike.","o":["Who is taller?","How tall are you?","What are they?","Where are they?"],"a":0,"k":"比较级：根据比较答语选问句 Who is taller?","e":"解析：答语在比较两人身高，问句用 Who is taller?"},
{"i":613054,"c":"6en-7","ch":"六下·第1单元 How tall are you?（比较级）","f":0,"d":2,"q":"I am 10. My sister is 8. So I am ____ than her.","o":["younger","older","young","old"],"a":1,"k":"比较级：年龄更大用 older","e":"解析：10 岁比 8 岁大，用 older。"},
{"i":613055,"c":"6en-7","ch":"六下·第1单元 How tall are you?（比较级）","f":0,"d":2,"q":"My pencil is 15 cm. Yours is 10 cm. Mine is ____ than yours.","o":["short","shorter","long","longer"],"a":3,"k":"比较级：更长用 longer","e":"解析：15 厘米比 10 厘米长，用 longer。"},
// ══════════ 六下·第2单元 Last weekend（一般过去时）══════════
{"i":613056,"c":"6en-8","ch":"六下·第2单元 Last weekend（一般过去时）","f":0,"d":2,"q":"I ____ watch TV last night. I did my homework.","o":["don't","didn't","doesn't","wasn't"],"a":1,"k":"过去时：否定用 didn't + 动词原形","e":"解析：过去时的否定用 didn't，后面动词用原形。"},
{"i":613057,"c":"6en-8","ch":"六下·第2单元 Last weekend（一般过去时）","f":0,"d":2,"q":"—Did you clean your room? —____","o":["Yes, I do.","Yes, I did.","Yes, I am.","No, I don't."],"a":1,"k":"过去时：Did 问句用 did 回答","e":"解析：Did 提问就用 did 回答，Yes, I did."},
{"i":613058,"c":"6en-8","ch":"六下·第2单元 Last weekend（一般过去时）","f":0,"d":2,"q":"We ____ to the museum yesterday.","o":["go","goes","went","going"],"a":2,"k":"过去时：go 的过去式是 went","e":"解析：yesterday 表过去，go 变 went。"},
{"i":613059,"c":"6en-8","ch":"六下·第2单元 Last weekend（一般过去时）","f":0,"d":2,"q":"—____? —I washed my clothes.","o":["What did you do?","Where did you go?","How are you?","What do you do?"],"a":0,"k":"过去时：根据答语选问句 What did you do?","e":"解析：答语说做了什么事，问句用 What did you do?"},
{"i":613060,"c":"6en-8","ch":"六下·第2单元 Last weekend（一般过去时）","f":0,"d":2,"q":"I ____ a film with my friend last Sunday.","o":["see","sees","saw","seeing"],"a":2,"k":"过去时：see 的过去式是 saw","e":"解析：过去时中 see 要变成 saw。"},
{"i":613061,"c":"6en-8","ch":"六下·第2单元 Last weekend（一般过去时）","f":0,"d":2,"q":"We ____ at home last Saturday.","o":["stay","stays","stayed","staying"],"a":2,"k":"过去时：规则动词加 -ed","e":"解析：规则动词的过去式直接加 ed，stay 变 stayed。"},
{"i":613062,"c":"6en-8","ch":"六下·第2单元 Last weekend（一般过去时）","f":0,"d":2,"q":"He often ____ football, but yesterday he ____ basketball.","o":["plays; play","play; played","plays; played","played; plays"],"a":2,"k":"过去时：现在时与过去时的对比","e":"解析：often 用一般现在时，yesterday 用过去式。"},
{"i":613063,"c":"6en-8","ch":"六下·第2单元 Last weekend（一般过去时）","f":0,"d":2,"q":"—Did he watch TV? —____. He read a book.","o":["No, he didn't","No, he doesn't","No, he isn't","Yes, he did"],"a":0,"k":"过去时：Did 问句的否定回答","e":"解析：后面说他看书了，说明没看电视，用 No, he didn't."},
// ══════════ 六下·第3单元 Where did you go?（过去时·旅行）══════════
{"i":613064,"c":"6en-9","ch":"六下·第3单元 Where did you go?（过去时·旅行）","f":0,"d":2,"q":"—____? —I went to Xinjiang.","o":["Where did you go?","What did you do?","How did you go?","When did you go?"],"a":0,"k":"旅行过去时：根据答语选问句 Where did you go?","e":"解析：答语说去了新疆，问句用 Where did you go?"},
{"i":613065,"c":"6en-9","ch":"六下·第3单元 Where did you go?（过去时·旅行）","f":0,"d":2,"q":"We ____ a horse on the farm yesterday.","o":["ride","rode","rides","riding"],"a":1,"k":"旅行过去时：ride 的过去式是 rode","e":"解析：过去时中 ride 要变成 rode。"},
{"i":613066,"c":"6en-9","ch":"六下·第3单元 Where did you go?（过去时·旅行）","f":0,"d":2,"q":"They ____ in the forest last weekend.","o":["go camping","goes camping","went camping","going camping"],"a":2,"k":"旅行过去时：go camping 的过去式","e":"解析：过去时中 go camping 变成 went camping。"},
{"i":613067,"c":"6en-9","ch":"六下·第3单元 Where did you go?（过去时·旅行）","f":0,"d":2,"q":"My mother ____ some gifts for us in Sanya.","o":["buy","buys","bought","buying"],"a":2,"k":"旅行过去时：buy 的过去式是 bought","e":"解析：过去时中 buy 要变成 bought。"},
{"i":613068,"c":"6en-9","ch":"六下·第3单元 Where did you go?（过去时·旅行）","f":0,"d":2,"q":"I ____ many pictures at the zoo.","o":["take","takes","took","taking"],"a":2,"k":"旅行过去时：take 的过去式是 took","e":"解析：过去时中 take 要变成 took。"},
{"i":613069,"c":"6en-9","ch":"六下·第3单元 Where did you go?（过去时·旅行）","f":0,"d":2,"q":"We ____ fresh food in the village.","o":["eat","eats","ate","eating"],"a":2,"k":"旅行过去时：eat 的过去式是 ate","e":"解析：过去时中 eat 要变成 ate。"},
{"i":613070,"c":"6en-9","ch":"六下·第3单元 Where did you go?（过去时·旅行）","f":0,"d":2,"q":"—____? —I went swimming in the lake.","o":["Where did you go?","What did you do?","How did you go?","Who went with you?"],"a":1,"k":"旅行过去时：根据答语选问句 What did you do?","e":"解析：答语说做了什么事，问句用 What did you do?"},
{"i":613071,"c":"6en-9","ch":"六下·第3单元 Where did you go?（过去时·旅行）","f":0,"d":2,"q":"—How did you go to Shanghai? —____","o":["I went there by train.","I go there by train.","I go to Shanghai.","I am happy."],"a":0,"k":"旅行过去时：How did 问交通方式的答语","e":"解析：问怎么去的，用过去时加 by train 回答。"},
// ══════════ 六下·季节与活动（综合时态·简短阅读）══════════
{"i":613072,"c":"6en-10","ch":"六下·季节与活动（综合时态·简短阅读）","f":0,"d":2,"q":"____ a lake in the park last year.","o":["There is","There was","There were","There are"],"a":1,"k":"综合时态：there was 表单数过去","e":"解析：last year 表过去，a lake 是单数，用 There was。"},
{"i":613073,"c":"6en-10","ch":"六下·季节与活动（综合时态·简短阅读）","f":0,"d":2,"q":"____ many trees in the garden before.","o":["There is","There was","There are","There were"],"a":3,"k":"综合时态：there were 表复数过去","e":"解析：many trees 是复数，又表过去，用 There were。"},
{"i":613074,"c":"6en-10","ch":"六下·季节与活动（综合时态·简短阅读）","f":0,"d":2,"q":"I ____ apples every autumn, but I ____ oranges last autumn.","o":["pick; pick","picked; pick","pick; picked","picks; picked"],"a":2,"k":"综合时态：一般现在与一般过去对比","e":"解析：every 用一般现在时，last 用过去式。"},
{"i":613075,"c":"6en-10","ch":"六下·季节与活动（综合时态·简短阅读）","f":0,"d":2,"q":"—____? —I like winter best.","o":["Which season do you like best?","What do you do?","Where are you?","How are you?"],"a":0,"k":"季节活动：根据答语选问句 Which season","e":"解析：答语说最喜欢的季节，问句用 Which season。"},
{"i":613076,"c":"6en-10","ch":"六下·季节与活动（综合时态·简短阅读）","f":0,"d":2,"q":"In summer, it is ____ and hot.","o":["sun","sunny","suny","sunly"],"a":1,"k":"季节活动：形容天气用 sunny","e":"解析：表示晴朗要用形容词 sunny。"},
{"i":613077,"c":"6en-10","ch":"六下·季节与活动（综合时态·简短阅读）","f":0,"d":2,"q":"We ____ mountains last spring.","o":["climb","climbs","climbed","climbing"],"a":2,"k":"综合时态：climb 的过去式 climbed","e":"解析：last spring 表过去，climb 加 ed。"},
{"i":613078,"c":"6en-10","ch":"六下·季节与活动（综合时态·简短阅读）","f":0,"d":2,"q":"Look! ____ a rainbow in the sky now.","o":["There was","There is","There were","There are"],"a":1,"k":"综合时态：there is 表现在单数","e":"解析：now 表现在，a rainbow 是单数，用 There is。"},
{"i":613079,"c":"6en-10","ch":"六下·季节与活动（综合时态·简短阅读）","f":0,"d":2,"q":"They ____ a snowman in winter last year.","o":["make","makes","made","making"],"a":2,"k":"综合时态：make 的过去式是 made","e":"解析：过去时中 make 要变成 made。"},
);
